### ISSUE TITLE
Add support for wildcards in known_hosts

### ISSUE THREAD

**Issue by OOTS** [paramiko/paramiko#1001]
Please add support for wildcards in `known_hosts` files.

For example, a known_hosts file like the following is accepted by running plain `ssh`:
    `[?xample.net]:42 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICdQrznEieszf9lLMzYnc+0i44nUCvhActa4dcf5C65q`

You can verify this by running `ssh -p 42 example.net` or `ssh-keygen -F [example.net]:42`.

Paramiko, however, throws an exception:

    $ python3
    >>> import paramiko
    >>> client = paramiko.SSHClient()
    >>> client.load_system_host_keys() # or client.load_host_keys(filename)
    >>> client.connect("example.net", port=42)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.5/dist-packages/paramiko/client.py", line 373, in connect
        self, server_hostkey_name, server_key
      File "/usr/local/lib/python3.5/dist-packages/paramiko/client.py", line 700, in missing_host_key
        raise SSHException('Server %r not found in known_hosts' % hostname)
    paramiko.ssh_exception.SSHException: Server '[example.net]:42' not found in known_hosts

I'm using paramiko 2.2.1.

Please add support for the `?` and `*` wildcards (for host names as well as for ports) in `known_hosts` files, as documented in the [sshd man page](https://linux.die.net/man/8/sshd).

**Comment by sanjeevrohila** [comment]
Is it implemented ?

**Comment by backbord** [comment]
There is a 5 year old PR https://github.com/paramiko/paramiko/pull/1053 -- can it be revived?

**Comment by filipeg** [comment]
There is also this more recent PR #1920
