### ISSUE TITLE
AuthenticationException on 2.2.1 but working on 2.1.2

### ISSUE THREAD

**Issue by im-jose** [paramiko/paramiko#1004]
I'm not really sure what's happening, but here is the execution of the same code using both versions:

# **2.2.1**

Python 2.7.6
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko, os
>>> paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
>>> ssh = paramiko.SSHClient()
>>> ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> ssh.connect("device-ip", 22, "username", "password", look_for_keys=False, allow_agent=False)
DEBUG:paramiko.transport:starting thread (client mode): 0xc782c550L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.2.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-4.1.2 SSH Secure Shell Toolkit
INFO:paramiko.transport:Connected (version 2.0, client 4.1.2)
DEBUG:paramiko.transport:kex algos:[u'diffie-hellman-group1-sha1'] server key:[u'ssh-dss'] client encrypt:[u'aes256-cbc', u'aes192-cbc', u'aes128-cbc', u'twofish256-cbc', u'twofish-cbc', u'twofish192-cbc', u'twofish128-cbc', u'blowfish-cbc', u'3des-cbc'] server encrypt:[u'aes256-cbc', u'aes192-cbc', u'aes128-cbc', u'twofish256-cbc', u'twofish-cbc', u'twofish192-cbc', u'twofish128-cbc', u'blowfish-cbc', u'3des-cbc'] client mac:[u'hmac-sha1', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-sha1', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-dss
DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-dss host key for "device-ip": e321e239567f4719bf88d5a1ed5cb052
DEBUG:paramiko.transport:EOF in transport thread
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/projects/project/projectenv/local/lib/python2.7/site-packages/paramiko/client.py", line 394, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/home/projects/project/projectenv/local/lib/python2.7/site-packages/paramiko/client.py", line 649, in _auth
    raise saved_exception
paramiko.ssh_exception.AuthenticationException: Authentication failed. 

-------------------------------------
# **2.1.2 - Working Version**

Python 2.7.6 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko, os
>>> paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
>>> ssh = paramiko.SSHClient()
>>> ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> ssh.connect("device-ip", 22, "username", "password", look_for_keys=False, allow_agent=False)
DEBUG:paramiko.transport:starting thread (client mode): 0xac4b33d0L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.1.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-4.1.2 SSH Secure Shell Toolkit
INFO:paramiko.transport:Connected (version 2.0, client 4.1.2)
DEBUG:paramiko.transport:kex algos:[u'diffie-hellman-group1-sha1'] server key:[u'ssh-dss'] client encrypt:[u'aes256-cbc', u'aes192-cbc', u'aes128-cbc', u'twofish256-cbc', u'twofish-cbc', u'twofish192-cbc', u'twofish128-cbc', u'blowfish-cbc', u'3des-cbc'] server encrypt:[u'aes256-cbc', u'aes192-cbc', u'aes128-cbc', u'twofish256-cbc', u'twofish-cbc', u'twofish192-cbc', u'twofish128-cbc', u'blowfish-cbc', u'3des-cbc'] client mac:[u'hmac-sha1', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-sha1', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
DEBUG:paramiko.transport:MAC agreed: hmac-md5
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-dss host key for device-ip: e321e239567f4719bf88d5a1ed5cb052
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!

**Comment by ploxiln** [comment]
Hmm, odd. I think "EOF in transport thread" means the ssh server didn't like something paramiko did, and closed the connection. One slight difference is "MAC agreed": `hmac-md5` in the working case, `hmac-sha1` in the no-longer-working case.

You could test changing the MAC priority list of the Transport, but unfortunately there's no good way to do that when using `SSHClient`. If you're up for it, you could edit `_preferred_macs` in `transport.py` to put `hmac-md5` first, and test with that modified version of paramiko.

**Comment by bitprophet** [comment]
Sadly the EOF errors seem to come up for all kinds of protocol and network issues, so it could be any number of things.

@im-jose I'd try out Paramiko 2.1.3 (i.e. a single point upgrade from 2.1.2) to see if that also triggers the issue; it is where the cipher preferences changed, but does _not_ include some of the other, potentially bigger changes from 2.2.x. Would at least rule out those issues and make it squarely something related to the ciphers (presumably.)
