### ISSUE TITLE
Import Paramiko is failing

### ISSUE THREAD

**Issue by singhaniashrinkhala** [paramiko/paramiko#1029]
I have paramiko version 1.9.0 installed.

However, when I try to import it:
```
[user]$ python
Python 2.6.6 (r266:84292, Sep  4 2013, 07:46:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/paramiko/__init__.py", line 62, in <module>
    from transport import SecurityOptions, Transport
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 33, in <module>
    from paramiko import util
  File "/usr/lib/python2.6/site-packages/paramiko/util.py", line 33, in <module>
    from paramiko.common import *
  File "/usr/lib/python2.6/site-packages/paramiko/common.py", line 98, in <module>
    from Crypto import Random
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/__init__.py", line 29, in <module>
    from Crypto.Random import _UserFriendlyRNG
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
    import FortunaGenerator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 34, in <module>
    from Crypto.Util.number import ceil_shift, exact_log2, exact_div
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in <module>
    if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
>>> 
```
I am not sure why I am getting this error. Any tips?

Some background about the machine:

```
#lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.5 (Santiago)
Release:	6.5
Codename:	Santiago
```

**Comment by ploxiln** [comment]
This is a problem in pycrypto. You could try re-installing pycrypto.

**Comment by singhaniashrinkhala** [comment]
@ploxiln thanks for the feedback. Trying it now

**Comment by singhaniashrinkhala** [comment]
Okay, I tried that. Didn't help @ploxiln

**Comment by singhaniashrinkhala** [comment]
@ploxiln  the issue is still there. I tried uninstalling and reinstalling pycrypto a couple of times. Doesn't work.
I get this warning while installing pycrypto:

warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.

**Comment by ploxiln** [comment]
can you use "yum" to install gmp-devel ?

**Comment by singhaniashrinkhala** [comment]
@ploxiln : this machine doesn't have connection to the internet. Let me see if I can find a package online.

**Comment by singhaniashrinkhala** [comment]
Used this gmp-devel-4.3.1-7.el6_2.2.x86_64.rpm  package and it fixed the issue. @ploxiln  Thank you! :)
