### ISSUE TITLE
AttributeError: 'Ed25519Key' object has no attribute 'public_blob'

### ISSUE THREAD

**Issue by ushuz** [paramiko/paramiko#1071]
brew installed Python 2.7.13 

paramiko (2.3.0)
bcrypt (3.1.3)
cryptography (2.0.3)
pyasn1 (0.3.6)
PyNaCl (1.1.2)

Downgrade to 2.2.2 fixed the problem.

```
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 386, in execute
    multiprocessing
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 276, in _execute
    return task.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/ushuz/Code/xiachufang-maint/push/fabfile.py", line 134, in push
    put(list_io, list_fn, use_sudo=True)
  File "/usr/local/lib/python2.7/site-packages/fabric/network.py", line 687, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/operations.py", line 346, in put
    ftp = SFTP(env.host_string)
  File "/usr/local/lib/python2.7/site-packages/fabric/sftp.py", line 33, in __init__
    self.ftp = connections[host_string].open_sftp()
  File "/usr/local/lib/python2.7/site-packages/fabric/network.py", line 159, in __getitem__
    self.connect(key)
  File "/usr/local/lib/python2.7/site-packages/fabric/network.py", line 151, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/usr/local/lib/python2.7/site-packages/fabric/network.py", line 481, in connect
    client.connect(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 416, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, t.gss_host,
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 618, in _auth
    self._transport.auth_publickey(username, key))
  File "/usr/local/lib/python2.7/site-packages/paramiko/transport.py", line 1447, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/local/lib/python2.7/site-packages/paramiko/auth_handler.py", line 209, in wait_for_response
    raise e
AttributeError: 'Ed25519Key' object has no attribute 'public_blob'
```

**Comment by ushuz** [comment]
It seems that [ed25519key.py](https://github.com/paramiko/paramiko/blob/378fa86814f52fc83b5721bec6b81c5e0e4826c3/paramiko/ed25519key.py#L58-L84) doesn't initialize `public_blob` property like [ecdsakey.py](https://github.com/paramiko/paramiko/blob/378fa86814f52fc83b5721bec6b81c5e0e4826c3/paramiko/ecdsakey.py#L104-L108)

**Comment by bitprophet** [comment]
Hrm, that means both A) there's a hole in our test suite and B) I probably needed to move that line to the top of `__init__` instead of simply deleting it. Will take a peek, thanks!

**Comment by bitprophet** [comment]
Hrm we're testing basic connectivity with Ed25519 user keys. Ah! But since we need certs around to test that functionality, and certs get automatically loaded (as per OpenSSH compatible behavior), our test keys always load the certs & thus have `public_blob` set. So I'll probably want to move the certs and copies of their keys into a separate location to avoid this.

**Comment by bitprophet** [comment]
Confirmed that once I do that, this error pops up, so now I can test the fix.
