### ISSUE TITLE
SSH Connection failing to Centos, Working on Ubuntu

### ISSUE THREAD

**Issue by schizoid90** [paramiko/paramiko#1088]
I'm using Paramiko to connect over SSH and run commands on some VMs. I'm getting the below error when connecting to CentOS servers (6.9 and 7.4) but not to Ubuntu (14.04 and 16.04).

paramiko.ssh_exception.AuthenticationException: Authentication failed

I set up the connection as below:

```
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
key = paramiko.RSAKey.from_private_key_file(keyfile)
client.connect(hostname=vmip,
                       port=22,
                       username=user,
                       pkey=key,
                       look_for_keys=False,)
```

keyfile exists and the key works for normal SSH connections. I added look_for_keys=False to rule out the possibility of accidentally using the wrong key.

Log output of the working connection (Ubuntu 14.04):

```
06/10/2017 15:38:25 - DEBUG: starting thread (client mode): 0x27d0ef90L
06/10/2017 15:38:25 - DEBUG: Local version/idstring: SSH-2.0-paramiko_1.16.0
06/10/2017 15:38:25 - DEBUG: Remote version/idstring: SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
06/10/2017 15:38:25 - INFO: Connected (version 2.0, client OpenSSH_6.6.1p1)
06/10/2017 15:38:25 - DEBUG: kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
06/10/2017 15:38:25 - DEBUG: Kex agreed: diffie-hellman-group1-sha1
06/10/2017 15:38:25 - DEBUG: Cipher agreed: aes128-ctr
06/10/2017 15:38:25 - DEBUG: MAC agreed: hmac-sha2-256
06/10/2017 15:38:25 - DEBUG: Compression agreed: none
06/10/2017 15:38:25 - DEBUG: kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
06/10/2017 15:38:25 - DEBUG: Switch to new keys ...
06/10/2017 15:38:25 - DEBUG: Adding ssh-rsa host key for 192.168.0.147: a9cf22b3f2dc7601a3e705d86da58581
06/10/2017 15:38:25 - DEBUG: Trying SSH key 301ec0be897aa776c905af4d83ce2ea7
06/10/2017 15:38:25 - DEBUG: userauth is OK
06/10/2017 15:38:25 - INFO: Authentication (publickey) successful!
06/10/2017 15:38:25 - DEBUG: [chan 0] Max packet in: 32768 bytes
06/10/2017 15:38:26 - DEBUG: [chan 0] Max packet out: 32768 bytes
06/10/2017 15:38:26 - DEBUG: Secsh channel 0 opened.
06/10/2017 15:38:26 - DEBUG: [chan 0] Sesch channel 0 request ok
```

Failure (CentOS 6.9):
```
06/10/2017 15:35:14 - DEBUG: starting thread (client mode): 0x57150090L
06/10/2017 15:35:14 - DEBUG: Local version/idstring: SSH-2.0-paramiko_1.16.0
06/10/2017 15:35:14 - DEBUG: Remote version/idstring: SSH-2.0-OpenSSH_5.3
06/10/2017 15:35:14 - INFO: Connected (version 2.0, client OpenSSH_5.3)
06/10/2017 15:35:14 - DEBUG: kex algos:[u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
06/10/2017 15:35:14 - DEBUG: Kex agreed: diffie-hellman-group1-sha1
06/10/2017 15:35:14 - DEBUG: Cipher agreed: aes128-ctr
06/10/2017 15:35:14 - DEBUG: MAC agreed: hmac-sha2-256
06/10/2017 15:35:14 - DEBUG: Compression agreed: none
06/10/2017 15:35:14 - DEBUG: kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
06/10/2017 15:35:14 - DEBUG: Switch to new keys ...
06/10/2017 15:35:14 - DEBUG: Adding ssh-rsa host key for 192.168.0.248: c08df36ccd33180b92e55a15ace146f0
06/10/2017 15:35:14 - DEBUG: Trying SSH key 301ec0be897aa776c905af4d83ce2ea7
06/10/2017 15:35:14 - DEBUG: userauth is OK
06/10/2017 15:35:14 - INFO: Authentication (publickey) failed.
06/10/2017 15:35:14 - ERROR: Authentication failed.
06/10/2017 15:35:14 - DEBUG: [chan 0] Max packet in: 32768 bytes
06/10/2017 15:35:14 - WARNING: Oops, unhandled type 3
```

I can't see any major difference between the two except a different "Remote version/idstring" and OpenSSH version.

**Comment by schizoid90** [comment]
further information and full traceback of the error

```
Authentication failed.
Traceback (most recent call last):
  File "/root/vdctemplates-issue14/vdctesting/linuxtests.py", line 38, in connect
    look_for_keys=False
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 367, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 584, in _auth
    raise saved_exception
AuthenticationException: Authentication failed.
```

Versions:
SSH:
Centos 6.9 - openssh-server-5.3p1-123.el6_9.x86_64
Centos 7.4 - openssh-server-7.4p1-12.el7_4.x86_64
Ubuntu - 1:7.2p2-4ubuntu2.2

Paramiko:
paramiko==1.16.0

Python:
Host and Ubuntu - 2.7.12
Centos 6.9 - 2.6.6
Centos 7.4 - 2.7.5

Would the older versions of python cause an issue?

**Comment by schizoid90** [comment]
OK so I've now deduced that this isn't a Paramiko issue as I created another script that only takes care of SSH connections and running a simple command and it succeeds on all systems.

I've run strace against the two scripts to see differences, the outputs of these are below.
[badstrace.txt](https://github.com/paramiko/paramiko/files/1372161/badstrace.txt)
[goodstrace.txt](https://github.com/paramiko/paramiko/files/1372162/goodstrace.txt)

I have edited out the useless information from these leaving just relevant stuff. This includes a lot of refused connections while waiting for port 22 to be open (in badstrace). Badstrace is from a script that also builds the VM where as goodstrace was run against an already running server but both were built from the same base template and should be identical.

Interesting notes from the two files. badstrace has an extra connect

```
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(22), sin_addr=inet_addr("192.168.0.218")}, 16) = 0
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 5
connect(5, {sa_family=AF_INET, sin_port=htons(22), sin_addr=inet_addr("192.168.0.218")}, 16) = 0
fcntl(5, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(5, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
```

```
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(22), sin_addr=inet_addr("192.168.0.153")}, 16) = 0
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
```

The number also changes though I'm not sure what this corresponds to?

It also appears that badtrace is looking for lots of different ssh keys even though look_for_keys=False as well as a lot of other guff that goodtrace doesn't have. I imagine this is contributing to the failure.

**Comment by schizoid90** [comment]
OK, found the issue eventually. The server wasn't yet ready to accept SSH requests. Despite me having this code for exactly that reason:

```python
result = 0
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        while result == 0:
            try:
                result = sock.connect((self.vmip, 22))
            except Exception:
                pass
```
