### ISSUE TITLE
Use of async as a variable name breaks Paramiko in Python 3.7

### ISSUE THREAD

**Issue by vEpiphyte** [paramiko/paramiko#1108]
After installing Paramiko 2.3.1 into a Python 3.7-rc docker container, attempting to import Paramiko fails.

```docker run --rm $IMAGE_ID python -c "import paramiko; print(paramiko)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/paramiko/__init__.py", line 31, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 70, in <module>
    from paramiko.sftp_client import SFTPClient
  File "/usr/local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 43, in <module>
    from paramiko.sftp_file import SFTPFile
  File "/usr/local/lib/python3.7/site-packages/paramiko/sftp_file.py", line 68
    self._close(async=True)
                    ^
SyntaxError: invalid syntax
```

According to https://www.python.org/dev/peps/pep-0492/#deprecation-plans ``async`` becomes a Python language keyword starting in Python 3.7.

Relates to https://github.com/vertexproject/synapse-docker-testimages/pull/37

Similar issue encountered in https://github.com/neovim/python-client/pull/274

**Comment by bitprophet** [comment]
Well that makes me grumpy. Where's Python 4.0 when you need it? 🙃 

Thank goodness, the only spots I see `[^_]async[^_]` are right around where you found it, and it's technically in a private API, so I can't feel too bad about renaming it. Will fix in a sec. Thank you for the report!

**Comment by vardhmanandroid2015** [comment]
Faced the same issue when upgraded docker client to latest one docker-3.7.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\__init__.py", line 2, in <module>
    from .api import APIClient
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\api\__init__.py", line 2, in <module>
    from .client import APIClient
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\api\client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\api\build.py", line 6, in <module>
    from .. import auth
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\auth.py", line 9, in <module>
    from .utils import config
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\utils\__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\utils\decorators.py", line 4, in <module>
    from . import utils
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\utils\utils.py", line 13, in <module>
    from .. import tls
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\tls.py", line 5, in <module>
    from .transport import SSLAdapter
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\transport\__init__.py", line 11, in <module>
    from .sshconn import SSHAdapter
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\docker\transport\sshconn.py", line 1, in <module>
    import paramiko
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\transport.py", line 66, in <module>
    from paramiko.sftp_client import SFTPClient
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\sftp_client.py", line 41, in <module>
    from paramiko.sftp_file import SFTPFile
  File "C:\Users\abhishek.jain\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\sftp_file.py", line 66
    self._close(async=True)
                    ^
SyntaxError: invalid syntax

**Comment by vEpiphyte** [comment]
@vardhmanandroid2015 The https://github.com/docker/docker-py library 3.7.0 release only includes paramiko if you do a extras install specifying ssh.  This is a problem with how you installed the library; not a problem with paramiko or docker-py.
