### ISSUE TITLE
Random failures for 'Error reading SSH protocol banner'

### ISSUE THREAD

**Issue by iDemonix** [paramiko/paramiko#1111]
Hi,

When connecting to a device that has an SSH banner, I'm getting random failures. I've tested using Python2 and Python3, and on both my MacBook Pro (High Sierra) and a CentOS 7 VM.

Here is my code:

```language-python
import paramiko
from easysnmp import snmp_get, snmp_walk, Session

# vars
host = '1.2.3.4'
user = 'blah'
password = 'removed'

# paramiko SSH client
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
paramiko.util.log_to_file("filename.log")
client.connect(host, username=user, password=password)

stdin, stdout, stderr = client.exec_command('show ver')
for line in stdout:
    print(line.strip('\n'))
client.close()
```

Running the script repeatedly, it randomly doesn't work:

```
[root@server1 ~]# python /tmp/test.py 
Hostname: myhost
Model: srx110h2-va
JUNOS Software Release [12.1X46-D40.2]
<SNMPVariable value='here' (oid='sysLocation', oid_index='0', snmp_type='OCTETSTR')>

[root@server1 ~]# python /tmp/test.py 
Hostname: myhost
Model: srx110h2-va
JUNOS Software Release [12.1X46-D40.2]
<SNMPVariable value='here' (oid='sysLocation', oid_index='0', snmp_type='OCTETSTR')>

[root@server1 ~]# python /tmp/test.py 
Traceback (most recent call last):
  File "/tmp/test.py", line 14, in <module>
    client.connect(host, username=user, password=password)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 385, in connect
    t.start_client(timeout=timeout)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 543, in start_client
    raise e
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

[root@server1 ~]# python /tmp/test.py 
Traceback (most recent call last):
  File "/tmp/test.py", line 14, in <module>
    client.connect(host, username=user, password=password)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 385, in connect
    t.start_client(timeout=timeout)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 543, in start_client
    raise e
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

This happens on both Mac and Linux, and doesn't seem to matter how long I wait between commands, it just seems to be random. I've tried it against this device (Juniper SRX) and some Cisco 800 and 2100 series routers, all with slightly different login banners, and they all seem to be affected.

**Comment by ploxiln** [comment]
It's because it's a switch, and not a server with a normal unix shell environment. See http://www.paramiko.org/faq.html#paramiko-doesn-t-work-with-my-cisco-windows-or-other-non-unix-system and #965 and #360 and many others

**Comment by luqasz** [comment]
Here is why ssh client works with cisco:
https://github.com/openssh/openssh-portable/blob/master/compat.c#L140
https://github.com/openssh/openssh-portable/blob/master/config.sub#L158

Which I can confirm when logging into cisco 6513 with `ssh -vvv` 

```
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.5p1 Ubuntu-10
debug1: Remote protocol version 2.0, remote software version Cisco-1.25
debug1: match: Cisco-1.25 pat Cisco-1.* compat 0x60000000
```
