### ISSUE TITLE
2.4.0, Setting specific KEX fails, but not setting it same KEX works

### ISSUE THREAD

**Issue by olmari** [paramiko/paramiko#1120]
If I set
`paramiko.Transport._preferred_kex = ('diffie-hellman-group-exchange-sha256')`
I get
`ERROR    - Exception: Incompatible ssh peer (no acceptable kex algorithm)`

but if I don't set it the connection works with very same kex applied:
`DEBUG    - Kex agreed: diffie-hellman-group-exchange-sha256`

So in this particular case kex that is wanted is applied, but I'd like to enforce it, but that is not working and I have no idea why. I suspect something in paramiko is failing for some weird reason, or PEBKAC, or both.

Related code snippet I've currently trying:
```
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
```
```
  def read_whitelist(self):
    paramiko.Transport._preferred_ciphers = ('aes256-ctr', 'aes192-ctr', 'aes128-ctr')
    paramiko.Transport._preferred_macs = ('hmac-sha2-512', 'hmac-sha2-256')
    paramiko.Transport._preferred_key_types = ('ssh-ed25519', 'ssh-rsa')
  # For some reason next line errors with incompatible kex, while not setting it makes it work with very same kex algo
  # paramiko.Transport._preferred_kex = ('diffie-hellman-group-exchange-sha256')
    ssh = paramiko.SSHClient()
    ssh.load_host_keys(os.path.expanduser(os.path.join("~", ".ssh", "known_hosts")))
    whitelistFileName = os.path.join(sys.path[0], 'whitelist.json')

    try:
      ssh.connect(hostname=config['whitelist_ssh_server'],
                  port=config['whitelist_ssh_port'],
                  username=config['whitelist_ssh_username'],
                  password=config['whitelist_ssh_password'].encode("ascii"),
                  key_filename=os.path.expanduser(config['whitelist_ssh_keyfile']))
      sftp = ssh.open_sftp()
      sftp.get(config['whitelist_ssh_getfile'], whitelistFileName)
      sftp.close()
      ssh.close()
```

Log snippet from preferred kex in place, connection not working:
```
2017-11-18 17:10:50,782: DEBUG    - Local version/idstring: SSH-2.0-paramiko_2.4.0
2017-11-18 17:10:50,807: DEBUG    - Remote version/idstring: SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u1
2017-11-18 17:10:50,808: INFO     - Connected (version 2.0, client OpenSSH_7.4p1)
2017-11-18 17:10:50,843: DEBUG    - kex algos:[u'curve25519-sha256@libssh.org', u'diffie-hellman-group-exchange-sha256'] server key:[u'ssh-ed25519', u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes256-gcm@openssh.com', u'aes128-gcm@openssh.com', u'aes256-ctr', u'aes192-ctr', u'aes128-ctr'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes256-gcm@openssh.com', u'aes128-gcm@openssh.com', u'aes256-ctr', u'aes192-ctr', u'aes128-ctr'] client mac:[u'hmac-sha2-512-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-512', u'hmac-sha2-256', u'hmac-ripemd160', u'umac-128@openssh.com'] server mac:[u'hmac-sha2-512-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-512', u'hmac-sha2-256', u'hmac-ripemd160', u'umac-128@openssh.com'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2017-11-18 17:10:50,844: ERROR    - Exception: Incompatible ssh peer (no acceptable kex algorithm)
2017-11-18 17:10:50,850: ERROR    - Traceback (most recent call last):
2017-11-18 17:10:50,851: ERROR    -   File "/home/gatekeeper/gatekeeper/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 1892, in run
2017-11-18 17:10:50,852: ERROR    -     self._handler_table[ptype](self, m)
2017-11-18 17:10:50,852: ERROR    -   File "/home/gatekeeper/gatekeeper/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 1990, in _negotiate_keys
2017-11-18 17:10:50,853: ERROR    -     self._parse_kex_init(m)
2017-11-18 17:10:50,854: ERROR    -   File "/home/gatekeeper/gatekeeper/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 2134, in _parse_kex_init
2017-11-18 17:10:50,854: ERROR    -     raise SSHException('Incompatible ssh peer (no acceptable kex algorithm)') # noqa
2017-11-18 17:10:50,855: ERROR    - SSHException: Incompatible ssh peer (no acceptable kex algorithm)
2017-11-18 17:10:50,856: ERROR    - 
2017-11-18 17:10:50,882: DEBUG    - Failed to load whitelist from server, error:
Incompatible ssh peer (no acceptable kex algorithm)
```

Log snippet from preferred kex commented out, connection working:
```
2017-11-18 16:59:44,501: DEBUG    - Local version/idstring: SSH-2.0-paramiko_2.4.0
2017-11-18 16:59:44,525: DEBUG    - Remote version/idstring: SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u1
2017-11-18 16:59:44,526: INFO     - Connected (version 2.0, client OpenSSH_7.4p1)
2017-11-18 16:59:44,551: DEBUG    - kex algos:[u'curve25519-sha256@libssh.org', u'diffie-hellman-group-exchange-sha256'] server key:[u'ssh-ed25519', u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes256-gcm@openssh.com', u'aes128-gcm@openssh.com', u'aes256-ctr', u'aes192-ctr', u'aes128-ctr'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes256-gcm@openssh.com', u'aes128-gcm@openssh.com', u'aes256-ctr', u'aes192-ctr', u'aes128-ctr'] client mac:[u'hmac-sha2-512-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-512', u'hmac-sha2-256', u'hmac-ripemd160', u'umac-128@openssh.com'] server mac:[u'hmac-sha2-512-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-512', u'hmac-sha2-256', u'hmac-ripemd160', u'umac-128@openssh.com'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2017-11-18 16:59:44,553: DEBUG    - Kex agreed: diffie-hellman-group-exchange-sha256
2017-11-18 16:59:44,554: DEBUG    - HostKey agreed: ssh-ed25519
2017-11-18 16:59:44,555: DEBUG    - Cipher agreed: aes256-ctr
2017-11-18 16:59:44,557: DEBUG    - MAC agreed: hmac-sha2-512
2017-11-18 16:59:44,558: DEBUG    - Compression agreed: none
2017-11-18 16:59:44,633: DEBUG    - Got server p (2048 bits)
2017-11-18 16:59:46,643: DEBUG    - kex engine KexGexSHA256 specified hash_algo <built-in function openssl_sha256>
2017-11-18 16:59:46,649: DEBUG    - Switch to new keys ...
2017-11-18 16:59:55,280: DEBUG    - Trying discovered key <censored> in /home/<censored>
2017-11-18 16:59:55,310: DEBUG    - userauth is OK
2017-11-18 16:59:55,351: INFO     - Authentication (publickey) successful!
2017-11-18 16:59:55,384: DEBUG    - [chan 0] Max packet in: 32768 bytes
2017-11-18 16:59:55,413: DEBUG    - Received global request "hostkeys-00@openssh.com"
2017-11-18 16:59:55,414: DEBUG    - Rejecting "hostkeys-00@openssh.com" global request from server.
2017-11-18 16:59:55,481: DEBUG    - [chan 0] Max packet out: 32768 bytes
2017-11-18 16:59:55,482: DEBUG    - Secsh channel 0 opened.
2017-11-18 16:59:55,516: DEBUG    - [chan 0] Sesch channel 0 request ok
2017-11-18 16:59:55,545: INFO     - [chan 0] Opened sftp connection (server version 3)
2017-11-18 16:59:55,548: DEBUG    - [chan 0] stat('<censored>')
2017-11-18 16:59:55,580: DEBUG    - [chan 0] open('<censored>', 'rb')
2017-11-18 16:59:55,610: DEBUG    - [chan 0] open('<censored>', 'rb') -> 00000000
2017-11-18 16:59:55,708: DEBUG    - [chan 0] close(00000000)
2017-11-18 16:59:55,743: INFO     - [chan 0] sftp session closed.
2017-11-18 16:59:55,744: DEBUG    - [chan 0] EOF sent (0)
2017-11-18 16:59:55,773: DEBUG    - EOF in transport thread
```

**Comment by ploxiln** [comment]
This is probably because `('diffie-hellman-group-exchange-sha256')`, it's a string inside grouping parentheses. Whereas `('ssh-ed25519', 'ssh-rsa')` is a tuple and `('diffie-hellman-group-exchange-sha256',)` would be a tuple.

By the way, monkey-patching private attributes is not the intended way to customize the list of algorithms, though it might be the far-easier way for you to do it for now. The api-supported way is to use the Transport directly (without SSHClient), and call `.get_security_options()` and then assign to `.kex` on the returned options object.

**Comment by olmari** [comment]
Hmm, need to up my Python-fu I guess... I tried to google around and that was closest thing I found out.. And yes, making it a tuple did work, monkey style or not :) Next to learn `.get_security_options()` etc. Thank you for help, much appreciated

**Comment by ploxiln** [comment]
The monkey-patching is understandable though, using the Transport directly involves a fair bit of obscure code ... anyway I'm glad you got it working :)

**Comment by olmari** [comment]
Made it working with more proper way:

```
def read_whitelist(self):
    whitelistFileName = os.path.join(sys.path[0], 'whitelist.json')
    log.debug("Loading SSH-key from " + os.path.expanduser(config['whitelist_ssh_keyfile']))
    key = paramiko.Ed25519Key.from_private_key_file(os.path.expanduser(config['whitelist_ssh_keyfile']), password=config['whitelist_ssh_password'].encode("ascii"))
    transport = paramiko.Transport((config['whitelist_ssh_server'], config['whitelist_ssh_port']))

    try:
      # Set allowed SSH/SFTP parameters, we (try to) only allow secure ones, tuple format
      transport.get_security_options().ciphers = ('aes256-ctr', 'aes192-ctr', 'aes128-ctr')
      transport.get_security_options().kex = ('diffie-hellman-group-exchange-sha256',)
      transport.get_security_options().digests = ('hmac-sha2-512', 'hmac-sha2-256')
      transport.get_security_options().key_types = ('ssh-ed25519', 'ssh-rsa')

      log.info("Retrieving whitelist from " + config['whitelist_ssh_server'])
      transport.connect(username=config['whitelist_ssh_username'], pkey=key)
      sftp = paramiko.SFTPClient.from_transport(transport)
      sftp.get(config['whitelist_ssh_getfile'], whitelistFileName)
      log.debug("Whitelist retrieved")
      transport.close()
      log.debug("SFTP-connection closed")
```
