### ISSUE TITLE
SFTP put hangs after a while, modifying channel.py or settings ultra_debug=True makes it work

### ISSUE THREAD

**Issue by schizo99** [paramiko/paramiko#1122]
I have an issue when using SFTPClient. We currently use Paramiko 1.15.1 but have the same issue with the latest Paramiko version.

When sending files to one of our servers it hangs after about 2MB has been sent.

While scouring the internet I found others having a similar issue with Duplicity so I tried their workaround. Which ment commenting out L1059 [https://github.com/paramiko/paramiko/blob/af9f16f9a03bede1c5af84d00bc73097f6b45b54/paramiko/channel.py#L1059](url)

This however made it stop working for other machines. So I decided to debug a little to see if I would be able to see exactly what was happening. Enabled DEBUG but saw nothing. In the source code I saw ultra_debug. So I tried setting that on the SFTPClient and all of a sudden the sendings work even with L1059 not commented out.

I've been trying to find the difference with/without ultra_debug = True but have not been able to see what actually makes it working when it's set to True.

Any insight into this issue would be greatly appreciated.

**Comment by schizo99** [comment]
This is the traceback I get when not changing L1059 or settings ultra_debug = True

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(node, timeout=60, username=username, password=password, look_for_keys=False)
sftp = ssh.open_sftp()
#sftp.ultra_debug=True
sftp.put("bigfile.zip","bigfile.zip")

> Traceback (most recent call last):
>   File "<console>", line 1, in <module>
>   File "/lib/python2.7/site-packages/paramiko/sftp_client.py", line 669, in put
>     return self.putfo(fl, remotepath, file_size, callback, confirm)
>   File "/lib/python2.7/site-packages/paramiko/sftp_client.py", line 626, in putfo
>     fr.write(data)
>   File "/lib/python2.7/site-packages/paramiko/file.py", line 331, in write
>     self._write_all(data)
>   File "/lib/python2.7/site-packages/paramiko/file.py", line 448, in _write_all
>     count = self._write(data)
>   File "/lib/python2.7/site-packages/paramiko/sftp_file.py", line 176, in _write
>     self._reqs.append(self.sftp._async_request(type(None), CMD_WRITE, self.handle, long(self._realpos), data[:chunk]))
>   File "/lib/python2.7/site-packages/paramiko/sftp_client.py", line 750, in _async_request
>     self._send_packet(t, msg)
>   File "/lib/python2.7/site-packages/paramiko/sftp.py", line 170, in _send_packet
>     self._write_all(out)
>   File "/lib/python2.7/site-packages/paramiko/sftp.py", line 135, in _write_all
>     raise EOFError()
> EOFError
