### ISSUE TITLE
Version 2.4.0 doesn't work on RHEL 6 (Python 2.6): ValueError: zero length field name in format

### ISSUE THREAD

**Issue by RadekBiba** [paramiko/paramiko#1123]
Here's what happens:

```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/rhui3-tests/tests/rhui3_tests/test_client_management.py", line 1, in <module>
    import nose, stitches, logging, yaml
  File "/usr/lib/python2.6/site-packages/stitches/__init__.py", line 3, in <module>
    from stitches.connection import Connection
  File "/usr/lib/python2.6/site-packages/stitches/connection.py", line 5, in <module>
    import paramiko
  File "/usr/lib/python2.6/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 89, in <module>
    class Transport(threading.Thread, ClosingContextManager):
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 103, in Transport
    _CLIENT_ID = 'paramiko_{}'.format(paramiko.__version__)
ValueError: zero length field name in format

```
I can downgrade to 2.3.1 for now, where everything works, but please fix this.

FWIW: https://stackoverflow.com/questions/19668395/str-format-for-python-2-6-gives-error-where-2-7-does-not

**Comment by dmtucker** [comment]
@RadekBiba [Python 2.6 support was dropped in 2.4.0](https://github.com/paramiko/paramiko/issues/1119).

**Comment by RadekBiba** [comment]
Ah, OK, thanks @dmtucker.
