### ISSUE TITLE
Using Fabric, When put is called, some files are failing upload with size mismatch.

### ISSUE THREAD

**Issue by syberkitten** [paramiko/paramiko#1133]
I'm trying to upload simple text file to a remote server
and it fails

Using Python 2.7
Paramiko 2.4.0 (from within Fabric)
On Mac OSX Sierra
To (target machine): Ubunto 14.04 on Amazon EC2

Other templates pass, so there is some kind of an inconsistency.

```
Warning: put() encountered an exception while uploading '<StringIO.StringIO instance at 0x105ef15a8>'

Traceback (most recent call last):
  File "/Users/ccc/.virtualenvs/py2.7/lib/python2.7/site-packages/fabric/operations.py", line 399, in put
    mode, local_is_path, temp_dir)
  File "/Users/xxx/.virtualenvs/py2.7/lib/python2.7/site-packages/fabric/sftp.py", line 256, in put
    rattrs = putter(local_path, remote_path)
  File "/Users/xxx/.virtualenvs/py2.7/lib/python2.7/site-packages/paramiko/sftp_client.py", line 692, in putfo
    'size mismatch in put!  {} != {}'.format(s.st_size, size))
IOError: size mismatch in put!  16753 != 16747
```

**Comment by syberkitten** [comment]
I found out the problem
The following character causes the problem (it's a kind of a quote or apostrophe)

```
’
```

**Comment by ploxiln** [comment]
Is this unicode quote mark in the filename of the file being transferred?

**Comment by syberkitten** [comment]
@ploxiln 
Yeah, It's In the file being transferred (content) not the file name.

**Comment by syberkitten** [comment]
this is the template conf I'm actually trying to upload, which fails 
until I remove the strange character.

https://github.com/emqtt/emqttd/blob/dd72083da52c95c743a92a53f2dbf8822e7d8977/etc/emq.conf

Please note that in this file, you'll see both normal apostrophe and the other one which fails,
when searching on the browser (CMD-F) it treats both the same, this you'll find 17 occurrences of 
```
’
```
and 
```
'
```
Which the browser treats the same (probably some kind of browser unicode normalization)

**Comment by maldn** [comment]
i stumbled across this as well.
the problem is https://github.com/paramiko/paramiko/blob/master/paramiko/sftp_client.py#L649 
the len() call produces different results depending on python 2 or 3.
basically:
`python2 -c'print(len("ß"))'` -> `2`
`python3 -c'print(len("ß"))'` -> `1`

**Comment by maldn** [comment]
quick follow-up: i hit the same issue through fabric as well.
I think Fabric should pass a BytesIO object for python3.
or Paramiko handles this special case as well. I will fix this tomorrow for fabric

**Comment by zrong** [comment]
Is this issue fixed? 

I use `Fabric3 1.14.post1` with `Paramiko 2.4.1`. This issue is still exists.

 ```
 <file obj> -> /srv/app/sagi-api/config.yaml

Fatal error: put() encountered an exception while uploading '<_io.StringIO object at 0x10a7939d8>'

Underlying exception:
    size mismatch in put!  2041 != 1883

Aborting.
```

**Comment by jsyrjala** [comment]
I am also hitting this problem with python3.7 and Paramiko 2.4.2

**Comment by jsyrjala** [comment]
In my case this bit of code failed sometimes with size mismatch error, and sometimes upload worked fine. I am trying to transfer smallish files which are from a few KB to couple hundred KB. The files are JPEG images.

```
client client.put(local_file, remote_file)
```

I replaced above bit with this code, and so far it has worked every time. This bit of code disables buffering for file reading.
```
    file_size = os.stat(local_file).st_size
    with open(local_file, "rb", buffering=0) as fl:
        return client.putfo(fl, remote_file, file_size, None, None)
```

**Comment by yinxiongchen** [comment]
I also have this problem. Is this problem fixed now?

**Comment by vsilent** [comment]
```
Confirm the same problem,  Python 3.6.9, Fabric3 1.14.post1,  
Fatal error: put() encountered an exception while uploading '<_io.StringIO object at 0x7f852dad9d38>'

Underlying exception:
    size mismatch in put!  2537 != 2531


**On source server**
>>> sys.stdout.encoding
'UTF-8'

**On remote target server** 
Python 2.7.12 (default, Aug 22 2019, 16:36:40)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdout.encoding
'ascii'
after that did :export PYTHONIOENCODING=UTF-8
>>> len("“Administrator’s Area”;")
29
python -c'import sys; print(sys.stdout.encoding); print(len("“Administrator’s Area”;"))'
UTF-8
29
python3 -c'import sys; print(sys.stdout.encoding); print(len("“Administrator’s Area”;"))'
UTF-8
23

```
May be it makes sense to force using same Python version on target machine with 
before uploading files. 
`trydirect@reg:~$ sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10`

**Comment by Mekk** [comment]
Well, I faced this too (on ą in some comment)… And absolutely can't switch default python to py3 on machines I am scripting around.

**Comment by blokhin** [comment]
FYI: this also appears when there's no free space left at the remote.

**Comment by cptx032** [comment]
I'm getting the same error with fabric3 (`Fabric3==1.14.post1`). Debugging the fabric3 code I've discovered what @maldn points in: https://github.com/paramiko/paramiko/issues/1133#issuecomment-354312357
In summary: the fabric opens the file reading their content as string and not bytes (decoding using utf-8). But after the file transfer, paramiko try to verify if the size of remote file is equal to the size of content given to it. Paramiko apparently counts the remote file size using the `stat` linux command, that give us the size in bytes and not in characters. As unicode characters can have more than one byte, probably the comparison will be wrong.

To fix this issue without replacing any character in my local file, instead of doing:

```python
from fabric.contrib import files

files.upload_template(
    filename="my_local_file",
    destination="/my/remote/path/"
)
```

Now I'm doing:

```python
from fabric import operations

with open("my_local_file", "rb") as f:
    operations.put(
        local_path=io.BytesIO(f.read()),
        remote_path="/my/remote/path/"
    )
```

ie.: I'm not passing the file string path, but a instance of `io.BytesIO` to prevent fabric from decoding the file content

This worked for me
