### ISSUE TITLE
Broken pipe error when closing channel

### ISSUE THREAD

**Issue by ilyaostttt** [paramiko/paramiko#1157]
Initially encountered when using sshtunnel package and opening/closing a connection multiple times without sending any data. It seems to happen because channel._pipe is being closed concurrently with possible calls to pipe.set() from another thread.

This seems like a duplicate of #691, but I believe that in this case no additional locking is required, but it must be ensured that _pipe is not used while being closed.

The exception looks like this usually:

```
paramiko/channel.py:1016: in _feed
    self.in_buffer.feed(s)
paramiko/buffered_pipe.py:108: in feed
    self._event.set()
paramiko/pipe.py:129: in set
    self._pipe.set()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <paramiko.pipe.PosixPipe object at 0x7f7ad5652310>

    def set(self):
        if self._set or self._closed:
            return
        self._set = True
>       os.write(self._wfd, b'*')
E       OSError: [Errno 32] Broken pipe

paramiko/pipe.py:67: OSError
```

**Comment by stromnet** [comment]
I can confirm that this is an issue in paramiko 2.4.2.

### In short:

I've tested to apply both the patch in #1158 and #691 (individually, not at the same time), and I have made several successful runs with both. 
As soon as I'm removing the patch, the errors are more or less always present.
**Thus, both patches can, individually, be used to successful fix the issue.**
 

### Details:
I'm having a suite of pytests which is using paramiko to verify behaviour of an external non-python component, and the test cases uses `transport.request_port_forward` to create a tunnel on a remote system. A thread then handles the data forwarding for each channel, pretty much as per the [rforward.py](https://github.com/paramiko/paramiko/blob/master/demos/rforward.py) example.

Paramiko have been used in these tests without any issues for a long time, but just for remote command execution and sftp.
Lately some new test scenarios where added, which uses SSH port forwarding. There is no heavy traffic on these, <1k messages mostly, but quite a lot of tunnel setup/teardowns. These have been failing every now and then from day one. The ones mostly failing is where I have multiple simultaneous incoming channels to my code (same forwarding/transport)

When the tunneled channels are closing down (remote & local closing at almost the same time), I sometimes get this logged:

`06:26:39 ERROR      [paramiko.transport] [transport.py:1746 _log] Socket exception: Bad file descriptor (9)`

And after that the transport is dead.

By adding some code to interrogate `transport.get_exception()` whenever I detect a broken transport (it's re-used between tests), I get the same error as described in this ticket and in #691:
```
06:26:39 ERROR      [testlib.sut_ssh] [sut_ssh.py:343 _ssh_is_connected] Exception details from (now dead) paramiko transport as reported by transport.get_exception():
Traceback (most recent call last):
  File "/home/some/dir/autotests/venv/lib64/python3.6/site-packages/paramiko/transport.py", line 2015, in run
    self._channel_handler_table[ptype](chan, m)
  File "/home/some/dir/autotests/venv/lib64/python3.6/site-packages/paramiko/channel.py", line 1029, in _feed
    self.in_buffer.feed(s)
  File "/home/some/dir/autotests/venv/lib64/python3.6/site-packages/paramiko/buffered_pipe.py", line 102, in feed
    self._event.set()
  File "/home/some/dir/autotests/venv/lib64/python3.6/site-packages/paramiko/pipe.py", line 130, in set
    self._pipe.set()
  File "/home/some/dir/autotests/venv/lib64/python3.6/site-packages/paramiko/pipe.py", line 67, in set
    os.write(self._wfd, b"*")
OSError: [Errno 9] Bad file descriptor
```

In one case I've also got this when trying to close the channel itself, but usually `channel.close()` does not throw an exception:

```
06:26:39 ERROR      [root] [sut_ssh.py:273 run] Exception while closing tunneled SSH channel ('127.0.0.1', 49150) (fd 37) -> ('10.20.6.109', 22) -> ('localhost', 40622) (fd 36)
Traceback (most recent call last):
  File "/home/some/dir/autotests/testlib/sut_ssh.py", line 271, in run
    self.channel.close()
  File "/home/some/dir/autotests/venv/lib64/python3.6/site-packages/paramiko/channel.py", line 671, in close
    self.transport._send_user_message(m)
  File "/home/some/dir/autotests/venv/lib64/python3.6/site-packages/paramiko/transport.py", line 1790, in _send_user_message
    self._send_message(data)
  File "/home/some/dir/autotests/venv/lib64/python3.6/site-packages/paramiko/transport.py", line 1766, in _send_message
    self.packetizer.send_message(data)
  File "/home/some/dir/autotests/venv/lib64/python3.6/site-packages/paramiko/packet.py", line 413, in send_message
    self.write_all(out)
  File "/home/some/dir/autotests/venv/lib64/python3.6/site-packages/paramiko/packet.py", line 354, in write_all
    raise EOFError()
EOFError
```

**Comment by ploxiln** [comment]
https://github.com/paramiko/paramiko/pull/1235 seems to have yet another different place to use locks to prevent a race in these two channel pipe states ... hard to tell if one of these three locking schemes makes the prevents the need for another, or conflicts with another.
