### ISSUE TITLE
TypeError: an integer is required (got type bytes) on python3.6 (python3.5 is ok)

### ISSUE THREAD

**Issue by abc19899** [paramiko/paramiko#1187]
here is sample code:

```
import logging
import paramiko
import scp


logging.basicConfig()



def create_scp_client(server, port, user, password):
    print(type(server), type(port), type(user), type(password))
    client = paramiko.SSHClient()
    client.load_system_host_keys()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    # help(client.connect)
    client.connect(server, port, user, password)
    # scp_client = scp.SCPClient(client.get_transport())
    # 修改了默认的sanitize, 以支持?, *
    scp_client = scp.SCPClient(client.get_transport(), sanitize=lambda x: x, socket_timeout=20)
    return scp_client


if True:
    if True:
        config = dict(
            port=22,
            password='8i9o0p-[',
        )
        host = '192.168.8.12'
        user = 'root'
        try:
            scp_client_ = create_scp_client(host, config['port'], user, config['password'])
        except Exception as e:
            logging.getLogger(__name__).error('create scp client fail(%s)(%s), ip(%s)' % (
                type(e), e, host
            ))
            import traceback
            traceback.print_exc()
            print(False)
        else:
            print(scp_client_)
```

when run with python3.6, it got error:

```
<class 'str'> <class 'int'> <class 'str'> <class 'str'>
ERROR:paramiko.transport:Unknown exception: an integer is required (got type bytes)
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/paramiko/transport.py", line 1925, in run
ERROR:paramiko.transport:    self.kex_engine.parse_next(ptype, m)
ERROR:paramiko.transport:  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/paramiko/kex_gex.py", line 91, in parse_next
ERROR:paramiko.transport:    return self._parse_kexdh_gex_reply(m)
ERROR:paramiko.transport:  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/paramiko/kex_gex.py", line 262, in _parse_kexdh_gex_reply
ERROR:paramiko.transport:    self.transport._set_K_H(K, self.hash_algo(hm.asbytes()).digest())
ERROR:paramiko.transport:  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/hashlib.py", line 90, in inner
ERROR:paramiko.transport:    return func(*args, **kwargs)
ERROR:paramiko.transport:TypeError: an integer is required (got type bytes)
ERROR:paramiko.transport:
ERROR:__main__:create scp client fail(<class 'TypeError'>)(an integer is required (got type bytes)), ip(192.168.8.12)
Traceback (most recent call last):
  File "tmp.py", line 33, in <module>
    scp_client_ = create_scp_client(host, config['port'], user, config['password'])
  File "tmp.py", line 17, in create_scp_client
    client.connect(server, port, user, password)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/paramiko/client.py", line 392, in connect
    t.start_client(timeout=timeout)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/paramiko/transport.py", line 545, in start_client
    raise e
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/paramiko/transport.py", line 1925, in run
    self.kex_engine.parse_next(ptype, m)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/paramiko/kex_gex.py", line 91, in parse_next
    return self._parse_kexdh_gex_reply(m)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/paramiko/kex_gex.py", line 262, in _parse_kexdh_gex_reply
    self.transport._set_K_H(K, self.hash_algo(hm.asbytes()).digest())
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/hashlib.py", line 90, in inner
    return func(*args, **kwargs)
TypeError: an integer is required (got type bytes)
False
```

python --version
Python 3.6.3

pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.24.0)
bcrypt (3.1.4)
cffi (1.11.5)
cryptography (2.2.2)
future (0.16.0)
idna (2.6)
jsonpickle (0.9.6)
paramiko (2.4.1)
pip (9.0.1)
psutil (5.4.3)
pyasn1 (0.4.2)
pycparser (2.18)
PyNaCl (1.2.1)
scp (0.10.2)
setuptools (36.5.0)
six (1.11.0)
virtualenv (15.1.0)

but python3.5 is ok:
python3 tmp.py 
```
<class 'str'> <class 'int'> <class 'str'> <class 'str'>
<scp.SCPClient object at 0x7f7533d05e80>
```

python3 --version
Python 3.5.1

 pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.24.0)
bcrypt (3.1.4)
cffi (1.11.5)
cryptography (2.2.2)
idna (2.6)
paramiko (2.4.1)
pip (9.0.3)
pyasn1 (0.4.2)
pycparser (2.18)
PyNaCl (1.2.1)
scp (0.10.2)
setuptools (18.0.1)
six (1.11.0)
virtualenv (13.1.2)

**Comment by abc19899** [comment]
I'm using python3.5 and python3.6 on the same computer.

cat /etc/issue
CentOS release 6.5 (Final)
Kernel \r on an \m

uname  -r
2.6.32-431.el6.x86_64

and python are installed by

yum install -y centos-release-SCL
yum install -y epel-release
yum install rh-python35
yum install rh-python36

**Comment by forever139** [comment]
the same quesion

**Comment by fengbin1234** [comment]
我也有同样的问题  pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
安装最新版本就可以
