### ISSUE TITLE
Bad exception handling in method paramiko.transport.Transport.run

### ISSUE THREAD

**Issue by tantale** [paramiko/paramiko#1204]
The exception handling done in the method `paramiko.transport.Transport.run` is wrong
when ``socket.timeout`` is raised.

In the fragment below, you try to extract the error message from the exception *args* attributes:

```python
# extracted from branch: 1.7, file: paramiko/transport.py, line: 1835
except socket.error as e:
	if type(e.args) is tuple:
		if e.args:
			emsg = '%s (%d)' % (e.args[1], e.args[0])
		else:  # empty tuple, e.g. socket.timeout
			emsg = str(e) or repr(e)
	else:
		emsg = e.args
	self._log(ERROR, 'Socket exception: ' + emsg)
	self.saved_exception = e
```

But if the exception contains a tuple with only one value, like `('timed out',)`,
another exception is raised:

```python
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "[...]/site-packages/paramiko/transport.py", line 1838, in run
    emsg = '%s (%d)' % (e.args[1], e.args[0])
IndexError: tuple index out of range
```

Suggested fix:

```python
except socket.error as e:
	if type(e.args) is tuple:
		if len(e.args) == 1:
			emsg = str(e.args[0])
		elif len(e.args) >= 2:
			emsg = '%s (%d)' % (e.args[1], e.args[0])
		else:  # empty tuple, e.g. socket.timeout
			emsg = str(e) or repr(e)
	else:
		emsg = e.args
	self._log(ERROR, 'Socket exception: ' + emsg)
	self.saved_exception = e
```

My configuration:

```python
>>> platform.uname()
('Linux', 'xxxxxxxxxx', '3.10.0-327.18.2.el7.x86_64', '#1 SMP Thu May 12 11:03:55 UTC 2016', 'x86_64', 'x86_64')
```

This problem exist for all versions from **1.7** to **2.4** and **master** with Python 2.7.5

**Comment by ngie-eign** [comment]
Alternatively, `socket.timeout` could be caught and handled appropriately.
