### ISSUE TITLE
put() doubling file size

### ISSUE THREAD

**Issue by cobaltjacket** [paramiko/paramiko#1217]
I have noticed a new problem when transmitting files to a certain server that the destination file is being doubled. In fact, the file itself is being appended to itself. It only happens with a particular server. 

`$ cat -v TEST_IGNORE_ZFIR1003-1.txt
sdfsfsdfsd^M
$ cat -v TEST_IGNORE_ZFIR1003-2.txt
sdfsfsdfsd^M
sdfsfsdfsd^M`

This actually errors out (rightfully so). Any thoughts as to why? The log below is from a production transmission, though the results are the same as what you see above.

`2018-05-21 14:08:54 (ECC-PRD-BofA-PosPay-Outbound-PUT): Local file TEST_IGNORE_ZFIR1000.TXT matches filespec: "*_ZFIR*"
2018-05-21 14:08:54 (ECC-PRD-BofA-PosPay-Outbound-PUT): Local file TEST_IGNORE_ZFIR1000.TXT exists remotely: False
Traceback (most recent call last):
  File "D:\Scripts\sftpTransfer\sftpTransfer-0.57.2.py", line 485, in sftpPut
    session.put(localDirFile,preserve_mtime=True) # Preserve timestamp
  File "C:\Program Files\Python\Python36\lib\site-packages\pysftp\__init__.py", line 366, in put
    self._sftp.utime(remotepath, times)
  File "C:\Program Files\Python\Python36\lib\site-packages\paramiko\sftp_client.py", line 547, in utime
    self._request(CMD_SETSTAT, path, attr)
  File "C:\Program Files\Python\Python36\lib\site-packages\paramiko\sftp_client.py", line 780, in _request
    return self._read_response(num)
  File "C:\Program Files\Python\Python36\lib\site-packages\paramiko\sftp_client.py", line 832, in _read_response
    self._convert_status(msg)
  File "C:\Program Files\Python\Python36\lib\site-packages\paramiko\sftp_client.py", line 863, in _convert_status
    raise IOError(errno.EACCES, text)
PermissionError: [Errno 13] This server does not support operations to modify file attributes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Scripts\sftpTransfer\sftpTransfer-0.57.2.py", line 605, in <module>
    sentFilesList = sftpPut()
  File "D:\Scripts\sftpTransfer\sftpTransfer-0.57.2.py", line 487, in sftpPut
    session.put(localDirFile) # Preserve timestamp
  File "C:\Program Files\Python\Python36\lib\site-packages\pysftp\__init__.py", line 364, in put
    confirm=confirm)
  File "C:\Program Files\Python\Python36\lib\site-packages\paramiko\sftp_client.py", line 727, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
  File "C:\Program Files\Python\Python36\lib\site-packages\paramiko\sftp_client.py", line 692, in putfo
    'size mismatch in put!  {} != {}'.format(s.st_size, size))
OSError: size mismatch in put!  24 != 12
`

**Comment by Amrouane** [comment]
Hi, did you find the solution for this ?

**Comment by cobaltjacket** [comment]
@Amrouane, I have not. I was hoping for comments from the authors. Have you encountered the same issue?

**Comment by Amrouane** [comment]
@cobaltjacket sam issue but with `pysftp` library. I was trying to transfer a file to server mailbox and I keep getting the error:
```
Traceback (most recent call last):
 File "SFTP.py", line 54, in <module>
   srv.put('file.zip','file.zip')
 File "C:\Users\HP\Anaconda3\lib\site-packages\pysftp\__init__.py", line 364, in put
   confirm=confirm)
 File "C:\Users\HP\Anaconda3\lib\site-packages\paramiko\sftp_client.py", line 759, in put
   return self.putfo(fl, remotepath, file_size, callback, confirm)
 File "C:\Users\HP\Anaconda3\lib\site-packages\paramiko\sftp_client.py", line 723, in putfo
   "size mismatch in put!  {} != {}".format(s.st_size, size)
OSError: size mismatch in put!  4628344 != 330596
```

**Comment by sihcpro** [comment]
Do you check the seek() function.
