### ISSUE TITLE
Unknown exception: 'type' object is not iterable

### ISSUE THREAD

**Issue by iAbadia** [paramiko/paramiko#1223]
Hi, I get an Unknown exception when connecting to a server from my Raspberry Pi. I can run this same script from my laptop and it works. They both use the same paramiko version (2.4.1) and cryptography version (222). It's intended to try and connect to a server to check availability from a Telegram Bot. I'm using python2. Raspbian version 8 (jessie) with OpenSSH version `OpenSSH_6.7p1 Raspbian-5+deb8u4, OpenSSL 1.0.1t  3 May 2016`

```
Connected (version 2.0, client OpenSSH_7.4)
2018-05-29 11:38:35,567 - paramiko.transport - ERROR - Unknown exception: 'type' object is not iterable
2018-05-29 11:38:35,576 - paramiko.transport - ERROR - Traceback (most recent call last):
2018-05-29 11:38:35,576 - paramiko.transport - ERROR -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1933, in run
2018-05-29 11:38:35,577 - paramiko.transport - ERROR -     self._handler_table[ptype](self, m)
2018-05-29 11:38:35,577 - paramiko.transport - ERROR -   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 2032, in _negotiate_keys
2018-05-29 11:38:35,578 - paramiko.transport - ERROR -     self.kex_engine.start_kex()
2018-05-29 11:38:35,578 - paramiko.transport - ERROR -   File "/usr/local/lib/python2.7/dist-packages/paramiko/kex_ecdh_nist.py", line 32, in start_kex
2018-05-29 11:38:35,578 - paramiko.transport - ERROR -     self._generate_key_pair()
2018-05-29 11:38:35,579 - paramiko.transport - ERROR -   File "/usr/local/lib/python2.7/dist-packages/paramiko/kex_ecdh_nist.py", line 53, in _generate_key_pair
2018-05-29 11:38:35,579 - paramiko.transport - ERROR -     self.P = ec.generate_private_key(self.curve, default_backend())
2018-05-29 11:38:35,579 - paramiko.transport - ERROR -   File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
2018-05-29 11:38:35,580 - paramiko.transport - ERROR -     from cryptography.hazmat.backends.openssl.backend import backend
2018-05-29 11:38:35,580 - paramiko.transport - ERROR -   File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
2018-05-29 11:38:35,580 - paramiko.transport - ERROR -     from cryptography.hazmat.backends.openssl.backend import backend
2018-05-29 11:38:35,581 - paramiko.transport - ERROR -   File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 16, in <module>
2018-05-29 11:38:35,581 - paramiko.transport - ERROR -     from cryptography import utils, x509
2018-05-29 11:38:35,582 - paramiko.transport - ERROR -   File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
2018-05-29 11:38:35,582 - paramiko.transport - ERROR -     from cryptography.x509.base import (
2018-05-29 11:38:35,582 - paramiko.transport - ERROR -   File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/base.py", line 16, in <module>
2018-05-29 11:38:35,583 - paramiko.transport - ERROR -     from cryptography.x509.extensions import Extension, ExtensionType
2018-05-29 11:38:35,583 - paramiko.transport - ERROR -   File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/extensions.py", line 24, in <module>
2018-05-29 11:38:35,583 - paramiko.transport - ERROR -     from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
2018-05-29 11:38:35,584 - paramiko.transport - ERROR -   File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/general_name.py", line 18, in <module>
2018-05-29 11:38:35,584 - paramiko.transport - ERROR -     from cryptography.x509.name import Name
2018-05-29 11:38:35,584 - paramiko.transport - ERROR -   File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/name.py", line 28, in <module>
2018-05-29 11:38:35,584 - paramiko.transport - ERROR -     _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
2018-05-29 11:38:35,585 - paramiko.transport - ERROR - TypeError: 'type' object is not iterable
```

The code that produces the exception. Crashes on ssh.connect:
```
    ssh = paramiko.SSHClient()
    user = open('.ssh-user').read().rstrip()
    passwd = open('.ssh-passwd').read().rstrip()

    # Try to connect
    try:
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(CLUSTER_HOSTNAME, port=CLUSTER_PORT,
                    username=user, password=passwd, timeout=5)
        ssh.close()
        return True
    except (paramiko.ssh_exception.BadHostKeyException, paramiko.ssh_exception.AuthenticationException,
            paramiko.ssh_exception.SSHException, socket.error) as e:
        return False
```

**Comment by bitprophet** [comment]
This isn't familiar to me & I see no other tickets here about it. I appear to be using Cryptography 2.2.2 locally and the test suite's fine so this probably only affects some subset of paths (from the traceback, I guess your host or private keys are ECDH style? which we ought to be testing in a basic sense...)

I'd go look on Cryptography's tracker in case this is legit a bug on their end, esp since the final line of the traceback is wholly within cryptography and appears to be referencing a locally defined/imported value. Gonna close as "probably not our fault" but if you find otherwise please comment!
