### ISSUE TITLE
SSH Exception: Illegal info request from server on Cisco ISR4331/K9 (15.5)

### ISSUE THREAD

**Issue by b2sweety** [paramiko/paramiko#1230]
I am running a playbook to retrieve the running configuration on 2 Cisco ISR4331/K9 routers. Both are running on the same OS version and use same credentials to log in. However, I am getting an SSH Exception: Illegal info request from server on Cisco ISR4451-X/K9-Version 15.5(3)S2. on one of the devices. The other works perfectly well.
ssh v2 is enabled on the device

ansible 2.4.0.0
config file = /home/ycaty/ansible.cfg
configured module search path = [u'/usr/lib/python2.7/site-packages/ansible/modules/scp_sidecar/ansible_modules']
ansible python module location = /usr/lib/python2.7/site-packages/ansible
executable location = /bin/ansible
python version = 2.7.5 (default, Nov 6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

Name: paramiko
Version: 2.4.1
Summary: SSH2 protocol library
Home-page: https://github.com/paramiko/paramiko/
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
License: LGPL
Location: /usr/lib/python2.7/site-packages
Requires: pyasn1, bcrypt, cryptography, pynacl

Here is the log output:

2018-06-06 13:51:49,288 p=4148 u=root |  using connection plugin network_cli
2018-06-06 13:51:49,327 paramiko.transport starting thread (client mode): 0x36d0e50L
2018-06-06 13:51:49,327 paramiko.transport Local version/idstring: SSH-2.0-paramiko_2.4.1
2018-06-06 13:51:49,328 paramiko.transport Remote version/idstring: SSH-2.0-Cisco-1.25
2018-06-06 13:51:49,328 paramiko.transport Connected (version 2.0, client Cisco-1.25)
2018-06-06 13:51:49,328 paramiko.transport kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] client mac:[u'hmac-sha1', u'hmac-sha1-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
2018-06-06 13:51:49,328 paramiko.transport Kex agreed: diffie-hellman-group-exchange-sha1
2018-06-06 13:51:49,328 paramiko.transport HostKey agreed: ssh-rsa
2018-06-06 13:51:49,329 paramiko.transport Cipher agreed: aes128-ctr
2018-06-06 13:51:49,329 paramiko.transport MAC agreed: hmac-sha1
2018-06-06 13:51:49,329 paramiko.transport Compression agreed: none
2018-06-06 13:51:49,529 paramiko.transport Got server p (2048 bits)
2018-06-06 13:51:49,607 paramiko.transport kex engine KexGex specified hash_algo <built-in function openssl_sha1>
2018-06-06 13:51:49,607 paramiko.transport Switch to new keys ...
2018-06-06 13:51:49,809 paramiko.transport userauth is OK
2018-06-06 13:51:49,809 paramiko.transport Auth banner: ^M
^M
                   =======================^M
                   **     ATTENTION     **^M
                   =======================^M
^M
                     STAGING LAB DEVICE^M

2018-06-06 13:51:49,869 paramiko.transport Exception: Illegal info request from server
2018-06-06 13:51:49,881 paramiko.transport Traceback (most recent call last):
2018-06-06 13:51:49,881 paramiko.transport   File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1949, in run
2018-06-06 13:51:49,881 paramiko.transport     handler(self.auth_handler, m)
2018-06-06 13:51:49,881 paramiko.transport   File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 622, in _parse_userauth_info_request
2018-06-06 13:51:49,881 paramiko.transport     raise SSHException('Illegal info request from server')
2018-06-06 13:51:49,881 paramiko.transport SSHException: Illegal info request from server
2018-06-06 13:51:49,881 paramiko.transport
2018-06-06 13:51:49,892 p=4148 u=root |  connecting to host 100.65.248.130 returned an error
2018-06-06 13:51:49,892 p=4148 u=root |  Illegal info request from server
2018-06-06 13:52:49,634 p=4083 u=root |  fatal: [STG-OF4-CE2]: FAILED! => {"changed": false, "failed": true, "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"}

The login is successful when I manually log into it:

login as: ads.user

               =======================
               **     ATTENTION     **
               =======================

                 STAGING LAB DEVICE
Using keyboard-interactive authentication.
ADS_ID_password:

            -=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=-
               S Y S T E M   A C C E S S   W A R N I N G
            -=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=-
You have connected to a private network. This system is to only be used
by authorized personnel for authorized staging purposes. Unauthorized access
or activity is a violation

Here is the playbook:

hosts: CiscoAll
gather_facts: True
connection: local

tasks:

name: RETRIEVE CONFIGURATION FILE
ios_command:
commands:
- show run
host: "{{ ansible_host }}"
username: "{{ ansible_user }}"
password: "{{ ansible_ssh_pass }}"
timeout: 300
register: config

name: SAVE OUTPUT
copy:
content: "{{ config.stdout[0] }}"
dest: "/home/ycaty/configurations

Can someone help!

**Comment by b2sweety** [comment]
Here are the logs of the device on which the playbook runs successfully:

2018-06-06 15:09:14,079 p=6076 u=root |  control socket path is /root/.ansible/pc/a75e93b318
2018-06-06 15:09:14,079 p=6076 u=root |  current working directory is /home/ycaty/fortify-base/test/fortify-ycaty
2018-06-06 15:09:14,079 p=6076 u=root |  using connection plugin network_cli
2018-06-06 15:09:14,116 paramiko.transport starting thread (client mode): 0x237add0L
2018-06-06 15:09:14,116 paramiko.transport Local version/idstring: SSH-2.0-paramiko_2.4.1
2018-06-06 15:09:14,117 paramiko.transport Remote version/idstring: SSH-2.0-Cisco-1.25
2018-06-06 15:09:14,117 paramiko.transport Connected (version 2.0, client Cisco-1.25)
2018-06-06 15:09:14,117 paramiko.transport kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] client mac:[u'hmac-sha1', u'hmac-sha1-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
2018-06-06 15:09:14,117 paramiko.transport Kex agreed: diffie-hellman-group-exchange-sha1
2018-06-06 15:09:14,117 paramiko.transport HostKey agreed: ssh-rsa
2018-06-06 15:09:14,118 paramiko.transport Cipher agreed: aes128-ctr
2018-06-06 15:09:14,118 paramiko.transport MAC agreed: hmac-sha1
2018-06-06 15:09:14,118 paramiko.transport Compression agreed: none
2018-06-06 15:09:14,320 paramiko.transport Got server p (2048 bits)
2018-06-06 15:09:14,445 paramiko.transport kex engine KexGex specified hash_algo <built-in function openssl_sha1>
2018-06-06 15:09:14,446 paramiko.transport Switch to new keys ...
2018-06-06 15:09:14,646 paramiko.transport userauth is OK
2018-06-06 15:09:14,750 paramiko.transport Authentication (password) successful!
2018-06-06 15:09:14,751 p=6076 u=root |  ssh connection done, setting terminal
2018-06-06 15:09:14,752 paramiko.transport [chan 0] Max packet in: 32768 bytes
2018-06-06 15:09:14,753 paramiko.transport [chan 0] Max packet out: 4096 bytes
2018-06-06 15:09:14,753 paramiko.transport Secsh channel 0 opened.
2018-06-06 15:09:14,756 paramiko.transport [chan 0] Sesch channel 0 request ok
2018-06-06 15:09:14,758 paramiko.transport [chan 0] Sesch channel 0 request ok
2018-06-06 15:09:14,760 p=6076 u=root |  loaded terminal plugin for network_os ios
2018-06-06 15:09:14,762 p=6076 u=root |  loaded cliconf plugin for network_os ios
2018-06-06 15:09:14,762 p=6076 u=root |  firing event: on_open_shell()
2018-06-06 15:09:14,820 p=6076 u=root |  ssh connection has completed successfully
2018-06-06 15:09:14,820 p=6076 u=root |  connection established to 10.14.22.23 in 0:00:00.741527
2018-06-06 15:09:14,821 p=6076 u=root |  local socket is set to listening
2018-06-06 15:09:15,077 p=6076 u=root |  incoming request accepted on persistent socket
2018-06-06 15:09:15,077 p=6076 u=root |  socket operation is CONTEXT
2018-06-06 15:09:15,078 p=6076 u=root |  updating play_context for connection
2018-06-06 15:09:15,078 p=6076 u=root |  socket operation completed with rc 0
2018-06-06 15:09:15,078 p=6076 u=root |  socket operation is RUN
2018-06-06 15:09:15,078 p=6076 u=root |  socket operation completed with rc 0
2018-06-06 15:09:15,823 p=6076 u=root |  incoming request accepted on persistent socket
2018-06-06 15:09:15,823 p=6076 u=root |  socket operation is CONTEXT
2018-06-06 15:09:15,823 p=6076 u=root |  updating play_context for connection
2018-06-06 15:09:15,824 p=6076 u=root |  socket operation completed with rc 0
2018-06-06 15:09:15,824 p=6076 u=root |  socket operation is EXEC
2018-06-06 15:09:15,824 p=6076 u=root |  Command executed: prompt()
2018-06-06 15:09:15,824 p=6076 u=root |  socket operation completed with rc 0
2018-06-06 15:09:16,115 p=6076 u=root |  incoming request accepted on persistent socket
2018-06-06 15:09:16,115 p=6076 u=root |  socket operation is EXEC
2018-06-06 15:09:16,115 p=6076 u=root |  Command executed: {"answer": null, "command": "show run", "prompt": null}
2018-06-06 15:09:16,353 p=6076 u=root |  socket operation completed with rc 0

**Comment by radssh** [comment]
Looks like there's an issue with the different handling of authentication types 'password' and 'keyboard-interactive' , and how paramiko is handling the two routers. The successful log does show password authentication being successful, where your earlier log from manually logging in shows 'keyboard-interactive'. 
Paramiko does try some tricks to quietly offer a password in response to a server that requests keyboard-interactive authentication method, but based on the logs, it is not clear if that is what is taking place. The server appears to request additional info during authentication, which paramiko is only coded to expect when doing keyboard-interactive authentication, which leads to the exception.
For clarification, can you use the ssh command line client with the verbose (-v) option, and show the initial server response line that begins ```debug1: Authentications that can continue: ``` I'm guessing that the hosts are configured slightly differently, leading to one working for authentication while the other fails.

**Comment by b2sweety** [comment]
I tried the ssh command line on both the devices and here are the logs:

1. Device A (The one that works good in the problem) : 
debug1: Authentications that can continue: publickey,keyboard-interactive,password
debug1: Next authentication method: publickey
debug1: Trying private key: /home/ycaty/.ssh/id_rsa
debug1: Trying private key: /home/ycaty/.ssh/id_dsa
debug1: Trying private key: /home/ycaty/.ssh/id_ecdsa
debug1: Trying private key: /home/ycaty/.ssh/id_ed25519
debug1: Next authentication method: keyboard-interactive
ADS_ID_password:
debug1: Authentication succeeded (keyboard-interactive).
Authenticated to 100.64.56.241 ([100.64.56.241]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
DEVICE-A#



2. Device B ( The one on which the playbook fails)

debug1: Authentications that can continue: publickey,keyboard-interactive,password
debug1: Next authentication method: publickey
debug1: Trying private key: /home/ycaty/.ssh/id_rsa
debug1: Trying private key: /home/ycaty/.ssh/id_dsa
debug1: Trying private key: /home/ycaty/.ssh/id_ecdsa
debug1: Trying private key: /home/ycaty/.ssh/id_ed25519
debug1: Next authentication method: keyboard-interactive
ADS_ID_password:
debug1: Authentication succeeded (keyboard-interactive).
Authenticated to 100.65.248.130 ([100.65.248.130]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8


                -=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=-
                   S Y S T E M   A C C E S S   W A R N I N G
                -=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=- -=*=-
You have connected to a private network.  This system is to only be used
by authorized personnel for authorized staging purposes. Unauthorized access
or activity is a violation
DEVICE-B#exit

**Comment by b2sweety** [comment]
Hi @radssh : Any other tests or troubleshooting steps you think I should perform to isolate the issue?

**Comment by radssh** [comment]
@b2sweety  - Try the command line client, still with -v, but also add `-o KbdInteractiveAuthentication=no` and see if there is different behavior between the two hosts.

Because they both are advertising "debug1: Authentications that can continue: publickey,keyboard-interactive,password", the OpenSSH client is choosing keyboard-interactive, which works in both cases. Paramiko will choose to try password authentication first, using keyboard-interactive only as a fallback. Forcing the command line client to start with password (and disable keyboard-interactive) should hopefully reval more info.

**Comment by radssh** [comment]
Well, that is rather odd. The client option KbdInteractiveAuthentication=no should prevent the client from even trying any keyboard-interactive, but the logs show (in both cases) that after trying the various public keys to authenticate, it is following the next in server list: `debug1: Next authentication method: keyboard-interactive`, leaving password as the only remaining authentication method to try. If your client supports it, try `-o PreferredAuthentications=password` instead - that should bypass attempting any other method (publickey, keyboard-interactive) and begin straight away with a password authentication attempt.

**Comment by b2sweety** [comment]
Hi @radssh. I upgraded the ansible from 2.4 to 2.5.4. I ran the same playbook and got the below error. 

<100.65.248.130> starting connection from persistent connection plugin
<100.65.248.130> local domain socket does not exist, starting it
<100.65.248.130> control socket path is /root/.ansible/pc/f6e5194c91
<100.65.248.130>
The full traceback is:
Traceback (most recent call last):
  File "/bin/ansible-connection", line 87, in start
    self.connection._connect()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/network_cli.py", line 292, in _connect
    ssh = self.paramiko_conn._connect()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 240, in _connect
    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 348, in _connect_uncached
    raise AnsibleConnectionFailure(msg)
AnsibleConnectionFailure: Authentication failed.

fatal: [DEVICE-B]: FAILED! => {
    "msg": "Authentication failed."

Here is the log output:

2018-06-14 12:33:12,166 paramiko.transport Trying discovered key 4cad74153aceea8fc789fb95284707af in /root/.ssh/id_rsa
2018-06-14 12:33:12,347 paramiko.transport userauth is OK
2018-06-14 12:33:12,349 paramiko.transport Auth banner:

                   =======================
                   **     ATTENTION     **
                   =======================

                     STAGING LAB DEVICE

2018-06-14 12:33:14,350 paramiko.transport Authentication (publickey) failed.
2018-06-14 12:33:14,368 paramiko.transport Disconnect (code 2): Protocol error: expected packet type 50, got 5
2018-06-14 12:33:14,370 p=19925 u=root |  shutdown complete
2018-06-14 12:33:14,397 p=19858 u=root |  fatal: [STG-OF4-CE2]: FAILED! => {"msg": "Authentication failed."}

Looking at the error message: paramiko.transport Disconnect (code 2): Protocol error: expected packet type 50, got 5, I did some search and found below solution: make allow_agent=False and look_for_keys=False 

I have added both of them in the ansible.cfg, but no luck.
Could you please help in resolving this.

**Comment by radssh** [comment]
That last error is a bit different, and a notorious issue between Cisco (and other non-OpenSSH based hosts) and Paramiko. The paramiko client currently starts all authentications by sending a SSH protocol service request followed by the auth request (after the service request is accepted). Cisco seems to only expect a single service request, followed by however many auth requests as it takes to successfully complete authentication. On receiving the second service request (5) instead of auth request (50), it gets confused and punts the connection as a protocol error. OpenSSH behaves differently, allowing the new service request to start the user auth from the begnning.

Your original logs seemed to show the B server sending a response in a situation where paramiko was not expecting the message the server replied to the last paramiko user auth request. Paramiko sent a password auth request, and the server appeared to respond with (60 - additional info), which is defined in the protocol as a way to require the user to change password on login. That's what I was trying to guide you to recreate with OpenSSH command line client, but it seems that it reports that it is always issuing the keyboard-interactive (and not password) auth method.

There is some work being done to better align the paramiko authentication flow with the how OpenSSH does it, but that won't be available for a while. In the meantime, you could try to force Ansible to use OpenSSH instead of Paramiko for the connection handling - set the Ansible DEFAULT_TRANSPORT to 'ssh' and see if that clears up your Cisco connections.

**Comment by urskog84** [comment]
Hi I have the same issue. On ISR4351/K9 running IOS Version 03.16.07b.S,

@radssh Can you give me an example how to set the DEFAULT_TRANSPORT to 'ssh' in the YAML file.
i user 
```
vars:
  - ansible_connection: network_cli

```

as the connection driver/setting.
