### ISSUE TITLE
Getting exception on screen even with blanket exception

### ISSUE THREAD

**Issue by chrisotter92** [paramiko/paramiko#1237]
I think I'm running into a cosmetic bug in _check_banner. When I run my connection in python 2.7 with my blanket exception the connection just failed. When I run it in 3.5 though the code still finishes just fine but my screen gets blasted with an exception from paramiko (running netmiko). It looks like in 3.5 the raise in "Python35\lib\site-packages\paramiko\packet.py:550" when it returns to transport.py:2049 instead of just passing the raise to netmiko it's displaying it (as though it wasn't handled properly) yet the rest of my code still continues to run.

I tried adding a blanket exception within netmiko to see if it would catch and it does see the error and continues running but it still doesn't stop the exception from showing on my screen. Only when I added:
            except ConnectionResetError:
                raise
to transport.py:2047 did not display this exception. The only issue is though it is no longer an SSHException so I get back socket.error:
Socket exception: An existing connection was forcibly closed by the remote host (10054)
Connection to device timed-out:

Adding this to netmiko\base_connection:699:
            except paramiko.ssh_exception.SSHException as e:
                print(e)
I see the exception is caught but still get the below output from my blanket exception:
Print(e) gets > Error reading SSH protocol banner [WinError 10054] An existing connection was forcibly closed by the remote host

The exception I'm getting even with a blanket exception.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35\lib\site-packages\paramiko\transport.py", line 2044, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "C:\Program Files (x86)\Python35\lib\site-packages\paramiko\packet.py", line 353, in readline
    buf += self._read_timeout(timeout)
  File "C:\Program Files (x86)\Python35\lib\site-packages\paramiko\packet.py", line 540, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35\lib\site-packages\paramiko\transport.py", line 1893, in run
    self._check_banner()
  File "C:\Program Files (x86)\Python35\lib\site-packages\paramiko\transport.py", line 2050, in _check_banner
    raise SSHException('Error reading SSH protocol banner {}'.format(str(e)))
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by virtualluke** [comment]
The exception is being handled, paramiko just logs the exception and you are seeing the logging output. You could disable logging with logging.getLogger('paramiko.transport').disabled = True

**Comment by timelmer-uw** [comment]
This was frustratingly hard to find. It may be beneficial for future users to more clearly surface this behavior, perhaps on the https://docs.paramiko.org/en/stable/api/ssh_exception.html page?
