### ISSUE TITLE
client.connect() fails when done with assert

### ISSUE THREAD

**Issue by adriano-pinaffo** [paramiko/paramiko#1260]
Hello,

Basically when I connect using `assert` it fails (presumably connect always returns `False`, regardless if it worked?) and when I connect using no checking it works fine. Can anyone confirm if this is a bug or if this is the normal behavior?

I was hoping to have a better way to know if my `connect()` worked. I know I can check the transport to see if it is active, but still...

```
>>> import paramiko
>>> client = paramiko.SSHClient()
>>> client.load_system_host_keys()
>>> client.set_missing_host_key_policy(paramiko.WarningPolicy())
>>> privkey = paramiko.RSAKey.from_private_key_file("/home/svc_houston.copy-local/.ssh/id_rsa")
>>> assert client.connect("<ip>", 22, "<myuser>",  pkey = privkey), "Error connecting with privkey"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: Error connecting with privkey
>>> assert client.connect("<ip>", 22, "<myuser>", "<mypass>"), "failed with pass"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: failed with pass
>>>
>>> client.connect(("<ip>", 22, "<myuser>", pkey = privkey)
>>> client.get_transport().is_active()
True
>>> client.close()
>>> client.connect(("<ip>", 22, "<myuser>", "<mypass>")
>>> client.get_transport().is_active()
True
>>> client.close()
```

**Comment by ploxiln** [comment]
`client.connect()` does not return anything (which is equivalent to returning `None` in python). None is not "truthy" so assert fails. If it can't connect, it should probably raise an exception, in most cases.

**Comment by adriano-pinaffo** [comment]
I see, so in my expect: statement I should look for BadHostKeyException, AuthenticationException, SSHException or socket.error.

Out of curiosity, why can´t it return `client.get_transport().is_active()`? That would be `True` and assert would not fail.

**Comment by ploxiln** [comment]
I guess it could - but the result of an assert is either nothing or an exception, and the result of client.connect() is either nothing or an exception, so it's like it does the assert for you ...
