### ISSUE TITLE
Paramiko on Cygwin is broke due to nacl/bindings/crypto_box.py

### ISSUE THREAD

**Issue by jackeisenbach3** [paramiko/paramiko#1265]
Hi,

I am using Python 2.7.14 on Cygwin. When I try to import paramiko, I get the following error:
>>> import paramiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 57, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/usr/lib/python2.7/site-packages/paramiko/ed25519key.py", line 22, in <module>
    import nacl.signing
  File "/usr/lib/python2.7/site-packages/nacl/signing.py", line 19, in <module>
    import nacl.bindings
  File "/usr/lib/python2.7/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/usr/lib/python2.7/site-packages/nacl/bindings/crypto_box.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: No such file or directory

It sure would be nice if that gets fixed.
Thanks,
Jack

**Comment by jackeisenbach3** [comment]
Here's some additional info:
$ pip list
Package      Version
------------ -------
asn1crypto   0.22.0
bcrypt       3.1.4
cffi         1.9.1
cryptography 1.8.1
enum34       1.1.6
idna         2.5
ipaddress    1.0.18
packaging    16.8
paramiko     2.4.1
pip          18.0
ply          3.9
pyasn1       0.2.3
pycparser    2.17
PyNaCl       1.2.1
pyOpenSSL    16.2.0
pyparsing    2.1.10
setuptools   28.8.0
six          1.10.0

**Comment by bitprophet** [comment]
I haven't seen this particular error before and don't run Windows so I can't try to reproduce; a VERY lightweight offhand guess is that maybe your environment lacks some of the backend (C) libraries required for FFI? You might want to google around to see if that brings up anything else you could install via Cygwin's package manager. Good luck!

**Comment by bitprophet** [comment]
Also, the usual troubleshooting steps apply here - consider trying some alternate versions of Cryptography, PyNaCL etc to see if any of those don't exhibit this issue.

**Comment by TT--** [comment]
Maybe [this comment](https://github.com/pyca/pynacl/issues/404#issuecomment-429267083) from "maintainer of Cygwin-package of pynacl (named python2-nacl and python3-nacl)" could help:

> Since Cygwin already contains a package for sodium, the trick is to install with the exported SODIUM_INSTALL=system environment variable.
