### ISSUE TITLE
Unexpected close connection by 2nd end

### ISSUE THREAD

**Issue by SebaM** [paramiko/paramiko#130]
Team

I'm dealing w/ a bit strictly configured sshd which drops connection after 2 unsuccessful authorization attempts. While paramiko by default before using user/passwd pair trying to use my public keys. So the result is connection is dropped even before 1st attempt of use user/passwd pair and I can't go on this host.
I looked into code however I don't see simple flag to workaround this issue.
Here you are my debug:
[DEBUG](MainThread) 01-08 13:13:54 installer                          :1664  fda2 launching
    1. check_connection[DEBUG](fda2) 01-08 13:13:54 installer                          :1306  self.check_connection(host="fda2")
[DEBUG](MainThread) 01-08 13:13:54 installer                          :1664  fda1 launching
    1. check_connection[DEBUG](MainThread) 01-08 13:13:54 installer                          :1667  thds=[]
[DEBUG](fda1) 01-08 13:13:54 installer                          :1306  self.check_connection(host="fda1")
[DEBUG](Thread-1) 01-08 13:13:54 paramiko.transport                 :1404  starting thread (client mode): 0x1b3b4d0L
[INFO](Thread-1) 01-08 13:13:54 paramiko.transport                 :1404  Connected (version 2.0, client OpenSSH_5.3)
[DEBUG](Thread-2) 01-08 13:13:55 paramiko.transport                 :1404  starting thread (client mode): 0x1ae02b0L
[INFO](Thread-2) 01-08 13:13:55 paramiko.transport                 :1404  Connected (version 2.0, client OpenSSH_5.3)
[DEBUG](Thread-1) 01-08 13:13:55 paramiko.transport                 :1404  kex algos:['diffie-hellman-group-exchange-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'ssh-dss'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] client mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] server mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
[DEBUG](Thread-1) 01-08 13:13:55 paramiko.transport                 :1404  Ciphers agreed: local=aes128-ctr, remote=aes128-ctr
[DEBUG](Thread-1) 01-08 13:13:55 paramiko.transport                 :1404  using kex diffie-hellman-group1-sha1; server key type ssh-rsa; cipher: local aes128-ctr, remote aes128-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
[DEBUG](Thread-2) 01-08 13:13:55 paramiko.transport                 :1404  kex algos:['diffie-hellman-group-exchange-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'ssh-dss'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] client mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] server mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
[DEBUG](Thread-2) 01-08 13:13:55 paramiko.transport                 :1404  Ciphers agreed: local=aes128-ctr, remote=aes128-ctr
[DEBUG](Thread-2) 01-08 13:13:55 paramiko.transport                 :1404  using kex diffie-hellman-group1-sha1; server key type ssh-rsa; cipher: local aes128-ctr, remote aes128-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
[DEBUG](Thread-1) 01-08 13:13:55 paramiko.transport                 :1404  Switch to new keys ...
[DEBUG](Thread-2) 01-08 13:13:55 paramiko.transport                 :1404  Switch to new keys ...
[DEBUG](fda1) 01-08 13:13:55 paramiko.transport                 :1404  Adding ssh-rsa host key for 135.1.188.10: d02e72abc795cba6f5b9249ce71fd42f
[DEBUG](fda1) 01-08 13:13:55 paramiko.transport                 :1404  Trying key 5cb69f14f5afc690bc1229ae8d3ba532 from D:\coding\workspace2\CATE\src\cate\etc/keys//id_rsa
[DEBUG](fda2) 01-08 13:13:55 paramiko.transport                 :1404  Adding ssh-rsa host key for 135.1.188.21: bd53ea7998c76cee5be55eef31fdec3d
[DEBUG](fda2) 01-08 13:13:55 paramiko.transport                 :1404  Trying key 5cb69f14f5afc690bc1229ae8d3ba532 from D:\coding\workspace2\CATE\src\cate\etc/keys//id_rsa
[DEBUG](Thread-1) 01-08 13:13:55 paramiko.transport                 :1404  userauth is OK
[DEBUG](Thread-2) 01-08 13:13:56 paramiko.transport                 :1404  userauth is OK
[INFO](Thread-1) 01-08 13:13:58 paramiko.transport                 :1404  Authentication (publickey) failed.
[INFO](Thread-2) 01-08 13:13:58 paramiko.transport                 :1404  Authentication (publickey) failed.
[DEBUG](fda2) 01-08 13:13:58 paramiko.transport                 :1404  Trying discovered key 59df7e9cad2b04e299a4adf9b501cb78 in D:\Documents and Settings\malyska/.ssh/id_rsa
[DEBUG](fda1) 01-08 13:13:58 paramiko.transport                 :1404  Trying discovered key 59df7e9cad2b04e299a4adcb78 in D:\Documents and Settings\malyska/.ssh/id_rsa
[DEBUG](Thread-1) 01-08 13:13:58 paramiko.transport                 :1404  userauth is OK
[DEBUG](Thread-2) 01-08 13:13:59 paramiko.transport                 :1404  userauth is OK
[INFO](Thread-1) 01-08 13:14:00 paramiko.transport                 :1404  Authentication (publickey) failed.
[DEBUG](fda2) 01-08 13:14:00 paramiko.transport                 :1404  Trying discovered key 0d66fad0c1bdd560e7adfbb39956242d in D:\Documents and Settings\malyska/.ssh/id_dsa
[INFO](Thread-2) 01-08 13:14:00 paramiko.transport                 :1404  Authentication (publickey) failed.
[DEBUG](fda1) 01-08 13:14:00 paramiko.transport                 :1404  Trying discovered key 0d66fad0c1bdd560e7adfbb6242d in D:\Documents and Settings\malyska/.ssh/id_dsa
[DEBUG](Thread-1) 01-08 13:14:00 paramiko.transport                 :1404  userauth is OK
[DEBUG](Thread-2) 01-08 13:14:00 paramiko.transport                 :1404  userauth is OK
[INFO](Thread-1) 01-08 13:14:00 paramiko.transport                 :1404  Disconnect (code 2): Too many authentication failures for root
[ERROR](fda2) 01-08 13:14:00 installer                          :1310  No existing session
Traceback (most recent call last):
  File "D:\coding\workspace2\CATE\src\cate\utils\installer2.py", line 1308, in call_cmd
    ret = eval(cmd)
  File "<string>", line 1, in <module>
  File "D:\coding\workspace2\CATE\src\cate\utils\installer2.py", line 1302, in check_connection
    (out, ret, err) = conn.execute("uname -a", cmd_timeout=60) #cmd, timeout
  File "D:\coding\workspace2\CATE\src\cate\sdk\base\csys\shell\base_shell.py", line 95, in execute
    return self.client.execute(cmd, _args, *_kwargs)
  File "D:\coding\workspace2\CATE\src\cate\sdk\base\net\base_ssh_client.py", line 232, in execute
    self.connect('exec')
  File "D:\coding\workspace2\CATE\src\cate\sdk\base\net\base_ssh_client.py", line 155, in connect
    key_filename=self.pubkey)
  File "build\bdist.win32\egg\paramiko\client.py", line 338, in connect
    self._auth(username, password, pkey, key_filenames, allow_agent, look_for_keys)
  File "build\bdist.win32\egg\paramiko\client.py", line 519, in _auth
    raise saved_exception
SSHException: No existing session

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — this one looks like a usage-side question that's covered by existing `SSHClient.connect` kwargs.

The trace shows paramiko trying agent keys + `~/.ssh/id_rsa` + `~/.ssh/id_dsa` before falling back to password. The sshd is configured with a low `MaxAuthTries` (default 6) and disconnects after the failed key attempts — *before* the password attempt ever runs. That's not a paramiko bug; it's the server enforcing a limit, and the right knob is to skip the key attempts entirely when you only want password auth.

Evidence:
- [`paramiko/client.py` L216-289](https://github.com/paramiko/paramiko/blob/main/paramiko/client.py#L216-L289) — `SSHClient.connect(... allow_agent=True, look_for_keys=True ...)` both default to `True`; docstrings at L285-289 read "set to False to disable connecting to the SSH agent" / "set to False to disable searching for discoverable private key files in `~/.ssh/`".
- Concretely, when only password auth is intended:
  ```python
  client.connect(host, username=user, password=pw,
                 allow_agent=False, look_for_keys=False)
  ```
  bypasses the agent + `~/.ssh/` scan and submits exactly one auth attempt.

If the OP's report was about something else (e.g. paramiko failing to honor `allow_agent=False`), point me at a repro and I'll dig further. Otherwise would you mind closing this out?

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the file:line references above were verified manually against `main`.*

**Comment by bskinn** [comment]
Thanks for surfacing this, @jbbqqf -- I'm going to close based on the age of the ticket alone. If this is still a problem in modern paramiko, @SebaM, please reopen and provide a fresh repro.
