### ISSUE TITLE
testcase test_kex_gss.test_2_gsskex_and_auth_rekey fails

### ISSUE THREAD

**Issue by akruis** [paramiko/paramiko#1312]
Paramiko from pull request #1311, k5test is installed.
OS: CentOS Linux release 7.5.1804 (Core) 

If I comment line https://github.com/paramiko/paramiko/blob/a8e8f9aa89c2c1fe65e4477d8d553eb5e669c927/tests/test_kex_gss.py#L148
running `pytest -v -k test_2_gsskex_and_auth_rekey` yields this output:

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.5, pytest-3.2.5, py-1.6.0, pluggy-0.4.0 -- /scr/agis/kruis/py4paramiko_new_gssapi/bin/python
cachedir: .cache
rootdir: /scr/agis/kruis/paramiko, inifile: setup.cfg
plugins: xdist-1.23.1, forked-0.2
collecting ... collected 231 items

tests/test_kex_gss.py::GSSKexTest::test_2_gsskex_and_auth_rekey FAILED

=================================== FAILURES ===================================
___________________ GSSKexTest.test_2_gsskex_and_auth_rekey ____________________

self = <tests.test_kex_gss.GSSKexTest testMethod=test_2_gsskex_and_auth_rekey>

    def test_2_gsskex_and_auth_rekey(self):
        """
            Verify that Paramiko can rekey.
            """
>       self._test_gsskex_and_auth(gss_host=None, rekey=True)

tests/test_kex_gss.py:153: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_kex_gss.py:125: in _test_gsskex_and_auth
    self.tc.get_transport().renegotiate_keys()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <paramiko.Transport at 0x3c1a2a10L (unconnected)>

    def renegotiate_keys(self):
        """
            Force this session to switch to new keys.  Normally this is done
            automatically after the session hits a certain number of packets or
            bytes sent or received, but this method gives you the option of forcing
            new keys whenever you want.  Negotiating new keys causes a pause in
            traffic both ways as the two sides swap keys and do computations.  This
            method returns when the session has switched to new keys.
    
            :raises:
                `.SSHException` -- if the key renegotiation failed (which causes
                the session to end)
            """
        self.completion_event = threading.Event()
        self._send_kex_init()
        while True:
            self.completion_event.wait(0.1)
            if not self.active:
                e = self.get_exception()
                if e is not None:
>                   raise e
E                   EOFError

paramiko/transport.py:1064: EOFError
---------------------------- Captured stderr setup -----------------------------
[388.276100159]	DEBUG:k5test.realm:Using discovered path for kdb5_util (/usr/sbin/kdb5_util
[392.441034317]	DEBUG:k5test.realm:Using discovered path for krb5kdc (/usr/sbin/krb5kdc
[396.270036697]	DEBUG:k5test.realm:Using default path for kadmin_local (/usr/sbin/kadmin.local): Command '['which', 'kadmin_local']' returned non-zero exit status 1
[400.015115738]	DEBUG:k5test.realm:Using discovered path for kprop (/usr/sbin/kprop
[403.912067413]	DEBUG:k5test.realm:Using discovered path for kadmind (/usr/sbin/kadmind
[407.977104187]	DEBUG:k5test.realm:Using discovered path for kinit (/usr/bin/kinit
[411.964893341]	DEBUG:k5test.realm:Using discovered path for klist (/usr/bin/klist
[1072.36409187]	DEBUG:k5test.realm:[OUTPUT FROM `/usr/sbin/kdb5_util create -W -s -P master`]
Loading random data
Initializing database '/tmp/tmpKFgWI_-krbtest/db' for realm 'KRBTEST.COM',
master key name 'K/M@KRBTEST.COM'


[1130.02896309]	DEBUG:k5test.realm:[OUTPUT FROM `/usr/sbin/kadmin.local -q addprinc -pw usertmpKFgWI_-krbtest user@KRBTEST.COM`]
WARNING: no policy specified for user@KRBTEST.COM; defaulting to no policy
Authenticating as principal kruis/admin@KRBTEST.COM with password.
Principal "user@KRBTEST.COM" created.


[1187.67404556]	DEBUG:k5test.realm:[OUTPUT FROM `/usr/sbin/kadmin.local -q addprinc -pw admintmpKFgWI_-krbtest user/admin@KRBTEST.COM`]
WARNING: no policy specified for user/admin@KRBTEST.COM; defaulting to no policy
Authenticating as principal kruis/admin@KRBTEST.COM with password.
Principal "user/admin@KRBTEST.COM" created.


[1228.94310951]	DEBUG:k5test.realm:[OUTPUT FROM `/usr/sbin/kadmin.local -q addprinc -randkey host/fd2ea210cb61@KRBTEST.COM`]
WARNING: no policy specified for host/fd2ea210cb61@KRBTEST.COM; defaulting to no policy
Authenticating as principal kruis/admin@KRBTEST.COM with password.
Principal "host/fd2ea210cb61@KRBTEST.COM" created.


[1369.09008026]	DEBUG:k5test.realm:[OUTPUT FROM `/usr/sbin/kadmin.local -q ktadd -k /tmp/tmpKFgWI_-krbtest/keytab -norandkey host/fd2ea210cb61@KRBTEST.COM`]
Authenticating as principal kruis/admin@KRBTEST.COM with password.
Entry for principal host/fd2ea210cb61@KRBTEST.COM with kvno 1, encryption type aes256-cts-hmac-sha1-96 added to keytab WRFILE:/tmp/tmpKFgWI_-krbtest/keytab.
Entry for principal host/fd2ea210cb61@KRBTEST.COM with kvno 1, encryption type aes128-cts-hmac-sha1-96 added to keytab WRFILE:/tmp/tmpKFgWI_-krbtest/keytab.


[1380.30004501]	DEBUG:k5test.realm:[OUTPUT FROM `/usr/sbin/krb5kdc -n`]
krb5kdc: starting...


[1398.23794365]	DEBUG:k5test.realm:[OUTPUT FROM `/usr/bin/kinit -V user@KRBTEST.COM`]
Using default cache: /tmp/tmpKFgWI_-krbtest/ccache
Using principal: user@KRBTEST.COM
Password for user@KRBTEST.COM: 
Authenticated to Kerberos v5


[1403.53393555]	DEBUG:k5test.realm:[OUTPUT FROM `/usr/bin/klist /tmp/tmpKFgWI_-krbtest/ccache`]
Ticket cache: FILE:/tmp/tmpKFgWI_-krbtest/ccache
Default principal: user@KRBTEST.COM

Valid starting     Expires            Service principal
10/05/18 17:53:28  10/06/18 17:53:28  krbtgt/KRBTEST.COM@KRBTEST.COM


----------------------------- Captured stderr call -----------------------------
[1450.01506805]	DEBUG:paramiko.transport:starting thread (client mode): 0x3c1a2a10L
[1450.56009293]	DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.2
[1460.03007889]	DEBUG:paramiko.transport:starting thread (server mode): 0x3c1a2b10L
[1460.43610573]	DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.2
[1460.57701111]	DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-paramiko_2.4.2
[1460.82305908]	DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-paramiko_2.4.2
[1461.27700806]	INFO:paramiko.transport:Connected (version 2.0, client paramiko_2.4.2)
[1461.40789986]	INFO:paramiko.transport:Connected (version 2.0, client paramiko_2.4.2)
[1463.01794052]	DEBUG:paramiko.transport:kex algos:[u'gss-gex-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'gss-group14-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'gss-group1-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-ed25519', u'ecdsa-sha2-nistp256', u'ecdsa-sha2-nistp384', u'ecdsa-sha2-nistp521', u'ssh-dss'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'3des-cbc'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'3des-cbc'] client mac:[u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
[1463.2589817]	DEBUG:paramiko.transport:Kex agreed: gss-gex-sha1-toWM5Slw5Ew8Mqkay+al2g==
[1463.49811554]	DEBUG:paramiko.transport:kex algos:[u'gss-gex-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'gss-group14-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'gss-group1-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'3des-cbc'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'3des-cbc'] client mac:[u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
[1463.68598938]	DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
[1463.9339447]	DEBUG:paramiko.transport:Kex agreed: gss-gex-sha1-toWM5Slw5Ew8Mqkay+al2g==
[1464.04910088]	DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
[1464.2291069]	DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
[1464.35594559]	DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
[1464.50591087]	DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
[1464.65492249]	DEBUG:paramiko.transport:Compression agreed: none
[1464.79892731]	DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
[1465.061903]	DEBUG:paramiko.transport:Compression agreed: none
[1502.09093094]	DEBUG:paramiko.transport:Picking p (1024 <= 2048 <= 8192 bits)
[1502.58302689]	DEBUG:paramiko.transport:Got server p (2048 bits)
[1723.85406494]	DEBUG:paramiko.transport:kex engine KexGSSGex specified hash_algo None, falling back to sha1
[1769.73795891]	DEBUG:paramiko.transport:kex engine KexGSSGex specified hash_algo None, falling back to sha1
[1769.87195015]	DEBUG:paramiko.transport:Switch to new keys ...
[1771.39496803]	DEBUG:paramiko.transport:Switch to new keys ...
[1773.53811264]	DEBUG:paramiko.transport:userauth is OK
[1773.99492264]	DEBUG:paramiko.transport:Auth request (type=gssapi-keyex) service=ssh-connection, username=user@KRBTEST.COM
[1774.17588234]	INFO:paramiko.transport:Auth granted (gssapi-keyex).
[1774.55306053]	INFO:paramiko.transport:Authentication (gssapi-keyex) successful!
[1776.9100666]	DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
[1777.66108513]	DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
[1777.78196335]	DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
[1778.03587914]	DEBUG:paramiko.transport:Secsh channel 0 (session) opened.
[1778.65195274]	DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
[1778.74803543]	DEBUG:paramiko.transport:Secsh channel 0 opened.
[1781.34489059]	DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
[1782.46092796]	DEBUG:paramiko.transport:kex algos:[u'gss-gex-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'gss-group14-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'gss-group1-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-ed25519', u'ecdsa-sha2-nistp256', u'ecdsa-sha2-nistp384', u'ecdsa-sha2-nistp521', u'ssh-dss'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'3des-cbc'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'3des-cbc'] client mac:[u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
[1782.97400475]	DEBUG:paramiko.transport:kex algos:[u'gss-gex-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'gss-group14-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'gss-group1-sha1-toWM5Slw5Ew8Mqkay+al2g==', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'3des-cbc'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'3des-cbc'] client mac:[u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
[1783.14304352]	DEBUG:paramiko.transport:Kex agreed: gss-gex-sha1-toWM5Slw5Ew8Mqkay+al2g==
[1783.3468914]	DEBUG:paramiko.transport:Kex agreed: gss-gex-sha1-toWM5Slw5Ew8Mqkay+al2g==
[1783.57100487]	DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
[1783.71095657]	DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
[1783.93292427]	DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
[1784.12699699]	DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
[1784.31987762]	DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
[1784.49702263]	DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
[1784.72089767]	DEBUG:paramiko.transport:Compression agreed: none
[1784.85798836]	DEBUG:paramiko.transport:Compression agreed: none
[1785.58707237]	DEBUG:paramiko.transport:Picking p (1024 <= 2048 <= 8192 bits)
[1786.29493713]	DEBUG:paramiko.transport:Got server p (2048 bits)
[1899.5039463]	ERROR:paramiko.transport:Unknown exception: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (22): accept_sec_context called with existing context handle
[1901.23605728]	ERROR:paramiko.transport:Traceback (most recent call last):
[1901.3209343]	ERROR:paramiko.transport:  File "/scr/agis/kruis/paramiko/paramiko/transport.py", line 2002, in run
[1901.40509605]	ERROR:paramiko.transport:    self.kex_engine.parse_next(ptype, m)
[1901.48091316]	ERROR:paramiko.transport:  File "/scr/agis/kruis/paramiko/paramiko/kex_gss.py", line 384, in parse_next
[1901.55506134]	ERROR:paramiko.transport:    return self._parse_kexgss_gex_init(m)
[1901.62992477]	ERROR:paramiko.transport:  File "/scr/agis/kruis/paramiko/paramiko/kex_gss.py", line 529, in _parse_kexgss_gex_init
[1901.70288086]	ERROR:paramiko.transport:    self.gss_host, client_token
[1901.77702904]	ERROR:paramiko.transport:  File "/scr/agis/kruis/paramiko/paramiko/ssh_gss.py", line 539, in ssh_accept_sec_context
[1901.84998512]	ERROR:paramiko.transport:    token = self._gss_srv_ctxt.step(recv_token)
[1901.93390846]	ERROR:paramiko.transport:  File "<decorator-gen-9>", line 2, in step
[1902.00805664]	ERROR:paramiko.transport:  File "/scr/agis/kruis/py4paramiko_new_gssapi/lib/python2.7/site-packages/gssapi/_utils.py", line 167, in check_last_err
[1902.08292007]	ERROR:paramiko.transport:    return func(self, *args, **kwargs)
[1902.15611458]	ERROR:paramiko.transport:  File "<decorator-gen-5>", line 2, in step
[1902.23002434]	ERROR:paramiko.transport:  File "/scr/agis/kruis/py4paramiko_new_gssapi/lib/python2.7/site-packages/gssapi/_utils.py", line 127, in catch_and_return_token
[1902.30298042]	ERROR:paramiko.transport:    return func(self, *args, **kwargs)
[1902.37689018]	ERROR:paramiko.transport:  File "/scr/agis/kruis/py4paramiko_new_gssapi/lib/python2.7/site-packages/gssapi/sec_contexts.py", line 519, in step
[1902.45199203]	ERROR:paramiko.transport:    return self._acceptor_step(token=token)
[1902.52494812]	ERROR:paramiko.transport:  File "/scr/agis/kruis/py4paramiko_new_gssapi/lib/python2.7/site-packages/gssapi/sec_contexts.py", line 525, in _acceptor_step
[1902.63295174]	ERROR:paramiko.transport:    self, self._channel_bindings)
[1902.71091461]	ERROR:paramiko.transport:  File "gssapi/raw/sec_contexts.pyx", line 368, in gssapi.raw.sec_contexts.accept_sec_context
[1902.78506279]	ERROR:paramiko.transport:GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (22): accept_sec_context called with existing context handle
[1902.85992622]	ERROR:paramiko.transport:
[1903.10692787]	DEBUG:paramiko.transport:EOF in transport thread
============================= 230 tests deselected =============================
=================== 1 failed, 230 deselected in 1.89 seconds ===================
```

@SebastianDeiss any idea?

**Comment by SebastianDeiss** [comment]
Based on the error message, my guess is that ``accept_sec_context`` is called with an already valid security context and therefore is called too often.

**Comment by akruis** [comment]
Do we need two separate security contexts? RFC 4462 chapter 4 paragraph 3 indicates that we need the initial context and additional contexts for rekeying:

"This method may be used only if the initial key exchange was
   performed using a GSS-API-based key exchange method defined in
   accordance with Section 2.  The GSS-API context used with this method
   is always that established during an initial GSS-API-based key
   exchange.  Any context established during key exchange for the
   purpose of rekeying MUST NOT be used with this method."

As far as I know the code in ssh_gss.py it uses only one context.
https://github.com/paramiko/paramiko/blob/426529220b81c295bd0698308b148612918669d6/paramiko/ssh_gss.py#L122-L126

Is that the root cause for this issue?

**Comment by SebastianDeiss** [comment]
I'm not sure, because rekeying should have been fixed with #1065. So, my guess is that we fixed rekeying only for the client mode and the server mode causes the error or it has something to do with the test environment. Did you try to rekey with a Paramiko SSH server outside of the test environment?
