### ISSUE TITLE
PKey.from_private_key and PKey.from_private_key_file broken

### ISSUE THREAD

**Issue by vpodzime** [paramiko/paramiko#1316]
```python
>>> from paramiko.pkey import PKey
>>> pkey = PKey.from_private_key_file("some/path/to/key")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/paramiko/pkey.py", line 206, in from_private_key_file
    key = cls(filename=filename, password=password)
TypeError: __init__() got an unexpected keyword argument 'filename'
```

and a similar thing happens with `from_private_key` except that it is trying to use a nonexisting `file_obj` keyword argument.

**Comment by ploxiln** [comment]
see https://github.com/paramiko/paramiko/issues/1303#issuecomment-425147744

(Don't use `PKey`, use the appropriate subclass e.g. `RSAKey`)

**Comment by vpodzime** [comment]
Closing as duplicate of #1303
