### ISSUE TITLE
SSH into account on domain?

### ISSUE THREAD

**Issue by jmarshall9120** [paramiko/paramiko#1334]
It seems when trying to connect to user account on a domain authentication fails.
I'm trying to SSH into a windows server using Paramiko. There are two accounts on the server:

administrator

administrator.DOMAIN

the 'administrator' account is a local account and the 'administrator.DOMAIN' is network account on a domain.

Interestingly, Paramiko doesn't seem to want to connect to Domain accounts.

For instance - this works in Powershell (passing the domian):

```
> ssh DOMAIN\administrator@MYHOST 
> DOMAIN\administrator@HOST's password: myPassword
```

And this works in Powershell (no domain - login to local account):

```
> ssh administrator@MYHOST myPassword
> administrator@HOST's password: myPassword
```

This works in Python Paramiko (no domain - login to local account):

 ```
   >client = paramiko.SSHClient()
    >client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    >client.connect(hostname='MYHOST', username='administrator', password='myPassword')
```

This **does not** work in Python Paramiko (passing the domain):

```
    >client = paramiko.SSHClient()   >client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    >client.connect(hostname='MYHOST',  username='DOMAIN\administrator', password='myPassword')
```

Is this a known issue or is there someway to get paramiko to accept a domain account?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jmarshall\Desktop\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\paramiko\client.py", line 437, in connect
    passphrase,
  File "C:\Users\jmarshall\Desktop\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\paramiko\client.py", line 749, in _auth
    raise saved_exception
  File "C:\Users\jmarshall\Desktop\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\paramiko\client.py", line 736, in _auth
    self._transport.auth_password(username, password)
  File "C:\Users\jmarshall\Desktop\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\paramiko\transport.py", line 1436, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "C:\Users\jmarshall\Desktop\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\paramiko\auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
Socket exception: An existing connection was forcibly closed by the remote host (10054)
>>> client.connect(hostname='HOST', username='DOMAIN\administrator', password='myPassword')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jmarshall\Desktop\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\paramiko\client.py", line 437, in connect
    passphrase,
  File "C:\Users\jmarshall\Desktop\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\paramiko\client.py", line 749, in _auth
    raise saved_exception
  File "C:\Users\jmarshall\Desktop\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\paramiko\client.py", line 736, in _auth
    self._transport.auth_password(username, password)
  File "C:\Users\jmarshall\Desktop\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\paramiko\transport.py", line 1436, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "C:\Users\jmarshall\Desktop\ETL\ETLApp\ETLAppEnv_3_7\lib\site-packages\paramiko\auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```

I have a copy of my problem posted on SO [here](https://stackoverflow.com/questions/53234611/connect-ssh-to-user-account-on-domain)

**Comment by jmarshall9120** [comment]
Resolved this.  The domain can be specified as username@DOMAIN in the username keyword arg of the SSHClient.connect() method.
