### ISSUE TITLE
python gssapi support is written against dead experimental version of gssapi

### ISSUE THREAD

**Issue by mimi1vx** [paramiko/paramiko#1335]
https://github.com/pythongssapi/python-gssapi don't have this exception.

version of gssapi with this Exceptions (https://github.com/sigmaris/python-gssapi) has noted from 2015 is dead and please use version above

```
Traceback (most recent call last):
  File "/usr/bin/repose", line 11, in <module>
    load_entry_point('repose==1.4.0', 'console_scripts', 'repose')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/repose/main.py", line 5, in <module>
    from .argparsing import get_parser
  File "/usr/lib/python3.6/site-packages/repose/argparsing.py", line 9, in <module>
    from .host import ParseHosts
  File "/usr/lib/python3.6/site-packages/repose/host.py", line 5, in <module>
    from .target import Target
  File "/usr/lib/python3.6/site-packages/repose/target/__init__.py", line 6, in <module>
    from ..connection import Connection, CommandTimeout
  File "/usr/lib/python3.6/site-packages/repose/connection.py", line 11, in <module>
    import paramiko
  File "/usr/lib/python3.6/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 38, in <module>
    from paramiko.auth_handler import AuthHandler
  File "/usr/lib/python3.6/site-packages/paramiko/auth_handler.py", line 72, in <module>
    from paramiko.ssh_gss import GSSAuth, GSS_EXCEPTIONS
  File "/usr/lib/python3.6/site-packages/paramiko/ssh_gss.py", line 55, in <module>
    GSS_EXCEPTIONS = (gssapi.GSSException,)
AttributeError: module 'gssapi' has no attribute 'GSSException'
```

**Comment by ploxiln** [comment]
fixed in #1311
