### ISSUE TITLE
If a single known_hosts line is problematic, paramiko bombs

### ISSUE THREAD

**Issue by cpbotha** [paramiko/paramiko#1346]
A previous issue resulted in paramiko continuing if meeting an `SSHException` whilst parsing known_hosts. See https://github.com/paramiko/paramiko/issues/490

However, I've just run into a `Invalid EC key` error, which is raised as `ValueError` (see exception trace below) and hence still manages to bomb the whole process.

```
Debug: Establishing ssh connection with 'zimmer-vault.stonethree.com' through port '22' as user 'cpbotha'
Debug: SELECT count from state_info WHERE rowid=1
Debug: fetched: [(12,)]
Debug: UPDATE state_info SET count = 12 WHERE rowid = 1
Error: Traceback (most recent call last):
  File "/Users/cpbotha/Library/Python/3.6/lib/python/site-packages/dvc/command/data_sync.py", line 46, in do_run
    with_deps=self.args.with_deps)
  File "/Users/cpbotha/Library/Python/3.6/lib/python/site-packages/dvc/project.py", line 765, in push
    show_checksums=show_checksums)
  File "/Users/cpbotha/Library/Python/3.6/lib/python/site-packages/dvc/data_cloud.py", line 117, in push
    show_checksums=show_checksums)
  File "/Users/cpbotha/Library/Python/3.6/lib/python/site-packages/dvc/remote/local.py", line 721, in push
    exists = remote.exists(remote.md5s_to_path_infos(md5s))
  File "/Users/cpbotha/Library/Python/3.6/lib/python/site-packages/dvc/remote/ssh.py", line 106, in exists
    port=self.port)
  File "/Users/cpbotha/Library/Python/3.6/lib/python/site-packages/dvc/remote/ssh.py", line 86, in ssh
    ssh.load_system_host_keys()
  File "/Users/cpbotha/Library/Python/3.6/lib/python/site-packages/paramiko/client.py", line 104, in load_system_host_keys
    self._system_host_keys.load(filename)
  File "/Users/cpbotha/Library/Python/3.6/lib/python/site-packages/paramiko/hostkeys.py", line 97, in load
    e = HostKeyEntry.from_line(line, lineno)
  File "/Users/cpbotha/Library/Python/3.6/lib/python/site-packages/paramiko/hostkeys.py", line 360, in from_line
    key = ECDSAKey(data=decodebytes(key), validate_point=False)
  File "/Users/cpbotha/Library/Python/3.6/lib/python/site-packages/paramiko/ecdsakey.py", line 168, in __init__
    self.verifying_key = numbers.public_key(backend=default_backend())
  File "/Users/cpbotha/Library/Python/3.6/lib/python/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 329, in public_key
    return backend.load_elliptic_curve_public_numbers(self)
  File "/Users/cpbotha/Library/Python/3.6/lib/python/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1381, in load_elliptic_curve_public_numbers
    ec_cdata, numbers.x, numbers.y)
  File "/Users/cpbotha/Library/Python/3.6/lib/python/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1648, in _ec_key_set_public_key_affine_coordinates
    raise ValueError("Invalid EC key.")
ValueError: Invalid EC key.
```

**Comment by dingens** [comment]
I'd like to bump this. This behavior is not helpful. After all, the purpose of a `known_hosts` file is to find a matching key-hostname pair. There is no sense in aborting if there is an incorrect line, it can just be treated the same as a non-matching line. Paramiko should just skip it and continue searching. (This is what ssh does as well, so I assume there are no negative security implications.)

I've had this problem as well (broken known hosts file installed by corporate admins which I could not change). SSH continued working, but paramiko aborted. I could only solve it by patching paramiko as below.

I'd suggest you evaluate if a similar change could be added to paramiko.

```
--- a/paramiko/hostkeys.py
+++ b/paramiko/hostkeys.py
@@ -95,6 +95,10 @@
                     entry = HostKeyEntry.from_line(line, lineno)
                 except SSHException:
                     continue
+                except InvalidHostKey as e:
+                    import warnings
+                    warnings.warn(f'Invalid host key line found and ignored: {e!r}')
+
                 if entry is not None:
                     _hostnames = entry.hostnames
                     for h in _hostnames:
```
