### ISSUE TITLE
conn.write_channel() does not work some how in this code.

### ISSUE THREAD

**Issue by amangoel6** [paramiko/paramiko#1357]
I tried the redispatch() as below somehow it does not work for me. Below is the script and output. and a Debug file is attached with

Script:

#!/usr/bin/env python
import logging
import netmiko
import signal
from netmiko import ConnectHandler, redispatch
import time
import sys
import os

logging.basicConfig(filename='DebugLog.log', filemode='w', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

netmiko_exceptions = (netmiko.ssh_exception.NetMikoTimeoutException,netmiko.ssh_exception.NetMikoAuthenticationException)
os_exception = (OSError)
uname = 'xxxxxxxxx'
pswd = 'xxxxxxxxxxxxx'
enpswd = 'xxxxxxxxxxxxxxx'
device_ip = {'xx.xx.xx.xx','yy.yy.yy.yy'}
cmd2 = ['sh run user']

try:
        conn = ConnectHandler(device_type='cisco_ios',ip='zz.zz.zz.zz', username='xxxxx',password=pswd,secret = enpswd)
        print(conn.find_prompt())
        print(conn.enable())

        
except netmiko_exceptions as e:
        print('Failed to connect', e)
        
else:
        for ip_add in device_ip:
                cmd1 = 'ssh -l xxxxxx ' + ip_add + '\n'
                print(cmd1)
                conn.write_channel(cmd1)
                ou = conn.read_channel()
                print(ou)
                if 'yes/no' in ou:
                        conn.write_channel('yes\n')
                if 'assword:' in ou:
                        print('it found Password in if condition')
                        conn.write_channel(conn.pswd + '\n')
                        ou = conn.read_channel()
                        if '>' in ou:
                                conn.secret = enpswd
                                redispatch(conn, device_type='cisco_asa')
                                conn.enable()
                                print(conn.find_prompt())
                                
                for command in cmd2:
                        #print(command)
                        op = conn.send_command_expect(command,'#')
                        print(op)
                        conn.write_channel('exit\n')
                        print(conn.find_prompt())
print(conn.disconnect())

Output/Result:

Jumpswitch#

ssh -l goyala xx.xx.xx.xx

% Password:  timeout expired!
[Connection to xx.xx.xx.xx aborted: error status 0]
exit
ssh -l goyala yy.yy.yy.yy

Traceback (most recent call last):
  File "C:/Users/s2843189/Downloads/My Scripts/test3.py", line 45, in <module>
    conn.write_channel(cmd1)
  File "C:\Users\s2843189\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\base_connection.py", line 270, in write_channel
    self._write_channel(out_data)
  File "C:\Users\s2843189\AppData\Local\Programs\Python\Python36\lib\site-packages\netmiko\base_connection.py", line 248, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data))
  File "C:\Users\s2843189\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\channel.py", line 846, in sendall
    sent = self.send(s)
  File "C:\Users\s2843189\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\channel.py", line 801, in send
    return self._send(s, m)
  File "C:\Users\s2843189\AppData\Local\Programs\Python\Python36\lib\site-packages\paramiko\channel.py", line 1180, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed
>>>

**Comment by amangoel6** [comment]
[DebugLog.log](https://github.com/paramiko/paramiko/files/2687397/DebugLog.log)
this is the debug file
