### ISSUE TITLE
"save_host_keys" fails if host keys file is empty

### ISSUE THREAD

**Issue by cowlinator** [paramiko/paramiko#1370]
`SSHClient.save_host_keys(known_hosts)` fails if the `known_hosts` file does not exist.
`SSHClient.save_host_keys(known_hosts)` also fails if the `known_hosts` file does exist, but is empty.

The expected behavior of "saving to a file" is that the file can be empty and need not exist.

The stacktrace is 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 147, in save_host_keys
    for keytype, key in keys.items():
  File "/usr/lib/python2.7/_abcoll.py", line 414, in items
    return [(key, self[key]) for key in self]
  File "/usr/lib/python2.7/site-packages/paramiko/hostkeys.py", line 145, in __iter__
    for k in self.keys():
  File "/usr/lib/python2.7/site-packages/paramiko/hostkeys.py", line 182, in keys
    if e.key is not None
AttributeError: 'str' object has no attribute 'get_name'
```

Version: 2.4.2
OS: Alpine Linux v3.8

**Comment by cowlinator** [comment]
Nevermind.  The cryptic error I got, which led me to my conclusion, was in fact unrelated to the nonexistance of the host_file.  

It was the result of using `SSHClient.get_host_keys().add()` with a string instead of the "PKey" for the "key" parameter.  Unfortunately, this caused no error until I called `SSHClient.save_host_keys()`

**Comment by greiginsydney** [comment]
I've reached the same conclusion as you @cowlinator, so I don't think you're going mad.

On my Raspberry Pi (Raspbian GNU/Linux 9 (stretch)) and Python 2.7, I found I needed to create ~/.ssh/known_hosts before the the key creation/writeback process will work.

ssh.connect throws an exception (pasted below) if known_hosts doesn't exist:

```python
    try:
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        # get host key, if we know one
        try:
            ssh.load_host_keys(os.path.expanduser('~/.ssh/known_hosts'))
            log('Paramiko loaded hosts keys file OK')
        except:
            log('Paramiko unable to open host keys file')
        ssh.connect(
            hostname=sftpServer,
            port=sftpPort,
            username=sftpUser,
            password=sftpPassword,
        )
        sftp = ssh.open_sftp()
    except paramiko.AuthenticationException as e:
        log('Authentication failed: ' + str(e))
        log('STATUS: SFTP Authentication failed')
        return
    except paramiko.SSHException as e:
        log('Unable to establish SSH connection: ' + str(e))
        if ('Connection timed out' in str(e)):
            log('STATUS: SFTP timed out connecting to ' + sftpServer)
        else:
            log('STATUS: SFTP Unable to establish SSH connection')
        return
    except paramiko.BadHostKeyException as e:
        log("Unable to verify server's host key: " + str(e))
        log("STATUS: SFTP Unable to verify server's host key")
        return
    except Exception as e:
        log('Exception signing in to SFTP server: ' + str(e))
        log('STATUS: SFTP exception signing in')
        return
```

Throws
```
[Errno 2] No such file or directory: '/home/pi/.ssh/known_hosts'
```

- Greig.

**Comment by ChipmunkV** [comment]
Why does `SSHClient.get_host_keys().add()` have the key type both as a keytype parameter ("ssh-rsa", "ssh-dss") and also as the type of the key to pass (like RSAKey,  ECDSAKey, DSSKey)?
