### ISSUE TITLE
Key format test broken on windows

### ISSUE THREAD

**Issue by Zageron** [paramiko/paramiko#1385]
https://github.com/paramiko/paramiko/blob/master/paramiko/pkey.py#L282-L289

**Comment by Zageron** [comment]
```
...
863 ERROR: not a valid RSA private key file                                                                                                 
[ERROR] not a valid RSA private key file                                                                                                    
863 DEBUG: not a valid RSA private key file                                                                                                 
Traceback (most recent call last):                                                                                                          
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\pyupdater\cli\__init__.py", line 108, in main               
    _real_main(args)                                                                                                                        
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\pyupdater\cli\__init__.py", line 84, in _real_main          
    dispatch_command(args, pyi_args)                                                                                                        
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\pyupdater\cli\__init__.py", line 97, in dispatch_command    
    cmd(args, pyi_args)                                                                                                                     
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\pyupdater\cli\commands.py", line 416, in _cmd_upload        
    pyu.set_uploader(upload_service, ns.keep)                                                                                               
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\pyupdater\core.py", line 90, in set_uploader                
    self.up.set_uploader(requested_uploader, keep)                                                                                          
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\pyupdater\uploader.py", line 97, in set_uploader            
    self.uploader = self.mgr.get_plugin(requested_uploader, init=True)                                                                      
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\pyupdater\utils\__init__.py", line 167, in get_plugin       
    plugin.init_config(config)                                                                                                              
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\scp_uploader.py", line 87, in init_config                   
    self.connect()                                                                                                                          
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\scp_uploader.py", line 136, in connect                      
    self.ssh.connect(self.host, **data)                                                                                                     
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\paramiko\client.py", line 437, in connect                   
    passphrase,                                                                                                                             
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\paramiko\client.py", line 749, in _auth                     
    raise saved_exception                                                                                                                   
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\paramiko\client.py", line 720, in _auth                     
    filename, pkey_class, passphrase                                                                                                        
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\paramiko\client.py", line 571, in _key_from_filepath        
    key = klass.from_private_key_file(key_path, password)                                                                                   
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\paramiko\pkey.py", line 206, in from_private_key_file       
    key = cls(filename=filename, password=password)                                                                                         
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\paramiko\rsakey.py", line 55, in __init__                   
    self._from_private_key_file(filename, password)                                                                                         
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\paramiko\rsakey.py", line 175, in _from_private_key_file    
    data = self._read_private_key_file("RSA", filename, password)                                                                           
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\paramiko\pkey.py", line 279, in _read_private_key_file      
    data = self._read_private_key(tag, f, password)                                                                                         
  File "c:\users\erane\appdata\local\programs\python\python36\lib\site-packages\paramiko\pkey.py", line 289, in _read_private_key           
    raise SSHException("not a valid " + tag + " private key file")                                                                          
paramiko.ssh_exception.SSHException: not a valid RSA private key file                                                                       
866 DEBUG: EOF in transport thread                                                                                                          
not a valid RSA private key file                                                                                                            
```

**Comment by Zageron** [comment]
Of course. Even after hours of testing and wasted time, as soon as I post it works.
The tool I am using was using the wrong key the entire time.
