### ISSUE TITLE
getting error after installing in Cygwin

### ISSUE THREAD

**Issue by abirlal** [paramiko/paramiko#1387]
Getting error after installing in Cygwin Windows 7.
Errors are as follows

Python 2.7.14 (default, Oct 31 2017, 21:12:13)
[GCC 6.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 90, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/usr/lib/python2.7/site-packages/paramiko/ed25519key.py", line 22, in <module>
    import nacl.signing
  File "/usr/lib/python2.7/site-packages/nacl/signing.py", line 19, in <module>
    import nacl.bindings
  File "/usr/lib/python2.7/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/usr/lib/python2.7/site-packages/nacl/bindings/crypto_box.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: No such file or directory

**Comment by ploxiln** [comment]
see #1265
