### ISSUE TITLE
'SSHException: No existing session' when multiple ssh keys in ssh-agent

### ISSUE THREAD

**Issue by eleksis** [paramiko/paramiko#1390]
Although similar ticket exists #1097 
I don't have exactly the same environment/setting, when this exception occurs.

**Example**

>import paramiko
>ssh = paramiko.SSHClient()
>ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>ssh.connect(ciscodevice, username=user, allow_agent=True)

**Setup** 

- Debian 9, Python 2.7.13, paramiko==2.4.2

- ssh-agent running, with 2 rsa-2048 keys (neither one is passphrase protected)

- Trying to connect to Cisco device (so far i tried 1941, 4500X, CX2960)

**Expected behavior**

Paramiko should try to use every key available from ssh-agent, to find the right one. This works if i try to connect to any linux server.

**Result**
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.virtualenvs/xyz/local/lib/python2.7/site-packages/paramiko/client.py", line 437, in connect
    passphrase,
  File "/home/me/.virtualenvs/xyz/local/lib/python2.7/site-packages/paramiko/client.py", line 749, in _auth
    raise saved_exception
paramiko.ssh_exception.SSHException: No existing session
```

**Notice**

If i remove unnecessary key from ssh-agent, and only leave the right one, it connects successfully.

**Comment by laughlinbarker** [comment]
I'm experiencing similar, with pure user/pass authentication method (paramiko==2.4.2). The first connection attempt to a remote host throws `No existing session`, while all following attempts succeed.

**Comment by dimka-rs** [comment]
Same here:
```
>>> import paramiko
>>> client = paramiko.SSHClient()
>>> client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> client.connect('192.168.2.100', username='root', password='root', allow_agent=False, look_for_keys=False, timeout=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/router/.local/lib/python3.6/site-packages/paramiko-2.4.2-py3.6.egg/paramiko/client.py", line 403, in connect
    server_key = t.get_remote_server_key()
  File "/home/router/.local/lib/python3.6/site-packages/paramiko-2.4.2-py3.6.egg/paramiko/transport.py", line 761, in get_remote_server_key
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
>>> 
```
Manual SSH connection to given ip with root/root works fine.
paramiko 2.4.2, **downgrading to 2.0.2 helps**

**Comment by ploxiln** [comment]
I think https://github.com/paramiko/paramiko/pull/1106 may fix your issue.

The openssh client normally makes a "none" auth request first, and then looks at the response to decide which type of auth request to make next. These appliances probably have a bug or "accidental assumption" that the first request is a "throw-away". That PR adds the initial "none" request to paramiko.

**Comment by zed** [comment]
I don't see how #1106 might help with the "If i remove unnecessary key from ssh-agent, and only leave the right one, it connects successfully." case

**Comment by Lightjohn** [comment]
I can confirm the sentence "If i remove unnecessary key from ssh-agent, and only leave the right one, it connects successfully." I store my key in keepass and when I opened my second DB my python script broke because of that. Closing the second DB solved the issue.

**Comment by DCkQ6** [comment]
I hit me also, I also removed secondary key from agent, but it forced me to increase a privileges of first key what is inconvenient for me ;(

**Comment by nise** [comment]
What do you with "If i remove unnecessary key from ssh-agent, and only leave the right one, it connects successfully."? Which ssh-agent?

**Comment by vincentbernat** [comment]
Rebasing #1106 on top of master (to get Python3 compatibility) does not solve the issue either for me.

**Comment by vincentbernat** [comment]
After tracing a bit, the issue is that Paramiko does that:

```
→ 5 SSH_MSG_SERVICE_REQUEST ssh-userauth
← 6 SSH_MSG_SERVICE_ACCEPT
→ 50 SSH_MSG_USERAUTH_REQUEST
← 51 SSH_MSG_USERAUTH_FAILURE
→ 5 SSH_MSG_SERVICE_REQUEST ssh-userauth
```

Then, Cisco does not expect to request `ssh-userauth` again and terminates the connection.

OpenSSH does that instead:

```
→ 5 SSH_MSG_SERVICE_REQUEST ssh-userauth
← 6 SSH_MSG_SERVICE_ACCEPT
→ 50 SSH_MSG_USERAUTH_REQUEST
← 51 SSH_MSG_USERAUTH_FAILURE
→ 50 SSH_MSG_USERAUTH_REQUEST
← 51 SSH_MSG_USERAUTH_FAILURE
→ 50 SSH_MSG_USERAUTH_REQUEST
← 52 SSH_MSG_USERAUTH_SUCCESS
```

So, to solve the issue, Paramiko should keep the auth request alive and requires one key after another instead of asking for `ssh-userauth` service. This would also be more efficient.

Looking at the code, it seems it's not easy to change that. Maybe we could provide an iterator on keys to `AuthHandler()` instead of a single key.

**Comment by vincentbernat** [comment]
I've fixed this and another subsequent problem in #1687. If someone else could test this solves the issue on their side as well.

**Comment by IPvSean** [comment]
any update here?

**Comment by bitprophet** [comment]
Linking this to #387 in case it's relevant to that overhaul 🤔

**Comment by mavcunha** [comment]
Hi all, it happened with my code. My agent has several keys and `client.py` (https://github.com/paramiko/paramiko/blob/1824a27c644132e5d46f2294c1e2fa131c5235,59/paramiko/client.py#L699) loops trying all of them. Even if you have a working key, if it is too down the list the SSH server will drop the connection; here's the trace:

```
Connected (version 2.0, client OpenSSH_7.6p1)
Authentication (publickey) failed.
Authentication (publickey) failed.
Authentication (publickey) failed.
Authentication (publickey) failed.
Authentication (publickey) failed.
Disconnect (code 2): Too many authentication failures
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mvaltas/Projects/blog/main.py", line 92, in deploy_uat
    result = Connection('blog_uat').run(command)
  File "<decorator-gen-3>", line 2, in run
  File "/Users/mvaltas/Library/Caches/pypoetry/virtualenvs/blog-mEfBCwKq-py3.10/lib/python3.10/site-packages/fabric/connection.py", line 29, in opens
    self.open()
  File "/Users/mvaltas/Library/Caches/pypoetry/virtualenvs/blog-mEfBCwKq-py3.10/lib/python3.10/site-packages/fabric/connection.py", line 636, in open
    self.client.connect(**kwargs)
  File "/Users/mvaltas/Library/Caches/pypoetry/virtualenvs/blog-mEfBCwKq-py3.10/lib/python3.10/site-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/Users/mvaltas/Library/Caches/pypoetry/virtualenvs/blog-mEfBCwKq-py3.10/lib/python3.10/site-packages/paramiko/client.py", line 766, in _auth
    raise saved_exception
  File "/Users/mvaltas/Library/Caches/pypoetry/virtualenvs/blog-mEfBCwKq-py3.10/lib/python3.10/site-packages/paramiko/client.py", line 702, in _auth
    self._transport.auth_publickey(username, key)
  File "/Users/mvaltas/Library/Caches/pypoetry/virtualenvs/blog-mEfBCwKq-py3.10/lib/python3.10/site-packages/paramiko/transport.py", line 1625, in auth_publickey
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
```

The way the ssh command line deals with this is using the `IdentityFile` which can point to a public key and ask the agent for that private key. So, if your `IdentityFile ~/.ssh/mykey.pub` the code would filter for `mykey` private.

I believe paramiko could do the same on https://github.com/paramiko/paramiko/blob/1824a27c644132e5d46f2294c1e2fa131c523559/paramiko/client.py#L699 and if has `key_name` or something defined it should not attempt all keys but filter the list first.

Hope this helps,
Cheers.

**Comment by NBardelot** [comment]
See OpenSSH documentation for sshd_config (if it is your SSH server implementation): 

**LoginGraceTime**
*The server disconnects after this time if the user has not successfully logged in. If the value is 0, there is no time limit. The 
**default is 120 seconds.***

**MaxSessions**
*Specifies the maximum number of open shell, login or subsystem (e.g. sftp) sessions permitted per network connection. Multiple sessions may be established by clients that support connection multiplexing. Setting MaxSessions to 1 will effectively disable session multiplexing, whereas setting it to 0 will prevent all shell, login and subsystem sessions while still permitting forwarding. **The default is 10.***

**MaxStartups**
*Specifies the maximum number of concurrent unauthenticated connections to the SSH daemon. Additional connections will be dropped until authentication succeeds or the LoginGraceTime expires for a connection. The default is 10:30:100.
Alternatively, random early drop can be enabled by specifying the three colon separated values start:rate:full (e.g. "10:30:60"). sshd(8) will refuse connection attempts with a probability of rate/100 (30%) if there are currently start (10) unauthenticated connections. The probability increases linearly and all connection attempts are refused if the number of unauthenticated connections reaches full (60).*

**PerSourceMaxStartups**
*Specifies the number of unauthenticated connections allowed from a given source address, or “none” if there is no limit. This limit is applied in addition to MaxStartups, whichever is lower. **The default is none.***

One or more of those limits might be reached while paramiko tries every key one by one.
