### ISSUE TITLE
SSHClient  password connect Authentication failed

### ISSUE THREAD

**Issue by zhaoxiaobin** [paramiko/paramiko#1423]
>>> paramiko.__version__
'2.4.1'
>>> ssh = paramiko.SSHClient()
>>> ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> ssh.connect(hostname='10.9.69.34',port=11130,username='isadmin',password='xxxxxx')
print client password exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/repo3/xiaobinz/vene/lib/python2.7/site-packages/paramiko/client.py", line 426, in connect
    passphrase,
  File "/repo3/xiaobinz/vene/lib/python2.7/site-packages/paramiko/client.py", line 718, in _auth
    raise saved_exception
paramiko.ssh_exception.AuthenticationException: Authentication failed.
>>> 

In linux shell ssh work fine
$ ssh -p 11130 isadmin@10.9.69.34
Setup is free to be used

isadmin@10.9.69.34's password: 

{nt1101}[USR0-shell]>
{nt1101}[USR0-shell]>

any clue for this issue?

**Comment by monofox** [comment]
Having similar problem. Server is a Red Hat server.
When i'm using SSH i get following authentication methods shown:
`debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password`

If i'm using paramiko 2.6.0 i get following authentication methods provided:
`Allowed methods: ['publickey', 'gssapi-keyex', 'gssapi-with-mic', 'keyboard-interactive'] `

We've enabled password authentication. And it works with regular ssh client. Just Paramiko is identifying keyboard-interactive instead of password authentication?

Paramiko Log: https://gist.github.com/monofox/edf7a7dcbab68cfe4540f39900b2b2c3 
SSH-Client Log: https://gist.github.com/monofox/d9da556d0bb2860ec5395f92ca75e7a6

**Comment by catafest** [comment]
works well ... for ssh port 22

#!/usr/bin/env python
import paramiko
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
conn= client.connect('127.0.0.1', port='22', username='your_user', password='your_pass')
stdin, stdout, stderr=client.exec_command('sudo hostname;w')
for line in stdout:
    print (line)

**Comment by monofox** [comment]
@catafest : thanks for your comment. Happened with SFTP. But tested now SSHClient as well as separate simple SFTP script, working. Can connect. Maybe @zhaoxiaobin could also test with Paramiko 2.6.0 and/or append log files here?

**Comment by danielMandelblat** [comment]
> works well ... for ssh port 22
> 
> #!/usr/bin/env python
> import paramiko
> client = paramiko.SSHClient()
> client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
> conn= client.connect('127.0.0.1', port='22', username='your_user', password='your_pass')
> stdin, stdout, stderr=client.exec_command('sudo hostname;w')
> for line in stdout:
> print (line)

Thanks, it works for me.

**Comment by eduardofbrito** [comment]
https://github.com/paramiko/paramiko/issues/391
