### ISSUE TITLE
[Feature Request] Expose all of remote's host keys

### ISSUE THREAD

**Issue by johnnybubonic** [paramiko/paramiko#1431]
Currently, it seems `Transport().get_remote_server_key()` returns a single hostkey (namely, the one that a connection verifies against).

Would it be possible to add functionality (probably via a different method, such as `Transport.get_all_remote_server_keys()` or a more brief `Transport().get_remote_server_keys()` (note the "keys", plural) to fetch ALL remote's host keys (such as **ssh-keyscan(1)**)? Ideally with parameters that support **ssh-keyscan**'s _-c_, _-D_, _-H_, and _-t_ switches as well. This is useful in gathering information about a remote SSH server without actually authorizing, etc. for e.g. auditing purposes.

Thoughts?

**Comment by radssh** [comment]
The `get_remote_server_key()` only references one key, specifically the one that was agreed upon during the protocol key exchange dialog. `ssh-keyscan` does its work by opening multiple connections, each passing a limited list of hostkey algorithms, and reporting each hostkey that was used for each successful key exchange negotiation. This does not require user authentication, since the key exchange is done at the Transport level, but does require a separate Transport for each key or certificate type probe. `ssh_keyscan` does group together "ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521" as a single request. This could be implemented by a function that made use of multiple Transports, instead of as a Transport method.

OpenSSH does support an extension that may be used on an authenticated Transport to collect a full list of host keys from the server, via a global request: the server may send to the client  "hostkeys-00@openssh.com" with a list of all host keys. This is used with the ssh client option UpdateHostKeys. Currently paramiko does nothing (other than logging) upon receiving a "hostkeys-00@openssh.com" global request, but this could be used as an alternative mechanism to do what you are seeking. This would require successful user authentication, as well as the remote server being OpenSSH (or supporting this OpenSSH extension).

**Comment by johnnybubonic** [comment]
Ah, this clears things up for me. I was under the impression the key algo negotiation was done after the transport layer had already been established, though in retrospect that doesn't exactly make much sense from either a structural nor ssh -vvv output's perspective, does it? Whoops.

In other words, this should be possible if I instantiated separate Transport objects for each hostkey algo I wished to test and seeing if I either get an exception or checking the result of .get_remote_server_key(), correct? (I'm not sure which it'd do; I'll have to test unless you know off the top of your head which it does.)

**Comment by johnnybubonic** [comment]
hi, revisiting this.

So this:

```Python
import paramiko

_dest = ('localhost', 22)

keys = []

t = paramiko.Transport(_dest)
secopts = t.get_security_options()
key_types = {k: None for k in list(secopts.key_types)}
t.close()

for kt in key_types:
    t = paramiko.Transport(_dest)
    t._preferred_keys = (kt, )
    t.start_client()
    key = t.get_remote_server_key()
    keys.append(key.get_base64())
    t.close()
```

gets me there, in the sense that it lets me iterate through hostkey types **without** authorizing (like **ssh-keyscan(1)** does, which is what I want).

HOWEVER.

On the call to .start_client(), if the server does NOT support a hostkey of a given type, a **chained** exception occurs:

```Python
Exception: Incompatible ssh peer (no acceptable host key)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/paramiko/transport.py", line 2083, in run
    self._handler_table[ptype](self, m)
  File "/usr/lib/python3.7/site-packages/paramiko/transport.py", line 2198, in _negotiate_keys
    self._parse_kex_init(m)
  File "/usr/lib/python3.7/site-packages/paramiko/transport.py", line 2378, in _parse_kex_init
    "Incompatible ssh peer (no acceptable host key)"
paramiko.ssh_exception.SSHException: Incompatible ssh peer (no acceptable host key)

Traceback (most recent call last):
  File "./test_ssh.py", line X, in _get_hostkey
    trnsprt.start_client()
  File "/usr/lib/python3.7/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/usr/lib/python3.7/site-packages/paramiko/transport.py", line 2083, in run
    self._handler_table[ptype](self, m)
  File "/usr/lib/python3.7/site-packages/paramiko/transport.py", line 2198, in _negotiate_keys
    self._parse_kex_init(m)
  File "/usr/lib/python3.7/site-packages/paramiko/transport.py", line 2378, in _parse_kex_init
    "Incompatible ssh peer (no acceptable host key)"
paramiko.ssh_exception.SSHException: Incompatible ssh peer (no acceptable host key)
```

Which, normally, okay. But because you **cannot** catch inner exceptions in a chain, ONLY the most outer exception, I can't catch these. I can do a pass or continue or log the outer one or whatever, and yeah, it'll continue - but _the inner exceptions still print to STDERR_.

**Please** consider implementing an actual method for unauthenticated hostkey scanning, or at the LEAST handle those exceptions in a way so that they don't get chained so I can catch them. Please. I'm begging.

**Comment by johnnybubonic** [comment]
otherwise one has to do some absolutely cockamamie things they have no business doing, e.g.:

```Python
import os
import paramiko
import sys

_dest = ('localhost', 22)

keys = []

t = paramiko.Transport(_dest)
secopts = t.get_security_options()
key_types = {k: None for k in list(secopts.key_types)}
t.close()

orig_stderr = sys.stderr
sys.stderr = open(os.devnull, 'w')
for kt in key_types:
    t = paramiko.Transport(_dest)
    t._preferred_keys = (kt, )
    t.start_client()
    key = t.get_remote_server_key()
    keys.append(key.get_base64())
    t.close()
sys.stderr.close()
sys.stderr = orig_stderr
```

So. Yeah. I feel dirty now. This can't be an ideal way of handling this.

**Comment by radssh** [comment]
That's not too far off from what I wound up cobbling together to do something similar.

Rather than `get_security_options`, I directly grabbed the key list from `Transport._preferred_keys`, and I explicitly called `t.logger.setLevel(logging.FATAL)` to suppress the error logging. You also do not have to ask for the keys one by one - any types at the head of the list that the server skipped over imply that there is no hostkey of that type available from the server. As I got host keys, I would pop the key type from the tuple and try again, so the only `Incompatible ssh peer (no acceptable host key)` I would get was on the final connection, and any remaining key types in my list were all not offered by the server.

Curiously, even `ssh-keyscan` seems to cut some corners of its own, grouping "ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521" together, even if requesting a specific ecdsa flavor, so it makes 3 (or 4, if dss is not disabled) connections to assemble its list. Similarly, it reduces explicit requests for "rsa-sha2-512" and "rsa-sha2-256" down to plain "ssh-rsa"

**Comment by superdaigo** [comment]
I've just tweaked @johnnybubonic 's script to get rid of `sys`, `os` and Exception.
```
import paramiko

_dest = ('localhost', 22)

host_keys = {}

t = paramiko.Transport(_dest)
preferred_keys = list(t.get_security_options().key_types)
t.close()

while True:
    t = paramiko.Transport(_dest)
    t._preferred_keys = tuple(preferred_keys)
    t.start_client()
    host_key = t.get_remote_server_key()
    host_key_name = host_key.get_name()
    if host_key_name in host_keys:
        break
    host_keys[host_key_name] = host_key
    t.close()
    preferred_keys.append(preferred_keys.pop(preferred_keys.index(host_key_name)))
```

I cannot say it's clean but this is okay for me.
