### ISSUE TITLE
SSHException: Invalid packet blocking when using invoke_shell

### ISSUE THREAD

**Issue by ianling** [paramiko/paramiko#1438]
The following code produces an exception in paramiko 2.4.2 on Xubuntu 18.04 x86-64, python 3.6.7

```
import paramiko
from paramiko.client import SSHClient
c = SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect('10.0.0.10', username='root', password='password')
x = c.invoke_shell()
x.exec_command('ls')
```

```
Traceback (most recent call last):
  File "/home/iling/.local/lib/python3.6/site-packages/paramiko/transport.py", line 1982, in run
    ptype, m = self.packetizer.read_message()
  File "/home/iling/.local/lib/python3.6/site-packages/paramiko/packet.py", line 451, in read_message
    raise SSHException("Invalid packet blocking")
paramiko.ssh_exception.SSHException: Invalid packet blocking
```

However, if I use `send()` and `recv()` instead of `exec_command()` then it works properly. I have tried many different hosts running different versions of different SSH servers (openssh, dropbear), but I still get this exception.

**Comment by ploxiln** [comment]
`exec_command()` is an alternative to `invoke_shell()`, they are not used together. `c.invoke_shell()` returned a channel already dedicated to that shell. You could do `c.exec_command()` instead.

**Comment by ianling** [comment]
I am trying to create an interactive login shell so that /etc/profile gets parsed on the server. It sounds like my best option is to do invoke_shell and then use `.send()` and `.recv()` to interact with that channel? If that is the case, you may want to consider documenting this or adding a more descriptive exception when people attempt to use exec_command on the object returned by invoke_shell, since the module allows you to do this.

**Comment by ploxiln** [comment]
Another option to get the "login shell init behavior" is to do `exec_command("/bin/bash -i -c 'your command here'")`

I agree, the error is confusing. But the relationship between the client, transport, channels, and stuff you do with channels, is ... somewhat of an advanced topic. For easier high-level usage you may want to try [Fabric](https://www.fabfile.org/)
