### ISSUE TITLE
paramiko.ssh_exception.AuthenticationException: Authentication timeout

### ISSUE THREAD

**Issue by AmirBitaraf** [paramiko/paramiko#1441]
I've faced an issue today trying to SSH with `paramiko`. 
Here is the code I'm trying to connect with:

```
>>> import paramiko                                                                                                                                   
>>> ssh = paramiko.SSHClient()                                                                                                                        
>>> ssh.load_system_host_keys()                                                                                                                       
>>> ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())                                                                                         
>>> k = paramiko.RSAKey.from_private_key_file(SSH_PRIVATE_PATH)                                                                                 
>>> import logging                                                                                                                                    
>>> logging.basicConfig(level=logging.DEBUG)                                                                                                          
>>> ssh.connect(hostname=HOSTNAME, username="root", pkey=k)
```

when I try to connect here's what I get:
```
DEBUG:paramiko.transport:starting thread (client mode): 0xdae1518                                                                                     
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.2                                                                               
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.4                                                                                 
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.4)                                                                                   
DEBUG:paramiko.transport:kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp5
21', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', '$cdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.co$', 'aes256-gcm@openssh.com', 'aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc'] server encrypt:['chacha20-poly1305@$penssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com', 'aes128-cbc', 'aes192-cbc', 'aes256-cbc', $blowfish-cbc', 'cast128-cbc', '3des-cbc'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-s$a2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] s$rver mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@ope$ssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] $erver compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False                                                      
DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
DEBUG:paramiko.transport:HostKey agreed: ssh-ed25519
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>                                               
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Trying SSH key b'***'
DEBUG:paramiko.transport:Trying discovered key b'***' in /path/to/ssh_key
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "paramiko/client.py", line 437, in connect                                               
    passphrase,
  File "paramiko/client.py", line 749, in _auth                                                 
    raise saved_exception
  File "paramiko/client.py", line 725, in _auth
    self._transport.auth_publickey(username, key)
  File "paramiko/transport.py", line 1507, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "paramiko/auth_handler.py", line 240, in wait_for_response
    raise AuthenticationException("Authentication timeout.")
paramiko.ssh_exception.AuthenticationException: Authentication timeout.
```

The code I'm using is fine as I use it to connect to my servers successfully.
I should also note that direct ssh from the client using `ssh` command and the used private key works fine.
Also changing `auth_timeout` and all timeouts to a big numbers didn't work.
After debugging a lot I just find out that the expected `SSH2_MSG_NEWKEYS` is not being sent from client when it is required. Here is the `/var/log/secure` debug log from the server:

```
May  7 18:12:46 NAME sshd[12302]: debug1: SSH2_MSG_KEXINIT sent [preauth]
May  7 18:12:47 NAME sshd[12302]: debug1: SSH2_MSG_KEXINIT received [preauth]                                                                         
May  7 18:12:47 NAME sshd[12302]: debug1: kex: algorithm: ecdh-sha2-nistp256 [preauth]                                                                
May  7 18:12:47 NAME sshd[12302]: debug1: kex: host key algorithm: ssh-ed25519 [preauth]                                                              
May  7 18:12:47 NAME sshd[12302]: debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none [preauth]                       
May  7 18:12:47 NAME sshd[12302]: debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none [preauth]                       
May  7 18:12:47 NAME sshd[12302]: debug1: kex: ecdh-sha2-nistp256 need=32 dh_need=32 [preauth]                                                        
May  7 18:12:47 NAME sshd[12302]: debug1: kex: ecdh-sha2-nistp256 need=32 dh_need=32 [preauth]                                                        
May  7 18:12:47 NAME sshd[12302]: debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]                                                                  
May  7 18:12:47 NAME sshd[12302]: debug1: rekey after 4294967296 blocks [preauth]                                                                     
May  7 18:12:47 NAME sshd[12302]: debug1: SSH2_MSG_NEWKEYS sent [preauth]
May  7 18:12:47 NAME sshd[12302]: debug1: expecting SSH2_MSG_NEWKEYS [preauth]  
```

What might be the problem?
Thanks a lot

Info:
Python Version: Python 3.6.6
Paramiko Version: 2.4.2
Server Info: 
CentOS Linux release 7.6.1810 (Core) 
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by AmirBitaraf** [comment]
There were no issue with `paramiko`. Connection was being dropped somewhere between client and server.

**Comment by rithesh98** [comment]
@AmirBitaraf how did you confirm this?

**Comment by AmirBitaraf** [comment]
> @AmirBitaraf how did you confirm this?

I don't recall clearly after 5 years, but AFAIK the connection was blocked through an application firewall. In our case, we confirmed it by testing behind that firewall.
