### ISSUE TITLE
UnicodeDecodeError During Kex: Solaris Server Language Lists Contains Invalid UTF-8

### ISSUE THREAD

**Issue by ameily** [paramiko/paramiko#1459]
I'm getting a weird error when connecting to a Solaris 8 SSH server. It appears that the SSH server is returning language lists that contains invalid UTF-8 codepoints, which raises a `UnicodeDecodeError`. I verified with Wireshark that Paramiko is receiving the correct language list from the server.

Wireshark of the KEX response from the server:

![image](https://user-images.githubusercontent.com/749571/59715099-1e16f180-91e1-11e9-9da8-bec89f9bc1d7.png)

Value parsed from paramiko (I added a `print()` in `Transport.get_text()`):

```
b'\xff\xff\xff\xff,geo,lcttab,iso_8859_1,iso_8859_15,en_CA,en_CA.ISO88591,en_US,en_US.ISO8859-1,en_US.ISO8859-15,en_US.ISO8859-15@euro,es,es_MX,es_MX.ISO8859-1,fr,fr_CA,fr_CA.ISO8859-1'
```

The actual stack trace:

```
Traceback (most recent call last):
  File "C:\myapp\test_ssh_solaris8.py", line 410, in connect
    allow_agent=False, look_for_keys=False, pkey=key)
  File "C:\myapp\venv\lib\site-packages\paramiko\client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File "C:\myapp\venv\lib\site-packages\paramiko\transport.py", line 601, in start_client
    raise e
  File "C:\myapp\venv\lib\site-packages\paramiko\transport.py", line 2024, in run
    self._handler_table[ptype](self, m)
  File "C:\myapp\venv\lib\site-packages\paramiko\transport.py", line 2139, in _negotiate_keys
    self._parse_kex_init(m)
  File "C:\myapp\venv\lib\site-packages\paramiko\transport.py", line 2251, in _parse_kex_init
    client_lang_list = m.get_list()
  File "C:\myapp\venv\lib\site-packages\paramiko\message.py", line 194, in get_list
    return self.get_text().split(",")
  File "C:\myapp\venv\lib\site-packages\paramiko\message.py", line 178, in get_text
    return u(self.get_string())
  File "C:\myapp\venv\lib\site-packages\paramiko\py3compat.py", line 147, in u
    return s.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

I'm using paramiko 2.5.0. It looks like Wireshark is detecting the first four bytes as invalid UTF-8 and interpreting them each as the UTF-8 replacement character (0xef 0xbf 0xbd == octal 357 277 275).

I confirmed that I can connect to the Solaris 8 server with putty and the OpenSSH client.

**Comment by bitprophet** [comment]
I can't reproduce this myself but my offhand thoughts are:

- What is OpenSSH client doing differently here? that's our reference implementation for the most part.
- Is this as simple as "we're using the wrong message decoding method"? I.e. is this field more correctly a `self.get_bytes()` instead of `self.get_string()` or something like that? Depends what we're doing with the result (I haven't dug yet).

**Comment by ameily** [comment]
My initial thought is add an optional `errors` argument to the `get_string()` (which passed down to `py3compat.u()`, which passes it to the Python verion's call to `decode()`). So, when getting the language list, it would be

```python
client_lang_list = m.get_list(errors='replace')
# calls
# get_list()
#   get_string()
#     py3compat.u()
```

As far as I can tell, the OpenSSH client is ignoring the client/server language lists. The client reads them from the server but never does anything with them.

```c
/* in sshconnect2.c */

void
ssh_kex2()
{
    /* ...... */

    kex_exchange_kexinit(client_kexinit, server_kexinit, sprop);
    /* here, sprop is an array of the kex reply (essentially the result of Transport._parse_kex_init() */

    kex = kex_choose_conf(myproposal, sprop, 0);
    for (i = 0; i < PROPOSAL_MAX; i++)
        xfree(sprop[i]);
    /* ...... */
}


/* in kex.c */

Kex *
kex_choose_conf(char *cprop[PROPOSAL_MAX], char *sprop[PROPOSAL_MAX], int server)
{
    /* no reference to language keys */
    /* if SSH was checking the language lists, I would expect to see something like:
         sprop[PROPOSAL_LANG_CTOS]
         sprop[PROPOSAL_LANG_STOC]
     */
}
```

So, client is reading the entire SSH Kex into an array of c strings (`sprop`) but never checking the values of the client/server language lists (`sprop[PROPOSAL_LANG_CTOS]` or `sprop[8]`).

**Comment by bitprophet** [comment]
Thanks for digging into that so I don't have to :D I think exposing decode args in `get_string` (and I guess `get_list` too, if it's documented as always returning a list of strings) is sensible enough, feels likely we'd run into similar problems later.

Don't have the bandwidth for patching this myself right now but if you file a PR that has some tests for this I might be able to merge it :) If you do, please base it off of the `2.4` branch as this would probably be classified a bugfix.

**Comment by ameily** [comment]
Yeah, I can submit a PR sometime this week.
