### ISSUE TITLE
pip install failing on debian jessie :  NameError: name 'platform_system' is not defined

### ISSUE THREAD

**Issue by arthurlogilab** [paramiko/paramiko#1466]
## Description of the issue

pip install docker-compose fails on paramiko on debian jessie. 

## Context information

```
              Downloading/unpacking docker-compose>=1.21.0
              Downloading/unpacking enum34>=1.0.4,<2 (from docker-compose>=1.21.0)
                Downloading enum34-1.1.6-py2-none-any.whl
              Downloading/unpacking requests>=2.6.1,!=2.11.0,!=2.12.2,!=2.18.0,<2.21 (from docker-compose>=1.21.0)
              Downloading/unpacking websocket-client>=0.32.0,<1.0 (from docker-compose>=1.21.0)
              Downloading/unpacking texttable>=0.9.0,<0.10 (from docker-compose>=1.21.0)
                Downloading texttable-0.9.1.tar.gz
                Running setup.py (path:/tmp/pip-build-VYiGUR/texttable/setup.py) egg_info for package texttable
                  /tmp/pip-build-VYiGUR/texttable/setup.py:12: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
                    # but WITHOUT ANY WARRANTY; without even the implied warranty of
              Downloading/unpacking cached-property>=1.2.0,<2 (from docker-compose>=1.21.0)
                Downloading cached_property-1.5.1-py2.py3-none-any.whl
              Downloading/unpacking docker[ssh]>=3.7.0,<4.0 (from docker-compose>=1.21.0)
              Downloading/unpacking jsonschema>=2.5.1,<3 (from docker-compose>=1.21.0)
                Downloading jsonschema-2.6.0-py2.py3-none-any.whl
              Downloading/unpacking docopt>=0.6.1,<0.7 (from docker-compose>=1.21.0)
                Downloading docopt-0.6.2.tar.gz
                Running setup.py (path:/tmp/pip-build-VYiGUR/docopt/setup.py) egg_info for package docopt
                  /tmp/pip-build-VYiGUR/docopt/setup.py:12: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
                    license='MIT',
              Downloading/unpacking backports.ssl-match-hostname>=3.5 (from docker-compose>=1.21.0)
                Downloading backports.ssl_match_hostname-3.7.0.1.tar.gz
                Running setup.py (path:/tmp/pip-build-VYiGUR/backports.ssl-match-hostname/setup.py) egg_info for package backports.ssl-match-hostname
                  /tmp/pip-build-VYiGUR/backports.ssl-match-hostname/setup.py:12: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
                    version='3.7.0.1',
              Downloading/unpacking six>=1.3.0,<2 (from docker-compose>=1.21.0)
                Downloading six-1.12.0-py2.py3-none-any.whl
              Downloading/unpacking dockerpty>=0.4.1,<0.5 (from docker-compose>=1.21.0)
                Downloading dockerpty-0.4.1.tar.gz
                Running setup.py (path:/tmp/pip-build-VYiGUR/dockerpty/setup.py) egg_info for package dockerpty
                  /tmp/pip-build-VYiGUR/dockerpty/setup.py:12: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
                    # distributed under the License is distributed on an "AS IS" BASIS,
              Downloading/unpacking PyYAML>=3.10,<4.3 (from docker-compose>=1.21.0)
                Running setup.py (path:/tmp/pip-build-VYiGUR/PyYAML/setup.py) egg_info for package PyYAML
                  /tmp/pip-build-VYiGUR/PyYAML/setup.py:12: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
                    supports standard YAML tags and provides Python-specific tags that
              Downloading/unpacking ipaddress>=1.0.16 (from docker-compose>=1.21.0)
                Downloading ipaddress-1.0.22-py2.py3-none-any.whl
              Downloading/unpacking certifi>=2017.4.17 (from requests>=2.6.1,!=2.11.0,!=2.12.2,!=2.18.0,<2.21->docker-compose>=1.21.0)
              Downloading/unpacking urllib3>=1.21.1,<1.25 (from requests>=2.6.1,!=2.11.0,!=2.12.2,!=2.18.0,<2.21->docker-compose>=1.21.0)
              Downloading/unpacking chardet>=3.0.2,<3.1.0 (from requests>=2.6.1,!=2.11.0,!=2.12.2,!=2.18.0,<2.21->docker-compose>=1.21.0)
              Downloading/unpacking idna>=2.5,<2.8 (from requests>=2.6.1,!=2.11.0,!=2.12.2,!=2.18.0,<2.21->docker-compose>=1.21.0)
              Downloading/unpacking docker-pycreds>=0.4.0 (from docker[ssh]>=3.7.0,<4.0->docker-compose>=1.21.0)
                Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl
              Downloading/unpacking paramiko>=2.4.2 (from docker[ssh]>=3.7.0,<4.0->docker-compose>=1.21.0)
              Cleaning up...
              Exception:
              Traceback (most recent call last):
                File "/home/example/.virtualenvs/docker-compose/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
                  status = self.run(options, args)
                File "/home/example/.virtualenvs/docker-compose/local/lib/python2.7/site-packages/pip/commands/install.py", line 290, in run
                  requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
                File "/home/example/.virtualenvs/docker-compose/local/lib/python2.7/site-packages/pip/req.py", line 1266, in prepare_files
                  req_to_install.extras):
                File "/home/example/.virtualenvs/docker-compose/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2401, in requires
                  dm = self._dep_map
                File "/home/example/.virtualenvs/docker-compose/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2597, in _dep_map
                  self.__dep_map = self._compute_dependencies()
                File "/home/example/.virtualenvs/docker-compose/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2630, in _compute_dependencies
                  common = frozenset(reqs_for_extra(None))
                File "/home/example/.virtualenvs/docker-compose/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2627, in reqs_for_extra
                  if req.marker_fn(override={'extra':extra}):
                File "/home/example/.virtualenvs/docker-compose/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/_markerlib/markers.py", line 113, in marker_fn
                  return eval(compiled_marker, environment)
                File "<environment marker>", line 1, in <module>
              NameError: name 'platform_system' is not defined
              
              Storing debug log for failure in /home/example/.pip/pip.log


```

## Additional information

debian jessie, pip install in virtualenv

Iniitialy reported on docker-compose, but it seems to be a problem with paramiko which was also released on monday 24th of june. https://github.com/docker/compose/issues/6770

**Comment by scottanderson42** [comment]
Seeing this on Ubuntu 14.04 LTS as well when installing Ansible 2.7.10 in a virtual environment. Reinitializing the virtualenv is a workaround for the issue.

```
(venv)~/jobs/staging/workspace$ pip install --upgrade ansible==2.7.10
Requirement already up-to-date: ansible==2.7.10 in ./venv/lib/python2.7/site-packages
Requirement already up-to-date: jinja2 in ./venv/lib/python2.7/site-packages (from ansible==2.7.10)
Requirement already up-to-date: PyYAML in ./venv/lib/python2.7/site-packages (from ansible==2.7.10)
Downloading/unpacking paramiko from https://files.pythonhosted.org/packages/4b/80/74dace9e48b0ef923633dfb5e48798f58a168e4734bca8ecfaf839ba051a/paramiko-2.6.0-py2.py3-none-any.whl#sha256=99f0179bdc176281d21961a003ffdb2ec369daac1a1007241f53374e376576cf (from ansible==2.7.10)
  Downloading paramiko-2.6.0-py2.py3-none-any.whl (199kB): 199kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File ".../workspace/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File ".../workspace/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File ".../workspace/venv/local/lib/python2.7/site-packages/pip/req.py", line 1265, in prepare_files
    req_to_install.extras):
  File ".../workspace/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2232, in requires
    dm = self._dep_map
  File ".../workspace/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2423, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File ".../workspace/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2456, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File ".../workspace/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2453, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File ".../workspace/venv/local/lib/python2.7/site-packages/pip/_vendor/_markerlib/markers.py", line 113, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'platform_system' is not defined
```

**Comment by ploxiln** [comment]
seems to be because of this in `setup.py`:

```
    extras_require={
        "gssapi": [
            "pyasn1>=0.1.7",
            'gssapi>=1.4.1;platform_system!="Windows"',
            'pywin32>=2.1.8;platform_system=="Windows"',
        ]
    },
```

I guess setuptools (which includes pkg_resources) is too old on debian 8 and ubuntu-14.04 to handle this syntax

**Comment by ploxiln** [comment]
(I think that if you update setuptools and pip in the virtualenv first, it might then enable installing latest paramiko to work.)

**Comment by xtagon** [comment]
I'm seeing the same error in a Debian Jessie docker image, Python 2.7, pip, and installing Ansible 2.6 (also tried ansible 2.7) which depends on paramiko. Paramiko 2.6.0.

Haven't found a solution yet, I tried updating setuputils first and resetting the virtualenv.

**Comment by dumle11** [comment]
I had to update setuptools to fix this problem:
`pip install --upgrade setuptools`
Hope it helps

**Comment by xtagon** [comment]
Thanks, but as I said I tried updating setuputils first. It didn't help in my case, the same error happened.

**Comment by KiransHub** [comment]
After updating setuptools I get the following: 

``` bash
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1091, in prepare_files
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 811, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range

Storing debug log for failure in /root/.pip/pip.log
```

**Comment by sshishov** [comment]
I guess it can be fixed by upgrading `pip` itself:
```sh
pip install -U pip
```
At least it fixes in my case. Also tried to update `setuptools` with no success

**Comment by Gelob** [comment]
pip install -U pip worked for me in my virtualenv (CentOS 7 with SCL enabled python35 virtualenv) but pyyaml failed to build wheel (ERROR: Failed building wheel for pyyaml) but after i ran pip install -U wheel pyyaml installed fine (pip install -I pyyaml)

**Comment by bitprophet** [comment]
Curious if there's an actionable fix here, all I can see after a quick skim is that we may want to nail down exactly which setuptools version enabled (or fixed?) the extras_require syntax, and list it in the install documentation.

Removing extras_require doesn't seem worthwhile considering the high value add; sadly, getting oneself on a "modern enough" setuptools/pip/etc is part & parcel of running Python code, regardless of distro - there's only so much we can do here upstream to help with that.

**Comment by mrustamov** [comment]
> I guess it can be fixed by upgrading `pip` itself:
> 
> ```shell
> pip install -U pip
> ```
> 
> At least it fixes in my case. Also tried to update `setuptools` with no success

I faced this problem while installing docker-compose on debian (i.e. raspberrypi) and upgrading pip helped me as well. Thx.

**Comment by rbosneag** [comment]
Same as @mrustamov I was trying to install *docker-compose* on raspbery pi as well but I had a problem upgrading *pip* on my Raspbian stating that it was owned by the OS:

> "Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS"

Actually the upgrade worked fine but installed it in */usr/local/bin* so the fix was to update PATH with */usr/local/bin* before */usr/bin* which contained the "default" OS *pip* version.

Now everything seems to work fine.

inspired from https://blog.hartwork.org/posts/regarding-not-uninstalling-pip-at-usr-lib-python2-7-dist-packages-owned-by-os/

**Comment by juju2112** [comment]
I tried installing different versions of setuptools to figure out which version works. I found that if I install setuptools v46.0.0, it gives me this message:

```
    ************************************************************
    You are running Setuptools on Python 2, which is no longer
    supported and
    >>> SETUPTOOLS WILL STOP WORKING <<<
    in a subsequent release (no sooner than 2020-04-20).
    Please ensure you are installing
    Setuptools using pip 9.x or later or pin to `setuptools<45`
    in your environment.
    If you have done those things and are still encountering
    this message, please comment in
    https://github.com/pypa/setuptools/issues/1458
    about the steps that led to this unsupported combination.
    ************************************************************
```

For me, running `pip install -U setuptools==44.1.1` made paramiko install successfully on Debian Jessie.
