### ISSUE TITLE
paramiko.SSHClient.connect raises unknown exception

### ISSUE THREAD

**Issue by genuinelucifer** [paramiko/paramiko#1472]
I am trying to catch the exception from connect using following code:
```
try:
        # call connect on SSHClient
    except paramiko.ssh_exception.BadHostKeyException:
            print("BadHostKeyException")
            raise
    except paramiko.ssh_exception.AuthenticationException as e:
        print("AuthenticationException")
        raise
    except paramiko.ssh_exception.SSHException as e:
        print("SSHException: ", str(e))
        raise e
    except socket.error as e:
        print("socket.error: ", str(e))
        raise e
    except:
        print("Some other error")
        raise
```

And the last print statement is executed. Why is it throwing such exception which is not in documentation? How to debug this?

The traceback is:
```
File "/home/ubuntu/xxxxxx/ssh_client.py", line 20, in connect_ssh
    ssh.connect(self.ip, username=self.username, key_filename=self.key)
   File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 660, in start_client
    raise e
 AttributeError: Raw
```

**Comment by ploxiln** [comment]
The problem is that you have `cryptography < 2.5` installed. setup.py requires `cryptography >= 2.5`.

(This exception is specifically from referencing `serialization.Encoding.Raw` in `kex_curve25519.py`.)

**Comment by genuinelucifer** [comment]
Thank you so much! 🎉 Upgrading cryptography solved the issue.   
  
For anyone else who comes across the same issue, I would comment extra info. After upgrading cryptography to 2.7 I ran into another error. Some symbol in Python API was not defined. I had to install another python version (2.7.9) by building it from source. Using python 2.7.9 with crypography 2.7 and paramiko 2.6 solved the issue.

**Comment by iamrpc** [comment]
Our python version got updated from 3.6.7 to 3.6.8 and we got a similar error. We are using Fabric v1.14.post1 and it installed Paramiko v2.4.2.

```
INFO     Connected (version 2.0, client OpenSSH_7.6p1)
ERROR    Unknown exception: Raw
ERROR    Traceback (most recent call last):
ERROR      File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2083, in run
ERROR        self._handler_table[ptype](self, m)
ERROR      File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2199, in _negotiate_keys
ERROR        self.kex_engine.start_kex()
ERROR      File "/usr/local/lib/python3.6/dist-packages/paramiko/kex_curve25519.py", line 54, in start_kex
ERROR        serialization.Encoding.Raw, serialization.PublicFormat.Raw
ERROR      File "/usr/lib/python3.6/enum.py", line 326, in __getattr__
ERROR        raise AttributeError(name) from None
ERROR    AttributeError: Raw    
Traceback (most recent call last):
 <-- redacted -->
    run("mkdir -p {}".format(FABRIC_DIR), quiet=True)
  File "/usr/local/lib/python3.6/dist-packages/fabric/network.py", line 692, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fabric/operations.py", line 1095, in run
    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
  File "/usr/local/lib/python3.6/dist-packages/fabric/operations.py", line 935, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/usr/local/lib/python3.6/dist-packages/fabric/state.py", line 435, in default_channel
    chan = _open_session()
  File "/usr/local/lib/python3.6/dist-packages/fabric/state.py", line 416, in _open_session
    transport = connections[env.host_string].get_transport()
  File "/usr/local/lib/python3.6/dist-packages/fabric/network.py", line 156, in __getitem__
    self.connect(key)
  File "/usr/local/lib/python3.6/dist-packages/fabric/network.py", line 148, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/usr/local/lib/python3.6/dist-packages/fabric/network.py", line 478, in connect
    client.connect(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2083, in run
    self._handler_table[ptype](self, m)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2199, in _negotiate_keys
    self.kex_engine.start_kex()
  File "/usr/local/lib/python3.6/dist-packages/paramiko/kex_curve25519.py", line 54, in start_kex
    serialization.Encoding.Raw, serialization.PublicFormat.Raw
  File "/usr/lib/python3.6/enum.py", line 326, in __getattr__
    raise AttributeError(name) from None
AttributeError: Raw
```

as suggested using cryptography >=2.5 fixed the problem. Thanks.

**Comment by marisogsg** [comment]
Good morning,

Sorry the inconveniences.

I write because obtained the next exception and I don´t know found solution.

The same code works perfectly with python 3.7 and cryptography 2.4.4 but I don´t use python > 3.5.

I make different test:
python 3.4.4 + crytpgraphy=2.4.2
python 3.4.4 + crytpgraphy=2.5
python 2.7.9, but I tried install cryptography==2.9 obtained more errors.
Please can you help me?

Regards,

1.
****************************************************************  
Unknown exception: Raw
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\paramiko\transport.py", line 2083, in run self._handler_table[ptype](self, m)
  File "C:\Python34\lib\site-packages\paramiko\transport.py", line 2199, in _negotiate_keys self.kex_engine.start_kex()
  File "C:\Python34\lib\site-packages\paramiko\kex_curve25519.py", line 54, in start_kex serialization.Encoding.Raw, serialization.PublicFormat.Raw
  File "C:\Python34\lib\enum.py", line 255, in __getattr__
    raise AttributeError(name) from None
AttributeError: Raw

Exception: Raw
****************************************************************  

2.
****************************************************************  
Traceback (most recent call last):
  File "ssh_client_pk2.py", line 3, in <module>
    import paramiko
  File "C:\Python34\lib\site-packages\paramiko\__init__.py", line 22, in <module> from paramiko.transport import SecurityOptions, Transport
  File "C:\Python34\lib\site-packages\paramiko\transport.py", line 129, in <module> class Transport(threading.Thread, ClosingContextManager):
  File "C:\Python34\lib\site-packages\paramiko\transport.py", line 190, in Transport
    if KexCurve25519.is_available():
  File "C:\Python34\lib\site-packages\paramiko\kex_curve25519.py", line 30, in i
s_available
    X25519PrivateKey.generate()
  File "C:\Python34\lib\site-packages\cryptography\hazmat\primitives\asymmetric\x25519.py", line 38, in generate
****************************************************************  

3.
****************************************************************  
Traceback (most recent call last):
  File "xx.py", line 3, in <module>
    import paramiko
  File "C:\Python34\lib\site-packages\paramiko\__init__.py", line 22, in <module> from paramiko.transport import SecurityOptions, Transport
  File "C:\Python34\lib\site-packages\paramiko\transport.py", line 129, in <module> class Transport(threading.Thread, ClosingContextManager):
  File "C:\Python34\lib\site-packages\paramiko\transport.py", line 190, in Transport if KexCurve25519.is_available():
  File "C:\Python34\lib\site-packages\paramiko\kex_curve25519.py", line 30, in is_available X25519PrivateKey.generate()
  File "C:\Python34\lib\site-packages\cryptography\hazmat\primitives\asymmetric\x25519.py", line 38, in generate from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Python34\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module> from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Python34\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 71, in <module> from cryptography.hazmat.bindings.openssl import binding
  File "C:\Python34\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 15, in <module> from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: No se puede encontrar el módulo especificado.
****************************************************************  

Best Regards,

**Comment by genuinelucifer** [comment]
@marisogsg For old python (your cases 1 & 2), please try with cryptography==2.2 and paramiko==2.2

For new python (case 3) please try with cryptography==2.7 and paramiko==2.6

**Comment by marisogsg** [comment]
Hi,

thanks for answers, but it does not work:

1. I have twuo virtual machine that simulate my app client/server for do ssh reverse with paramiko.
2. In my virtual client (windows xp, I need test with this operative system):
	- python 3.4.2
	- paramiko 2.6
	- cryptography 2.7
	
3. In my virtual server (debian 9):
	- python 3.5.3
	- paramiko 2.6
	- cryptography 2.7

In this probe, not connect because obtained the next error:
C:\Documents and Settings\user\Mis documentos>python client.py
Traceback (most recent call last):
  File "client.py", line 31, in <module> import paramiko
  File "C:\Python34\lib\site-packages\paramiko\__init__.py", line 22, in <module> from paramiko.transport import SecurityOptions, Transport
  File "C:\Python34\lib\site-packages\paramiko\transport.py", line 129, in <module> class Transport(threading.Thread, ClosingContextManager):
  File "C:\Python34\lib\site-packages\paramiko\transport.py", line 190, in Transport if KexCurve25519.is_available():
  File "C:\Python34\lib\site-packages\paramiko\kex_curve25519.py", line 30, in is_available X25519PrivateKey.generate()
  File "C:\Python34\lib\site-packages\cryptography\hazmat\primitives\asymmetric\x25519.py", line 38, in generate from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Python34\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module> from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Python34\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 74, in <module> from cryptography.hazmat.bindings.openssl import binding
  File "C:\Python34\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 15, in <module> from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

4. I tried install pyopenssl, but continue this error.

5. In befores's test, connect but obtained the errors.

Best Regards,
