### ISSUE TITLE
Authentication Failed on devices where copyright banner is presented before password prompt (ADVA)

### ISSUE THREAD

**Issue by bops-47** [paramiko/paramiko#1476]
I have two ADVA NIDs, one on an older version, 9.5, one on a newer version, 9.6. Per the vendor, one of the changes between these versions is when the copyright banner is presented during SSH authentication. 

When logging in via terminal, here is the output on the 9.5 version:
```
---> ssh 10.0.10.100 -l root
Copyright (c) 2017 ADVA Optical Networking SE. All rights reserved.
root@10.0.10.100's password:
********************************************************************************
Authorized users only!!
********************************************************************************
NID1-->
```
 Here is the 9.6 version:
```
---> ssh 10.0.10.102 -l root
root@10.0.10.102's password:
Copyright (c) 2018 ADVA Optical Networking SE. All rights reserved.
********************************************************************************
Authorized users only!!
********************************************************************************
NID2-->
```

When attempting to login to the device on version 9.5 with the following code, I get Authentication errors. Connecting to the device on version 9.6 using the same code (save for the ip of course) works perfectly fine. 

```
Python 3.6.3 (default, Mar 20 2018, 13:50:41)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import paramiko
>>>
>>> ip = '10.0.10.100'
>>> username = 'root'
>>> password = 'password'
>>>
>>> con = paramiko.SSHClient()
>>> con.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>>
>>> con.connect(ip, username=username, password=password, look_for_keys=False, allow_agent=False)

```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/dev/bkirkland/lib64/python3.6/site-packages/paramiko/client.py", line 425, in connect
    passphrase,
  File "/opt/dev/bkirkland/lib64/python3.6/site-packages/paramiko/client.py", line 718, in _auth
    raise saved_exception
  File "/opt/dev/bkirkland/lib64/python3.6/site-packages/paramiko/client.py", line 703, in _auth
    self._transport.auth_password(username, password)
  File "/opt/dev/bkirkland/lib64/python3.6/site-packages/paramiko/transport.py", line 1381, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "/opt/dev/bkirkland/lib64/python3.6/site-packages/paramiko/auth_handler.py", line 231, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```

I believe this may be related #1177, hopefully these extra details can help.

**Comment by bops-47** [comment]
```
auth_handler.py:
    def _parse_service_accept(self, m):
        service = m.get_text()
        if service == "ssh-userauth":
            self._log(DEBUG, "userauth is OK")
            m = Message()
            m.add_byte(cMSG_USERAUTH_REQUEST)
            m.add_string(self.username)
            m.add_string("ssh-connection")
            m.add_string(self.auth_method)
            if self.auth_method == "password":
                m.add_boolean(False)
                password = b(self.password)
                m.add_string(password)
```

Without the above user/password sending being split up into some sort of expect-like behavior (not worth it for a single device/version), I'm not convinced this issue can be resolved. May have to chalk it up to a bad vendor implementation and close the issue.

**Comment by radssh** [comment]
This could be yet another device implementation of skipping the ssh protocol based user authentication, and allowing the session to authenticate with nothing, then relying on the established session managing an interactive username/password prompt.

Would you mind running `ssh -vvv root@10.0.10.X` connecting to the 9.5 (non-working) server to trace the protocol exchange, specifically looking for a section that (for OpenSSH) looks like this:
```
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 53
debug3: input_userauth_banner
Ubuntu 18.04.2 LTS
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password,keyboard-interactive
```

The packet type meanings here: 50=UserauthRequest, 53=BannerContents, 51=UserauthFailed, and 52=UserauthSuccess. Typically, the client issues the first 50 with a specific null authentication type, as a query for the server to send a list of acceptable authentication methods (here, it has send the list "publickey,password,keyboard-interactive").

Typically, if paramiko is given a password or a key, it will use it in the initial 50 message, and will not send a null authentication type message. For devices that are specifically expecting that null authentication request at the beginning, that can cause this type of authentication error.

**Comment by bops-47** [comment]
> Would you mind running `ssh -vvv root@10.0.10.X` connecting to the 9.5 (non-working) server to trace the protocol exchange, specifically looking for a section that (for OpenSSH) looks like this:

Of course. I didn't see a list of acceptable authentication methods, so I'll include everything from the service_accept to where I'm asked for a password.

```
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (none).
Authenticated to 10.0.10.100 ([10.0.10.100]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: network
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: receive packet: type 91
debug2: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x10
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug3: send packet: type 98
debug1: Sending environment.
debug3: Ignored env XDG_SESSION_ID
debug3: Ignored env HOSTNAME
debug3: Ignored env TERM
debug3: Ignored env SHELL
debug3: Ignored env HISTSIZE
debug3: Ignored env SSH_CLIENT
debug3: Ignored env OLDPWD
debug3: Ignored env SSH_TTY
debug3: Ignored env USER
debug3: Ignored env LS_COLORS
debug3: Ignored env VIRTUAL_ENV
debug3: Ignored env MAIL
debug3: Ignored env PATH
debug3: Ignored env PWD
debug1: Sending env LANG = en_US.UTF-8
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env PS1
debug3: Ignored env HISTCONTROL
debug3: Ignored env SHLVL
debug3: Ignored env HOME
debug3: Ignored env LOGNAME
debug3: Ignored env SSH_CONNECTION
debug3: Ignored env LESSOPEN
debug3: Ignored env XDG_RUNTIME_DIR
debug3: Ignored env HISTTIMEFORMAT
debug3: Ignored env _
debug2: channel 0: request shell confirm 1
debug3: send packet: type 98
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: shell request accepted on channel 0


Copyright (c) 2017 ADVA Optical Networking SE. All rights reserved.

root@10.0.10.100's password:
```

**Comment by radssh** [comment]
Thanks. That log shows what I was suspecting. The server is accepting the preliminary authentication request as valid, even though it doesn't contain anything tangible other than the username.

`debug1: Authentication succeeded (none).`

The interaction about prompting for password (and the banner) are occurring in the shell already started in the session. As outlined earlier, paramiko currently is geared for doing the user authentication via the ssh protocol, and the `SSHClient` doesn't issue a preliminary "none" authentication request at all, though I think there is a pull request for adding that as an feature. There is also a looming ToDo to rework the whole user authentication mechanism to be more flexible as well as more maintainable.

**Comment by sroodman** [comment]
Was this ever resolved?  I am trying to work with several of the adva platforms below 9.6 and get an authentication failed message like its not even trying.

**Comment by Snackhous3** [comment]
Same. Was this ever solved? Palo Alto devices are displaying the same behavior. Ran -vvv on SSH output for version 9.1.X devices.

**Comment by Snackhous3** [comment]
I am working on the issue. If anything comes from it I will submit a PR

**Comment by avatarofhope2** [comment]
@Snackhous3, would that resolve the ADVA issue with "none" authentication

**Comment by bskinn** [comment]
Dropping a link to https://github.com/paramiko/paramiko/issues/1177#issuecomment-1644392641 here, and @avatarofhope2's (unsuccessful thus far) efforts to find a solution for this using the new auth tooling in paramiko v3.2 (see the [3.2 CHANGELOG] and scroll down to the first red info box).

[3.2 changelog]: https://www.paramiko.org/changelog.html#3.2.0
