### ISSUE TITLE
paramiko doesn't work with D-Link

### ISSUE THREAD

**Issue by knopka** [paramiko/paramiko#148]
I try to execute command on network equipment using paramiko. With Cisco routers it works perfectly, but with D-Link it doesn't work.

(env)rkireev@spd-server:~/django$ python
Python 2.7.3 (default, Aug  1 2012, 05:16:07) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import paramiko
> > > paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
> > > client = paramiko.SSHClient()
> > > client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
> > > client.connect('172.23.128.161', username='XXX', password='YYY', allow_agent=False, look_for_keys=False)
> > > DEBUG:paramiko.transport:starting thread (client mode): 0xa07606cL
> > > INFO:paramiko.transport:Connected (version 2.0, client 1.00.000)
> > > DEBUG:paramiko.transport:kex algos:['diffie-hellman-group1-sha1'] server key:['ssh-dss', 'ssh-rsa'] client encrypt:['3des-cbc', 'blowfish-cbc', 'twofish-cbc', 'twofish256-cbc', 'twofish192-cbc', 'twofish128-cbc', 'aes256-cbc', 'aes192-cbc', 'aes128-cbc', 'arcfour', 'cast128-cbc'] server encrypt:['3des-cbc', 'blowfish-cbc', 'twofish-cbc', 'twofish256-cbc', 'twofish192-cbc', 'twofish128-cbc', 'aes256-cbc', 'aes192-cbc', 'aes128-cbc', 'arcfour', 'cast128-cbc'] client mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] server mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
> > > DEBUG:paramiko.transport:Ciphers agreed: local=aes128-cbc, remote=aes128-cbc
> > > DEBUG:paramiko.transport:using kex diffie-hellman-group1-sha1; server key type ssh-rsa; cipher: local aes128-cbc, remote aes128-cbc; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
> > > DEBUG:paramiko.transport:Switch to new keys ...
> > > DEBUG:paramiko.transport:Adding ssh-rsa host key for 172.23.128.161: 0c2d8ffbb7d6ebf81282c181be8b53e9
> > > DEBUG:paramiko.transport:userauth is OK
> > > INFO:paramiko.transport:Authentication (password) successful!
> > > 
> > > stdin, stdout, stderr = client.exec_command('cable_diag ports all')
> > > DEBUG:paramiko.transport:[chan 1] Max packet in: 34816 bytes
> > > DEBUG:paramiko.transport:[chan 1] Max packet out: 8192 bytes
> > > INFO:paramiko.transport:Secsh channel 1 opened.
> > > DEBUG:paramiko.transport:[chan 1] EOF sent (1)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/rkireev/django/env/local/lib/python2.7/site-packages/paramiko/client.py", line 374, in exec_command
> > >     chan.exec_command(command)
> > >   File "/home/rkireev/django/env/local/lib/python2.7/site-packages/paramiko/channel.py", line 218, in exec_command
> > >     self._wait_for_event()
> > >   File "/home/rkireev/django/env/local/lib/python2.7/site-packages/paramiko/channel.py", line 1122, in _wait_for_event
> > >     raise e
> > > paramiko.SSHException: Channel closed.
> > > DEBUG:paramiko.transport:[chan 1] EOF received (1)
> > > 
> > > DEBUG:paramiko.transport:EOF in transport thread

**Comment by erjuampe** [comment]
I have the same problem. I'm trying to use ssh over paramiko to connect dlink switch. When the connection is done and do exec the channel closed it.

  ```
File "prueba.py", line 28, in <module>
    stdin, stdout, stderr = c.exec_command("help")
  File "/usr/local/lib/python2.6/dist-packages/paramiko/client.py", line 405, in exec_command
    chan.exec_command(command)
  File "/usr/local/lib/python2.6/dist-packages/paramiko/channel.py", line 60, in _check
    return func(self, *args, **kwds)
  File "/usr/local/lib/python2.6/dist-packages/paramiko/channel.py", line 229, in exec_command
    self._wait_for_event()
  File "/usr/local/lib/python2.6/dist-packages/paramiko/channel.py", line 1086, in _wait_for_event
    raise e
paramiko.ssh_exception.SSHException: Channel closed.

```

Anyone with an answer? maybe another alternate solution?

thanks

**Comment by knopka** [comment]
Hi,
now I'm using Exscript, it works fine with D-Link, Huawei and Cisco.

**Comment by erjuampe** [comment]
Thanks for comment. I´ll test it

**Comment by erjuampe** [comment]
Thanks you very much. It's works!!

**Comment by knopka** [comment]
Glad to help)

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — this one looks out-of-scope: D-Link CLI switches (and most embedded-firmware SSH stacks of that era) don't implement the SSH "exec" channel — they only accept an interactive shell channel. lndbrg (CONTRIBUTOR) called this out in 2013-03-12.

Evidence:
- The repro is `client.exec_command("...")` which requests an `exec` subsystem channel; the device immediately closes the channel because its SSH server has no exec handler — the right API for that class of device is `Channel.invoke_shell()` / `SSHClient.invoke_shell()`, which both ship in paramiko.
- Two later commenters on this thread (erjuampe + knopka, 2016-03) reported success against the same D-Link class by driving an interactive shell session via another network-CLI library (Exscript) — i.e., the workaround is exactly "use the interactive-shell path", not a paramiko fix.
- The same server-side limitation already came up and was acknowledged in #132 (mina-ssh / sshd-core does not allow exec channels either; lndbrg there said the issue "should probably be closed" for the same reason).

If a repro exists where paramiko misbehaves *vs `openssh -t` against the same D-Link* (rather than vs `openssh "command"`), happy to dig further. Otherwise this looks closeable.

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against `main`.*

**Comment by bskinn** [comment]
Thanks for this, @jbbqqf -- agreed, this seems closeable, especially given the age.

I think #132 should stay open, though -- kellybyrd [raises](https://github.com/paramiko/paramiko/issues/132#issuecomment-15986706) the prospect of incorrect auth fallback by paramiko, with which bitprophet concurred but left it as 'needs investigation'.
