### ISSUE TITLE
Help!SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by Evan-D** [paramiko/paramiko#1482]
Tue, 23 Jul 2019 10:34:01 transport.py[line:1819] DEBUG starting thread (client mode): 0x34a3ef10L
Tue, 23 Jul 2019 10:34:01 transport.py[line:1819] DEBUG Local version/idstring: SSH-2.0-paramiko_2.6.0
Tue, 23 Jul 2019 10:34:01 transport.py[line:1819] ERROR Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
Tue, 23 Jul 2019 10:34:01 transport.py[line:1817] ERROR Traceback (most recent call last):
Tue, 23 Jul 2019 10:34:01 transport.py[line:1817] ERROR   File "/home/lenovo/.local/lib/python2.7/site-packages/paramiko/transport.py", line 2039, in run
Tue, 23 Jul 2019 10:34:01 transport.py[line:1817] ERROR     self._check_banner()
Tue, 23 Jul 2019 10:34:01 transport.py[line:1817] ERROR   File "/home/lenovo/.local/lib/python2.7/site-packages/paramiko/transport.py", line 2216, in _check_banner
Tue, 23 Jul 2019 10:34:01 transport.py[line:1817] ERROR     "Error reading SSH protocol banner" + str(e)
Tue, 23 Jul 2019 10:34:01 transport.py[line:1817] ERROR SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
Tue, 23 Jul 2019 10:34:01 transport.py[line:1817] ERROR

**Comment by Evan-D** [comment]
Are there any solution?Thx!

**Comment by Ismael-Safadi** [comment]
Same error !

**Comment by mhallak** [comment]
Do you have a solution to this problem?

**Comment by Ismael-Safadi** [comment]
Sadly still same error

**Comment by vanhul** [comment]
Same error!!

**Comment by Kani999** [comment]
Also running into the same issue.

```
starting thread (client mode): 0x32636ee0
Local version/idstring: SSH-2.0-paramiko_2.7.2
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/opt/nautobot/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/opt/nautobot/lib/python3.8/site-packages/paramiko/packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/opt/nautobot/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

OnboardException: fail-general: Error reading SSH protocol banner
```

I'm using optional arguments as follow `{'conn_timeout': 3000, 'auth_timeout': 3000, 'banner_timeout': 3000, 'session_timeout': 3000}` but with no luck.

**Comment by gquittet** [comment]
I have the same issue:

```text
DEBUG:paramiko.transport:starting thread (client mode): 0xb34fac40
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.9.2
ERROR:paramiko.transport:Exception (client): Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "transport.py", line 2270, in _check_banner
ERROR:paramiko.transport:    buf = self.packetizer.readline(timeout)
ERROR:paramiko.transport:  File "packet.py", line 380, in readline
ERROR:paramiko.transport:    buf += self._read_timeout(timeout)
ERROR:paramiko.transport:  File "packet.py", line 609, in _read_timeout
ERROR:paramiko.transport:    raise EOFError()
ERROR:paramiko.transport:EOFError
ERROR:paramiko.transport:
ERROR:paramiko.transport:During handling of the above exception, another exception occurred:
ERROR:paramiko.transport:
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "transport.py", line 2093, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "transport.py", line 2274, in _check_banner
ERROR:paramiko.transport:    raise SSHException(
ERROR:paramiko.transport:paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

This issue crash the SSH of my switch and I can't connect to it with Putty without any restart of the service.

**Comment by gquittet** [comment]
@bitprophet

**Comment by Summer-Shen98** [comment]
did any one have some solutions to avoid this exception?
I have found that when I use paramiko on win10 os this exception would not appear even though I connection for hundred times,but when I use paramiko on unbuntu os it would raise this exception after 3-4 times connection. My ssh server is an openwrt router.....It looks like that this problem has been appeared for several years.....

**Comment by jun66j5** [comment]
> did any one have some solutions to avoid this exception? I have found that when I use paramiko on win10 os this exception would not appear even though hundred times ssh connections , but when I use paramiko on unbuntu os it would raise this exception after 3-4 times connection. My ssh server is an openwrt router.....It looks like that this problem has been appeared for several years.....

@Summer-Shen98 This issue is typically caused your connection closed by ssh server. Check whether no errors are logged in your ssh server and ssh server's configurations. Also, I'd suggest asking on openwrt forum.

See also:
* [Limiting login attempts (was: Is robzr's bearDropper unmaintained?) - Installing and Using OpenWrt - OpenWrt Forum](https://forum.openwrt.org/t/limiting-login-attempts-was-is-robzrs-beardropper-unmaintained/31695)
* [Attempts Limit to log-in SSH - Installing and Using OpenWrt - OpenWrt Forum](https://forum.openwrt.org/t/attempts-limit-to-log-in-ssh/28741/5)

p.s. Stop commenting to all issues which the same exception is raised.

**Comment by Summer-Shen98** [comment]
@jun66j5 It did nothing to do with openwrt , it seems that when I call the function that closes the ssh connection，it sometines did not really work, because I captured packet on my PC with wireshark,the client did not send TCP FIN packet when the close function called...

**Comment by jun66j5** [comment]
@Summer-Shen98 I think your script has something wrong in case which TCP FIN not sent although invoking SSHClient.close. At least, your issue is different with this issue. This issue is connection reset while connecting ssh server and reading banner the ssh server. I'd suggest creating an new issue with your script, exception and stack trace.
