### ISSUE TITLE
[Windows] Interaction between Paramiko, Pyinstaller, and PuTTY Pageant on SSHClient.connect(...)

### ISSUE THREAD

**Issue by david-brownell** [paramiko/paramiko#1487]
[Related StackOverflow question I made earlier](https://stackoverflow.com/questions/57047710/paramiko-sshclient-connect-fails-when-packaged-with-pyinstaller-on-windows)

`SSHClient.connect` will raise a `TypeError` from `_winapi.py` when both these conditions are met:

* The executable running `paramiko` has been packaged with `pyinstaller`; this interaction occurs in both `--onefile` and `--onedir` modes
* PuTTY Pageant is running

Software versions:

* Paramiko 2.6.0
* Pyinstaller 3.5 and nightly 4.0.dev0+ce887b462
* Python 2.7.15
* Windows 10 Pro, Version 10.0.17134, Build 17134
* PuTTY Pageant 0.70

Minimal example:

```python
import paramiko

# The nature of this issue unfortunately requires
# a server that responds to SSH connections to test
host = None  # Put a valid hostname here
port = 22  # Put a valid port here

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(
    hostname=host,
    port=port,
    username=None,
    password=None,
    timeout=5
)
```

Results when PuTTY Pageant is running:

```
> virtualenv venv
> venv\Scripts\activate.bat
> pip install pyinstaller==3.5 paramiko==2.6.0
[output truncated for brevity]
> pyinstaller minimal-paramiko-example.py
[output truncated for brevity]
> dist\minimal-paramiko-example\minimal-paramiko-example.exe
Traceback (most recent call last):
  File "minimal-paramiko-example.py", line 16, in <module>
    timeout=5
  File "site-packages\paramiko\client.py", line 446, in connect
  File "site-packages\paramiko\client.py", line 691, in _auth
  File "site-packages\paramiko\agent.py", line 379, in __init__
  File "site-packages\paramiko\agent.py", line 65, in _connect
  File "site-packages\paramiko\agent.py", line 82, in _send_message
  File "site-packages\paramiko\win_pageant.py", line 129, in send
  File "site-packages\paramiko\win_pageant.py", line 96, in _query_pageant
  File "site-packages\paramiko\_winapi.py", line 179, in write
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
[16768] Failed to execute script minimal-paramiko-example

> python minimal-paramiko-example.py  # Will result in an AuthenticationException, since username and password are None; this is expected and normal
[output truncated for brevity]
```

There are two workarounds:

* Close Pageant, or
* Don't package the executable with pyinstaller

**Comment by m6461** [comment]
Did you resolve the issue? I am having a similar problem where the executable runs in to problem to establish connections (both SSH and Telnet). The python script works, but the executable does not work reliably.
