### ISSUE TITLE
v2.6.0 emits lines to stderr

### ISSUE THREAD

**Issue by dharasty** [paramiko/paramiko#1489]
In my script I'm trying to SSH to several addresses in a range.  I do not know the underlying condition that is causing this error (below)... BUT the **BUG** is that these lines are emitted to the stderr, which glops up the output from my script.

Please either:
- handle this error (and don't emit lines to either the stdout or stderr)
- ignore the error (and don't emit lines to either the stdout or stderr)
- if the condition should be of interest to the API user (me), then RAISE an error, and I'll catch it and handle the case ... and STILL and don't emit lines to either the stdout or stderr!

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 2109, in run
    handler(self.auth_handler, m)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/auth_handler.py", line 278, in _parse_service_accept
    m.add_string(self.username)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/message.py", line 274, in add_string
    self.add_int(len(s))
TypeError: object of type 'NoneType' has no len()
```
Thanks...

**Comment by ploxiln** [comment]
presumably, that exception is being caught here:
https://github.com/paramiko/paramiko/blob/2.6.0/paramiko/transport.py#L2145

and then logged, which goes through this method:
https://github.com/paramiko/paramiko/blob/2.6.0/paramiko/transport.py#L1814

which uses the logger which is created and named here:
https://github.com/paramiko/paramiko/blob/2.6.0/paramiko/transport.py#L475

So, you could suppress these particular messages with something along the lines of:

```python
logging.getLogger("paramiko.transport").setLevel(logging.CRITICAL)
```

I don't think paramiko just writes to stdout or stderr - it just uses the python standard logging module.
