### ISSUE TITLE
IOError: [Errno 2] No such file - on put()

### ISSUE THREAD

**Issue by mrbirl** [paramiko/paramiko#149]
When attempting to upload files I'm occasionally getting the following error
`File "build/bdist.macosx-10.8-intel/egg/paramiko/sftp_client.py", line 565, in put
    File "build/bdist.macosx-10.8-intel/egg/paramiko/sftp_client.py", line 245, in open
    File "build/bdist.macosx-10.8-intel/egg/paramiko/sftp_client.py", line 635, in _request
    File "build/bdist.macosx-10.8-intel/egg/paramiko/sftp_client.py", line 682, in _read_response
    File "build/bdist.macosx-10.8-intel/egg/paramiko/sftp_client.py", line 708, in _convert_status
    IOError: [Errno 2] No such file`
even if the local file and remote path certainly exist. More details here - http://stackoverflow.com/questions/15481934/ioerror-errno-2-no-such-file-paramiko-put

**Comment by aliceinwire** [comment]
which is your paramiko version ?
i have similar problem.

**Comment by aliceinwire** [comment]
Traceback (most recent call last):
  File "test.py", line 201, in build_process
    sftp.put(localpath, filepath)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 612, in put
    file_size = os.stat(localpath).st_size
OSError: [Errno 2] No such file or directory: '/var/tmp/download/space/more/x.x.x/patch1.patch'
DEBUG:EOF in transport thread


But the file exist and is readable.

**Comment by angineering** [comment]
I am also seeing this issue using pysftp 0.2.8. It happens more often than not, even when I try adding re-tries and sleeps.

**Comment by krishnaanandk** [comment]
I have the same error on paramiko 2.4.1. File transfer using put results in the "[Errno 2] No such file
" error sporadically, even though the files and paths exist. Any update on this? Are there any workarounds? Thanks!

**Comment by HuangWeiTao** [comment]
I met this error yesterday and have solved it. It's not a bug of paramiko. It's probably that you don't create directories first in the remote machine before you transfer files.
SFTPClient.mkdir() wouldn't create recursive directories for you, but only the direct one.
So make sure you create all the parent directories before you call SFTPClientsftp.put(local_path,remote_path)

following is the same code:


import pathlib

def create_parent_dirs(remote_path):
    remote_path = pathlib.Path(remote_path)
    parent_list = list(remote_path.parents)
    # reverse the parent directories so it would create the ancestor frist
    parent_list.reverse()
    for parent in parent_list:
        directory = parent.as_posix()  # covert to posix path
        try:
            sftp.stat(directory)  # test if remote_dir exists
        except IOError:
            sftp.mkdir(directory)
            sftp.stat(directory)


create_parent_dirs(remote_path)
sftp.put(local_path, remote_path)

**Comment by HuangWeiTao** [comment]
I met this error yesterday and have solved it. It's not a bug of paramiko. It's probably that you don't create directories first in the remote machine before you transfer files.
SFTPClient.mkdir() wouldn't create recursive directories for you, but only the direct one.
So make sure you create all the parent directories before you call SFTPClientsftp.put(local_path,remote_path)

following is the same code:

```
import pathlib

def create_parent_dirs(remote_path):
    remote_path = pathlib.Path(remote_path)
    parent_list = list(remote_path.parents)
    # reverse the parent directories so it would create the ancestor frist
    parent_list.reverse()
    for parent in parent_list:
        directory = parent.as_posix()  # covert to posix path
        try:
            sftp.stat(directory)  # test if remote_dir exists
        except IOError:
            sftp.mkdir(directory)
            sftp.stat(directory)


create_parent_dirs(remote_path)
sftp.put(local_path, remote_path)
```

**Comment by zachliu** [comment]
I also got this error recently but I'm sure it's not because of the directories issue that @HuangWeiTao mentioned. I'm supposed to `sftp.put` the file to the root directory of the remote SFTP and yet still I experienced this error.

**Comment by jwdeitch** [comment]
I am encountering the same behavior - it's entirely intermintentent.
It looks at first glance as though there is a race condition in where the client will put the document on the remote, and then immediately issue a `stat` to confirm delivery - the remote filesystem in some cases may not be read-after-write consistent, causing the error seen here.

**Comment by drdee** [comment]
Would setting `confirm=False` in the `put` call sidestep this race condition?

**Comment by jwdeitch** [comment]
@drdee That should do it - however I wanted to make sure the file actually did arrive. I just basically wrapped the `put` call in a loop that iterated 3 times, and inside that I put a try & except and on except, I continued and tried again (and also put in a sleep for 1 second). This worked well. After 3 iterations of the exception being raised, it raised an actual exception to signal a failure. Hope this helps!

**Comment by Ryan-M3** [comment]
I'm also getting this error when doing a put on some servers, but the stack trace has different lines than the OP:

```
File "[redacted] python3.6/site-packages/paramiko/sftp_client.py", line 759, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
  File "[redacted] python3.6/site-packages/paramiko/sftp_client.py", line 720, in putfo
    s = self.stat(remotepath)
  File "[redacted] python3.6/site-packages/paramiko/sftp_client.py", line 493, in stat
    t, msg = self._request(CMD_STAT, path)
  File "[redacted] python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "[redacted] python3.6/site-packages/paramiko/sftp_client.py", line 865, in _read_response
    self._convert_status(msg)
  File "[redacted] python3.6/site-packages/paramiko/sftp_client.py", line 894, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
```

Maybe this is a different issue than other people's issues. The file is correctly uploaded, but stat fails in this opaque way. Race condition would make sense, but I don't know how I'd verify that's what's actually happening.

**Comment by xiaoxiao-24** [comment]
I'm also get the same error when I use the airflow operator **[SFTPOperator](https://airflow.apache.org/docs/apache-airflow-providers-sftp/stable/_api/airflow/providers/sftp/operators/sftp/index.html#airflow.providers.sftp.operators.sftp.SFTPOperator.execute)** to put a file.

> `[2021-04-26 17:20:15,477] {{sftp.py:153}} INFO - Starting to transfer file from /tmp/OK_2021-04-24.csv to upload/incoming/IN/OK_2021-04-24.csv
> [2021-04-26 17:20:15,490] {{taskinstance.py:1455}} ERROR - Error while transferring from /tmp/OK_2021-04-24.csv to upload/incoming/IN/OK_2021-04-24.csv, error: [Errno 2] No such file
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/airflow/providers/sftp/operators/sftp.py", line 154, in execute
>     sftp_client.put(self.local_filepath, self.remote_filepath, confirm=self.confirm)
>   File "/usr/local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 759, in put
>     return self.putfo(fl, remotepath, file_size, callback, confirm)
>   File "/usr/local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 714, in putfo
>     with self.file(remotepath, "wb") as fr:
>   File "/usr/local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 372, in open
>     t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
>   File "/usr/local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 813, in _request
>     return self._read_response(num)
>   File "/usr/local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 865, in _read_response
>     self._convert_status(msg)
>   File "/usr/local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 894, in _convert_status
>     raise IOError(errno.ENOENT, text)
> FileNotFoundError: [Errno 2] No such file
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
>     self._prepare_and_execute_task_with_callbacks(context, task)
>   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
>     result = self._execute_task(context, task_copy)
>   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
>     result = task_copy.execute(context=context)
>   File "/usr/local/airflow/modules/lbc/airflow/operators/ftp.py", line 596, in execute
>     super().execute(context)
>   File "/usr/local/lib/python3.7/site-packages/airflow/providers/sftp/operators/sftp.py", line 157, in execute
>     raise AirflowException(f"Error while transferring {file_msg}, error: {str(e)}")
> airflow.exceptions.AirflowException: Error while transferring from /tmp/OK_LBC_SI_ACS_ANNONCES_EN_LOT_2021-04-24.csv to upload/incoming/IN/OK_LBC_SI_ACS_ANNONCES_EN_LOT_2021-04-24.csv, error: [Errno 2] No such file
> [2021-04-26 17:20:15,491] {{taskinstance.py:1503}} INFO - Marking task as FAILED. dag_id=notebook_science_crm_ads_by_lot, task_id=upload_ok_file_to_sftp, execution_date=20210424T220000, start_date=20210426T172014, end_date=20210426T172015
> [2021-04-26 17:20:15,522] {{configuration.py:356}} WARNING - section/key [smtp/smtp_user] not found in config`
> 

solution is we should use a absolu path for `local_filepath="/tmp/file.txt"` and `remote_filepath="/tmp/tmp1/tmp2/file.txt"`.

**Comment by smittysmee** [comment]
Bump on this

**Comment by max-l** [comment]
I'm getting the bug with paramiko version 2.11.0, pythin 3.8.10
The bug is intermittent, it happens 30% of the time.

**Comment by cyptech27** [comment]
Just be sure the all the folders are correctly created and have the same naming as in the script.

**Comment by ovatsug35** [comment]
thank, it was a good solution
