### ISSUE TITLE
AttributeError: 'Backend' object has no attribute 'x25519_supported'

### ISSUE THREAD

**Issue by ababak** [paramiko/paramiko#1492]
After reinstalling Paramiko, I've got this:
```
Python 2.7.5 (default, Jun 20 2019, 20:27:34) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 129, in <module>
    class Transport(threading.Thread, ClosingContextManager):
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 190, in Transport
    if KexCurve25519.is_available():
  File "/usr/lib/python2.7/site-packages/paramiko/kex_curve25519.py", line 30, in is_available
    X25519PrivateKey.generate()
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/x25519.py", line 39, in generate
    if not backend.x25519_supported():
AttributeError: 'Backend' object has no attribute 'x25519_supported'
```

**Comment by ababak** [comment]
P.S. And then when exiting:

```
>>> 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 120, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 120, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable
```

**Comment by ploxiln** [comment]
```
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/x25519.py", line 39, in generate
    if not backend.x25519_supported():
AttributeError: 'Backend' object has no attribute 'x25519_supported'
```

this means that your `cryptography` library installation is messed up. Perhaps it is linking to an openssl it did not expect. Or maybe you have both an older version installed from a system package and a newer version installed from pip, and some part of it is being imported from the older package and some part from the newer, somehow.

**Comment by ababak** [comment]
Reinstalling `cryptography` did help.
Thank you
