### ISSUE TITLE
SSH server can't be logged on second time after logged on once.

### ISSUE THREAD

**Issue by agzpaoyi** [paramiko/paramiko#1499]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\109.104.117.190\iv\Python-Scripts\PYTS2.0\PYTS\driver\ssh.py", line 74, in initSsh
    self.client.connect(hostname, port, username, password)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paramiko\client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paramiko\transport.py", line 660, in start_client
    raise e
  File "C:\ProgramData\Anaconda3\lib\site-packages\paramiko\transport.py", line 2083, in run
    self._handler_table[ptype](self, m)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paramiko\transport.py", line 2199, in _negotiate_keys
    self.kex_engine.start_kex()
  File "C:\ProgramData\Anaconda3\lib\site-packages\paramiko\kex_curve25519.py", line 54, in start_kex
    serialization.Encoding.Raw, serialization.PublicFormat.Raw
  File "C:\Users\SRCS\AppData\Roaming\Python\Python37\site-packages\cryptography\hazmat\backends\openssl\x25519.py", line 63, in public_bytes
    encoding, format, self, self._evp_pkey, None
  File "C:\Users\SRCS\AppData\Roaming\Python\Python37\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1814, in _public_key_bytes
    raise TypeError("encoding must be an item from the Encoding enum")
TypeError: encoding must be an item from the Encoding enum

[DU] Init DU Ssh Error!

My logging on script is as follows,
self.trans = paramiko.Transport((hostname, port))
self.trans.connect(username=username, password=password)
            
self.ssh = paramiko.SSHClient()
self.ssh._transport = self.trans
self.ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy()) 

self.channel = self.trans.open_session()
           
self.channel.get_pty()
self.channel.invoke_shell()
self.channel.settimeout(9000)

**Comment by agzpaoyi** [comment]
I have tried many times in spyder, I have to restart kernal if I have connected to the ssh server once. But I need to connect  and disconnect to the server repeatly for many times in my case.
Have you got any idea to solve this case? Or is there any problem in basis code?
Environment:
paramiko: 2.6
cryptography: 2.7
win7 64bit
Thanks a lot!

**Comment by agzpaoyi** [comment]
SSH debug shows as below:
DEB [20190827-19:37:27.616] thr=3   paramiko.transport: starting thread (client mode): 0x87643d30
DEB [20190827-19:37:27.636] thr=3   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.6.0
DEB [20190827-19:37:27.638] thr=3   paramiko.transport: Remote version/idstring: SSH-2.0-OpenSSH_7.4
INF [20190827-19:37:27.639] thr=3   paramiko.transport: Connected (version 2.0, client OpenSSH_7.4)
DEB [20190827-19:37:27.642] thr=3   paramiko.transport: kex algos:['curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr'] client mac:['hmac-sha1', 'hmac-ripemd160'] server mac:['hmac-sha1', 'hmac-ripemd160'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEB [20190827-19:37:27.644] thr=3   paramiko.transport: Kex agreed: curve25519-sha256@libssh.org
DEB [20190827-19:37:27.646] thr=3   paramiko.transport: HostKey agreed: ssh-ed25519
DEB [20190827-19:37:27.648] thr=3   paramiko.transport: Cipher agreed: aes128-ctr
DEB [20190827-19:37:27.650] thr=3   paramiko.transport: MAC agreed: hmac-sha1
DEB [20190827-19:37:27.652] thr=3   paramiko.transport: Compression agreed: none
ERR [20190827-19:37:27.746] thr=3   paramiko.transport: Unknown exception: encoding must be an item from the Encoding enum
ERR [20190827-19:37:27.760] thr=3   paramiko.transport: Traceback (most recent call last):
ERR [20190827-19:37:27.767] thr=3   paramiko.transport:   File "C:\ProgramData\Anaconda3\lib\site-packages\paramiko\transport.py", line 2083, in run
ERR [20190827-19:37:27.774] thr=3   paramiko.transport:     self._handler_table[ptype](self, m)
ERR [20190827-19:37:27.780] thr=3   paramiko.transport:   File "C:\ProgramData\Anaconda3\lib\site-packages\paramiko\transport.py", line 2199, in _negotiate_keys
ERR [20190827-19:37:27.783] thr=3   paramiko.transport:     self.kex_engine.start_kex()
ERR [20190827-19:37:27.788] thr=3   paramiko.transport:   File "C:\ProgramData\Anaconda3\lib\site-packages\paramiko\kex_curve25519.py", line 54, in start_kex
ERR [20190827-19:37:27.791] thr=3   paramiko.transport:     serialization.Encoding.Raw, serialization.PublicFormat.Raw
ERR [20190827-19:37:27.793] thr=3   paramiko.transport:   File "C:\Users\SRCS\AppData\Roaming\Python\Python37\site-packages\cryptography\hazmat\backends\openssl\x25519.py", line 63, in public_bytes
ERR [20190827-19:37:27.796] thr=3   paramiko.transport:     encoding, format, self, self._evp_pkey, None
ERR [20190827-19:37:27.799] thr=3   paramiko.transport:   File "C:\Users\SRCS\AppData\Roaming\Python\Python37\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1814, in _public_key_bytes
ERR [20190827-19:37:27.802] thr=3   paramiko.transport:     raise TypeError("encoding must be an item from the Encoding enum")
ERR [20190827-19:37:27.805] thr=3   paramiko.transport: TypeError: encoding must be an item from the Encoding enum

**Comment by agzpaoyi** [comment]
It is a installing problem.. I installed cryptography to the 'User\AppData\Roaming\Python\Python37\site-packages' directory using pip --user command. I moved to normal dir and the error no longer comes.
