### ISSUE TITLE
Paramiko error with threads 

### ISSUE THREAD

**Issue by Ismael-Safadi** [paramiko/paramiko#1511]
ERROR:paramiko.transport:  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 2039, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 2216, in _check_banner
ERROR:paramiko.transport:    "Error reading SSH protocol banner" + str(e)
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner

hi guys , im using paramiko version 2.6 and im facing this error when execute this pice of code with multiThreading 

`ssh = paramiko.SSHClient() 

    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    ssh_stdin = ssh_stdout = ssh_stderr = None

    pointer = False

    ssh.connect(hostname, username=username, password=password)`

**Comment by faydogan** [comment]
Hi Ismael,

We were getting the same error from some of our switches/routers, we find a work around with defining Telnet connections accepted and both telnet/ssh forbidden ones. This error occures on modems (drytek, hw, airties etc.) because of package sizes are different.

So, we have defined a function as shown below, this might give you an idea (you can omit the SQL part :) ) :
`def connectToCPESSH(ip, uname, pin, CI_LOCAL_ID, CI_Name, CI_Org_Name, runIDnull):
    ip =  ip.strip()
    SSHCliente = ""
    try:
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        client.connect(ip, port=22, username=uname, password=pin, timeout=240,banner_timeout=250, auth_timeout=500)
        SSHCliente = client.invoke_shell()
        return SSHCliente
    except paramiko.ssh_exception.SSHException as ssh1Err:
        #print("Cihaz SSH version hatası : " + str(ssh1Err))
        return "Cihaz SSH version hatası : " + str(ssh1Err)
        if isinstance(SSHCliente, paramiko.channel.Channel):
            SSHCliente.close()
        sys.exit()
    except ValueError as ssh2Err:
        #print("Cihaz SSH version error: " + str(ssh2Err))
        return "Cihaz SSH version error: " + str(ssh2Err)
        if isinstance(SSHCliente, paramiko.channel.Channel):
            SSHCliente.close()
        sys.exit()
    except TypeError as ssh3Err:
        #print("Cihaz SSH version error: " + str(ssh3Err))
        return "Cihaz SSH version error: " + str(ssh3Err)
        if isinstance(SSHCliente, paramiko.channel.Channel):
            SSHCliente.close()
        sys.exit()
    except Exception as e:
        if isinstance(SSHCliente, paramiko.channel.Channel):
            SSHCliente.close()
        try:
            tln = telnetlib.Telnet(ip)
            result = tln.read_until(b":")
            rsT = "TELNET Response : \r\n" + str(result)
            #logging.warn("Upsss! SSH Connection Failed ! But Telnet Succeeded" + str(e))
            #logging.warn("Upsss! SSH Connection Failed ! But Telnet Succeeded")
            sqlQueryr = "INSERT INTO autocpe.autocpecheck (CI_LOCAL_ID, CI_Org_Name, CI_NAME, CI_IP_ADDRESS, CI_CLASS, LOOPBACK100IP,RUNID) \
            VALUES (%s, %s, %s, %s, %s, %s, %s)"
            sqlValuesr = (int(CI_LOCAL_ID), str(CI_Org_Name), str(CI_Name), str(ip), 'ERROR IN CONNECTION (SSH) !!!', str(rsT),str(runIDnull))
            DBCxn2 = mysql.connector.connect(
              host="localhost",
              user="root",
              passwd=""
            )
            try:
                insertSQL2 = DBCxn2.cursor()
                insertSQL2.execute(sqlQueryr, sqlValuesr)
            except Exception as m:
                print("SQL INSERT Error"+m.args)
            finally:
                DBCxn2.commit()
                DBCxn2.close()
                tln.close()
            sys.exit()
            return "none"
        except Exception as t:
            #logging.warn("Upsss! Both Telnet and SSH Connection Failed ! " + str(e) + " ### " + str(t))
            logging.warn("Upsss! Both Telnet and SSH Connection Failed ! ")
            sqlQueryr = "INSERT INTO autocpe.autocpecheck (CI_LOCAL_ID, CI_Org_Name, CI_NAME, CI_IP_ADDRESS, CI_CLASS, LOOPBACK100IP,RUNID) \
            VALUES (%s, %s, %s, %s, %s, %s, %s)"
            sqlValuesr = (int(CI_LOCAL_ID), str(CI_Org_Name), str(CI_Name), str(ip), 'ERROR IN CONNECTION (SSH & TELNET) !!!', str(e) + "\r\n" + str(t),str(runIDnull))
            DBCxn2 = mysql.connector.connect(
              host="localhost",
              user="root",
              passwd=""
            )
            try:
                insertSQL2 = DBCxn2.cursor()
                insertSQL2.execute(sqlQueryr, sqlValuesr)
            except Exception as m:
                print("SQL INSERT ERROR 2" + m.args)
            finally:
                DBCxn2.commit()
                DBCxn2.close()
            sys.exit()
            return "none"`

**Comment by AstraLuma** [comment]
I think I'm hitting this. I'm doing work with `concurrent.futures` and threads, using one connection per job, and 20 threads I start getting:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/local/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/usr/local/lib/python3.8/site-packages/paramiko/packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./skopeo-pull.py", line 41, in <module>
    proc = run_command_rand(f"skopeo list-tags docker://{image}")
  File "./skopeo-pull.py", line 37, in run_command_rand
    return run_command(host, command)
  File "/workspaces/ptc-testing/ssh.py", line 35, in run_command
    client = connect_ssh(host)
  File "/workspaces/ptc-testing/ssh.py", line 30, in connect_ssh
    client.connect(**cfg)
  File "/usr/local/lib/python3.8/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```
