### ISSUE TITLE
Paramiko Invalid key on ed25519 host key

### ISSUE THREAD

**Issue by teran-mckinney** [paramiko/paramiko#1517]
In upgrading to Debian Buster (client and server), I noticed this bug. I'm using an RSA private key to connect.

```
DEBUG:paramiko.transport:starting thread (client mode): 0x91566be0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.9p1
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.9p1)
DEBUG:paramiko.transport:kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1'] server key:['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
DEBUG:paramiko.transport:HostKey agreed: ssh-ed25519
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
/usr/local/lib/python3.7/dist-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())
/usr/local/lib/python3.7/dist-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.curve, Q_S_bytes
/usr/local/lib/python3.7/dist-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  hm.add_string(self.Q_C.public_numbers().encode_point())
DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-ed25519 host key for [127.0.0.1]:4000: b'5604030da55b2a7efac8485f5710f3e2'
Traceback (most recent call last):
  File "/usr/local/sbin/vwcmd", line 269, in <module>
    output = cli.run()
  File "/usr/local/lib/python3.7/dist-packages/aaargh/app.py", line 176, in run
    return func(**kwargs)
  File "/usr/local/sbin/vwcmd", line 120, in ssh_all
    raise(e)
  File "/usr/local/sbin/vwcmd", line 111, in ssh_all
    key_filename=key_filename)
  File "/usr/local/sbin/vwcmd", line 80, in ssh
    key_filename=key_filename)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/client.py", line 437, in connect
    passphrase,
  File "/usr/local/lib/python3.7/dist-packages/paramiko/client.py", line 749, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.7/dist-packages/paramiko/client.py", line 662, in _auth
    key_filename, pkey_class, passphrase
  File "/usr/local/lib/python3.7/dist-packages/paramiko/client.py", line 571, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/pkey.py", line 206, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/ed25519key.py", line 81, in __init__
    signing_key = self._parse_signing_key_data(data, password)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/ed25519key.py", line 130, in _parse_signing_key_data
    raise SSHException("Invalid key")
```

2.4.2, 2.4.3, 2.5.1, 2.6.0 all do this. `ssh` works just fine.

**Comment by MichalMazurek** [comment]
I had the same error, the issue is that it tries to go through all available PKey classes and it overwrites `saved_exception` for each loop over the classes, the culprit is here (paramiko/client.py:631):
```python
        if not two_factor:
            for key_filename in key_filenames:
                for pkey_class in (RSAKey, DSSKey, ECDSAKey, Ed25519Key):
                    try:
                        key = self._key_from_filepath(key_filename, pkey_class, passphrase)
                        allowed_types = set(self._transport.auth_publickey(username, key))
                        two_factor = allowed_types & two_factor_types
                        if not two_factor:
                            return
                        break
                    except SSHException as e:
                        saved_exception = e
```

The issue actually is in RSAKey or really PKey class, it errors on parsing of the first line of the key file. In my case my rsa key starts with:
```
-----BEGIN OPENSSH PRIVATE KEY-----
```
And code at (paramiko/pkey.py:270) looks like that:
```python
    def _read_private_key(self, tag, f, password=None):
        lines = f.readlines()
        start = 0
        beginning_of_key = "-----BEGIN " + tag + " PRIVATE KEY-----"
        while start < len(lines) and lines[start].strip() != beginning_of_key:
            start += 1
        if start >= len(lines):
            raise SSHException("not a valid " + tag + " private key file")
        # parse any headers first
        ...
```

And `tag` gets only two values, `RSA` or `DSA` - not `OPENSSH` as stated in pkey file.

**Comment by teran-mckinney** [comment]
Thank for digging into this. Nice findings!

**Comment by ploxiln** [comment]
support for the new openssh key format is proposed in #1343

**Comment by teran-mckinney** [comment]
Great, thank you!

**Comment by hSaria** [comment]
Support added in Paramiko [2.7](https://github.com/paramiko/paramiko/blob/master/sites/www/changelog.rst).

**Comment by rgl** [comment]
I'm using paramiko 2.7.1 in Windows and this is not working for me. Paramiko can only load legacy PEM private keys (`-----BEGIN RSA PRIVATE KEY-----`).

I'm using Python 3.8.5 and these packages:

```
    windows: Running C:\vagrant\examples\python\execute-command\run.ps1...
    windows: Collecting paramiko==2.7.1
    windows:   Downloading paramiko-2.7.1-py2.py3-none-any.whl (206 kB)
    windows: Collecting bcrypt>=3.1.3
    windows:   Downloading bcrypt-3.2.0-cp36-abi3-win_amd64.whl (28 kB)
    windows: Collecting cryptography>=2.5
    windows:   Downloading cryptography-3.1-cp38-cp38-win_amd64.whl (1.5 MB)
    windows: Collecting pynacl>=1.0.1
    windows:   Downloading PyNaCl-1.4.0-cp38-cp38-win_amd64.whl (206 kB)
    windows: Collecting six>=1.4.1
    windows:   Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
    windows: Collecting cffi>=1.1
    windows:   Downloading cffi-1.14.2-cp38-cp38-win_amd64.whl (179 kB)
    windows: Collecting pycparser
    windows:   Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
    windows: Installing collected packages: six, pycparser, cffi, bcrypt, cryptography, pynacl, paramiko
    windows: Successfully installed bcrypt-3.2.0 cffi-1.14.2 cryptography-3.1 paramiko-2.7.1 pycparser-2.20 pynacl-1.4.0 six-1.15.0
```

The full source code is at https://github.com/rgl/openssh-server-windows-vagrant/tree/master/examples/python/execute-command.

**Comment by ploxiln** [comment]
@rgl I think that particular bug may be fixed by https://github.com/paramiko/paramiko/pull/1606

The relevant error report from your linked code sample, for convenience:

```
# NB paramiko ONLY supports the legacy PEM private key format of:
#       -----BEGIN RSA PRIVATE KEY-----
# NB it does NOT support the more recent format of:
#       -----BEGIN OPENSSH PRIVATE KEY-----
#    if you try, it will error with a strange error of:
#       paramiko.ssh_exception.SSHException: Invalid key
#       ValueError: ('Invalid private key', [
#           _OpenSSLErrorWithText(
#               code=67764350,
#               lib=4,
#               func=160,
#               reason=126,
#               reason_text=b'error:040A007E:rsa routines:RSA_check_key_ex:iqmp not inverse of q')])
```

**Comment by rgl** [comment]
@ploxiln or maybe https://github.com/paramiko/paramiko/commit/81064206bf3cec2ca4372257ff138481e1227b91
