### ISSUE TITLE
Paramiko error with password identification

### ISSUE THREAD

**Issue by jaimesaez97** [paramiko/paramiko#1522]
Hello.

I have done all the steps explained here and I have an error testing demo.py and demo_server.py.

In the server machine (192.168.159.29) I run demo_server.py

    ubuntu@osm:~/paramiko/demos$ sudo python demo_server.py
    Read key: 60733844cb5186657fdedaa22b5a57d5
    Listening for connection ...
In the client machine (192.168.159.27) I run demo.py and connect to 192.168.159.29:

    osm@osm:~/paramiko/demos$ sudo python demo.py
    Hostname: 192.168.159.29:2200
And these are the results on both machine:

Server Machine

  ubuntu@osm:~/paramiko/demos$ sudo python demo_server.py
  Read key: 60733844cb5186657fdedaa22b5a57d5
  Listening for connection ...
  Got a connection!
  *** No channel.
Client Machine

  osm@osm:~/paramiko/demos$ sudo python demo.py
  Hostname: 192.168.159.29:2200
  *** WARNING: Unknown host key!
  Username [root]: ubuntu
  Auth by (p)assword, (r)sa key, or (d)ss key? [p] p
  Password for osm@192.168.159.29:
  *** Caught exception: <class 'paramiko.ssh_exception.AuthenticationException'>: Authentication failed.
  Traceback (most recent call last):
    File "demo.py", line 166, in <module>
      manual_auth(username, hostname)
    File "demo.py", line 94, in manual_auth
      t.auth_password(username, pw)
    File "/home/osm/.local/lib/python2.7/site-packages/paramiko/transport.py", line 1509, in auth_password
      return self.auth_handler.wait_for_response(my_event)
    File "/home/osm/.local/lib/python2.7/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
      raise e
  AuthenticationException: Authentication failed.

I also have tested to ssh the server machine with the same parameters through `ssh command` and it works successfully.

Regards.

**Comment by ZupoLlask** [comment]
Hi @jaimesaez97!

Were you passing an object to password attribute from connect() method...
```
host = '127.0.0.1'
user = 'youruser'
pass = 'yourpass'
paramiko.SSHClient().connect(host, username=user, password=pass)
```

... or directly the password string itself?
```
host = '127.0.0.1'
user = 'youruser'
paramiko.SSHClient().connect(host, username=user, password='yourpass')
```

I've just found out that the former fails as in your logs, while the latter works as expected!

**Comment by ljluestc** [comment]
```

import socket
import threading
import paramiko

host_key = paramiko.RSAKey(filename='test_rsa.key')

class Server(paramiko.ServerInterface):
    def _init_(self):
        self.event = threading.Event()

    def check_channel_request(self, kind, chanid):
        if kind == 'session':
            return paramiko.OPEN_SUCCEEDED
        return paramiko.OPEN_FAILED_ADMINISTRATIVELY_PROHIBITED

    def check_auth_password(self, username, password):
        if (username == 'osm') and (password == 'yourpassword'):
            return paramiko.AUTH_SUCCESSFUL
        return paramiko.AUTH_FAILED

server = '192.168.159.29'
ssh_port = 2200

try:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind((server, ssh_port))
except Exception as e:
    print(f'Bind failed: {e}')
    exit(1)

try:
    sock.listen(100)
    print('Listening for connection ...')
    client, addr = sock.accept()
except Exception as e:
    print(f'Listen/accept failed: {e}')
    exit(1)

print('Got a connection!')

try:
    t = paramiko.Transport(client)
    t.add_server_key(host_key)
    server = Server()

    try:
        t.start_server(server=server)
    except paramiko.SSHException:
        print('SSH negotiation failed.')

    chan = t.accept(20)
    if chan is None:
        print('*** No channel.')
        exit(1)

    print('Authenticated!')

    chan.send('Welcome to ssh server!')
    while True:
        try:
            command = input("Enter command: ").strip('\n')
            if command != '':
                chan.send(command)
                print(chan.recv(1024).decode('utf-8'))
        except KeyboardInterrupt:
            print('Exiting.')
            break
    chan.close()
    t.close()
except Exception as e:
    print(f'Caught exception: {e}')
    try:
        t.close()
    except:
        pass
    exit(1)
```

**Comment by jun66j5** [comment]
@ljluestc Stop spamming
