### ISSUE TITLE
can't catch exception when init SSHClient.connect() using incorrect ip

### ISSUE THREAD

**Issue by Jefung** [paramiko/paramiko#1530]
1. environment
* python3.6
* paramiko 2.6.0
2. my test code
```python
import paramiko
ip="116.62.186.208" # ip is wrong
port="22"
username="jefung"
id_rsa_file="/Users/jefung/.ssh/id_rsa"
ssh = paramiko.SSHClient()
private_key_path = id_rsa_file
key = paramiko.RSAKey.from_private_key_file(private_key_path)
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
try:
    ssh.connect(ip, port, username, key, timeout=10)
except Exception as e:
    print("my catch exception: {}".format(e))
```
3.  test code output
there is a Unknown exception that I can't catch.
```bash
my catch exception: Expected unicode or bytes, got <paramiko.rsakey.RSAKey object at 0x000002D496B9F5F8>
Unknown exception: Expected unicode or bytes, got <paramiko.rsakey.RSAKey object at 0x000002D496B9F5F8>
Traceback (most recent call last):
  File "D:\py3.6\lib\site-packages\paramiko\transport.py", line 2109, in run
    handler(self.auth_handler, m)
  File "D:\py3.6\lib\site-packages\paramiko\auth_handler.py", line 283, in _parse_service_accept
    password = b(self.password)
  File "D:\py3.6\lib\site-packages\paramiko\py3compat.py", line 142, in b
    raise TypeError("Expected unicode or bytes, got {!r}".format(s))
TypeError: Expected unicode or bytes, got <paramiko.rsakey.RSAKey object at 0x000002D496B9F5F8>
```
4. my question
how can I handle exception when  connect() failed?

**Comment by ploxiln** [comment]
The fourth argument to `SSHClient.connect()` is _password_, not _pkey_, so that is causing the exception you are getting in that example. The transport was able to connect to that ip address, there is an ssh server there:

```
$ nc 116.62.186.208 22
SSH-2.0-OpenSSH_6.6.1
```
