### ISSUE TITLE
 Exception: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by matingara** [paramiko/paramiko#1533]
I am trying to use paramiko to get information from a Juniper SRX5800 through a proxy connection.

My development environment is on a MacBook Pro and I am a little suspicious that this may have something to do with the "ssh" on the Mac Book Pro itself.

The code I am using works just fine when connecting to a router running NX-OS (A Cisco 7010).

When I hit the Junos box I get the following result:

 Exception: Error reading SSH protocol banner

Can someone please advise if there is a solution to this or what further information I should provide.

Thanks.

The full set of messages are as follows:

2019-10-24 13:30:57,918 - [netab]- CRITICAL - dcnvnj1822da4501 - show chassis routing-engine - proxy connected
2019-10-24 13:30:58,902 - [netab]- ERROR    - Exception: Error reading SSH protocol banner
2019-10-24 13:30:58,904 - [netab]- ERROR    - Traceback (most recent call last):
2019-10-24 13:30:58,904 - [netab]- ERROR    -   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/transport.py", line 2211, in _check_banner
2019-10-24 13:30:58,904 - [netab]- ERROR    -     buf = self.packetizer.readline(timeout)
2019-10-24 13:30:58,904 - [netab]- ERROR    -   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/packet.py", line 380, in readline
2019-10-24 13:30:58,904 - [netab]- ERROR    -     buf += self._read_timeout(timeout)
2019-10-24 13:30:58,904 - [netab]- ERROR    -   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/packet.py", line 609, in _read_timeout
2019-10-24 13:30:58,904 - [netab]- ERROR    -     raise EOFError()
2019-10-24 13:30:58,904 - [netab]- ERROR    - EOFError
2019-10-24 13:30:58,904 - [netab]- ERROR    - 
2019-10-24 13:30:58,904 - [netab]- ERROR    - During handling of the above exception, another exception occurred:
2019-10-24 13:30:58,904 - [netab]- ERROR    - 
2019-10-24 13:30:58,904 - [netab]- ERROR    - Traceback (most recent call last):
2019-10-24 13:30:58,904 - [netab]- ERROR    -   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/transport.py", line 2039, in run
2019-10-24 13:30:58,904 - [netab]- ERROR    -     self._check_banner()
2019-10-24 13:30:58,904 - [netab]- ERROR    -   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/transport.py", line 2216, in _check_banner
2019-10-24 13:30:58,904 - [netab]- ERROR    -     "Error reading SSH protocol banner" + str(e)
2019-10-24 13:30:58,904 - [netab]- ERROR    - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2019-10-24 13:30:58,905 - [netab]- ERROR    - 
2019-10-24 13:30:58,905 - [netab]- CRITICAL - dcnvnj1822da4501 - show chassis routing-engine - Logon failed
2019-10-24 13:30:58,905 - [netab]- WARNING  - dcnvnj1822da4501 - show chassis routing-engine - thread finished

**Comment by mayalaso** [comment]
I ran into the same issue. If I ssh directly from the terminal it goes thru fine. But if I use python code (paramiko) to connect to SRX it throws me the same error. Mine is MacOS Mohave 10.14.6. Does anyone know what is the solution to this problem.

**Comment by muksatgit** [comment]
for me, I just switched my network form a firewalled to an open network and everything worked

**Comment by lokesh8421** [comment]
I am also experiencing the same error.
------------------------------------
ERROR    paramiko.transport:transport.py:1819 Exception: Error reading SSH protocol banner
ERROR    paramiko.transport:transport.py:1817 Traceback (most recent call last):
ERROR    paramiko.transport:transport.py:1817   File "/opt/freeware/lib/python3.7/site-packages/paramiko/transport.py", line 2212, in _check_banner
ERROR    paramiko.transport:transport.py:1817     buf = self.packetizer.readline(timeout)
ERROR    paramiko.transport:transport.py:1817   File "/opt/freeware/lib/python3.7/site-packages/paramiko/packet.py", line 380, in readline
ERROR    paramiko.transport:transport.py:1817     buf += self._read_timeout(timeout)
ERROR    paramiko.transport:transport.py:1817   File "/opt/freeware/lib/python3.7/site-packages/paramiko/packet.py", line 609, in _read_timeout
ERROR    paramiko.transport:transport.py:1817     raise EOFError()
ERROR    paramiko.transport:transport.py:1817 EOFError
ERROR    paramiko.transport:transport.py:1817
ERROR    paramiko.transport:transport.py:1817 During handling of the above exception, another exception occurred:
ERROR    paramiko.transport:transport.py:1817
ERROR    paramiko.transport:transport.py:1817 Traceback (most recent call last):
ERROR    paramiko.transport:transport.py:1817   File "/opt/freeware/lib/python3.7/site-packages/paramiko/transport.py", line 2039, in run
ERROR    paramiko.transport:transport.py:1817     self._check_banner()
ERROR    paramiko.transport:transport.py:1817   File "/opt/freeware/lib/python3.7/site-packages/paramiko/transport.py", line 2217, in _check_banner
ERROR    paramiko.transport:transport.py:1817     "Error reading SSH protocol banner" + str(e)
ERROR    paramiko.transport:transport.py:1817 paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR    paramiko.transport:transport.py:1817

**Comment by vanhul** [comment]
Sadly, same error :(

**Comment by Kani999** [comment]
Also running into the same issue.

```
Local version/idstring: SSH-2.0-paramiko_2.7.2
Exception: Error reading SSH protocol banner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/opt/nautobot/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

I'm using optional arguments as follow `{'conn_timeout': 3000, 'auth_timeout': 3000, 'banner_timeout': 3000, 'session_timeout': 3000}` but with no luck.
