### ISSUE TITLE
paramiko.ssh_exception.AuthenticationException: Authentication failed.

### ISSUE THREAD

**Issue by matingara** [paramiko/paramiko#1534]
I am trying to use paramiko to get information from a Cisco "ios" box through a proxy connection.

The ios box is as follows:

Cisco IOS XE Software, Version 03.13.07.S - Extended Support Release
Cisco IOS Software, ASR1000 Software (X86_64_LINUX_IOSD-ADVENTERPRISEK9-M), Version 15.4(3)S7, RELEASE SOFTWARE (fc3)

My development environment is on a MacBook Pro and I am a little suspicious that this may have something to do with the "ssh" on the Mac Book Pro itself.

The code I am using works just fine when connecting to a router running NX-OS (A Cisco 7010).

When I hit the "ios" box I get the following result:

paramiko.ssh_exception.AuthenticationException: Authentication failed.

If i run the exact same code in a docker container on a RHEL server it works just fine.  (My next step is to spin up a copy of this Docker container on my Mac).

Any advice?

Thanks.

Full set of error messages below:

2019-10-24 13:36:15,142 - [netab]- INFO     - exhi1-ncs-r03 - show processes cpu sort | include "seconds" - proxy connected
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/joelspencer/Library/Mobile Documents/com~apple~CloudDocs/Box Sync/Box Sync/source/CSD-ALL-AVITA/csd-avita-netab/netab-app/netab/utils.py", line 194, in run
    pkey=None, key_filename=None, timeout=None, allow_agent=True, compress=False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/client.py", line 751, in _auth
    self._transport.auth_password(username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/transport.py", line 1509, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paramiko/auth_handler.py", line 236, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

**Comment by matingara** [comment]
This afternoon, I have spun up my application (written using python 3.7, flask, restplus) in a Docker container on my Mac and the ssh problems have disappeared.

So the problem is definitely something to do with "ssh" on the Mac itself.

**Comment by ZupoLlask** [comment]
Hi @matingara!

Were you passing an object to password attribute from connect() method...
```
host = '127.0.0.1'
user = 'youruser'
pass = 'yourpass'
paramiko.SSHClient().connect(host, username=user, password=pass)
```

... or directly the password string itself?
```
host = '127.0.0.1'
user = 'youruser'
paramiko.SSHClient().connect(host, username=user, password='yourpass')
```

I've just found out that the former fails as in your logs, while the latter works as expected!
