### ISSUE TITLE
Import Error on Paramiko

### ISSUE THREAD

**Issue by kk20198615** [paramiko/paramiko#1539]
Hi.,

When i tried to import paramiko i am getting below error. Please help me to solve it.

I have tried adding python DLL path ssystem variable it did not help me 

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-110cb50357c7>", line 1, in <module>
    import paramiko
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.6\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.6\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paramiko\transport.py", line 129, in <module>
    class Transport(threading.Thread, ClosingContextManager):
  File "C:\ProgramData\Anaconda3\lib\site-packages\paramiko\transport.py", line 190, in Transport
    if KexCurve25519.is_available():
  File "C:\ProgramData\Anaconda3\lib\site-packages\paramiko\kex_curve25519.py", line 30, in is_available
    X25519PrivateKey.generate()
  File "C:\Users\knavagekar\AppData\Roaming\Python\Python37\site-packages\cryptography\hazmat\primitives\asymmetric\x25519.py", line 38, in generate
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.6\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\knavagekar\AppData\Roaming\Python\Python37\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.6\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\knavagekar\AppData\Roaming\Python\Python37\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 75, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.6\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\knavagekar\AppData\Roaming\Python\Python37\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 195, in <module>
    Binding.init_static_locks()
  File "C:\Users\knavagekar\AppData\Roaming\Python\Python37\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 142, in init_static_locks
    __import__("_ssl")
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.6\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    self.showtraceback(running_compiled_code=True)
TypeError: showtraceback() got an unexpected keyword argument 'running_compiled_code'

**Comment by ploxiln** [comment]
This an error in the [cryptography module](https://github.com/pyca/cryptography) importing its openssl binary component. Try re-pip-installing cryptography, and if you still get this problem you can ask at the cryptography project linked above.
