### ISSUE TITLE
SSHException: key cannot be used for signing

### ISSUE THREAD

**Issue by kmoza** [paramiko/paramiko#1574]
I am trying to do an SSH connection to a device from my host and on both host and device I have Ubuntu 18.04 installed. I use paramiko library to connect to the device from host and below is the exception I am getting. 

`[2019-12-08 20:09:49,829] [INFO] : Connected (version 2.0, client OpenSSH_7.6)
[2019-12-08 20:09:49,932] [ERROR] : Exception: key cannot be used for signing
[2019-12-08 20:09:49,932] [ERROR] : Traceback (most recent call last):
[2019-12-08 20:09:49,933] [ERROR] :   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1795, in run
[2019-12-08 20:09:49,933] [ERROR] :     self.auth_handler._handler_table[ptype](self.auth_handler, m)
[2019-12-08 20:09:49,933] [ERROR] :   File "/usr/local/lib/python2.7/dist-packages/paramiko/auth_handler.py", line 241, in _parse_service_accept
[2019-12-08 20:09:49,933] [ERROR] :     sig = self.private_key.sign_ssh_data(blob)
[2019-12-08 20:09:49,933] [ERROR] :   File "/usr/local/lib/python2.7/dist-packages/paramiko/agent.py", line 400, in sign_ssh_data
[2019-12-08 20:09:49,934] [ERROR] :     raise SSHException('key cannot be used for signing')
[2019-12-08 20:09:49,934] [ERROR] : SSHException: key cannot be used for signing
[2019-12-08 20:09:49,934] [ERROR] : 
[2019-12-08 20:09:49,949] [WARNING] : [SSH Connection Failed] Unable to connect`

My steps to connect to the device are as below.

`ssh = SSHClient()
            ssh.set_missing_host_key_policy(AutoAddPolicy())
            ssh.connect(self._host, port=self._port, username=self._uname, password=self._pwd, timeout=20,
                        compress=True)`

Since then I have tried to run the connect call in stress using 1 lakhs iterations however the failure didnt reproduce.

What could be the reasons for the above mentioned exception.

**Comment by kmoza** [comment]
Can anyone help on pointing out in which situation the above issue occurs and the probable reason for the same.

**Comment by ploxiln** [comment]
Since you are specifying a password, I'm guessing that you don't intend to use an ssh key file. But it seems that paramiko is finding an ssh key file, but it is a public-key only. So if you specify `look_for_keys=False` and `allow_agent=False` to `ssh.connect()`, that should prevent it from trying to find and use ssh key files, and maybe avoid your problem.

By the way, please use triple-backticks, on their own lines, in order to format a multi-line code quote correctly so that it is readable, like this:

    ```
    triple backticks are on their own lines
    so newlines are preserved
    as intended
    ```

**Comment by kmoza** [comment]
@ploxiln thanks for explanation , but why would paramiko find a ssh key file when `pkey=None, key_filename=None` are by default set to `None`. Also if I am mistaken please let me know at which stage of authentication at http://docs.paramiko.org/en/2.6/api/client.html paramiko is finding the key file according to the above mentioned error.

**Comment by ploxiln** [comment]
> look_for_keys (bool) – set to False to disable searching for discoverable private key files in ~/.ssh/

... otherwise it looks for `~/.ssh/id_rsa` and `~/.ssh/id_ed25519` etc, like the standard openssh client "ssh" does.

> allow_agent (bool) – set to False to disable connecting to the SSH agent

... otherwise it connects to the ssh agent socket at `$SSH_AUTH_SOCK` to try any keys registered with the ssh agent, like the standard openssh client "ssh" does

**Comment by nise** [comment]
@ploxiln Thank you for the hint!

**Comment by kmoza** [comment]
> @ploxiln Thank you for the hint!

@nise Please let us know what issue did you face and how this was helpful.

**Comment by kashirin-alex** [comment]
It is assumed to be the same nature of the issue (Key location and default-configurations).

Is there Truth to the immediate solution? (Are there any suggestions in regards OS-package distributions?)
https://kashirin-alex.github.io/swc-db/install/swcdb_cluster/#known-issues

**Comment by Googluu** [comment]
Graciasssss
