### ISSUE TITLE
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key with ProxyCommand

### ISSUE THREAD

**Issue by JoeCheez** [paramiko/paramiko#1589]
I'm trying to open a connection with ProxyCommand and its inferring an OpenSSH key and failing instead of trying my key as an RSA key.  Am I missing something or is this a bug?  I don't see any way to manually specify a key type on the client.  All my other connections that don't use ProxyCommand are working fine.

```
Traceback (most recent call last):
  File "check-updates.py", line 27, in <module>
    client.connect(host_config.get('hostname'), port, host_config.get('username'), key_filename = host_config.get('identityfile'), sock = paramiko.ProxyCommand(host_config.get('proxycommand')))
  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 677, in _auth
    key_filename, pkey_class, passphrase
  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 586, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/pkey.py", line 235, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/ed25519key.py", line 58, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/pkey.py", line 341, in _read_private_key
    "encountered {} key, expected {} key".format(keytype, tag)
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key
```

**Comment by ploxiln** [comment]
This is a misleading exception ... the paramiko client auth code tried to load your key file with every available key type, and every one had some problem, and this is just the last key type in the list it tried, and the last error it encountered. You could try loading your key file with the `RSAKey` class directly to see what the real exception for that is. If none, maybe it just wasn't accepted by the remote server.

**Comment by JoeCheez** [comment]
Thanks for your assistance.  I managed to make it work with the top example [here](http://www.tonicebrian.com/posts/2016/05/15/python-tunnels.html.), which did include specifying that the key is an RSAKey.
