### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'time' while connecting to openssh 7.4

### ISSUE THREAD

**Issue by xairam** [paramiko/paramiko#1617]
So, I am Having the same problem whiele logging into dells idrac 6.
It takes like 4-6 seconds to login, but I get the content of "ls -la" back, after it "crashes". 

    23:09:53.786 Current date: 2020-02-04
    23:09:53.786 Started a new SSH session.
    23:09:53.790 Connecting to SSH server 192.168.2.3:22.
    23:09:53.792 Connection established.
    23:09:54.820 Server version: SSH-2.0-OpenSSH_7.4
    23:09:54.820 First key exchange started. Cryptographic provider: Windows CNG (x86) with additions
    23:09:54.824 Host key algorithm list after reordering: RSA/sha2-512,RSA/sha2-256,Ed25519,ECDSA/nistp256,RSA,ECDSA/secp256k1,ECDSA/nistp521,ECDSA/nistp384.
    23:09:59.530 Received host key from the server. Algorithm: RSA, size: 2048 bits, SHA-256 fingerprint: wkLKJInigQ3DtHH7yGipvv/3DTXGnpfjzW8FpDlpPm4.
    23:09:59.537 First key exchange completed using Curve25519. Session encryption: aes256-ctr, integrity: hmac-sha1, compression: none.
    23:09:59.537 Attempting password authentication.
    23:10:01.757 Authentication completed.
    23:10:01.757 Extension "no-flow-control" disabled.
    23:10:01.822 Synchronizing with server's host keys.
    23:10:01.832 Host key synchronization completed without saving or erasing any keys. Number of keys received: 4.
    23:10:01.863 Terminal channel opened.
    23:10:01.863 Opened session channel 0.
    23:10:01.877 Terminal channel: PTY request accepted.
    23:10:01.915 Terminal channel: Terminal shell opened.
    23:10:01.924 Terminal channel: Terminal process launched.

This is normal server where no problem occures.

```
    23:10:39.102 Current date: 2020-02-04
    23:10:39.102 Started a new SSH session.
    23:10:39.107 Connecting to SSH server 192.168.2.2:22.
    23:10:39.109 Connection established.
    23:10:39.118 Server version: SSH-2.0-OpenSSH_8.1
    23:10:39.118 First key exchange started. Cryptographic provider: Windows CNG (x86) with additions
    23:10:39.122 Host key algorithm list after reordering: RSA/sha2-512,RSA/sha2-256,Ed25519,ECDSA/nistp256,RSA,ECDSA/secp256k1,ECDSA/nistp521,ECDSA/nistp384.
    23:10:39.143 Received host key from the server. Algorithm: RSA, size: 2048 bits, SHA-256 fingerprint: +TELx98+4h1eSL3e2EMPWn3YKW1Cr5OpR0SyGe30BsI.
    23:10:39.149 First key exchange completed using Curve25519. Session encryption and integrity: aes256-gcm, compression: none.
    23:10:39.150 Attempting password authentication.
    23:10:39.158 Authentication completed.
    23:10:39.158 Extension "no-flow-control" disabled.
    23:10:39.165 Synchronizing with server's host keys.
    23:10:39.165 Host key synchronization completed without saving or erasing any keys. Number of keys received: 3.
    23:10:39.194 Terminal channel opened.
    23:10:39.194 Opened session channel 0.
    23:10:39.201 Terminal channel: PTY request accepted.
    23:10:39.201 Terminal channel: Terminal shell opened.
    23:10:39.211 Terminal channel: Terminal process launched.

```

===============================================================================

RACADM version 2.91 (Build 02)

Copyright (c) 2003-2010 Dell, Inc.

All Rights Reserved

===============================================================================

RACADM usage syntax:

 racadm <subcommand> <options>

Examples:

 racadm getsysinfo

 racadm getsysinfo -d

 racadm getniccfg

 racadm setniccfg -d

 racadm setniccfg -s 192.168.0.120 255.255.255.0 192.168.0.1

 racadm getconfig -g cfgLanNetworking

Display a list of available subcommands for the RAC:

 racadm help

Display more detailed help for a specific subcommand:

 racadm help <subcommand>

-------------------------------------------------------------------------------

Exception ignored in: <function BufferedFile.__del__ at 0x00000257E07BB3A0>
Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\file.py", line 66, in __del__
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\channel.py", line 1392, in close
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\channel.py", line 991, in shutdown_write
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\channel.py", line 967, in shutdown
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python38\lib\site-packages\paramiko\transport.py", line 1846, in _send_user_message
AttributeError: 'NoneType' object has no attribute 'time'

Process finished with exit code 0

**Comment by xairam** [comment]
Its possible to supress this ? I cant explain how this error occures and why... 
when I connect to another server openssh 8.1 i dont have this problem. 

BTW im on windows. Gonna try it on my pi too.

**Comment by max-block** [comment]
I have the the same problem:

```
Exception ignored in: <function BufferedFile.__del__ at 0x10dbe7550>
Traceback (most recent call last):
  File "/Users/max/p/pypi__paramiko/.venv/lib/python3.8/site-packages/paramiko/file.py", line 66, in __del__
  File "/Users/max/p/pypi__paramiko/.venv/lib/python3.8/site-packages/paramiko/channel.py", line 1392, in close
  File "/Users/max/p/pypi__paramiko/.venv/lib/python3.8/site-packages/paramiko/channel.py", line 991, in shutdown_write
  File "/Users/max/p/pypi__paramiko/.venv/lib/python3.8/site-packages/paramiko/channel.py", line 967, in shutdown
  File "/Users/max/p/pypi__paramiko/.venv/lib/python3.8/site-packages/paramiko/transport.py", line 1846, in _send_user_message
AttributeError: 'NoneType' object has no attribute 'time'
```

I'm on macos and using an Ubuntu 18.04 server.

**Comment by baran81** [comment]
Hi,
same issue on with  Python 3.8.1

anyone spot a workaround for this?

**Comment by uerg** [comment]
any updates?
got same problem using Python 3.8.1 paramiko 2.7.1 connecting to OpenSSH_7.9p1, OpenSSL 1.1.1a  20 Nov 2018

**Comment by ploxiln** [comment]
This exception is raised from a simple `time.time()` call here:

```python
    def _send_user_message(self, data):
        """
        send a message, but block if we're in key negotiation.  this is used
        for user-initiated requests.
        """
        start = time.time()
        while True:
            ...
```

That's the standard library `time` module, from `import time` at the top of the file. How could that possibly fail? Well, this must be during the exit of the process, and python must be cleaning up and freeing everything somehow ... I'm not familiar with this process, but it seems likely related to this stuff, also near the top of `transport.py`

```python
# for thread cleanup
_active_threads = []

def _join_lingering_threads():
    for thr in _active_threads:
        thr.stop_thread()

import atexit

atexit.register(_join_lingering_threads)
```

All those threads are "daemonized" with `self.setDaemon(True)`, so this doesn't wait for them to exit. It just tells them to start the process of stopping, then this `atexit` handler finishes, and the threads are still working on stopping after the main thread continues to clean up imports and stuff (well that's my wild guess).

So the fix might be to have this atexit handler wait a second or so for the transport threads to actually exit. (Or get rid of the atexit behavior if it's not really needed.)

**Comment by murmelade** [comment]
Same problem on Python 3.7.3 using Vagrant box debian/buster64.
Can reproduce this issue on Paramiko 2.7.1 and Paramiko 2.7.0.
Paramiko 2.6.0 works without this exception.

**Comment by wirecat** [comment]
I'm also getting this on `ArchLinux 4/9/2020`, `Python 3.8.2`, and `python-paramiko 2.7.1-1`.

**Comment by eduardogpg** [comment]
In some cases this happens, i solved the problem like @wirecat said, I slept the thread for 0.1 seconds before read the stdout.

**Comment by CloudZazu** [comment]
Got the same issue on Python 3.8.4 for Mac Mojave but sleep resolved it.

**Comment by synchronizing** [comment]
Solved issue by using context manager (`__enter__`, `__exit__`) definitions to close session. `time` trick mentioned above did not work for me -- currently utilizing `PySFTP` (wrapper on top of Paramiko). 

* MacOS Mojave 10.15.5
* OpenSSL version LibreSSL 2.8.3
* Python version 3.8.0

**Comment by jon88** [comment]
Had the same problem with:
* Python version 3.8.1
* Paramiko 2.7.2 or 2.7.1

Paramiko 2.6.0 is working without exceptions.
Solved similar as @synchronizing . I had paramiko cleanup in `__del__` method and that was the root cause for me for this issue. After moving the paramiko cleanup to context managers (before GC) everything works.

**Comment by rudy-ve** [comment]
I found an alternative solution.
I had the same problem when  using pysftp
My code was something like :

 **import pysftp**
 ...... some setup
 **sftp = pysftp.Connection (host=ftpHost,username=ftpUser,password=ftpPass, cnopts = cnopts , port= ftpPort )**
........ some ftp commands


At the end of my code i just added
**sftp=None**

And the problem was solved.

**Comment by kajariagrawal** [comment]
@eduardogpg putting a sleep worked

**Comment by vxgmichel** [comment]
I worked around it by closing the `stdin` file object:
```python
stdin, stdout, stderr = client.exec_command('ls -l')
stdin.close()
```

**Comment by noahbroyles** [comment]
> I worked around it by closing the `stdin` file object:
> 
> ```python
> stdin, stdout, stderr = client.exec_command('ls -l')
> stdin.close()
> ```

This did the trick for me on MacOS Catalina! Thank you!

**Comment by Nagidal** [comment]
I am also troubled by this:
```
  File "C:\ProgramData\Anaconda3\envs\claw\lib\site-packages\paramiko\client.py", line 508, in exec_command
    chan = self._transport.open_session(timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'open_session'
```
It happens when I connect to a host which is in the process of booting up and not completely ready to communicate. SSH session gets established, but when I want to use the transport to exec_command, I get this.

Will try the `stdin.close()` trick

**Comment by dlink** [comment]
These didn't work for me:

@eduardogpg's sleep(n)
@rudy-ve's: sftp = None

This DID work for me:

@synchronizing's: \_\_enter\_\_, \_\_exit\_\_ 

However I went with this solution, to simply silence the error, in order to not change my code.

```
    def __del__(self):
	try:
            self.close()
	except Exception as e:
            if str(e) != "'NoneType' object has no attribute 'time'":
		raise
```

CentOS 8, Python 3.9.5

**Comment by john-aws** [comment]
Interestingly, moving the call to `exec_command()` from module-level into a function (`main` in my case) seems to avoid this problem.

```
import paramiko

client = paramiko.SSHClient()
client.load_system_host_keys()

def main():
    client.connect('example.com', username='joe', key_filename='/users/joe/.ssh/joe.pem')
    stdin, stdout, stderr = client.exec_command("ls /home/joe/config/")

    for line in stdout.read().splitlines():
        print("stdout:", line)

    for line in stderr.read().splitlines():
        print("stderr:", line)

if __name__ == "__main__":
    main()
```

**Comment by PangYiMing** [comment]
attempt add "import time" at header.I'm OK.
```
import time
import paramiko

# connect
trans = paramiko.Transport(("xx.xx.xx.xx", 22))
trans.connect(username="root", password="you_passwd")

# trans
ssh = paramiko.SSHClient()
ssh._transport = trans

# your script
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh_stdin, ssh_stdout, ssh_stderr = ssh.exec_command("ls -l")
print(ssh_stdout.read())

# close
trans.close()
```

**Comment by liqi001** [comment]
> These didn't work for me:
> 
> @eduardogpg's sleep(n) @rudy-ve's: sftp = None
> 
> This DID work for me:
> 
> @synchronizing's: __enter__, __exit__
> 
> However I went with this solution, to simply silence the error, in order to not change my code.
> 
> ```
>     def __del__(self):
> 	try:
>             self.close()
> 	except Exception as e:
>             if str(e) != "'NoneType' object has no attribute 'time'":
> 		raise
> ```
> 
> CentOS 8, Python 3.9.5

thanks !! It's very useful !!! it help me ！！

**Comment by bskinn** [comment]
Flagged for policy decision on the [proposed docs change by @stuz5000](https://github.com/paramiko/paramiko/issues/1617#issuecomment-1031729015):

>     * change the recommended usage to be with a context manager (Paramiko should provide and recommend this)

**Comment by tehybel** [comment]
This bug is still relevant in 2024....

It is triggered by this code, which imports paramiko inside an __init__ function:

`    def __init__(self):
        log.debug("making ssh connection..")
        import paramiko
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.load_host_keys(os.path.expanduser('~/.ssh/known_hosts'))
        ssh.connect(SERVER, username="...")

        # stdin, stdout, stderr
        self._remote, self._output, self._ssh_stderr = ssh.exec_command("...")
`

Moving the `import paramiko` line outside of __init__ and to the top of the file resolved the error.

So the issue is triggered whenever exec_command is run within the same scope that imported paramiko.

**Comment by tehybel** [comment]
This can be worked around by adding a check to `_send_user_message` inside `transport.py`:

```
    def _send_user_message(self, data):
        """
        send a message, but block if we're in key negotiation.  this is used
        for user-initiated requests.
        """
        if not self.active:
            return
            
        start = time.time()
        while True:
            self.clear_to_send.wait(0.1)
            if not self.active:
                self._log( 
                    DEBUG, "Dropping user packet because connection is dead."
                )  # noqa
                return
            self.clear_to_send_lock.acquire()
            ...

```

This is needed because if the current thread is shutting down, the reference to the time module is None, so accessing time.time causes an exception. In this situation self.active is False, so there is really no need for the call to time.time at all -- the loop will just return in its first iteration anyway.

Someone with better insight into the code base can determine if this is the right way to fix this, but I've confirmed it does get rid of the error for me.

**Comment by shubhamhii** [comment]
Hi,

We are also seeing the same exception on AIX.

 openssh version: 8.1
python version: 3.12
paramiko version: 4.0.0
