### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 84: invalid start byte

### ISSUE THREAD

**Issue by paragonjh** [paramiko/paramiko#1631]
paramiko version: 2.6.0
When I read the stdout of Korean alphabet in code get this error:

Traceback (most recent call last):
  File "gtest_runner.py", line 305, in execute_zephyr_test
    runResults = executor.runTest()
  File "gtest_runner.py", line 65, in runTest
    for line in self.stdout:
  File "/vol/users/june1103.kim/.local/lib/python3.6/site-packages/paramiko/file.py", line 125, in __next__
    line = self.readline()
  File "/vol/users/june1103.kim/.local/lib/python3.6/site-packages/paramiko/file.py", line 334, in readline
    return line if self._flags & self.FLAG_BINARY else u(line)
  File "/vol/users/june1103.kim/.local/lib/python3.6/site-packages/paramiko/py3compat.py", line 147, in u
    return s.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 84: invalid start byte

please help me :).
I want to read the Korean alphabet in code using parameko.

**Comment by hakaishi** [comment]
Fix in progress. There is a pull request at #1995
