### ISSUE TITLE
double exception on non responding host

### ISSUE THREAD

**Issue by ink1** [paramiko/paramiko#1657]
I'm getting a double exception from a non responding host. Code skeleton:
```
try:
	client = paramiko.SSHClient()
	client.connect(host, timeout=10)
except socket.timeout:
	pass
except paramiko.SSHException:
	pass
except:
	pass
```
The errors:
```
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "paramiko/2.6.0/lib/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "paramiko/2.6.0/lib/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "paramiko/2.6.0/lib/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "paramiko/2.6.0/lib/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "paramiko/2.6.0/lib/paramiko/transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```
I'm not on the latest version but the files in question - transport.py and packet.py - have not been touched since 2.6 release.
When 
https://github.com/paramiko/paramiko/blob/master/paramiko/transport.py#L2211
blows, 
https://github.com/paramiko/paramiko/blob/master/paramiko/transport.py#L2216
still gets triggered even though e is empty.
What is the recommended way of handling such cases?

**Comment by ploxiln** [comment]
> still gets triggered even though e is empty

`e` is a `socket.timeout()` which generates an empty string. It could be fixed by changing the SSHException string formatting.

```
>>> import socket
>>> "%s" % socket.timeout()
''
>>> "%r" % socket.timeout()
'timeout()'
```

The "double exception" is because an exception was raised while handling another exception. But it was intended for the raised exception to *replace* the other exception, and in python2 it did, but in python3 it gets the "During handling of the above exception, another exception occurred" (which is usually helpful, but not intended in this case). This can be fixed by adding `from None` to the end of the `raise SSHException(...)` statement, but that is only compatible with python3, not with python2.

The reason why your try/except clauses do not catch this SSHException is that it occurs in a separate thread with the Transport creates. The client raises yet another exception, which your code catches silently (but you could log or print it to see for sure).
