### ISSUE TITLE
PasswordRequiredException not raised when key with passphrase is passed via 'key_filename'

### ISSUE THREAD

**Issue by ipmonk** [paramiko/paramiko#1664]
when passing in an RSA private key + passphrase as "key_filename", if a passphrase is not supplied it should raise PasswordRequiredException, but it doesn't. 
The following code demonstrates the problem:

> import paramiko
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect("8.8.8.8", username="foobar", port="22", key_filename="id_rsa", passphrase=None)
ssh_session = client.get_transport().open_session()

results in this traceback, which is unexpected

> Traceback (most recent call last):
  File "para.py", line 5, in <module>
    client.connect("8.8.8.8", username="foobar", port="22", key_filename="id_rsa")
  File "/home/user/foo/lib/python3.5/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/home/user/foo/lib/python3.5/site-packages/paramiko/client.py", line 767, in _auth
    raise saved_exception
  File "/home/user/foo/lib/python3.5/site-packages/paramiko/client.py", line 677, in _auth
    key_filename, pkey_class, passphrase
  File "/home/user/foo/lib/python3.5/site-packages/paramiko/client.py", line 586, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/user/foo/lib/python3.5/site-packages/paramiko/pkey.py", line 235, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/user/foo/lib/python3.5/site-packages/paramiko/ed25519key.py", line 58, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/home/user/foo/lib/python3.5/site-packages/paramiko/pkey.py", line 341, in _read_private_key
    "encountered {} key, expected {} key".format(keytype, tag)
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key

I've tested that the PasswordRequiredException does get raised but it is caught by this try: except: block in _auth from client.py:

         for key_filename in key_filenames:
            for pkey_class in (RSAKey, DSSKey, ECDSAKey, Ed25519Key):
                try:
                    key = self._key_from_filepath(
                        key_filename, pkey_class, passphrase
                    )
                    allowed_types = set(
                        self._transport.auth_publickey(username, key)
                    )
                    two_factor = allowed_types & two_factor_types
                    if not two_factor:
                        return
                    break
                except SSHException as e:
                    saved_exception = e
                    
The loop doesn't stop at this point, it carries on processing the other key types until another exception is hit which overwrites PasswordRequiredException, this newer one is raised instead. 

It it feasible for PasswordRequiredException to be raised so the real reason for the failure is exposed?   

// I found that the following method does generate the correct exception. 
// However, libraries such as junos-eznc dont use this method. 

> import paramiko
client = paramiko.SSHClient()
filename = paramiko.RSAKey.from_private_key_file('id_rsa', password=None)
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect("8.8.8.8", username="footer", port="22", pkey=filename)
ssh_session = client.get_transport().open_session()
> Traceback (most recent call last):
  File "para.py", line 3, in <module>
    filename = paramiko.RSAKey.from_private_key_file('id_rsa', password=None)
  File "/home/user/foo/lib/python3.5/site-packages/paramiko/pkey.py", line 235, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/user/foo/lib/python3.5/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/home/user/foo/lib/python3.5/site-packages/paramiko/rsakey.py", line 175, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/home/user/foo/lib/python3.5/site-packages/paramiko/pkey.py", line 308, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/home/user/foo/lib/python3.5/site-packages/paramiko/pkey.py", line 334, in _read_private_key
    data = self._read_private_key_pem(lines, end, password)
  File "/home/user/foo/lib/python3.5/site-packages/paramiko/pkey.py", line 386, in _read_private_key_pem
    raise PasswordRequiredException("Private key file is encrypted")
paramiko.ssh_exception.PasswordRequiredException: Private key file is encrypted

**Comment by ploxiln** [comment]
this is a case of https://github.com/paramiko/paramiko/issues/387

This particular case may be fixed in my fork, https://github.com/ploxiln/paramiko-ng/releases/tag/2.8.0
specifically by https://github.com/ploxiln/paramiko-ng/pull/57 and https://github.com/ploxiln/paramiko-ng/pull/59

**Comment by ipmonk** [comment]
@ploxiln thanks! I confirm, the issue isn't seen in paramiko-ng
