### ISSUE TITLE
Timeout defaults need to be float not int.

### ISSUE THREAD

**Issue by amosbaker** [paramiko/paramiko#1669]
banner_timeout, handshake_timeout, and auth_timeout are param noted as being float but none of them are. The method packet.start_handshake() does a cast which is also sensible since a user can pass something through but the defaults should at least be the correct type.

This is important because when they are passed through to socket.settimeout() that method actually verifies the type and complains.

https://github.com/paramiko/paramiko/blob/dccc563c3a581a14ceaa261b5fe0d08539f84b87/paramiko/transport.py#L484

**Comment by ploxiln** [comment]
I don't think `socket.settimeout()` really does complain about getting an int instead of a float though? (Which makes sense, since in python, an int can be used pretty much anywhere that takes a float).

```
$ python3
Python 3.7.3 (default, Jun  2 2020, 19:48:59) 
...
>>> import socket
>>> s = socket.socket()
>>> s.settimeout(15)
>>> # no complaints
```

```
$ python2
Python 2.7.16 (default, Apr 17 2020, 18:29:03) 
>>> import socket
>>> s = socket.socket()
>>> s.settimeout(15)
>>> # no complaints
```

**Comment by amosbaker** [comment]
Apologies, I don't remember all the context and my log files have since rolled but essentially when a remote server was misbehaving and exceeded the default banner_timeout with debug level logging we were getting:
`Exception=a float is required`

Which was not the actual cause of the issue admittedly but it did result in a false start. 

So while python did the necessary conversion the message was not suppressed and seeing as it's the default value I thought it was an easy win, especially since there is absolutely no risk.

**Comment by ploxiln** [comment]
I'm just trying to figure out where that comes from, maybe it's particular to a particular OS, or a particular variant of python, or a particular kind of socket ...

**Comment by amosbaker** [comment]
Sure, if any of this helps. 

> cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.10 (Santiago)
> python
Python 2.7.12 (default, Nov  8 2016, 13:17:08)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
> pip freeze | grep paramiko
paramiko==2.4.2

**Comment by MrMino** [comment]
Conversion of values in `settimeout()` is being done in C, but it's done by the python's time module, which accepts both ints and floating points.

See `[sock_settimeout()](https://github.com/python/cpython/blob/master/Modules/socketmodule.c#L2874)` -> `[socket_parse_timeout()](https://github.com/python/cpython/blob/master/Modules/socketmodule.c#L2823)` -> `[_PyTime_FromSecondsObject()](https://github.com/python/cpython/blob/master/Python/pytime.c#L435)` -> `[_PyTime_FromObject()](https://github.com/python/cpython/blob/master/Python/pytime.c#L401)`

The object this machinery creates is assigned to the socket itself, then used in `[internal_select()](https://github.com/python/cpython/blob/master/Modules/socketmodule.c#L710)` and there, [it is converted into miliseconds](https://github.com/python/cpython/blob/master/Modules/socketmodule.c#L746).

There's no OS-dependent implementation wagon in that train.

**Comment by MrMino** [comment]
Are you sure that what you've seen in the logs is actually from paramiko? I've grepped CPython and Paramiko code base for `Exception=` and got nothing. Or was that a loose paraphrase of the actual log?

**Comment by ploxiln** [comment]
OK, it's possible to get this exception text (well, not the "Exception=" part, that must be from the surrounding application) from Python-2.7 when you pass a string where a number is needed:

```
Python 2.7.16 (default, Apr 17 2020, 18:29:03) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import math, time, socket
>>> math.sin(1)
0.8414709848078965
>>> math.sin("1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a float is required

>>> time.sleep(1)
# works
>>> time.sleep("1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a float is required

>>> s = socket.socket()
>>> s.settimeout(1)
# works
>>> s.settimeout("1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: a float is required
```

Python-3 instead uses the text "TypeError: must be real number, not str" or "TypeError: an integer is required (got type str)" (even for cases where a float is expected, like `socket.settimeout()`).

**Comment by MrMino** [comment]
It would seem as if there was an uncast value from some user input. @amosbaker could that be the case in your application?

**Comment by amosbaker** [comment]
@MrMino - The only user input is a somewhat static configuration for a program that runs on a schedule to route files from one server to another via paramiko sftp. The user can only provide username, password or sshkey, host, and port. 

The `Exception=` was definitely from how we re-raised the exception for logging.

**Comment by MrMino** [comment]
@amosbaker reraising for logging is not a good idea, and IMO you should avoid it where possible. Unless expected, exceptions should scream at you as loudly as possible, otherwise you get situations like here: you know something _not correct_ happened, but you don't know when and where.

I don't know about @ploxiln or @bitprophet, but I'm afraid I won't help here, unless you can reproduce this again and provide the whole traceback.

**Comment by amosbaker** [comment]
@MrMino - This issue was opened in April, I don't have the evidence I had then so my mistake for leaving some of it out. I'm not actually asking for assistance in troubleshooting the issue, I know what happened and it was related to an sftp server behaving very badly. Reproducing should be as direct as ensuring your sftp server connects and then just not returning the banner for more than 15 seconds.

My only request was to change the type of the defaults to actually be the type that is indicated and expected. 

Finally we aren't re-raising anything, it was poor word choice because in reality we are logging the exception. If we have 36 files to transfer and 1 fails we don't automatically give up on the other 35 we log the exception and carry on if at all possible.

**Comment by MrMino** [comment]
Oh, right, sorry, didn't notice the OP date. Sorry for misreading your intentions.

**Comment by MrMino** [comment]
Oh, right, sorry, didn't notice the OP date. Sorry for misreading your intentions.

Still, the proposition that `int` ⊄ `float` is not supported anywhere. Even [PEP 484](https://www.python.org/dev/peps/pep-0484/#the-numeric-tower) specifically states that:

>  when an argument is annotated as having type float, an argument of type int is acceptable

Given the above I don't think there's a reason to change the default.
