### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by jumping** [paramiko/paramiko#17]
``` python
Exception in thread Thread-12 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/threading.py", line 486, in __bootstrap_inner
  File "build/bdist.freebsd-8.2-RELEASE-i386/egg/paramiko/transport.py", line 1574, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
Exception in thread Thread-13 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/threading.py", line 486, in __bootstrap_inner
  File "build/bdist.freebsd-8.2-RELEASE-i386/egg/paramiko/transport.py", line 1574, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
Exception in thread Thread-9 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/threading.py", line 486, in __bootstrap_inner
  File "build/bdist.freebsd-8.2-RELEASE-i386/egg/paramiko/transport.py", line 1574, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
Exception in thread Thread-8 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/threading.py", line 486, in __bootstrap_inner
  File "build/bdist.freebsd-8.2-RELEASE-i386/egg/paramiko/transport.py", line 1574, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/threading.py", line 486, in __bootstrap_inner
  File "build/bdist.freebsd-8.2-RELEASE-i386/egg/paramiko/transport.py", line 1574, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
```

**Comment by khenderick** [comment]
Using paramiko ```1.15.2```, I'm still having this issue:

```
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1642, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
```

**Comment by mksharma** [comment]
I installed latest Paramiko and using python 2.7
Got this error:
Captured stdout:
      	Exception in thread Thread-1 (most likely raised during interpreter shutdown):
      	Traceback (most recent call last):
      	File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
      	File "/opt/move/epg-tools/local/lib/python2.7/site-packages/paramiko/transport.py", line 1613, in run
      	<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'

**Comment by curtmcd** [comment]
I'm still suffering from this problem under Python 2.7.6, Fabric 1.8.2, Paramiko 1.10.1, and have developed the following workaround that seems to be working so far.

My program allocates an object in a main() function from a class that uses Fabric calls. I have Fabric close all ssh connections in this object's destructor because the object goes out of scope when main() returns.

    import fabric.network
    import fabric.state

    class MyObject(...):
        ... methods that use fabric ...
        def __del__(self):
            fabric.state.output.status = False
            fabric.network.disconnect_all()

**Comment by styk-tv** [comment]
Happens to me on Mac (10.11.5) dev when using execute @parallel tasks on multiple hosts. Task execute successfully but this exception happens on exit and is followed with Process finished with exit code 0 message which is somewhat confusing.

Fabric (1.11.1)
paramiko (1.15.2)
`
Exception in thread Thread-9 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/site-packages/paramiko/transport.py", line 1642, in run
`

**Comment by mpetronic** [comment]
I'm running Python 2.7.14 and paramiko==2.4.1 and Fabric==1.14.0 and using fabric in an integration test to manage setting up external resources for the test. If I add the following, it seems to eliminate the exception. I can run the testing repeatedly without the tearDownClass() method, and I get the exception probably about 50% of the time, on exiting the test successfully. It is mainly annoying to see this exception print out as the last output from a successful test. :) With the tearDownClass below, I don't see the exception occurring:

    @classmethod
    def tearDownClass(cls):
        # This is part of trying to suppress a paramiko shutdown bug
        # https://github.com/paramiko/paramiko/issues/17
        logger.info('tearDownClass')
        fabric.state.output.status = False
        fabric.network.disconnect_all()

Kudos to @curtmcd for the suggestion of the two calls to fabric to disconnect_all()

**Comment by bskinn** [comment]
Hi! I'm helping bitprophet by going through the issues and PRs backlog, and for anything more than a few years old, we're just closing them out for now.

If this is still a live bug, please reopen the issue, and comment to let us know it's still of interest.

Thanks!
