### ISSUE TITLE
unable to connect to password+key enabled SFTP server using pysftp

### ISSUE THREAD

**Issue by arthuersundar** [paramiko/paramiko#1711]
I'm trying to connect to a SFTP server which is (password + private key)enabled, it is not working. I keep getting the below exception. I'm able to connect to the SFTP using the terminal, filezilla and winscp. 

It is failing only with pysftp. 

paramiko.ssh_exception.BadAuthenticationType: Bad authentication type; allowed types: ['publickey']
al003110321:pysftp $ /usr/local/opt/python/bin/python3.7 /Users//pysftp/test.py
Traceback (most recent call last):
  File "/Users/s1881582/pysftp/test.py", line 2, in <module>
    sftp = pysftp.Connection(‘HOST’, username=‘USERNAME’, password=‘PASSWORD’, private_key = ‘PATHTOKEY’, private_key_pass = ‘KEYPASS’)
  File "/usr/local/lib/python3.7/site-packages/pysftp/__init__.py", line 143, in __init__
    self._transport.connect(**self._tconnect)
  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 1336, in connect
    self.auth_password(username, password)
  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 1509, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/local/lib/python3.7/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.BadAuthenticationType: Bad authentication type; allowed types: ['publickey']
al003110321:pysftp $

**Comment by addisonklinke** [comment]
I experience the exact same issue which seems to be an unhandled case in paramiko's authentication options. The issue is in the `transport.connect()` function from [transport.py:1331](https://github.com/paramiko/paramiko/blob/master/paramiko/transport.py#L1331)

```
# Prior code...

elif pkey is not None:
    self._log(DEBUG, "Attempting public-key auth...")
    self.auth_publickey(username, pkey)
else:
    self._log(DEBUG, "Attempting password auth...")
    self.auth_password(username, password)
```

As seen in the excerpt, `password` is not used when `pkey` is provided (and vice versa). In order to provide both for authentication, we would need to implement a new method `self.auth_publickey_password()` and direct the connection accordingly. Unfortunately, without understanding the inner workings of this library, I cannot suggest how best to accomplish this

**Comment by arthuersundar** [comment]
Hi, yes we are looking for both (password + pkey) to authenticate.

**Comment by addisonklinke** [comment]
@arthuersundar I'm not affiliated with this repository, so I was merely commenting to provide additional evidence in support of your request. Perhaps @bitprophet can address this for us?

**Comment by ploxiln** [comment]
You can create the transport and then call the authentication methods manually. In fact, usually one will use the `SSHClient` class which has its own (more elaborate and featureful) logic for calling authentication methods:
https://github.com/paramiko/paramiko/blob/2.7.1/paramiko/client.py#L614-L760

It is up to pysftp to use `SSHClient` or call `Transport` methods differently. Looks like it just uses the transport connect auth args, the handling for which you pointed out:
https://bitbucket.org/dundeemt/pysftp/src/1c0791759688a733a558b1a25d9ae04f52cf6a64/pysftp/__init__.py#lines-114:143

**Comment by s1011448** [comment]
Hi, is there any solution for using password + pkey to authenticate?
