### ISSUE TITLE
ProxyCommand leaves open pipes

### ISSUE THREAD

**Issue by aayla-secura** [paramiko/paramiko#1715]
`ProxyCommand.close` does not close `stdin`, `stdout` and `stderr` which leaves 3 open pipes after each connection. Eventually this results in `OSError: Too many files open`. I suggest the following fix (taking into account the suggested fix for issue #1713):

```
diff -U0 -r a/proxy.py b/proxy.py
--- a/proxy.py	2020-07-08 09:13:04.000000000 +1200
+++ b/proxy.py	2020-07-08 09:58:24.000000000 +1200
@@ -122 +122,5 @@
-        os.kill(self.process.pid, signal.SIGTERM)
+        self.process.stdin.close()
+        self.process.stdout.close()
+        self.process.stderr.close()
+        self.process.terminate()
+        self.process.wait()
```

NOTE: With this fix there is now an exception thrown due to a race condition between `Transport.run` and `Transport.stop_thread`:

```
Exception: ProxyCommand("ssh -W 1.2.3.4:22 proxy") returned nonzero exit status: Bad file descriptor
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paramiko/proxy.py", line 107, in recv
    r, w, x = select([self.process.stdout], [], [], select_timeout)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 2055, in run
    ptype, m = self.packetizer.read_message()
  File "/usr/local/lib/python3.7/site-packages/paramiko/packet.py", line 459, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/usr/local/lib/python3.7/site-packages/paramiko/packet.py", line 301, in read_all
    x = self.__socket.recv(n)
  File "/usr/local/lib/python3.7/site-packages/paramiko/proxy.py", line 119, in recv
    raise ProxyCommandFailure(" ".join(self.cmd), e.strerror)
paramiko.ssh_exception.ProxyCommandFailure: ProxyCommand("ssh -W 1.2.3.4:22 proxy") returned nonzero exit status: Bad file descriptor
```

This is because the descriptors will be closed while the other thread is still in the main loop in `Transport.stop_thread`, before the next time it checks `self.active`. Perhaps you could just add another `except` block for `OSError`?

===
Here's a test for it with a quick and dirty fix for the exception thrown due to the race condition described above:

```
import logging
from time import sleep
import sys
import os
import resource
import stat
import socket

from paramiko import SSHClient, ProxyCommand
from paramiko.client import MissingHostKeyPolicy


logger = logging.getLogger('paramiko test')
handler = logging.StreamHandler(sys.stdout)
handler.setFormatter(logging.Formatter(
    fmt=('[%(asctime)s] %(name)s '
         '(%(threadName)s): %(message)s'),
    datefmt='%d/%b/%Y %H:%M:%S'))
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)


SSH_HOST = '1.2.3.4'               # CHANGE THIS
SSH_USER = 'user'                  # CHANGE THIS
PROXY = 'ssh -W 1.2.3.4:22 proxy'  # CHANGE THIS


class ProxyCommandPatched(ProxyCommand):
    def close(self):
        # needs a better fix: there is a race condition between
        # stop_thread and run.
        sleep(0.5)
        self.process.stdin.close()
        self.process.stdout.close()
        self.process.stderr.close()
        # terminate is same as
        # os.kill(self.process.pid, signal.SIGTERM)
        self.process.terminate()
        # this is to prevent zombie processes, see issue 1713
        self.process.wait()

class IgnoreMissingHostKeyPolicy(MissingHostKeyPolicy):
    def missing_host_key(self, client, hostname, key):
        pass


def _num_open_fds(suff):
    n = 0
    for fd in range(resource.getrlimit(resource.RLIMIT_NOFILE)[0]):
        try:
            st = os.fstat(fd)
        except OSError:
            continue
        n += 1
        logger.debug('FD {}: {}'.format(fd, stat.filemode(st.st_mode)))
    logger.info('{}: {} open FDs'.format(suff, n))
    return n

def connect(cls):
    logger.info('--------------------Connecting using {}'.format(
        cls.__name__))
    _num_open_fds('before proxy connect')
    proxy = cls(PROXY)
    conn = SSHClient()
    conn.set_missing_host_key_policy(IgnoreMissingHostKeyPolicy)
    conn.connect(SSH_HOST, username=SSH_USER, sock=proxy)
    conn.close()
    sleep(0.5)
    _num_open_fds('after disconnect')


connect(ProxyCommandPatched)
connect(ProxyCommand)
```

It prints the following:

```
[08/Jul/2020 10:00:32] paramiko test (MainThread): --------------------Connecting using ProxyCommandPatched
[08/Jul/2020 10:00:32] paramiko test (MainThread): FD 0: -rw-------
[08/Jul/2020 10:00:32] paramiko test (MainThread): FD 1: prw-rw----
[08/Jul/2020 10:00:32] paramiko test (MainThread): FD 2: crw--w----
[08/Jul/2020 10:00:32] paramiko test (MainThread): FD 3: crw-rw-rw-
[08/Jul/2020 10:00:32] paramiko test (MainThread): before proxy connect: 4 open FDs
[08/Jul/2020 10:00:34] paramiko test (MainThread): FD 0: -rw-------
[08/Jul/2020 10:00:34] paramiko test (MainThread): FD 1: prw-rw----
[08/Jul/2020 10:00:34] paramiko test (MainThread): FD 2: crw--w----
[08/Jul/2020 10:00:34] paramiko test (MainThread): FD 3: crw-rw-rw-
[08/Jul/2020 10:00:34] paramiko test (MainThread): after disconnect: 4 open FDs
[08/Jul/2020 10:00:34] paramiko test (MainThread): --------------------Connecting using ProxyCommand
[08/Jul/2020 10:00:34] paramiko test (MainThread): FD 0: -rw-------
[08/Jul/2020 10:00:34] paramiko test (MainThread): FD 1: prw-rw----
[08/Jul/2020 10:00:34] paramiko test (MainThread): FD 2: crw--w----
[08/Jul/2020 10:00:34] paramiko test (MainThread): FD 3: crw-rw-rw-
[08/Jul/2020 10:00:34] paramiko test (MainThread): before proxy connect: 4 open FDs
[08/Jul/2020 10:00:35] paramiko test (MainThread): FD 0: -rw-------
[08/Jul/2020 10:00:35] paramiko test (MainThread): FD 1: prw-rw----
[08/Jul/2020 10:00:35] paramiko test (MainThread): FD 2: crw--w----
[08/Jul/2020 10:00:35] paramiko test (MainThread): FD 3: crw-rw-rw-
[08/Jul/2020 10:00:35] paramiko test (MainThread): FD 5: prw-rw----
[08/Jul/2020 10:00:35] paramiko test (MainThread): FD 6: prw-rw----
[08/Jul/2020 10:00:35] paramiko test (MainThread): FD 8: prw-rw----
[08/Jul/2020 10:00:35] paramiko test (MainThread): after disconnect: 7 open FDs
```

**Comment by MrMino** [comment]
Quick question: shouldn't `os.kill(pid, signal.SIGTERM)` actually close the file descriptors used by the process, such that it is visible to the interpreter? It's kind of weird, that after telling the OS to terminate the process you have to manually ensure that everything is closed.

**Comment by ploxiln** [comment]
In C, you do have to explicitly close all file descriptors. But in python, usually they are closed automatically when the file-like-objects are garbage-collected. That might not happen right away, depending how references to them are retained ... so it's considered good practice to explicitly close everything. (I might suggest doing the closes  after the `process.wait()` though.)

**Comment by MrMino** [comment]
I second the proposition for closing the FDs after `process.wait()`. Doing otherwise might lead to weird races where closing stdin makes the process execute an unnecessary side effect before it is actually terminated.

**Comment by MrMino** [comment]
On the other hand, shouldn't we also consider the cases where `SIGTERM` is ignored by the process in question?
