### ISSUE TITLE
some problems with keyboard-interactive 

### ISSUE THREAD

**Issue by meteordragon** [paramiko/paramiko#1719]
my code
`def ihandler(title ,instructions ,hashlist):`
	`if hashlist:`
		`if hashlist!='':`
			`password=input()`
			`return [password]`
		`if hashlist == '':`
			`return []`
`trans.auth_interactive (username,ihandler)`
error code
`Unknown exception: object of type 'NoneType' has no len()`
`Exception in thread Thread-1:`
`Traceback (most recent call last):`
 ` File "D:\app\Python\Python38-32\lib\site-packages\paramiko\transport.py", line 2109, in run`
   ` handler(self.auth_handler, m)`
 ` File "D:\app\Python\Python38-32\lib\site-packages\paramiko\auth_handler.py", line 678, in _parse_userauth_info_request`
`TypeError: object of type 'NoneType' has no len()`

the error line:
`        m.add_int(len(response_list))`
so i add this in front of it 

`        if response_list==None:`
 `               response_list=''`
auth successed

**Comment by ploxiln** [comment]
see https://github.com/paramiko/paramiko/pull/1706
