### ISSUE TITLE
invalid private key (RSA)

### ISSUE THREAD

**Issue by jerome-diver** [paramiko/paramiko#1742]
Hi, from vorta, who is a borg GUI backup application, i get this python-paramiko error:

2020-08-30 23:41:58,411 - vorta.i18n - DEBUG - Loading translation failed for ['fr', 'fr-FR', 'fr-Latn-FR'].
2020-08-30 23:41:58,418 - apscheduler.scheduler - INFO - Scheduler started
2020-08-30 23:41:58,419 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2020-08-30 23:41:58,419 - vorta.scheduler - DEBUG - New job for profile jerome-laptop-gigabyte was added.
2020-08-30 23:41:58,430 - qdarkstyle - DEBUG - Reading QSS file in: :qdarkstyle/style.qss
2020-08-30 23:41:58,430 - qdarkstyle - INFO - QSS file sucessfuly loaded.
2020-08-30 23:41:58,430 - qdarkstyle - DEBUG - Checking patches for being applied.
2020-08-30 23:41:58,431 - qdarkstyle - INFO - Found application patches to be applied.
Traceback (most recent call last):
  File "/usr/bin/vorta", line 33, in <module>
    sys.exit(load_entry_point('vorta==0.6.26', 'gui_scripts', 'vorta')())
  File "/usr/lib/python3.8/site-packages/vorta/__main__.py", line 37, in main
    app = VortaApp(sys.argv, single_app=True)
  File "/usr/lib/python3.8/site-packages/vorta/application.py", line 60, in __init__
    self.open_main_window_action()
  File "/usr/lib/python3.8/site-packages/vorta/application.py", line 81, in open_main_window_action
    self.main_window = MainWindow(self)
  File "/usr/lib/python3.8/site-packages/vorta/views/main_window.py", line 49, in __init__
    self.repoTab = RepoTab(self.repoTabSlot)
  File "/usr/lib/python3.8/site-packages/vorta/views/repo_tab.py", line 55, in __init__
    self.init_ssh()
  File "/usr/lib/python3.8/site-packages/vorta/views/repo_tab.py", line 88, in init_ssh
    keys = get_private_keys()
  File "/usr/lib/python3.8/site-packages/vorta/utils.py", line 77, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/usr/lib/python3.8/site-packages/paramiko/pkey.py", line 235, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/usr/lib/python3.8/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/lib/python3.8/site-packages/paramiko/rsakey.py", line 176, in _from_private_key_file
    self._decode_key(data)
  File "/usr/lib/python3.8/site-packages/paramiko/rsakey.py", line 194, in _decode_key
    key = rsa.RSAPrivateNumbers(
  File "/usr/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 311, in private_key
    return backend.load_rsa_private_numbers(self)
  File "/usr/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 630, in load_rsa_private_numbers
    return _RSAPrivateKey(self, rsa_cdata, evp_pkey)
  File "/usr/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 320, in __init__
    raise ValueError("Invalid private key", errors)
ValueError: ('Invalid private key', [_OpenSSLErrorWithText(code=67764350, lib=4, func=160, reason=126, reason_text=b'error:040A007E:rsa routines:RSA_check_key_ex:iqmp not inverse of q')])
[1]    104965 segmentation fault (core dumped)  vorta

I'm on Archlinux and python-paramiko installed from community repo is version 2.7.1-2

**Comment by nathanielmanistaatgoogle** [comment]
@jerome-diver: I believe [you'll want to upgrade to paramiko 2.7.2](https://github.com/paramiko/paramiko/pull/1723).

**Comment by jerome-diver** [comment]
@nathanielmanistaatgoogle yes, that's it, thank you

**Comment by MrMino** [comment]
@jerome-diver anything stopping you from closing this?

**Comment by jerome-diver** [comment]
@MrMino no, i didn't see i can close it, sorry.
