### ISSUE TITLE
ConnectionResetError when sending cSSH2_AGENTC_REQUEST_IDENTITIES

### ISSUE THREAD

**Issue by lsiden** [paramiko/paramiko#1745]
Traceback (most recent call last):
        File "./scripts/kpi_collector.py", line 80, in <module>
          main()
        File "./scripts/kpi_collector.py", line 74, in main
          equipment_connect.download_kpi_files(equip, days_back=ARGS.days_back)
        File "/var/www/api/kaos-api/lib/equipment/connect.py", line 41, in download_kpi_files
          with self.ssh_connection(equip_host) as ssh:
        File "/var/www/api/kaos-api/lib/equipment/connect.py", line 102, in ssh_connection
          ssh.connect(host, username=self._kpi_username, auth_timeout=self._auth_timeout)
        File "/var/www/api/kaos-api/venv/lib/python3.8/site-packages/paramiko/client.py", line 435, in connect
          self._auth(
        File "/var/www/api/kaos-api/venv/lib/python3.8/site-packages/paramiko/client.py", line 691, in _auth
          self._agent = Agent()
        File "/var/www/api/kaos-api/venv/lib/python3.8/site-packages/paramiko/agent.py", line 379, in __init__
          self._connect(conn)
        File "/var/www/api/kaos-api/venv/lib/python3.8/site-packages/paramiko/agent.py", line 65, in _connect
          ptype, result = self._send_message(cSSH2_AGENTC_REQUEST_IDENTITIES)
        File "/var/www/api/kaos-api/venv/lib/python3.8/site-packages/paramiko/agent.py", line 83, in _send_message
          data = self._read_all(4)
        File "/var/www/api/kaos-api/venv/lib/python3.8/site-packages/paramiko/agent.py", line 88, in _read_all
          result = self._conn.recv(wanted)
      ConnectionResetError: [Errno 104] Connection reset by peer

This worked yesterday.

From a bash shell I can type "ssh user@server ls" and it succeeds.  ('user' and 'server' are not the real names and user already has an ssh key on the server).

I opened a shell session on the remote server, but could not find anything like /var/logs/ssh, or even /var/logs/system. Anyway, it's pretty locked down, so I'm out of options.

Is there anything else I can check for?

**Comment by lsiden** [comment]
I just fixed my problem. After checking the code in agent.py, I looked at the value of SSH_AUTH_SOCK in my shell environment. I found a file under /tmp.  I deleted it.  Now all is good.  

Is it possible that something didn't get cleaned up?  Is there anything I can do to make sure it gets cleaned up safely in the future?

I could have the script check for the file $SSH_AUTH_SOCK and unlink it if it's found each time before I connect, but this seems a bit ham-handed and shouldn't be necessary, should it?

Can you advise?

**Comment by MrMino** [comment]
The "`Connection`" in the exception message you got here is in reference to connection to SSH agent. It communicates with clients via sockets. You probably killed `ssh-agent` process without starting a new one.
