### ISSUE TITLE
Unbound method set_missing_host_key_policy() must be called with SSHClient instance as first argument 

### ISSUE THREAD

**Issue by virendra-09** [paramiko/paramiko#1746]
I am getting error while executing the below script

import sys
import time
import paramiko
import os
import cmd
import datetime

###set date and time
now = datetime.datetime.now()

###authentication
USER = 'cisco'
PASSWORD = 'cisco'
secret = 'cisco'

###start FOR ...in
f = open('cisco_routerswitch.txt')
for ip in f.readlines():
ip = ip.strip()
###prefix files for backup
filename_prefix ='switches_backup' + ip

    ###session start
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(ip, port, username=USER, password=PASSWORD,look_for_keys=False)

    ###ssh shell
    chan = client.invoke_shell()
    time.sleep(2)
    ###enter enable secret
    chan.send('en\n')
    chan.send(secret +'\n')
    time.sleep(1)
    ###terminal lenght for no paging
    chan.send('term len 0\n')
    time.sleep(1)
    ###show config and write output
    chan.send('sh run\n')
    time.sleep(30)
    output = chan.recv(999999)
    ###show output config and write file with prefix, date and time
    print (output)
    ###filename in format (filename_prefix,now.day,now.month,now.year,now.hour,now.minute,now.second)
    filename = "%s_%.2i%.2i%i_%.2i%.2i%.2i" % (filename_prefix,now.year,now.month,now.day,now.hour,now.minute,now.second)
    ff = open(filename, 'a')
    ###ff.write(output)
    ff.write(output.decode("utf-8") )
    ff.close()
    ###close ssh session
    client.close()

    print (ip)
    f.close()

error :

]$ python backup_cisco_routerswitch.py
Traceback (most recent call last):
File "backup_cisco_routerswitch.py", line 28, in
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
TypeError: unbound method set_missing_host_key_policy() must be called with SSHClient instance as first argument (got AutoAddPolicy instance instead)

**Comment by virendra-09** [comment]
Some more editing and able to fix first issue but now ran into a new one 

Able to access switch 

sw7#exit
Connection closed.

but still get Auth error :

$ python backup_cisco_routerswitch.py
Traceback (most recent call last):
  File "backup_cisco_routerswitch.py", line 30, in <module>
    ssh.connect(ip, port, username=USER, password=PASSWORD)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 380, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 621, in _auth
    raise saved_exception
paramiko.ssh_exception.AuthenticationException: Authentication failed.
