### ISSUE TITLE
OSError: Failure - please help to increase the timeout

### ISSUE THREAD

**Issue by stvnkem** [paramiko/paramiko#1747]
Hello,

I am getting this exception when downloading files from several servers (network switches) at the same time.
How can I increase the timeout?

```
CRITICAL :: 2020-09-13 01:06:21,671 :: 46 :: Thread-4800 ::  def_log_exceptions :: Unhandled exception: Traceback (most recent call last):
  File "coll_diag_3.py", line 71, in run
    run_old(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "coll_diag_3.py", line 228, in ssh_session
    def_get_coll_diag_file(hostname, timestamp_str)
  File "coll_diag_3.py", line 125, in def_get_coll_diag_file
    sftp.get(remoteFilePath, localFilePath)
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/pysftp/__init__.py", line 249, in get
    self._sftp.get(remotepath, localpath, callback=callback)
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/paramiko/sftp_client.py", line 802, in get
    size = self.getfo(remotepath, fl, callback)
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/paramiko/sftp_client.py", line 782, in getfo
    reader=fr, writer=fl, file_size=file_size, callback=callback
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/paramiko/sftp_client.py", line 678, in _transfer_with_callback
    data = reader.read(32768)
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/paramiko/file.py", line 219, in read
    new_data = self._read(read_size)
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/paramiko/sftp_file.py", line 186, in _read
    CMD_READ, self.handle, long(self._realpos), int(size)
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/paramiko/sftp_client.py", line 865, in _read_response
    self._convert_status(msg)
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/paramiko/sftp_client.py", line 898, in _convert_status
    raise IOError(text)
OSError: Failure
```

**Comment by MrMino** [comment]
Some more information would be nice: what kind of switches, some code to reproduce, etc.

What makes you think that SFTP will work on these servers? Not every SSH implementation supports SFTP subsystem.

**Comment by stvnkem** [comment]
> Some more information would be nice: what kind of switches, some code to reproduce, etc.
> 
> What makes you think that SFTP will work on these servers? Not every SSH implementation supports SFTP subsystem.

It does, but the download speed is ISDN-like... 5-8k/sec.

**Comment by MrMino** [comment]
@stvnkem the error you are getting here is not because of a timeout.

Please give us a minimal example of the code you are using along with some information about these switches: preferably variant / version of the SSH server, vendor / model might also help.
