### ISSUE TITLE
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner 

### ISSUE THREAD

**Issue by Suchismita1tutun** [paramiko/paramiko#1752]
I am using paramiko to ssh into a private ec2 machine via a bastion host. The bastion host is a managed instance by AWS system manager.
While creating ssh session using paramiko with ProxyCommand "aws ssm start-session --target <<bastion-host>> --document AWS-StartSSHSession --parameters portNumber=22", I am getting this debug log as below.
```
2020-09-22 15:31:31,082 | paramiko.transport           | DEBUG | starting thread (client mode): 0x1f692748
2020-09-22 15:31:31,083 | paramiko.transport           | DEBUG | Local version/idstring: SSH-2.0-paramiko_2.7.2
2020-09-22 15:31:41,154 | paramiko.transport           | DEBUG | Banner:
**2020-09-22 15:31:41,155 | paramiko.transport           | DEBUG | Banner: Starting session with SessionId: <<session-id>>**
2020-09-22 15:31:43,171 | paramiko.transport           | ERROR | Exception: Error reading SSH protocol banner
2020-09-22 15:31:43,188 | paramiko.transport           | ERROR | Traceback (most recent call last):
2020-09-22 15:31:43,189 | paramiko.transport           | ERROR |   File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2211, in _check_banner
2020-09-22 15:31:43,190 | paramiko.transport           | ERROR |     buf = self.packetizer.readline(timeout)
2020-09-22 15:31:43,190 | paramiko.transport           | ERROR |   File "/usr/local/lib/python3.6/dist-packages/paramiko/packet.py", line 380, in readline
2020-09-22 15:31:43,193 | paramiko.transport           | ERROR |     buf += self._read_timeout(timeout)
2020-09-22 15:31:43,194 | paramiko.transport           | ERROR |   File "/usr/local/lib/python3.6/dist-packages/paramiko/packet.py", line 622, in _read_timeout
2020-09-22 15:31:43,194 | paramiko.transport           | ERROR |     raise socket.timeout()
2020-09-22 15:31:43,195 | paramiko.transport           | ERROR | socket.timeout
2020-09-22 15:31:43,196 | paramiko.transport           | ERROR |
2020-09-22 15:31:43,196 | paramiko.transport           | ERROR | During handling of the above exception, another exception occurred:
2020-09-22 15:31:43,197 | paramiko.transport           | ERROR |
2020-09-22 15:31:43,198 | paramiko.transport           | ERROR | Traceback (most recent call last):
2020-09-22 15:31:43,198 | paramiko.transport           | ERROR |   File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2039, in run
2020-09-22 15:31:43,200 | paramiko.transport           | ERROR |     self._check_banner()
2020-09-22 15:31:43,200 | paramiko.transport           | ERROR |   File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2216, in _check_banner
2020-09-22 15:31:43,201 | paramiko.transport           | ERROR |     "Error reading SSH protocol banner" + str(e)
2020-09-22 15:31:43,202 | paramiko.transport           | ERROR | paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2020-09-22 15:31:43,202 | paramiko.transport           | ERROR |
```

The bold line shows that the proxy command ran successfully. However, the _check_banner method of the paramiko client failed to validate.

Could you please assist me in this regard ?

**Comment by spencerbug** [comment]
I am also having this issue, seems similar to https://github.com/paramiko/paramiko/issues/673 which was resolved in 2016... 

I get that error when doing an SSH proxycommand (with fake credentials)
```
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(hostname='192.168.128.20',username='username',password='password',sock=paramiko.ProxyCommand("sshpass -ppassword ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -n -W %h:%p root@192.168.0.55"))
```
Error I get:
```
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/Users/sneilan/.local/share/virtualenvs/fy21-automation-aZ4mtq-f/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/Users/sneilan/.local/share/virtualenvs/fy21-automation-aZ4mtq-f/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/Users/sneilan/.local/share/virtualenvs/fy21-automation-aZ4mtq-f/lib/python3.8/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneilan/.local/share/virtualenvs/fy21-automation-aZ4mtq-f/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/Users/sneilan/.local/share/virtualenvs/fy21-automation-aZ4mtq-f/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Traceback (most recent call last):
  File "/Users/sneilan/.local/share/virtualenvs/fy21-automation-aZ4mtq-f/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/Users/sneilan/.local/share/virtualenvs/fy21-automation-aZ4mtq-f/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/Users/sneilan/.local/share/virtualenvs/fy21-automation-aZ4mtq-f/lib/python3.8/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sneilan/.local/share/virtualenvs/fy21-automation-aZ4mtq-f/lib/python3.8/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/Users/sneilan/.local/share/virtualenvs/fy21-automation-aZ4mtq-f/lib/python3.8/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/Users/sneilan/.local/share/virtualenvs/fy21-automation-aZ4mtq-f/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/Users/sneilan/.local/share/virtualenvs/fy21-automation-aZ4mtq-f/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

**Comment by GaetanLepage** [comment]
I have the exact same error while trying to ssh through a bastion.
I tried to increase the `banner_timeout` but it doesn't work...

**Comment by SuchismitaGoswami** [comment]
@GaetanLepage I tried with increasing timeout, but no luck :-(

**Comment by vanhul** [comment]
someone solved the problem?

**Comment by Sita1005** [comment]
Even i too faced the same issue, when i specify ip address proxy host. So i have specified as FQDN name of the proxy host.

**Comment by jluxiaotao** [comment]
Same issue with you.
seems like when it try starting a thread this ERROR occurs.

**Comment by jluxiaotao** [comment]
Same issue with you.
seems like when it try starting a thread this ERROR occurs.
https://github.com/AmadeusITGroup/JumpSSH/issues/214

**Comment by hhoke** [comment]
FWIW this popped up every time I used a virtualenv (through both pip and poetry), but when I just did a default pip install it connected like a charm

**Comment by skozlovf** [comment]
I have then same case as @SuchismitaGoswami when my connection is slow.
Found what the reason is because after initial wait for `banner_timeout` it uses `2` sec timeout to pull remaining banner lines.
I connect successfully if increase this hardcoded value.

Maybe add separate timeout var or use `banner_timeout` there?

See: [paramiko/transport.py:2209](https://github.com/paramiko/paramiko/blob/a598ca14d6451343c69be97e0e1c65eb15c0e607/paramiko/transport.py#L2209).

**Comment by stef1205** [comment]
Had the same issue and found that increasing range from 100 to 200 in _check_banner fixed the problem

**Comment by gabriels1234** [comment]
> Had the same issue and found that increasing range from 100 to 200 in _check_banner fixed the problem

Not when the failure is immediate. adding timeouts won't help.

**Comment by clg-shyam** [comment]
check your ports :key:

**Comment by batchenr** [comment]
> FWIW this popped up every time I used a virtualenv (through both pipenv and poetry), but when I just did a default pip install it connected like a charm

Having the same issue using venv and paramiko 3.3.1
Is anyone found a solution?

**Comment by Bryan-Graterol** [comment]
Tengo este mismo problema me lanza este error(error reading ssh protocol banner) no se si el problema es de Paramiko o del dispositivo, ya que entra a varios dispositivos pero con alguno me lanza ese error y es como si fuera al azar

**Comment by batchenr** [comment]
> > FWIW this popped up every time I used a virtualenv (through both pipenv and poetry), but when I just did a default pip install it connected like a charm
> 
> Having the same issue using venv and paramiko 3.3.1 Is anyone found a solution?

Well for some reason downgraded to paramiko 3.2.0 has solved the issue for me

**Comment by sjvigo** [comment]
I'm having the same issue using venv and paramiko 3.4.0 `paramiko.ssh_exception.SSHException: Error reading SSH protocol banner` . I've hardcoded the banner_timeout but the error persists. Any solution?

**Comment by GuydoEinar** [comment]
I solved this issue like this:

```
ip = "192.168.1.1"
port = 22
sock.setsockopt(socket.SOL_SOCKET, 25, str("eth0").encode('utf-8'))
sock.connect((ip, port))
tp = Transport((ip,port))
tp.connect(None, username, password)

ssh = SSHClient()
ssh._transport = tp
```

And now you can use the client as you want.

**Comment by NeffIsBack** [comment]
We also encountered the error in https://github.com/Pennyw0rth/NetExec/issues/312. My guess would be that this is some kind of race condition inside of paramiko. Imo handling the non existent banner properly and return some kind of empty string or else would be the best solution.

**Comment by Mrbibi38** [comment]
Hello, 

I currently have the same problem on paramiko v3.5.0. **If anyone have a fix for this, this will be awesome!**

The following error occurs when a new client tries to connect:

```
2024-11-24 09:29:11,258 - paramiko.transport - DEBUG - starting thread (server mode): 0xbfbd5d0
2024-11-24 09:29:11,259 - paramiko.transport - DEBUG - Local version/idstring: SSH-2.0-paramiko_3.5.0
2024-11-24 09:29:26,288 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2024-11-24 09:29:26,289 - paramiko.transport - ERROR - Traceback (most recent call last):
2024-11-24 09:29:26,290 - paramiko.transport - ERROR -   File "/root/ssh-proxy/.venv/lib/python3.11/site-packages/paramiko/transport.py", line 2369, in _check_banner
2024-11-24 09:29:26,290 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2024-11-24 09:29:26,290 - paramiko.transport - ERROR -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-24 09:29:26,290 - paramiko.transport - ERROR -   File "/root/ssh-proxy/.venv/lib/python3.11/site-packages/paramiko/packet.py", line 395, in readline
2024-11-24 09:29:26,290 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2024-11-24 09:29:26,290 - paramiko.transport - ERROR -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-24 09:29:26,290 - paramiko.transport - ERROR -   File "/root/ssh-proxy/.venv/lib/python3.11/site-packages/paramiko/packet.py", line 673, in _read_timeout
2024-11-24 09:29:26,290 - paramiko.transport - ERROR -     raise socket.timeout()
2024-11-24 09:29:26,290 - paramiko.transport - ERROR - TimeoutError
2024-11-24 09:29:26,290 - paramiko.transport - ERROR -
2024-11-24 09:29:26,291 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2024-11-24 09:29:26,291 - paramiko.transport - ERROR -
2024-11-24 09:29:26,291 - paramiko.transport - ERROR - Traceback (most recent call last):
2024-11-24 09:29:26,291 - paramiko.transport - ERROR -   File "/root/ssh-proxy/.venv/lib/python3.11/site-packages/paramiko/transport.py", line 2185, in run
2024-11-24 09:29:26,291 - paramiko.transport - ERROR -     self._check_banner()
2024-11-24 09:29:26,291 - paramiko.transport - ERROR -   File "/root/ssh-proxy/.venv/lib/python3.11/site-packages/paramiko/transport.py", line 2373, in _check_banner
2024-11-24 09:29:26,291 - paramiko.transport - ERROR -     raise SSHException(
2024-11-24 09:29:26,291 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2024-11-24 09:29:26,291 - paramiko.transport - ERROR -
```

**Comment by AdmirallBelyash** [comment]
Hello!
I currently have the same problem on paramiko, trying to connect to sftp server. I tried to increase the banner_timeout but it doesn't work.

Lib versions:
paramiko 3.5.0
bcrypt 4.2.1
cryptography  44.0.0

To connect, I use the following code:
```
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(
    hostname=host,
    port=port,
    username=user,
    password=password,
    pkey=self._get_pkey(),
    timeout=settings.SFTP_CONNECTION_TIMEOUT,
    auth_timeout=settings.SFTP_AUTH_TIMEOUT,
    banner_timeout=settings.SFTP_BANNER_TIMEOUT,
)

sftp = ssh.open_sftp()
```

I use several sftp servers and have found that this error does not appear for all of them. 
For sftp server with image `atmoz/sftp:alpine-3.7` all workings fine. Also using the telnet command I found out that the server uses `OpenSSH_7.5`

For sftp server with image `atmoz/sftp:alpine` which was updated 13-01-2025(https://hub.docker.com/r/atmoz/sftp) I get the following error `paramiko.ssh_exception.SSHException: Error reading SSH protocol banner`. using the telnet command I found out that the server uses `OpenSSH_9.9`

For sftp server image of which I do not know, I found out with the help of telnet command that the server uses `GoAnywhere7.6.0`

**Comment by eliasp** [comment]
It looks to me, like this is some non-threadsafe/concurrent access problem of reading from the socket.

I'm using paramiko via pyinfra and see a huge number of hosts failing due to this error, but as soon as I set `--parallel 1`, the number of occurences across several hundreds of hosts seems to be drastically reduced.

After digging around a bit in `packet.py` I suspected the use of `time.time` vs `time.monotonic` might play a role here, but replacing all relevant occurences didn't make any difference.

**Comment by acarapetis** [comment]
We've got the same issue using `aws ssm start-session` as a ProxyCommand - in certain environments (e.g. bitbucket pipelines for us) there's a long enough gap between the "Starting session" line (from the SSM middleman) and the rest of the banner (from the real SSH server) that it times out. Subclassing Transport with a patched `_check_banner` that increases that 2 second timeout fixed it. Another vote for exposing that timeout with some kind of configuration parameter.
