### ISSUE TITLE
ansible.module_utils.connection.ConnectionError: q must be exactly 160, 224, or 256 bits long

### ISSUE THREAD

**Issue by anthonyxpalermo** [paramiko/paramiko#1757]
I keep getting this error when running my f5 playbooks
I tried generating a new ssh key but same issue.

The full traceback is:
Traceback (most recent call last):
  File "/Users/palea009/.pyenv/versions/3.8.0/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/Users/palea009/.pyenv/versions/3.8.0/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 663, in _execute
    result = self._handler.run(task_vars=variables)
  File "/Users/palea009/gitlab/ansible-cda-tools/collections/ansible_collections/f5networks/f5_modules/plugins/action/bigip.py", line 93, in run
    out = conn.get_prompt()
  File "/Users/palea009/.pyenv/versions/3.8.0/lib/python3.8/site-packages/ansible/module_utils/connection.py", line 195, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
ansible.module_utils.connection.ConnectionError: q must be exactly 160, 224, or 256 bits long
fatal: [one.two.com]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

 python3 -c 'import paramiko; print(paramiko.__version__)'
2.7.2

 ansible --version
 57287 1601646003.81102: starting run
ansible 2.10.1
  config file = /Users/palea009/gitlab/ansible-cda-tools/ansible.cfg
  configured module search path = ['/Users/palea009/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/palea009/.pyenv/versions/3.8.0/lib/python3.8/site-packages/ansible
  executable location = /Users/palea009/.pyenv/versions/3.8.0/bin/ansible
  python version = 3.8.0 (default, Oct  1 2020, 09:52:48) [Clang 10.0.1 (clang-1001.0.46.4)]

**Comment by anthonyxpalermo** [comment]
Can anyone help with this issue ?
I have not found a solution ....

**Comment by ploxiln** [comment]
see https://github.com/paramiko/paramiko/issues/909#issuecomment-607838902
or https://github.com/paramiko/paramiko/issues/750#issuecomment-571953674

**Comment by jpiironen** [comment]
Looks like this is not exactly the same issue, but I would try to ensure it's not the same issues as in this comment https://github.com/paramiko/paramiko/issues/750#issuecomment-634540604.
