### ISSUE TITLE
sftp open error: TypeError: catching classes that do not inherit from BaseException is not allowed

### ISSUE THREAD

**Issue by refriedjello** [paramiko/paramiko#1772]
I am running on CentOS 7.7.1908, Python 3.6.8-13.el7, and paramiko 2.7.2.

I have this script that attempts to open a file open on a remote server:

```
#!/usr/bin/env python3
import paramiko

server =         'serverName'
user =           'userName'
ssh_hosts_file = '/path/.ssh/known_hosts'
ssh_key =        '/path/.ssh/id_rsa'

client = paramiko.SSHClient()
client.load_host_keys(ssh_hosts_file)
client.connect(server, port=22, username=user, password="None", key_filename=ssh_key)

sftp_client = client.open_sftp()
remote_file = sftp_client.open('/tmp/test-file', 'r')
```

When I execute I get this error:

```
Exception ignored in: <bound method SFTPFile.__del__ of <paramiko.sftp_file.SFTPFile object at 0x7fbc8a3dbcf8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/sftp_file.py", line 76, in __del__
  File "/usr/local/lib/python3.6/site-packages/paramiko/sftp_file.py", line 108, in _close
TypeError: catching classes that do not inherit from BaseException is not allowed
```

If I open the file for appending it does succeed. I can add a new line to that file. However, the error is still generated.

Can someone help me to understand how I can solve this, so an error is not returned?

**Comment by refriedjello** [comment]
If I downgrade to paramiko 2.6.0 the error goes away. Still present in 2.7.0 and 2.7.1 however.

**Comment by ploxiln** [comment]
It's complaining about this code:

https://github.com/paramiko/paramiko/blob/2.7.2/paramiko/sftp_file.py#L98-L110

```python
        try:
            if async_:
                # GC'd file handle could be called from an arbitrary thread
                # -- don't wait for a response
                self.sftp._async_request(type(None), CMD_CLOSE, self.handle)
            else:
                self.sftp._request(CMD_CLOSE, self.handle)
        except EOFError:
            # may have outlived the Transport connection
            pass
        except (IOError, socket.error):
            # may have outlived the Transport connection
            pass
```

This code didn't change since paramiko-2.6.0, and these exceptions do inherit from BaseException (I tested in Python-3.7 but this would have been true since Python-2.6 at least):

```
>>> issubclass(EOFError, BaseException)
True
>>> issubclass(IOError, BaseException)
True
>>> issubclass(socket.error, BaseException)
True
```

There has been a case in the past where Red Hat patches to python caused very strange exceptions for paramiko: https://github.com/paramiko/paramiko/issues/1182 ...

**Comment by afuaxb2** [comment]
if you close the files you open with ftpclient before end of program, it seems to resolve the issue.
so add remote_file.close() before the end of the program.

I had the same issue and this cleared it.
