### ISSUE TITLE
[question]: Getting connection reset while it works when running same command on host directly

### ISSUE THREAD

**Issue by ggrimaux** [paramiko/paramiko#1777]
Hello,

I'm running a test where there are clients started with docker-compose and having SSH port exposed. 
Then another docker that is started and contacting clients using SSH port mapped. 

When doing SSH from this docker host it is working. But when running via python and Paramiko I'm getting connection reset.

I do not understand why I'm getting such issues.

```
b'[LOG] 12:28:54  | 192.168.1.21 | root | s=F+I+S+V | 22011 | '
======= ERROR =======
[Errno 104] Connection reset by peer
=====================
######################
Traceback (most recent call last):
  File "stress_status_updater.py", line 157, in <module>
    smc_client.accept_finger_print()
  File "/home/prod/smc/qaet/lib/python/api_tests/util/smc_client.py", line 184, in accept_finger_print
    self.ssh_object.connect()
  File "/home/prod/smc/qaet/lib/python/api_tests/util/ssh.py", line 44, in connect
    port=self.port)
  File "/home/prod/.local/lib/python3.5/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/home/prod/.local/lib/python3.5/site-packages/paramiko/client.py", line 691, in _auth
    self._agent = Agent()
  File "/home/prod/.local/lib/python3.5/site-packages/paramiko/agent.py", line 379, in __init__
    self._connect(conn)
  File "/home/prod/.local/lib/python3.5/site-packages/paramiko/agent.py", line 65, in _connect
    ptype, result = self._send_message(cSSH2_AGENTC_REQUEST_IDENTITIES)
  File "/home/prod/.local/lib/python3.5/site-packages/paramiko/agent.py", line 83, in _send_message
    data = self._read_all(4)
  File "/home/prod/.local/lib/python3.5/site-packages/paramiko/agent.py", line 88, in _read_all
    result = self._conn.recv(wanted)
ConnectionResetError: [Errno 104] Connection reset by peer

```

The code to connect is quite simple
```

    def connect(self):
        """
        Connect to host and keep SSH connection
        """
        ssh_session = paramiko.SSHClient()
        ssh_session.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        self.out.log_msg("{} | {} | {} | {} |"
                         .format(self.ip,
                                 self.user,
                                 self.pwd,
                                 self.port))
        ssh_session.connect(hostname=self.ip,
                            username=self.user,
                            password=self.pwd,
                            port=self.port)
```

Any help would be very appreciated.

Thanks in advance.

/Greg.

**Comment by ggrimaux** [comment]
ah maybe I found. Looks like it is working when disabling user_agent.

**Comment by ploxiln** [comment]
This error is about the connection to the SSH Agent being reset. It looks like you are not actually trying to use an SSH Agent. Normally, it will fail to connect initially, or it won't get any relevant user-auth keys, and it will just return nothing, or it will raise a `SSHException` and paramiko will try a different auth method. But in your case, it is seemingly connecting to what it thinks is an SSH Agent (but probably isn't) and getting a different unexpected kind of exception when trying to use that SSH Agent connection, and that breaks out of the whole auth flow. If the code that calls `SSHClient.connect()` passes the kwarg `allow_agent=False` that will work-around this issue.
