### ISSUE TITLE
SSHClient.exec_command may cause a deadlock if stderr and stdout exceed 2MiB each.

### ISSUE THREAD

**Issue by fukasawah** [paramiko/paramiko#1778]
I think this is caused by the following deadlock.

- Transport thread: Writing to STDERR buffer(window_size?) is blocking
- App thread : Reading from STDOUT buffer is blocking

My code may be wrong, but I can't find the right code. I think this fix is difficult, so we need to be careful.

BTW, I found the workaround. but I'm not sure if it's right... 

### Reproduce code

```
# for STDOUT output and STDERR output of 10MiB each
command = '''bash -c 'dd if=/dev/urandom bs=1024 count=10240 >&1 & dd if=/dev/urandom bs=1024 count=10240 >&2; wait' '''

import paramiko
client = paramiko.SSHClient()

client.set_missing_host_key_policy(paramiko.MissingHostKeyPolicy())
client.connect(hostname="127.0.0.1", port=2222, username="test", password="test") # change it 

(stdin, stdout, stderr) = client.exec_command(command, timeout=5)

stdout_data = stdout.read() # <= blocking and timeout ... !!
stderr_data = stderr.read()

code = stdout.channel.recv_exit_status()
```

### Expected, Actual

I was expecting an none error, but the actual result was the next stack trace. 

Environment 1: Windows 10 Pro (Host) to Ubuntu 20.04.1 LTS (on Hyper-V on Host) 

- Python: 3.7.6
- paramiko version: 2.7.2

```
Traceback (most recent call last):
  File "C:\Users\fukas\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "C:\Users\fukas\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    stdout_data = stdout.read() # <= blocking and timeout ... !!
  File "C:\Users\fukas\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\file.py", line 200, in read
    new_data = self._read(self._DEFAULT_BUFSIZE)
  File "C:\Users\fukas\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\channel.py", line 1361, in _read
    return self.channel.recv(size)
  File "C:\Users\fukas\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout
```

Environment 2: Ubuntu 20.04.1 LTS (on Hyper-V) -> (loopback)

- Python: 3.8.5
- paramiko version: 2.7.2

```
Traceback (most recent call last):
  File "/home/fukasawah/.local/lib/python3.8/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/home/fukasawah/.local/lib/python3.8/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    stdout_data = stdout.read() # <= blocking and timeout ... !!
  File "/home/fukasawah/.local/lib/python3.8/site-packages/paramiko/file.py", line 200, in read
    new_data = self._read(self._DEFAULT_BUFSIZE)
  File "/home/fukasawah/.local/lib/python3.8/site-packages/paramiko/channel.py", line 1361, in _read
    return self.channel.recv(size)
  File "/home/fukasawah/.local/lib/python3.8/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout
Exception ignored in: <function BufferedFile.__del__ at 0x7fd53d4d04c0>
Traceback (most recent call last):
  File "/home/fukasawah/.local/lib/python3.8/site-packages/paramiko/file.py", line 66, in __del__
  File "/home/fukasawah/.local/lib/python3.8/site-packages/paramiko/channel.py", line 1392, in close
  File "/home/fukasawah/.local/lib/python3.8/site-packages/paramiko/channel.py", line 991, in shutdown_write
  File "/home/fukasawah/.local/lib/python3.8/site-packages/paramiko/channel.py", line 967, in shutdown
  File "/home/fukasawah/.local/lib/python3.8/site-packages/paramiko/transport.py", line 1846, in _send_user_message
AttributeError: 'NoneType' object has no attribute 'time'

```

### Workaround

The `Channel.recv(size)` method is non-blocking, so I'll use it.
And, repeat until SSH_MSG_CHANNEL_EOF packet are received or the buffer is empty. 

But, High CPU usage...

```
# for STDOUT output and STDERR output of 10MiB each
command = '''bash -c 'dd if=/dev/urandom bs=1024 count=10240 >&1 & dd if=/dev/urandom bs=1024 count=10240 >&2; wait' '''

import paramiko
client = paramiko.SSHClient()

client.set_missing_host_key_policy(paramiko.MissingHostKeyPolicy())
client.connect(hostname="127.0.0.1", port=2222, username="test", password="test") # change it 

channel = client.get_transport().open_session(timeout=5)

try: 
    channel.exec_command(command)
    RECV_SIZE = 1024 * 32
    stdout_data = b''
    stderr_data = b''

    while not channel.eof_received or channel.recv_ready() or channel.recv_stderr_ready():
        stdout_data += channel.recv(RECV_SIZE)
        stderr_data += channel.recv_stderr(RECV_SIZE)

    code = channel.recv_exit_status()

finally:
    channel.close()

client.close()
```

**Comment by fukasawah** [comment]
FYI, I just found out that this has been mentioned in the past on stackoverflow...
https://stackoverflow.com/questions/23504126/do-you-have-to-check-exit-status-ready-if-you-are-going-to-check-recv-ready

It helps to understand how paramiko works.
