### ISSUE TITLE
'NoneType' object has no attribute 'time'

### ISSUE THREAD

**Issue by jzhang82119** [paramiko/paramiko#1797]
ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(host, port, username, password)

        stdin, stdout, stderr = ssh.exec_command(command, get_pty=True)
        print(stdout.read().decode('utf-8'))

Basically I am running a ssh to a target and run some simple command like ls. I got the the following error. Not sure why. 
I have tried a few different version of python. The error does not seem to be related to python version. I tried paramiko 2.7.2 and 2.7.1.     

Exception ignored in: <function BufferedFile.__del__ at 0x7faabbcb5430>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/paramiko/file.py", line 66, in __del__
  File "/root/miniconda3/lib/python3.8/site-packages/paramiko/channel.py", line 1392, in close
  File "/root/miniconda3/lib/python3.8/site-packages/paramiko/channel.py", line 991, in shutdown_write
  File "/root/miniconda3/lib/python3.8/site-packages/paramiko/channel.py", line 967, in shutdown
  File "/root/miniconda3/lib/python3.8/site-packages/paramiko/transport.py", line 1846, in _send_user_message
AttributeError: 'NoneType' object has no attribute 'time'

**Comment by ploxiln** [comment]
see probably related https://github.com/paramiko/paramiko/issues/1617

**Comment by cvdnn** [comment]
add the below:
```Python
if __name__ == "__main__":
    main()
```
then put your code in the main() def

**Comment by kalvdans** [comment]
> Why? Why this works? And why is this open for so long without solution?
> It works, for sure, but i can't wrap my head around why?

Objects will then be garbage-collected when main() returns, not when the interpreter quits and tears down modules in an arbitrary order. I'd say it is bad habit to implement any `__del__()` methods at all.

**Comment by maretodoric** [comment]
> > Why? Why this works? And why is this open for so long without solution?
> > It works, for sure, but i can't wrap my head around why?
> 
> Objects will then be garbage-collected when main() returns, not when the interpreter quits and tears down modules in an arbitrary order. I'd say it is bad habit to implement any `__del__()` methods at all.

Ok, sure. But I'm using paramiko.SSHClient as a context manager. I would think that at least the __exit__ would take care of it.
