### ISSUE TITLE
Not accepting password encrypted key

### ISSUE THREAD

**Issue by robvdl** [paramiko/paramiko#1798]
I keep getting the following error with fabric 2 / Paramiko:

    paramiko.ssh_exception.PasswordRequiredException: Private key file is encrypted

I don't know where to start because there are so many open issues that all sounds so similar.

But I am really trying to upgrade to fabric 2, tried it twice already in the last few years but every time I run into something like this:

```
Traceback (most recent call last):
  File "/usr/bin/fab", line 8, in <module>
    sys.exit(program.run())
  File "/opt/fabric2/lib/python3.6/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/opt/fabric2/lib/python3.6/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/opt/fabric2/lib/python3.6/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/opt/fabric2/lib/python3.6/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/rob/Projects/dietdecoder/fabfile.py", line 114, in deploy
    remote.run('uname -a')
  File "<decorator-gen-3>", line 2, in run
  File "/opt/fabric2/lib/python3.6/site-packages/fabric/connection.py", line 29, in opens
    self.open()
  File "/opt/fabric2/lib/python3.6/site-packages/fabric/connection.py", line 634, in open
    self.client.connect(**kwargs)
  File "/opt/fabric2/lib/python3.6/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/opt/fabric2/lib/python3.6/site-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/opt/fabric2/lib/python3.6/site-packages/paramiko/client.py", line 735, in _auth
    filename, pkey_class, passphrase
  File "/opt/fabric2/lib/python3.6/site-packages/paramiko/client.py", line 586, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/opt/fabric2/lib/python3.6/site-packages/paramiko/pkey.py", line 235, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/opt/fabric2/lib/python3.6/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/opt/fabric2/lib/python3.6/site-packages/paramiko/rsakey.py", line 175, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/opt/fabric2/lib/python3.6/site-packages/paramiko/pkey.py", line 308, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/opt/fabric2/lib/python3.6/site-packages/paramiko/pkey.py", line 334, in _read_private_key
    data = self._read_private_key_pem(lines, end, password)
  File "/opt/fabric2/lib/python3.6/site-packages/paramiko/pkey.py", line 386, in _read_private_key_pem
    raise PasswordRequiredException("Private key file is encrypted")
paramiko.ssh_exception.PasswordRequiredException: Private key file is encrypted
```

I tried both ssh-agent and --prompt-for-passphrase but to no avail. This is manually installing the latest fabric and paramiko in a virtualenv in /opt on Ubuntu 18.04

I would really like to see this fixed but don't know where to start and in the mean time am just going to have to go back to fabric 1.

I believe the issue is likely in Paramiko rather than fabric, perhaps it doesn't like my key.

Every project at my work is still stuck on fabric 1 / python 2 and I would like to showcase fabric 2 but I can't even get the thing working myself. We all use passphrases on keys at work, so if I can't get this going it's likely others can't either.

**Comment by robvdl** [comment]
```
fab --version
Fabric 2.5.0
Paramiko 2.7.2
Invoke 1.4.1
```

Running on Python 3.6 on Ubuntu 18.04 LTS

**Comment by robvdl** [comment]
I think this is the issue: https://github.com/paramiko/paramiko/issues/1394
