### ISSUE TITLE
AttributeError: ResourceManager instance has no attribute '_warn_unsafe_extraction'

### ISSUE THREAD

**Issue by howdydoody123** [paramiko/paramiko#180]
I keep getting this error when I run my script. I am using Python 2.6.6 and Pycrypto 2.6 

Full trace:
Traceback (most recent call last):
  File "poo.py", line 1, in <module>
    import paramiko
  File "build/bdist.linux-x86_64/egg/paramiko/**init**.py", line 64, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 33, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/util.py", line 33, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/common.py", line 98, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Random/**init**.py", line 29, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Random/Fortuna/FortunaGenerator.py", line 35, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Util/Counter.py", line 59, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Util/_counter.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Util/_counter.py", line 4, in __bootstrap__
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 914, in resource_filename
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1601, in get_resource_filename
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1629, in _extract_resource
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 990, in get_cache_path
AttributeError: ResourceManager instance has no attribute '_warn_unsafe_extraction'

Code:

import paramiko
import scp

username = 'root'
password = 'thepassword'
try:
    t = paramiko.Transport(('thehost', '22'))
    t.connect(username=username, password=password)
    sftp = paramiko.SFTPClient.from_transport(t)
    sftp.put('something.properties','/home/Data')
finally:
    t.close()

**Comment by ljluestc** [comment]
```
import paramiko
import scp

username = 'root'
password = 'thepassword'

# Set up the SSH transport
try:
    # Create a new transport with the given host and port
    t = paramiko.Transport(('thehost', 22))
    
    # Connect using the provided credentials
    t.connect(username=username, password=password)
    
    # Create an SFTP client from the transport
    sftp = paramiko.SFTPClient.from_transport(t)
    
    # Upload a file
    sftp.put('something.properties', '/home/Data')
finally:
    # Always close the transport to free up resources
    t.close()

```
