### ISSUE TITLE
paramiko.ssh_exception.SSHException: Incompatible ssh peer

### ISSUE THREAD

**Issue by dburtsev** [paramiko/paramiko#1829]
Hello
We have an old Python 2.7 script on Linux which works for years. Our company upgrades SFTP server and the script can't connect anymore. This is the error:
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "/var/cache/tomcat8/temp/interpreter-6645297390516703219.tmp", line 11, in <module>
    transport.connect(username = username, password = password)
  File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 979, in connect
    self.start_client()
  File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 407, in start_client
    raise e
paramiko.ssh_exception.SSHException: Incompatible ssh peer (no acceptable kex algorithm)

Thank you,
Dmitriy Burtsev

**Comment by dburtsev** [comment]
I am trying to install paramici for python 3.6
python3 -m pip --version
pip 21.0.1 from /home/ec2-user/.local/lib/python3.6/site-packages/pip (python 3.6)

sudo python3 -m pip install paramiko
 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f123e25d668>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/paramiko/
  Could not find a version that satisfies the requirement paramiko (from versions: )
No matching distribution found for paramiko

**Comment by dburtsev** [comment]
I fix python 3 installation issue.
sudo python3 -m pip install --upgrade pip --proxy server:port
sudo python3 -m pip install paramiko --proxy server:port
