### ISSUE TITLE
2.7.2: pytest warnings

### ISSUE THREAD

**Issue by kloczek** [paramiko/paramiko#1844]
```console
============================================================================= warnings summary =============================================================================
tests/test_channelfile.py::TestChannelStdinFile::test_defaults_to_unbuffered_reading
tests/test_channelfile.py::TestChannelStdinFile::test_can_override_mode_and_bufsize
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function BufferedFile.__del__ at 0x7fc627240940>

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/paramiko-2.7.2/paramiko/file.py", line 66, in __del__
      self.close()
    File "/home/tkloczko/rpmbuild/BUILD/paramiko-2.7.2/paramiko/channel.py", line 1392, in close
      self.channel.shutdown_write()
    File "/home/tkloczko/rpmbuild/BUILD/paramiko-2.7.2/paramiko/channel.py", line 991, in shutdown_write
      self.shutdown(1)
    File "/home/tkloczko/rpmbuild/BUILD/paramiko-2.7.2/paramiko/channel.py", line 967, in shutdown
      self.transport._send_user_message(m)
  AttributeError: 'NoneType' object has no attribute '_send_user_message'

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
```

**Comment by kloczek** [comment]
Closing as it is no longer valid for latest version.
