### ISSUE TITLE
SSHException: No existing session for threading

### ISSUE THREAD

**Issue by hhhhYot** [paramiko/paramiko#1848]
First of all, forgive me for my poor English.Try to use multithreading to batch login H3C devices and issue commands.There are 400 H3C devices.When the number of devices is small, no error will be reported.The first section is the content of the error report, the second section is the code part of the source code that throws an exception, and the third section is my code.Hope to get help~~~~~~

```Exception in thread Thread-28:
Traceback (most recent call last):
  File "C:\A\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\A\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:/stduen/python/PycharmProjects/paramiko-async/paramiko-test.py", line 35, in run_script
    ssh.connect(hostname=ip, username=username, password=pwd, timeout=2)
  File "C:\A\Python\Python36\lib\site-packages\paramiko\client.py", line 412, in connect
    server_key = t.get_remote_server_key()
  File "C:\A\Python\Python36\lib\site-packages\paramiko\transport.py", line 834, in get_remote_server_key
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
```
       def get_remote_server_key(self):
        ""
        Return the host key of the server (in client mode).

        .. note::
            Previously this call returned a tuple of ``(key type, key
            string)``. You can get the same effect by calling `.PKey.get_name`
            for the key type, and ``str(key)`` for the key string.

        :raises: `.SSHException` -- if no session is currently active.

        :return: public key (`.PKey`) of the remote server
        """
        if (not self.active) or (not self.initial_kex_done):
            raise SSHException("No existing session")
        return self.host_key
```

`
if __name__ == '__main__':
    for index, row in df.iterrows():
        p = threading.Thread(target=run_script, args=(row['ip'], row['用户名'], row['密码'], row['超级密码']))
        con_list.append(p)
    for cons in con_list:
        cons.start()
    for cons in con_list:
        cons.join()
    for key, val in res.items():
        dd = dd.append(val, ignore_index=True)
    dd.to_excel(outf, index=None)
    outf.save()
`

**Comment by hhhhYot** [comment]
> 首先，请原谅我的英文不好。请尝试使用多线程批量登录H3C设备并发出命令。有400台H3C设备。当设备数量很少时，不会报告任何错误。希望获得帮助，以下是错误内容，第二部分是在源代码中引发异常的代码片段
> 
> ```
> Traceback (most recent call last):
>   File "C:\A\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\A\Python\Python36\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "D:/stduen/python/PycharmProjects/paramiko-async/paramiko-test.py", line 35, in run_script
>     ssh.connect(hostname=ip, username=username, password=pwd, timeout=2)
>   File "C:\A\Python\Python36\lib\site-packages\paramiko\client.py", line 412, in connect
>     server_key = t.get_remote_server_key()
>   File "C:\A\Python\Python36\lib\site-packages\paramiko\transport.py", line 834, in get_remote_server_key
>     raise SSHException("No existing session")
> paramiko.ssh_exception.SSHException: No existing session
> ```
> 
> ```
>    def get_remote_server_key(self):
>     ""
>     Return the host key of the server (in client mode).
> 
>     .. note::
>         Previously this call returned a tuple of ``(key type, key
>         string)``. You can get the same effect by calling `.PKey.get_name`
>         for the key type, and ``str(key)`` for the key string.
> 
>     :raises: `.SSHException` -- if no session is currently active.
> 
>     :return: public key (`.PKey`) of the remote server
>     """
>     if (not self.active) or (not self.initial_kex_done):
>         raise SSHException("No existing session")
>     return self.host_key
> ```

**Comment by h3man5h** [comment]
did you find any solution. I am getting the same error when I use threading. For a serial run, it works properly.

![image](https://user-images.githubusercontent.com/81043775/118651908-edc99a80-b7dd-11eb-999f-859127d4c132.png)
