### ISSUE TITLE
TypeError: Expected unicode or bytes, got None

### ISSUE THREAD

**Issue by chriskessel** [paramiko/paramiko#1880]
This probably isn't an issue so much as an educational thing for me, but I'm not sure where else to ask. I'm using this via Airflow 2's SFTPHook. My pyproject.toml says I'm on 2.7.2 for paramiko.

I'm getting the following error trying to upload the file to an sftp server (atmoz). Atmoz and Airflow are running in a docker-compose.yaml setup.

```
Traceback (most recent call last):
 ...airflow stack bits...
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/sftp/hooks/sftp.py", line 263, in path_exists
    return conn.exists(path)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/pysftp/__init__.py", line 829, in exists
    self._sftp.stat(remotepath)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/paramiko/sftp_client.py", line 491, in stat
    path = self._adjust_cwd(path)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/paramiko/sftp_client.py", line 905, in _adjust_cwd
    path = b(path)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/paramiko/py3compat.py", line 142, in b
    raise TypeError("Expected unicode or bytes, got {!r}".format(s))
TypeError: Expected unicode or bytes, got None
```

Any idea what that means and what I might be doing wrong? I am able to upload a file to the atmoz sftp container manually via command line sftp. I filed this here given it's paramiko at the last part of the stack, my apologies if this is the wrong project.

**Comment by chriskessel** [comment]
Oh! Geez, it's always something stupid, but maybe worth adding as an input validation. I had a step where it creates the directory if it's missing, but the input to that was an unset variable (None value), hence that error.
