### ISSUE TITLE
Connecting on SSH non-default port through jumphost failed

### ISSUE THREAD

**Issue by SeglaSamaty** [paramiko/paramiko#1888]
Hi everyone, 
I'm hitting on a weird issue with paramiko.

Setup:

`mylocalhost ------------------> 22:jumpserver --------------------> 6006:target_host`

- My  goal is to make connection from mylocalhost (linux) to target_host (cisco ios) via jumpserver. 
-  with jumpserver accepting connexions only on ssh default port 22. 
-  and target_host accepting connexions only on port 6006.

I also set passwordless ssh connexion between mylocalhost and jumpserver.

Using Paramiko = 2.7.2

Content of /home/gituser/.ssh/config
```
host  jumpserver
  IdentityFile  /home/gituser/.ssh/id_rsa
  IdentitiesOnly  yes
  user  jumpinguser
  hostname  10.10.10.11
  Protocol 2
  StrictHostKeyChecking  no

host  * !jumpserver
  Protocol 2
  StrictHostKeyChecking  no
  ProxyCommand ssh -F /home/gituser/.ssh/config -W %h:%p jumpserver

```

My code 

```
#!/usr/bin/env python3
import logging
logging.basicConfig(filename='para2.log', level=logging.DEBUG)
import io
import os
import paramiko
from getpass import getpass
from os import path

target_host = '10.10.10.10'
target_port = 6006
target_user = 'targetuser'
jumpserver = '10.10.10.11'
jumpserver_port = 22

conn_dict = {
  'hostname': target_host, 
  'port': target_port, 
  'username': target_user,
  'password': getpass("Target User password: "),
  'look_for_keys': False,
  'allow_agent': False,
  'key_filename': None,
  'pkey': None,
  'passphrase': None,
  'timeout': 10,
  'auth_timeout': None,
  'banner_timeout': 15,
  'sock': None
}

# Using Paramiko to parse the ssh config file
full_path = path.abspath(path.expanduser('/home/gituser/.ssh/config'))
if path.exists(full_path):
  ssh_config_instance = paramiko.SSHConfig()
  with io.open(full_path, "rt", encoding="utf-8") as f:
    ssh_config_instance.parse(f)
    source = ssh_config_instance.lookup(target_host)

#Create proxy socket
proxy = paramiko.ProxyCommand(source["proxycommand"])
conn_dict['sock']=proxy

#Create Client session
remote_conn_pre = paramiko.SSHClient()
remote_conn_pre.load_host_keys('/home/gituser/.ssh/id_rsa')
remote_conn_pre.set_missing_host_key_policy(paramiko.AutoAddPolicy())

#connect
remote_conn_pre.connect(**conn_dict)


stdin, stdout, stderr = remote_conn_pre.exec_command("show users")
for line in stdout.read().split(b'\n'):
  print(str(line))

remote_conn_pre.close()
proxy.close()
```
-------------------------------------------------------------------------------------------------------------------------------------------------------
Code fails with the setup above,

```
Enter passphrase for key '/home/gituser/.ssh/id_rsa': 
gituser@10.10.10.11's password: 
Traceback (most recent call last):
  File "para_ori_oib.py", line 53, in <module>
    remote_conn_pre.connect(**conn_dict)
  File "/home/gituser/.pyenv/versions/3.8.5/lib/python3.8/site-packages/paramiko/client.py", line 412, in connect
    server_key = t.get_remote_server_key()
  File "/home/gituser/.pyenv/versions/3.8.5/lib/python3.8/site-packages/paramiko/transport.py", line 834, in get_remote_server_key
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
```

but when I change the ssh port on target_host to be the default (22) and make the changes in my code everything works fine.
`mylocalhost ------------------> 22:jumpserver --------------------> 22:target_host`.

```
b'==============================================================\r'
b' SSHv2 access\r'
b'\r'
b'==============================================================\r'
b'####  ####
b'==============================================================\r'
b'\r'
b'    Line       User       Host(s)              Idle       Location\r'
b'*392 vty 0/0/1 targetuse idle                 00:00:01 10.11.10.11\r'
b'\r'
b'  Interface    User               Mode         Idle     Peer Address\r'
```

Paramiko seems to handle deferentially the ssh ports in this use case. Does someone know what is going on??

Thx.

**Comment by FloLaco** [comment]
I think you hit a bug.
Regarding the code : https://github.com/paramiko/paramiko/blob/93dba53fba7da34f34660ac4f5fba4cae317a6ed/paramiko/config.py#L423

You can't use other port than 22 for your target device if you don't provide the `Port 6006` in the ssh config file.
To solve this issue, you have to add another argument to the `lookup(hostname)` function (http://docs.paramiko.org/en/stable/api/config.html#paramiko.config.SSHConfig.lookup).
This function aims to give you the config for the `hostname` AND make variable expansion (meaning replace %h:%p with proper value).
To fix the bug, the `lookup` function should also take the port, for the variable expansion.

We just have to discuss about precedence over : 
- port provided by user in the function
- port provided in the ssh_config file
- default (`SSH_PORT` https://github.com/paramiko/paramiko/blob/93dba53fba7da34f34660ac4f5fba4cae317a6ed/paramiko/config.py#L43)

**Comment by SeglaSamaty** [comment]
> Hi everyone,
> I'm hitting on a weird issue with paramiko.
> 
> Setup:
> 
> `mylocalhost ------------------> 22:jumpserver --------------------> 6006:target_host`
> 
> * My  goal is to make connection from mylocalhost (linux) to target_host (cisco ios) via jumpserver.
> * with jumpserver accepting connexions only on ssh default port 22.
> * and target_host accepting connexions only on port 6006.
> 
> I also set passwordless ssh connexion between mylocalhost and jumpserver.
> 
> Using Paramiko = 2.7.2
> 
> Content of /home/gituser/.ssh/config
> 
> ```
> host  jumpserver
>   IdentityFile  /home/gituser/.ssh/id_rsa
>   IdentitiesOnly  yes
>   user  jumpinguser
>   hostname  10.10.10.11
>   Protocol 2
>   StrictHostKeyChecking  no
> 
> host  * !jumpserver
>   Protocol 2
>   StrictHostKeyChecking  no
>   ProxyCommand ssh -F /home/gituser/.ssh/config -W %h:%p jumpserver
> ```
> 
> My code
> 
> ```
> #!/usr/bin/env python3
> import logging
> logging.basicConfig(filename='para2.log', level=logging.DEBUG)
> import io
> import os
> import paramiko
> from getpass import getpass
> from os import path
> 
> target_host = '10.10.10.10'
> target_port = 6006
> target_user = 'targetuser'
> jumpserver = '10.10.10.11'
> jumpserver_port = 22
> 
> conn_dict = {
>   'hostname': target_host, 
>   'port': target_port, 
>   'username': target_user,
>   'password': getpass("Target User password: "),
>   'look_for_keys': False,
>   'allow_agent': False,
>   'key_filename': None,
>   'pkey': None,
>   'passphrase': None,
>   'timeout': 10,
>   'auth_timeout': None,
>   'banner_timeout': 15,
>   'sock': None
> }
> 
> # Using Paramiko to parse the ssh config file
> full_path = path.abspath(path.expanduser('/home/gituser/.ssh/config'))
> if path.exists(full_path):
>   ssh_config_instance = paramiko.SSHConfig()
>   with io.open(full_path, "rt", encoding="utf-8") as f:
>     ssh_config_instance.parse(f)
>     source = ssh_config_instance.lookup(target_host)
> 
> #Create proxy socket
> proxy = paramiko.ProxyCommand(source["proxycommand"])
> conn_dict['sock']=proxy
> 
> #Create Client session
> remote_conn_pre = paramiko.SSHClient()
> remote_conn_pre.load_host_keys('/home/gituser/.ssh/id_rsa')
> remote_conn_pre.set_missing_host_key_policy(paramiko.AutoAddPolicy())
> 
> #connect
> remote_conn_pre.connect(**conn_dict)
> 
> 
> stdin, stdout, stderr = remote_conn_pre.exec_command("show users")
> for line in stdout.read().split(b'\n'):
>   print(str(line))
> 
> remote_conn_pre.close()
> proxy.close()
> ```
> 
> Code fails with the setup above,
> 
> ```
> Enter passphrase for key '/home/gituser/.ssh/id_rsa': 
> gituser@10.10.10.11's password: 
> Traceback (most recent call last):
>   File "para_ori_oib.py", line 53, in <module>
>     remote_conn_pre.connect(**conn_dict)
>   File "/home/gituser/.pyenv/versions/3.8.5/lib/python3.8/site-packages/paramiko/client.py", line 412, in connect
>     server_key = t.get_remote_server_key()
>   File "/home/gituser/.pyenv/versions/3.8.5/lib/python3.8/site-packages/paramiko/transport.py", line 834, in get_remote_server_key
>     raise SSHException("No existing session")
> paramiko.ssh_exception.SSHException: No existing session
> ```
> 
> but when I change the ssh port on target_host to be the default (22) and make the changes in my code everything works fine.
> `mylocalhost ------------------> 22:jumpserver --------------------> 22:target_host`.
> 
> ```
> b'==============================================================\r'
> b' SSHv2 access\r'
> b'\r'
> b'==============================================================\r'
> b'####  ####
> b'==============================================================\r'
> b'\r'
> b'    Line       User       Host(s)              Idle       Location\r'
> b'*392 vty 0/0/1 targetuse idle                 00:00:01 10.11.10.11\r'
> b'\r'
> b'  Interface    User               Mode         Idle     Peer Address\r'
> ```
> 
> Paramiko seems to handle deferentially the ssh ports in this use case. Does someone know what is going on??
> 
> Thx.
