### ISSUE TITLE
ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by sixtone** [paramiko/paramiko#1948]
Hello!

Not sure if this is a pysftp bug but as of late I am getting an error message that states:

`Exception ignored in: <function Connection.__del__ at 0x000001A9EF6CD288>
Traceback (most recent call last):
  File "C:\Users\d.green\AppData\Roaming\Python\Python37\site-packages\pysftp\__init__.py", line 1013, in __del__
  File "C:\Users\d.green\AppData\Roaming\Python\Python37\site-packages\pysftp\__init__.py", line 795, in close
ImportError: sys.meta_path is None, Python is likely shutting down`

Whenever the connection is beeing closed. It's pointing to "import logging" in the __init__.py file. Thought i'd put this error here, just in case, it's not my system causing the error in the first place :)

Best Regards

**Comment by jun66j5** [comment]
I believe that absolutely is an issue of pysftp. Please report it to the maintainer of pysftp.
