### ISSUE TITLE
Transport.connect() raises EOFError

### ISSUE THREAD

**Issue by nuistzhou** [paramiko/paramiko#1965]
I encapsulated the SFTP connection as a class shown below:

```python
class SFTP_Transfer:
    def __init__(self) -> None:
        try:
            self.transport = paramiko.Transport(sock=(settings.SFTP_CRED["HOST"], settings.SFTP_CRED["PORT"]))
            self.transport.connect(username=settings.SFTP_CRED["USER"], password=settings.SFTP_CRED["PASSWORD"])
            self.sftp = paramiko.SFTPClient.from_transport(self.transport)
        except paramiko.SSHException as e:
            logger.exception(e)
    def close(self,):
        if self.sftp:
            self.sftp.close()
        if self.transport:
            self.transport.close()
```

However, when I use it in below way, it causes 'transport' EOFError issue:
```python
        try:
            sftp_transfer = SFTP_Transfer()
            for file in sftp_transfer.sftp.listdir(self.remote_processed_path):
                processed = os.path.join(self.remote_processed_path, file).replace("\\", "/")
                archived = os.path.join(self.remote_processed_archive, file).replace("\\", "/")
                sftp_transfer.sftp.rename(processed , archived )
            sftp_transfer.close()
        except Exception as e:
            logger.exception(e)
```

```
Traceback (most recent call last):
  File "/home/xxx/xxx/xxx/xxx/xxx/xxx.py", line 318, in archive_sftp
    sftp_transfer = SFTP_Transfer()
  File "/home/xxx/xxx/xxx/xxx/xxx.py", line 40, in __init__
    self.transport.connect(username=settings.SFTP_CRED["USER"], password=settings.SFTP_CRED["PASSWORD"])
  File "/home/xxx/.conda/envs/xxx/lib/python3.9/site-packages/paramiko/transport.py", line 1291, in connect
    self.start_client()
  File "/home/xxx/.conda/envs/xxx/lib/python3.9/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/home/xxx/.conda/envs/xxx/lib/python3.9/site-packages/paramiko/transport.py", line 2055, in run
    ptype, m = self.packetizer.read_message()
  File "/home/xxx/.conda/envs/xxx/lib/python3.9/site-packages/paramiko/packet.py", line 459, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/home/xxx/.conda/envs/xxx/lib/python3.9/site-packages/paramiko/packet.py", line 299, in read_all
    raise EOFError()
EOFError
```

Don't know why, it happens on both Windows and CentOS platform.

**Comment by jun66j5** [comment]
I believe that is not a paramiko issue. Check log of the ssh server. Also, what OS and version is your ssh server?

**Comment by CaMi1le** [comment]
@nuistzhou same error, how you deal with it?

**Comment by adrian-martinez-dev** [comment]
@nuistzhou I'm having this issue too
