### ISSUE TITLE
can't set file st_mtime with utime method, get OSError: FSETSTAT unsupported

### ISSUE THREAD

**Issue by JingxinPan** [paramiko/paramiko#1969]
Hello,
I want to set the modified time of the file in SFTP. I use the utime method, but get error:
```
>>> sftp.utime('******',(1642307598,1642307598))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/paramiko/sftp_client.py", line 580, in utime
    self._request(CMD_SETSTAT, path, attr)
  File "/usr/lib/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "/usr/lib/python3.6/site-packages/paramiko/sftp_client.py", line 865, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python3.6/site-packages/paramiko/sftp_client.py", line 898, in _convert_status
    raise IOError(text)
OSError: SETSTAT unsupported
>>> paramiko.__version__
'2.4.2'
```
Is this operation supported? Could anyone help me with this issue?
Thanks.

**Comment by jun66j5** [comment]
That is not a paramiko issue. The error means your ssh server doesn't support to set timestamp of the file.

**Comment by JingxinPan** [comment]
Got it, the SFTP server is in AWS environment, it seems this kind of operation is not supported.
