### ISSUE TITLE
A bug or parameter key problem

### ISSUE THREAD

**Issue by shuke163** [paramiko/paramiko#1996]
python code:
```
import sys
import logging
import paramiko

root = logging.getLogger()
root.setLevel(logging.DEBUG)
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger("paramiko").setLevel(logging.DEBUG)

private_key_path = '/Users/shuke/.ssh/keys/root.pem'

key = paramiko.RSAKey.from_private_key_file(private_key_path)
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('192.168.1.100', port=22, username='root', pkey=key, timeout=60,
            disabled_algorithms=dict(pubkeys=["rsa-sha2-512", "rsa-sha2-256"]))
stdin, stdout, stderr = ssh.exec_command('df -Th')
print(stdout.read())
ssh.close()
```

output:
```
DEBUG:paramiko.transport:starting thread (client mode): 0x10229ff0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.9.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.4
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.4)
DEBUG:paramiko.transport:=== Key exchange possibilities ===
DEBUG:paramiko.transport:kex algos: curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group-exchange-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha256, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1
DEBUG:paramiko.transport:server key: ssh-rsa, rsa-sha2-512, rsa-sha2-256, ecdsa-sha2-nistp256, ssh-ed25519
DEBUG:paramiko.transport:client encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com, aes128-cbc, aes192-cbc, aes256-cbc, blowfish-cbc, cast128-cbc, 3des-cbc
DEBUG:paramiko.transport:server encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com, aes128-cbc, aes192-cbc, aes256-cbc, blowfish-cbc, cast128-cbc, 3des-cbc
DEBUG:paramiko.transport:client mac: umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1
DEBUG:paramiko.transport:server mac: umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1
DEBUG:paramiko.transport:client compress: none, zlib@openssh.com
DEBUG:paramiko.transport:server compress: none, zlib@openssh.com
DEBUG:paramiko.transport:client lang: <none>
DEBUG:paramiko.transport:server lang: <none>
DEBUG:paramiko.transport:kex follows: False
DEBUG:paramiko.transport:=== Key exchange agreements ===
DEBUG:paramiko.transport:Kex: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey: ssh-ed25519
DEBUG:paramiko.transport:Cipher: aes128-ctr
DEBUG:paramiko.transport:MAC: hmac-sha2-256
DEBUG:paramiko.transport:Compression: none
DEBUG:paramiko.transport:=== End of kex handshake ===
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Got EXT_INFO: {'server-sig-algs': b'rsa-sha2-256,rsa-sha2-512'}
DEBUG:paramiko.transport:Adding ssh-ed25519 host key for 192.168.1.100: b'b8a675630759ee8dfefd59f480090f8f'
DEBUG:paramiko.transport:Trying SSH key b'd3885f9edb67358293cd379964ac5dcd'
DEBUG:paramiko.transport:userauth is OK
DEBUG:paramiko.transport:Finalizing pubkey algorithm for key of type 'ssh-rsa'
DEBUG:paramiko.transport:Our pubkey algorithm list: ['ssh-rsa']
DEBUG:paramiko.transport:Server-side algorithm list: ['rsa-sha2-256', 'rsa-sha2-512']
DEBUG:paramiko.transport:No common pubkey algorithms exist! Dying.
ERROR:paramiko.transport:Exception (client): Unable to agree on a pubkey algorithm for signing a 'ssh-rsa' key!
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/paramiko/transport.py", line 2163, in run
ERROR:paramiko.transport:    handler(self.auth_handler, m)
ERROR:paramiko.transport:  File "/usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/paramiko/auth_handler.py", line 366, in _parse_service_accept
ERROR:paramiko.transport:    algorithm = self._finalize_pubkey_algorithm(key_type)
ERROR:paramiko.transport:  File "/usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/paramiko/auth_handler.py", line 334, in _finalize_pubkey_algorithm
ERROR:paramiko.transport:    raise AuthenticationException(err.format(key_type))
ERROR:paramiko.transport:paramiko.ssh_exception.AuthenticationException: Unable to agree on a pubkey algorithm for signing a 'ssh-rsa' key!
ERROR:paramiko.transport:
DEBUG:paramiko.transport:Trying discovered key b'45984b35b2f1773729294ca7ce5ec6ac' in /Users/bytedance/.ssh/id_rsa
Traceback (most recent call last):
  File "/Users/bytedance/Work/byte/common/hids/para.py", line 26, in <module>
    ssh.connect('192.168.1.100', port=22, username='root', pkey=key, timeout=60,
  File "/usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/paramiko/client.py", line 766, in _auth
    raise saved_exception
  File "/usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/paramiko/client.py", line 742, in _auth
    self._transport.auth_publickey(username, key)
  File "/usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/paramiko/transport.py", line 1624, in auth_publickey
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
```
This is the code and debug information，The server uses centos7.6.1810. The openssh-server version is openssh-server-7.4p1-16.el7.x86_64,paramiko=2.9.2
It is normal to use the following code:
```
import sys
import logging
import paramiko

root = logging.getLogger()
root.setLevel(logging.DEBUG)
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger("paramiko").setLevel(logging.DEBUG)

private_key_path = '/Users/shuke/.ssh/keys/root.pem'

key = paramiko.RSAKey.from_private_key_file(private_key_path)
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('192.168.1.100', port=22, username='root', pkey=key, timeout=60,
            disabled_algorithms={'keys': ['rsa-sha2-256', 'rsa-sha2-512']})
stdin, stdout, stderr = ssh.exec_command('df -Th')
print(stdout.read())
ssh.close()
```

**Comment by shuke163** [comment]
After removal, a message is displayed indicating Authentication failed.

**Comment by jun66j5** [comment]
Please post the error with debug logging.

**Comment by shuke163** [comment]
code
```
ssh.connect('192.168.1.100', port=22, username='root', pkey=key, timeout=60)
```
debug logging
```
DEBUG:paramiko.transport:starting thread (client mode): 0x655df00
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.9.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_5.3
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_5.3)
DEBUG:paramiko.transport:=== Key exchange possibilities ===
DEBUG:paramiko.transport:kex algos: diffie-hellman-group-exchange-sha256, diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1
DEBUG:paramiko.transport:server key: ssh-rsa, ssh-dss
DEBUG:paramiko.transport:client encrypt: aes128-ctr, aes192-ctr, aes256-ctr, arcfour256, arcfour128, aes128-cbc, 3des-cbc, blowfish-cbc, cast128-cbc, aes192-cbc, aes256-cbc, arcfour, rijndael-cbc@lysator.liu.se
DEBUG:paramiko.transport:server encrypt: aes128-ctr, aes192-ctr, aes256-ctr, arcfour256, arcfour128, aes128-cbc, 3des-cbc, blowfish-cbc, cast128-cbc, aes192-cbc, aes256-cbc, arcfour, rijndael-cbc@lysator.liu.se
DEBUG:paramiko.transport:client mac: hmac-md5, hmac-sha1, umac-64@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-ripemd160, hmac-ripemd160@openssh.com, hmac-sha1-96, hmac-md5-96
DEBUG:paramiko.transport:server mac: hmac-md5, hmac-sha1, umac-64@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-ripemd160, hmac-ripemd160@openssh.com, hmac-sha1-96, hmac-md5-96
DEBUG:paramiko.transport:client compress: none, zlib@openssh.com
DEBUG:paramiko.transport:server compress: none, zlib@openssh.com
DEBUG:paramiko.transport:client lang: <none>
DEBUG:paramiko.transport:server lang: <none>
DEBUG:paramiko.transport:kex follows: False
DEBUG:paramiko.transport:=== Key exchange agreements ===
DEBUG:paramiko.transport:Kex: diffie-hellman-group-exchange-sha256
DEBUG:paramiko.transport:HostKey: ssh-rsa
DEBUG:paramiko.transport:Cipher: aes128-ctr
DEBUG:paramiko.transport:MAC: hmac-sha2-256
DEBUG:paramiko.transport:Compression: none
DEBUG:paramiko.transport:=== End of kex handshake ===
DEBUG:paramiko.transport:Got server p (2048 bits)
DEBUG:paramiko.transport:kex engine KexGexSHA256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 192.168.1.100: b'33f5f5ea3a02c46b4b9b3aa826971a62'
DEBUG:paramiko.transport:Trying SSH key b'd3885f9edb67358293cd379964ac5dcd'
DEBUG:paramiko.transport:userauth is OK
DEBUG:paramiko.transport:Finalizing pubkey algorithm for key of type 'ssh-rsa'
DEBUG:paramiko.transport:Our pubkey algorithm list: ['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa']
DEBUG:paramiko.transport:Server did not send a server-sig-algs list; defaulting to our first preferred algo ('rsa-sha2-512')
DEBUG:paramiko.transport:NOTE: you may use the 'disabled_algorithms' SSHClient/Transport init kwarg to disable that or other algorithms if your server does not support them!
INFO:paramiko.transport:Authentication (publickey) failed.
DEBUG:paramiko.transport:Trying discovered key b'45984b35b2f1773729294ca7ce5ec6ac' in /Users/bytedance/.ssh/id_rsa
DEBUG:paramiko.transport:userauth is OK
DEBUG:paramiko.transport:Finalizing pubkey algorithm for key of type 'ssh-rsa'
DEBUG:paramiko.transport:Our pubkey algorithm list: ['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa']
DEBUG:paramiko.transport:Server did not send a server-sig-algs list; defaulting to our first preferred algo ('rsa-sha2-512')
DEBUG:paramiko.transport:NOTE: you may use the 'disabled_algorithms' SSHClient/Transport init kwarg to disable that or other algorithms if your server does not support them!
INFO:paramiko.transport:Authentication (publickey) failed.
Traceback (most recent call last):
  File "/Users/bytedance/Work/byte/common/hids/para.py", line 27, in <module>
    ssh.connect('192.168.1.100', port=22, username='root', pkey=key, timeout=60)
  File "/usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/paramiko/client.py", line 766, in _auth
    raise saved_exception
  File "/usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/paramiko/client.py", line 742, in _auth
    self._transport.auth_publickey(username, key)
  File "/usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/paramiko/transport.py", line 1634, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/paramiko/auth_handler.py", line 258, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```
It works fine using the following code
```
ssh.connect('192.168.1.100', port=22, username='root', pkey=key, timeout=60,
            disabled_algorithms=dict(pubkeys=["rsa-sha2-512", "rsa-sha2-256"]))
```

**Comment by jun66j5** [comment]
You're trying to connect different versions of OpenSSH server.

OpenSSSH 7.4 in first comment. 
```
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.4
```
`disabled_algorithms=dict(pubkeys=["rsa-sha2-512", "rsa-sha2-256"]))` is _not_ needed to connect OpenSSH 7.4.

OpenSSH 5.3 in the latest comment.
```
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_5.3
```
`disabled_algorithms=dict(pubkeys=["rsa-sha2-512", "rsa-sha2-256"]))` is needed to connect OpenSSH 5.3.

**Comment by shuke163** [comment]
> 

I think I know why. Thank you！@jun66j5
