### ISSUE TITLE
cannot import paramiko on mac

### ISSUE THREAD

**Issue by divideconcept** [paramiko/paramiko#1998]
While `import paramiko` works fine on Windows 11 and Ubuntu 20.04, on macOS 12 I have the following error:

```
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:28:27) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/divide/TorchStudio/python/lib/python3.9/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/Users/divide/TorchStudio/python/lib/python3.9/site-packages/paramiko/transport.py", line 91, in <module>
    from paramiko.dsskey import DSSKey
  File "/Users/divide/TorchStudio/python/lib/python3.9/site-packages/paramiko/dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "/Users/divide/TorchStudio/python/lib/python3.9/site-packages/paramiko/pkey.py", line 31, in <module>
    import bcrypt
  File "/Users/divide/TorchStudio/python/lib/python3.9/site-packages/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt  # type: ignore
ImportError: dlopen(/Users/divide/TorchStudio/python/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libffi.7.dylib
  Referenced from: /Users/divide/TorchStudio/python/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
  Reason: tried: '/Users/divide/TorchStudio/python/lib/libffi.7.dylib' (no such file), '/Users/divide/TorchStudio/python/lib/libffi.7.dylib' (no such file), '/Users/divide/TorchStudio/python/lib/python3.9/site-packages/../../libffi.7.dylib' (no such file), '/Users/divide/TorchStudio/python/lib/libffi.7.dylib' (no such file), '/Users/divide/TorchStudio/python/lib/libffi.7.dylib' (no such file), '/Users/divide/TorchStudio/python/lib/python3.9/site-packages/../../libffi.7.dylib' (no such file), '/Users/divide/TorchStudio/python/bin/../lib/libffi.7.dylib' (no such file), '/Users/divide/TorchStudio/python/bin/../lib/libffi.7.dylib' (no such file), '/usr/local/lib/libffi.7.dylib' (no such file), '/usr/lib/libffi.7.dylib' (no such file)
```

Environment: Macbook Air M1, macOS 12.0.1, miniconda x86_64, Python 3.9.10, conda-forge/noarch::paramiko-2.9.2-pyhd8ed1ab_0 (same error with paramiko 2.8.x, 2.7x)

**Comment by jun66j5** [comment]
That is an issue of cffi binary and/or TorchStudio distribution, not a paramiko issue.
Try to reinstall cffi.
```
$ pip uninstall -y cffi
$ pip install --no-cache-dir cffi
```

**Comment by divideconcept** [comment]
Indeed `conda install cffi -c conda-forge` solved the issue !
