### ISSUE TITLE
fat file, but missing compatible architecture have 'i386,x86_64', need 'arm64e' error with bcrypt on Mac M1 Pro chip

### ISSUE THREAD

**Issue by crmpicco** [paramiko/paramiko#1999]
I have recently upgraded from a 2017 MBP to a 2021 MBP with the M1 Pro chip.

Since then i've had issue running a Python 2.7 script.

I am using paramiko:

```
#!/usr/bin/env python
...
import paramiko
...
```
    
...and when I run the script I get the following error:

```
Traceback (most recent call last):
  File "/Users/crmpicco/deploy.py", line 14, in <module>
    import paramiko
  File "/Library/Python/2.7/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/Library/Python/2.7/site-packages/paramiko/transport.py", line 90, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/Library/Python/2.7/site-packages/paramiko/ed25519key.py", line 17, in <module>
    import bcrypt
  File "/Library/Python/2.7/site-packages/bcrypt/__init__.py", line 25, in <module>
    from bcrypt import _bcrypt
ImportError: dlopen(/Library/Python/2.7/site-packages/bcrypt/_bcrypt.so, 0x0002): tried: '/Library/Python/2.7/site-packages/bcrypt/_bcrypt.so' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/_bcrypt.so' (no such file)
```

The file definitely exists, as the error says, but i'm unsure how to proceed.

```
locate bcrypt.so
/Library/Python/2.7/site-packages/bcrypt/_bcrypt.so
```

Have any other Paramiko users experienced this in a Python 2 environment?

**Comment by jun66j5** [comment]
```
missing compatible architecture (have 'i386,x86_64', need 'arm64e'
```
Are you reading this error message?

2017 MBP is x64_86  architecture, but 2021 MBP with the M1 Pro is arm64e architecture. You must reinstall all binaries in /Library/Python/2.7/site-packages. That is not a paramiko issue.
