### ISSUE TITLE
Test suite will need to be able to handle SHA-1 signatures not being supported

### ISSUE THREAD

**Issue by pghmcfc** [paramiko/paramiko#2004]
Red Hat Enterprise Linux 9 will have SHA-1 signatures disabled by default:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/VVLHQAWI3IQ7NRLKMUHJ27JV3V2JAFDP/
This change is already visible in CentOS 9 Stream, which is where development of RHEL-9 is happening.
Building paramiko on CentoOS 9 Stream results in many test suite failures due to lack of SHA-1 signature support, like this one:
```
_______________________ SSHClientTest.test_auth_timeout ________________________

self = <tests.test_client.SSHClientTest testMethod=test_auth_timeout>

    @slow
    def test_auth_timeout(self):
        """
        verify that the SSHClient has a configurable auth timeout
        """
        # Connect with a half second auth timeout
>       self.assertRaises(
            AuthenticationException,
            self._test_connection,
            password="unresponsive-server",
            auth_timeout=0.5,
        )

tests/test_client.py:501: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_client.py:205: in _test_connection
    self.tc.connect(**dict(self.connect_kwargs, **kwargs))
paramiko/client.py:406: in connect
    t.start_client(timeout=timeout)
paramiko/transport.py:698: in start_client
    raise e
paramiko/transport.py:2109: in run
    ptype, m = self.packetizer.read_message()
paramiko/packet.py:459: in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def read_all(self, n, check_rekey=False):
        """
        Read as close to N bytes as possible, blocking as long as necessary.
    
        :param int n: number of bytes to read
        :return: the data read, as a `str`
    
        :raises:
            ``EOFError`` -- if the socket was closed before all the bytes could
            be read
        """
        out = bytes()
        # handle over-reading from reading the banner line
        if len(self.__remainder) > 0:
            out = self.__remainder[:n]
            self.__remainder = self.__remainder[n:]
            n -= len(out)
        while n > 0:
            got_timeout = False
            if self.handshake_timed_out():
                raise EOFError()
            try:
                x = self.__socket.recv(n)
                if len(x) == 0:
>                   raise EOFError()
E                   EOFError

paramiko/packet.py:303: EOFError
----------------------------- Captured stderr call -----------------------------
[2613.8741970062256]	DEBUG:paramiko.transport:starting thread (client mode): 0xcd796880
[2614.0990257263184]	DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.10.1
[2620.7938194274902]	DEBUG:paramiko.transport:starting thread (server mode): 0xcd7b72e0
[2620.9588050842285]	DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.10.1
[2621.018171310425]	DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-paramiko_2.10.1
[2621.058940887451]	INFO:paramiko.transport:Connected (version 2.0, client paramiko_2.10.1)
[2621.150255203247]	DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-paramiko_2.10.1
[2621.2127208709717]	INFO:paramiko.transport:Connected (version 2.0, client paramiko_2.10.1)
[2621.6342449188232]	DEBUG:paramiko.transport:=== Key exchange possibilities ===
[2621.701240539551]	DEBUG:paramiko.transport:kex algos: curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group16-sha512, diffie-hellman-group-exchange-sha256, diffie-hellman-group14-sha256, diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1
[2621.7429637908936]	DEBUG:paramiko.transport:server key: ecdsa-sha2-nistp256, rsa-sha2-512, rsa-sha2-256, ssh-rsa
[2621.7803955078125]	DEBUG:paramiko.transport:client encrypt: aes128-ctr, aes192-ctr, aes256-ctr, aes128-cbc, aes192-cbc, aes256-cbc, blowfish-cbc, 3des-cbc
[2621.8161582946777]	DEBUG:paramiko.transport:server encrypt: aes128-ctr, aes192-ctr, aes256-ctr, aes128-cbc, aes192-cbc, aes256-cbc, blowfish-cbc, 3des-cbc
[2621.8512058258057]	DEBUG:paramiko.transport:client mac: hmac-sha2-256, hmac-sha2-512, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1, hmac-md5, hmac-sha1-96, hmac-md5-96
[2621.8860149383545]	DEBUG:paramiko.transport:server mac: hmac-sha2-256, hmac-sha2-512, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1, hmac-md5, hmac-sha1-96, hmac-md5-96
[2621.919631958008]	DEBUG:paramiko.transport:client compress: none
[2621.952533721924]	DEBUG:paramiko.transport:server compress: none
[2621.9866275787354]	DEBUG:paramiko.transport:client lang: <none>
[2622.0200061798096]	DEBUG:paramiko.transport:server lang: <none>
[2622.053623199463]	DEBUG:paramiko.transport:kex follows: False
[2622.0862865448]	DEBUG:paramiko.transport:=== Key exchange agreements ===
[2622.1280097961426]	DEBUG:paramiko.transport:Kex: curve25519-sha256@libssh.org
[2622.16854095459]	DEBUG:paramiko.transport:HostKey: ssh-rsa
[2622.211694717407]	DEBUG:paramiko.transport:Cipher: aes128-ctr
[2622.257709503174]	DEBUG:paramiko.transport:MAC: hmac-sha2-256
[2622.2984790802]	DEBUG:paramiko.transport:Compression: none
[2622.3325729370117]	DEBUG:paramiko.transport:=== End of kex handshake ===
[2622.4119663238525]	DEBUG:paramiko.transport:=== Key exchange possibilities ===
[2622.469186782837]	DEBUG:paramiko.transport:kex algos: curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group16-sha512, diffie-hellman-group-exchange-sha256, diffie-hellman-group14-sha256, diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1, ext-info-c
[2622.5104331970215]	DEBUG:paramiko.transport:server key: ssh-rsa, ssh-ed25519, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, rsa-sha2-512, rsa-sha2-256, ssh-dss
[2622.548818588257]	DEBUG:paramiko.transport:client encrypt: aes128-ctr, aes192-ctr, aes256-ctr, aes128-cbc, aes192-cbc, aes256-cbc, blowfish-cbc, 3des-cbc
[2622.5855350494385]	DEBUG:paramiko.transport:server encrypt: aes128-ctr, aes192-ctr, aes256-ctr, aes128-cbc, aes192-cbc, aes256-cbc, blowfish-cbc, 3des-cbc
[2622.6205825805664]	DEBUG:paramiko.transport:client mac: hmac-sha2-256, hmac-sha2-512, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1, hmac-md5, hmac-sha1-96, hmac-md5-96
[2622.6556301116943]	DEBUG:paramiko.transport:server mac: hmac-sha2-256, hmac-sha2-512, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1, hmac-md5, hmac-sha1-96, hmac-md5-96
[2622.6966381073]	DEBUG:paramiko.transport:client compress: none
[2622.73907661438]	DEBUG:paramiko.transport:server compress: none
[2622.7705478668213]	DEBUG:paramiko.transport:client lang: <none>
[2622.804641723633]	DEBUG:paramiko.transport:server lang: <none>
[2622.838258743286]	DEBUG:paramiko.transport:kex follows: False
[2622.8716373443604]	DEBUG:paramiko.transport:=== Key exchange agreements ===
[2622.913360595703]	DEBUG:paramiko.transport:Kex: curve25519-sha256@libssh.org
[2622.957468032837]	DEBUG:paramiko.transport:HostKey: ssh-rsa
[2623.000383377075]	DEBUG:paramiko.transport:Cipher: aes128-ctr
[2623.042583465576]	DEBUG:paramiko.transport:MAC: hmac-sha2-256
[2623.0826377868652]	DEBUG:paramiko.transport:Compression: none
[2623.117446899414]	DEBUG:paramiko.transport:=== End of kex handshake ===
[2624.711036682129]	ERROR:paramiko.transport:Unknown exception: sha1 is not supported by this backend for RSA signing.
[2624.9938011169434]	ERROR:paramiko.transport:Traceback (most recent call last):
[2625.0383853912354]	ERROR:paramiko.transport:  File "/builddir/build/BUILD/paramiko-2.10.1/paramiko/transport.py", line 2129, in run
[2625.075578689575]	ERROR:paramiko.transport:    self.kex_engine.parse_next(ptype, m)
[2625.105857849121]	ERROR:paramiko.transport:  File "/builddir/build/BUILD/paramiko-2.10.1/paramiko/kex_curve25519.py", line 62, in parse_next
[2625.1344680786133]	ERROR:paramiko.transport:    return self._parse_kexecdh_init(m)
[2625.1626014709473]	ERROR:paramiko.transport:  File "/builddir/build/BUILD/paramiko-2.10.1/paramiko/kex_curve25519.py", line 92, in _parse_kexecdh_init
[2625.1916885375977]	ERROR:paramiko.transport:    sig = self.transport.get_server_key().sign_ssh_data(
[2625.22029876709]	ERROR:paramiko.transport:  File "/builddir/build/BUILD/paramiko-2.10.1/paramiko/rsakey.py", line 126, in sign_ssh_data
[2625.253677368164]	ERROR:paramiko.transport:    sig = self.key.sign(
[2625.281572341919]	ERROR:paramiko.transport:  File "/usr/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 501, in sign
[2625.3089904785156]	ERROR:paramiko.transport:    return _rsa_sig_sign(self._backend, padding, algorithm, self, data)
[2625.336170196533]	ERROR:paramiko.transport:  File "/usr/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 244, in _rsa_sig_sign
[2625.363349914551]	ERROR:paramiko.transport:    pkey_ctx = _rsa_sig_setup(
[2625.3905296325684]	ERROR:paramiko.transport:  File "/usr/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 213, in _rsa_sig_setup
[2625.417947769165]	ERROR:paramiko.transport:    raise UnsupportedAlgorithm(
[2625.4451274871826]	ERROR:paramiko.transport:cryptography.exceptions.UnsupportedAlgorithm: sha1 is not supported by this backend for RSA signing.
[2625.4723072052]	ERROR:paramiko.transport:
[2625.53334236145]	DEBUG:paramiko.transport:EOF in transport thread
------------------------------ Captured log call -------------------------------
DEBUG    paramiko.transport:transport.py:1873 starting thread (client mode): 0xcd796880
DEBUG    paramiko.transport:transport.py:1873 Local version/idstring: SSH-2.0-paramiko_2.10.1
DEBUG    paramiko.transport:transport.py:1873 starting thread (server mode): 0xcd7b72e0
DEBUG    paramiko.transport:transport.py:1873 Local version/idstring: SSH-2.0-paramiko_2.10.1
DEBUG    paramiko.transport:transport.py:1873 Remote version/idstring: SSH-2.0-paramiko_2.10.1
INFO     paramiko.transport:transport.py:1873 Connected (version 2.0, client paramiko_2.10.1)
DEBUG    paramiko.transport:transport.py:1873 Remote version/idstring: SSH-2.0-paramiko_2.10.1
INFO     paramiko.transport:transport.py:1873 Connected (version 2.0, client paramiko_2.10.1)
DEBUG    paramiko.transport:transport.py:1873 === Key exchange possibilities ===
DEBUG    paramiko.transport:transport.py:1873 kex algos: curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group16-sha512, diffie-hellman-group-exchange-sha256, diffie-hellman-group14-sha256, diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1
DEBUG    paramiko.transport:transport.py:1873 server key: ecdsa-sha2-nistp256, rsa-sha2-512, rsa-sha2-256, ssh-rsa
DEBUG    paramiko.transport:transport.py:1873 client encrypt: aes128-ctr, aes192-ctr, aes256-ctr, aes128-cbc, aes192-cbc, aes256-cbc, blowfish-cbc, 3des-cbc
DEBUG    paramiko.transport:transport.py:1873 server encrypt: aes128-ctr, aes192-ctr, aes256-ctr, aes128-cbc, aes192-cbc, aes256-cbc, blowfish-cbc, 3des-cbc
DEBUG    paramiko.transport:transport.py:1873 client mac: hmac-sha2-256, hmac-sha2-512, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1, hmac-md5, hmac-sha1-96, hmac-md5-96
DEBUG    paramiko.transport:transport.py:1873 server mac: hmac-sha2-256, hmac-sha2-512, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1, hmac-md5, hmac-sha1-96, hmac-md5-96
DEBUG    paramiko.transport:transport.py:1873 client compress: none
DEBUG    paramiko.transport:transport.py:1873 server compress: none
DEBUG    paramiko.transport:transport.py:1873 client lang: <none>
DEBUG    paramiko.transport:transport.py:1873 server lang: <none>
DEBUG    paramiko.transport:transport.py:1873 kex follows: False
DEBUG    paramiko.transport:transport.py:1873 === Key exchange agreements ===
DEBUG    paramiko.transport:transport.py:1873 Kex: curve25519-sha256@libssh.org
DEBUG    paramiko.transport:transport.py:1873 HostKey: ssh-rsa
DEBUG    paramiko.transport:transport.py:1873 Cipher: aes128-ctr
DEBUG    paramiko.transport:transport.py:1873 MAC: hmac-sha2-256
DEBUG    paramiko.transport:transport.py:1873 Compression: none
DEBUG    paramiko.transport:transport.py:1873 === End of kex handshake ===
DEBUG    paramiko.transport:transport.py:1873 === Key exchange possibilities ===
DEBUG    paramiko.transport:transport.py:1873 kex algos: curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group16-sha512, diffie-hellman-group-exchange-sha256, diffie-hellman-group14-sha256, diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1, ext-info-c
DEBUG    paramiko.transport:transport.py:1873 server key: ssh-rsa, ssh-ed25519, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, rsa-sha2-512, rsa-sha2-256, ssh-dss
DEBUG    paramiko.transport:transport.py:1873 client encrypt: aes128-ctr, aes192-ctr, aes256-ctr, aes128-cbc, aes192-cbc, aes256-cbc, blowfish-cbc, 3des-cbc
DEBUG    paramiko.transport:transport.py:1873 server encrypt: aes128-ctr, aes192-ctr, aes256-ctr, aes128-cbc, aes192-cbc, aes256-cbc, blowfish-cbc, 3des-cbc
DEBUG    paramiko.transport:transport.py:1873 client mac: hmac-sha2-256, hmac-sha2-512, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1, hmac-md5, hmac-sha1-96, hmac-md5-96
DEBUG    paramiko.transport:transport.py:1873 server mac: hmac-sha2-256, hmac-sha2-512, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1, hmac-md5, hmac-sha1-96, hmac-md5-96
DEBUG    paramiko.transport:transport.py:1873 client compress: none
DEBUG    paramiko.transport:transport.py:1873 server compress: none
DEBUG    paramiko.transport:transport.py:1873 client lang: <none>
DEBUG    paramiko.transport:transport.py:1873 server lang: <none>
DEBUG    paramiko.transport:transport.py:1873 kex follows: False
DEBUG    paramiko.transport:transport.py:1873 === Key exchange agreements ===
DEBUG    paramiko.transport:transport.py:1873 Kex: curve25519-sha256@libssh.org
DEBUG    paramiko.transport:transport.py:1873 HostKey: ssh-rsa
DEBUG    paramiko.transport:transport.py:1873 Cipher: aes128-ctr
DEBUG    paramiko.transport:transport.py:1873 MAC: hmac-sha2-256
DEBUG    paramiko.transport:transport.py:1873 Compression: none
DEBUG    paramiko.transport:transport.py:1873 === End of kex handshake ===
ERROR    paramiko.transport:transport.py:1873 Unknown exception: sha1 is not supported by this backend for RSA signing.
ERROR    paramiko.transport:transport.py:1871 Traceback (most recent call last):
ERROR    paramiko.transport:transport.py:1871   File "/builddir/build/BUILD/paramiko-2.10.1/paramiko/transport.py", line 2129, in run
ERROR    paramiko.transport:transport.py:1871     self.kex_engine.parse_next(ptype, m)
ERROR    paramiko.transport:transport.py:1871   File "/builddir/build/BUILD/paramiko-2.10.1/paramiko/kex_curve25519.py", line 62, in parse_next
ERROR    paramiko.transport:transport.py:1871     return self._parse_kexecdh_init(m)
ERROR    paramiko.transport:transport.py:1871   File "/builddir/build/BUILD/paramiko-2.10.1/paramiko/kex_curve25519.py", line 92, in _parse_kexecdh_init
ERROR    paramiko.transport:transport.py:1871     sig = self.transport.get_server_key().sign_ssh_data(
ERROR    paramiko.transport:transport.py:1871   File "/builddir/build/BUILD/paramiko-2.10.1/paramiko/rsakey.py", line 126, in sign_ssh_data
ERROR    paramiko.transport:transport.py:1871     sig = self.key.sign(
ERROR    paramiko.transport:transport.py:1871   File "/usr/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 501, in sign
ERROR    paramiko.transport:transport.py:1871     return _rsa_sig_sign(self._backend, padding, algorithm, self, data)
ERROR    paramiko.transport:transport.py:1871   File "/usr/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 244, in _rsa_sig_sign
ERROR    paramiko.transport:transport.py:1871     pkey_ctx = _rsa_sig_setup(
ERROR    paramiko.transport:transport.py:1871   File "/usr/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 213, in _rsa_sig_setup
ERROR    paramiko.transport:transport.py:1871     raise UnsupportedAlgorithm(
ERROR    paramiko.transport:transport.py:1871 cryptography.exceptions.UnsupportedAlgorithm: sha1 is not supported by this backend for RSA signing.
ERROR    paramiko.transport:transport.py:1871 
DEBUG    paramiko.transport:transport.py:1873 EOF in transport thread
```

**Comment by bitprophet** [comment]
Offhand, torn between using this as an excuse to rip out SHA1 entirely (obviously, in a backwards incompat release, one of which is already pending for Python 2 removal) and the much more expedient "mark all such tests using pytest mark tooling so RHEL/CentOS 9 (/ equiv Fedora) can readily skip them". I would certainly merge a PR doing the latter without too much fuss.
