### ISSUE TITLE
SFTP with ProxyCommand throwing Error reading SSH protocol banner

### ISSUE THREAD

**Issue by adarsh-chauhan** [paramiko/paramiko#2018]
Hi all 

trying to run the following and i cant seem to get it working

Its accessing an sftp server behind a bastion

using `Version: 2.10.3`

```
>>> with paramiko.proxy.ProxyCommand(f'sshpass -p {SBC_PASSWORD} ssh -o "ProxyJump 10.10.10.1" admin@20.20.20.1') as pc:
...     with paramiko.client.SSHClient() as client:
...         client.connect('100.71.133.13', sock=pc, banner_timeout=60)
...         sftp = client.open_sftp()
...         o = sftp.listdir()
...         print(o.readline())
... 
```

```
DEBUG:paramiko.transport:starting thread (client mode): 0xe45bed0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.10.3
DEBUG:paramiko.transport:Banner: vtc-us-east-...f87cf77-esbc# SSH-2.0-paramiko_2.10.3
DEBUG:paramiko.transport:Banner: % command not found
DEBUG:paramiko.transport:Banner: vtc-us-east-...f87cf77-esbc# 
ERROR:paramiko.transport:Exception (client): Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/home/<redacted>/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2270, in _check_banner
ERROR:paramiko.transport:    buf = self.packetizer.readline(timeout)
ERROR:paramiko.transport:  File "/home/<redacted>/.local/lib/python3.7/site-packages/paramiko/packet.py", line 380, in readline
ERROR:paramiko.transport:    buf += self._read_timeout(timeout)
ERROR:paramiko.transport:  File "/home/<redacted>/.local/lib/python3.7/site-packages/paramiko/packet.py", line 622, in _read_timeout
ERROR:paramiko.transport:    raise socket.timeout()
ERROR:paramiko.transport:socket.timeout
ERROR:paramiko.transport:
ERROR:paramiko.transport:During handling of the above exception, another exception occurred:
ERROR:paramiko.transport:
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/home/<redacted>/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2093, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/home/<redacted>/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2275, in _check_banner
ERROR:paramiko.transport:    "Error reading SSH protocol banner" + str(e)
ERROR:paramiko.transport:paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
Traceback (most recent call last):
  File "/home/<redacted>/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2270, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/<redacted>/.local/lib/python3.7/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/home/<redacted>/.local/lib/python3.7/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/<redacted>/.local/lib/python3.7/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/home/<redacted>/.local/lib/python3.7/site-packages/paramiko/transport.py", line 698, in start_client
    raise e
  File "/home/<redacted>/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2093, in run
    self._check_banner()
  File "/home/<redacted>/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2275, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

**Comment by tubiana** [comment]
I also have the same problem on Windows 11.

I have to specify that I had another issue (like this https://github.com/paramiko/paramiko/issues/512) and I made a change on proxy.py based on https://github.com/JulianEberius/paramiko/commit/bb1f795db46891961b6a816df3c59e132de7f211

Here's my log : 
```
Exception (client): Error reading SSH protocol banner
Traceback (most recent call last):
  File "C:\Users\tubia\anaconda3\envs\alphasub\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "C:\Users\tubia\anaconda3\envs\alphasub\lib\site-packages\paramiko\packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "C:\Users\tubia\anaconda3\envs\alphasub\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tubia\anaconda3\envs\alphasub\lib\site-packages\paramiko\transport.py", line 2093, in run
    self._check_banner()
  File "C:\Users\tubia\anaconda3\envs\alphasub\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\tubia\anaconda3\envs\alphasub\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\tubia\anaconda3\envs\alphasub\lib\site-packages\paramiko\transport.py", line 2213, in run
    self.packetizer.close()
  File "C:\Users\tubia\anaconda3\envs\alphasub\lib\site-packages\paramiko\packet.py", line 207, in close
    self.__socket.close()
  File "C:\Users\tubia\anaconda3\envs\alphasub\lib\site-packages\paramiko\proxy.py", line 124, in close
    os.kill(self.process.pid, signal.SIGTERM)
PermissionError: [WinError 5] Accès refusé

```

Thank you :)

**Comment by tramontano** [comment]
I have the exact same scenario, had faced the issue (https://github.com/paramiko/paramiko/issues/512) and also made the change on proxy.py based on https://github.com/JulianEberius/paramiko/commit/bb1f795db46891961b6a816df3c59e132de7f211

In my case, the SSH connection works, but I'm always getting the error  `Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\site-packages\paramiko\transport.py", line 2226, in run
    self.sock.close()
  File "C:\Program Files\Python37\lib\site-packages\paramiko\proxy.py", line 124, in close
    os.kill(self.process.pid, signal.SIGTERM)
PermissionError: [WinError 5] Access is denied`

Thanks!

**Comment by jun66j5** [comment]
> In my case, the SSH connection works, but I'm always getting the error
> 
> `PermissionError: [WinError 5] Access is denied`

If you're running on Windows, please try #2130.

**Comment by jun66j5** [comment]
@tramontano your issue is the same as #512, not this.
