### ISSUE TITLE
Writing in append mode fails on TypeError when stat does not return st_size

### ISSUE THREAD

**Issue by UOndro** [paramiko/paramiko#2050]
Writing in append mode fails on the following error:

`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

The problem is that [_get_size](https://github.com/paramiko/paramiko/blob/main/paramiko/sftp_file.py#L519) method in SFTPFile can return None, which is then used to assign value to [_realpos](https://github.com/paramiko/paramiko/blob/29c4d3210b745e7d56c328ffebc2513ebfb482fb/paramiko/file.py#L508).

The [_get_size](https://github.com/paramiko/paramiko/blob/main/paramiko/sftp_file.py#L519) method can return None when [stat](https://github.com/paramiko/paramiko/blob/29c4d3210b745e7d56c328ffebc2513ebfb482fb/paramiko/sftp_attr.py#L100) does not return st_size in response. 

Stack trace:
```  
File "/usr/local/lib/python3.8/site-packages/paramiko/file.py", line 405, in write
    self._write_all(data)
  File "/usr/local/lib/python3.8/site-packages/paramiko/file.py", line 522, in _write_all
    count = self._write(data)
  File "/usr/local/lib/python3.8/site-packages/paramiko/sftp_file.py", line 199, in _write
    long(self._realpos),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by bskinn** [comment]
Do you know, what should the correct behavior be when `_get_size()` returns `None`? Can it successfully continue the append-write? Or should paramiko surface this as an error/exception condition?

Which Python and paramiko versions are you using here?

**Comment by jun66j5** [comment]
Related issue: [#1980 (comment)](https://github.com/paramiko/paramiko/issues/1980#issuecomment-1029310765)

Are you using what ssh server?

**Comment by UOndro** [comment]
> Do you know, what should the correct behavior be when _get_size() returns None? Can it successfully continue the append-write? Or should paramiko surface this as an error/exception condition?

Not sure. However, the code already handles if an exception is raised during calling stat(). If the exception is raised, paramiko defaults to 0. So, I think when st_size is None,  `_get_size()` should also default to 0. 

> Which Python and paramiko versions are you using 

We use paramiko 2.7.2(however, I check also a new version and this bug is still there) and we use python 3.8.


> Are you using what ssh server?
It's the client's server, so I don't know, but I asked them if they could provide this information. 

cc. @jun66j5 @bskinn

**Comment by jun66j5** [comment]
> It's the client's server, so I don't know, but I asked them if they could provide this information.

Please provide remote server's version using the following script:

```python
import paramiko
t = paramiko.Transport((server, port))  # replace with your ssh server and port
t.connect()
print(t.remote_version)
```

**Comment by UOndro** [comment]
```
In [13]: print(w._transport.remote_version)                                                                                                                   
SSH-2.0-FILES.COM
```
They are using https://www.files.com/ as their ssh server.

**Comment by jun66j5** [comment]
SFTP protocol doesn't support append mode. `SFTPFile` class retrieve the file size and write data from position using the size when append mode is required.

However, it doesn't seem that the SFTP server on files.com sends the size of a file. Please ask this behavior on files.com's support.

I think we could check the size of a file when append mode is required.

```diff
diff --git a/paramiko/sftp_file.py b/paramiko/sftp_file.py
index 6c2a1336e..6e571bdbb 100644
--- a/paramiko/sftp_file.py
+++ b/paramiko/sftp_file.py
@@ -63,6 +63,8 @@ class SFTPFile(BufferedFile):
         self.sftp = sftp
         self.handle = handle
         BufferedFile._set_mode(self, mode, bufsize)
+        if (self._flags & self.FLAG_APPEND) != 0 and self._size is None:
+            raise SFTPError("Append mode requires the file size")
         self.pipelined = False
         self._prefetching = False
         self._prefetch_done = False
```

**Comment by UOndro** [comment]
We debug it a little more and we found out that their server supports append mode. However, we tried to append to not existing file, and because the file does not exist server does not return st_size - which means st_size == None. 

What happens on paramiko side is:

1. Open file in append mode
2. Get size of the opened file - if the file does not existed before, stat  will return None
3. Try to [write](https://github.com/paramiko/paramiko/blob/main/paramiko/sftp_file.py#L199) on position returned from _get_size - exception is raised because trying to convert None to int
4. Because we close the file no matter of the exception(classic with statement), the file is created, which means if you repeat it again, the error won't be raised

I think the correct fix is:

```
def _get_size(self):
        try:
            st_size = self.stat().st_size
            if st_size is None:
                return 0
        except:
            return 0
```

**Comment by jun66j5** [comment]
That behavior is weird. `SFTPClient.stat()` raises `FileNotFoundError: [Errno 2] No such file` when the given path is not found. I think sftp server on files.com has the issue.

```pycon
>>> import paramiko
>>> cli = paramiko.SSHClient()
>>> cli.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> cli.connect('127.0.0.1', username='jun66j5')
>>> sftp_cli = cli.open_sftp()
>>> sftp_cli.stat('/etc/hosts')
<SFTPAttributes: [ size=240 uid=0 gid=0 mode=0o100644 atime=1424408416 mtime=1420518101 ]>
>>> sftp_cli.stat('/path/to/notfound')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jun66j5/src/paramiko/paramiko/sftp_client.py", line 493, in stat
    t, msg = self._request(CMD_STAT, path)
  File "/home/jun66j5/src/paramiko/paramiko/sftp_client.py", line 822, in _request
    return self._read_response(num)
  File "/home/jun66j5/src/paramiko/paramiko/sftp_client.py", line 874, in _read_response
    self._convert_status(msg)
  File "/home/jun66j5/src/paramiko/paramiko/sftp_client.py", line 903, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
```

**Comment by jun66j5** [comment]
Sorry. I missed `SFTPFile.stat()` uses `CMD_FSTAT` but `SSHClient.stat()` uses `CMD_STAT`.

OpenSSH's sftp server returns `size=0` when append mode is used for missing file.

```pycon
>>> cli = paramiko.SSHClient()
>>> cli.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> cli.connect('127.0.0.1', username='jun66j5')
>>> sftp_cli = cli.open_sftp()
>>> f = sftp_cli.open('/tmp/notfound', 'a')
>>> print(repr(f.stat()))
<SFTPAttributes: [ size=0 uid=1000 gid=1000 mode=0o100664 atime=1653315962 mtime=1653315962 ]>
```

**Comment by bskinn** [comment]
Thanks @UOndro and @jun66j5 for this work to evaluate and confirm the state of things. bitprophet will have the final word, but I think the general direction of the fix (return size as zero when `.st_size()` returns `None`) is correct. 

----

@UOndro, I think your [proposed fix](https://github.com/paramiko/paramiko/issues/2050#issuecomment-1134611783) is too aggressive. Returning zero on _all_ exceptions may mask other problems inappropriately. Something as simple as this will probably suffice:

```
def _get_size(self):
    return self.stat().st_size or 0
```

If `.st_size` is returned as `None`, the `or` will fall through and `0` will be returned instead.

Would you like to put together a PR? If so, it would be ideal to add a test for this case, too. Thanks!

**Comment by bitprophet** [comment]
I agree with @bskinn that the more targeted fallback - treating a lack of, or None, `st_size` as being equivalent to `0`, is the right way to go here.
