### ISSUE TITLE
Socket exception: Connection reset by peer (104)

### ISSUE THREAD

**Issue by Stella-Sirius** [paramiko/paramiko#2097]
Hi, I always got error message"Socket exception: Connection reset by peer (104)" after received following error logs.

I got these errors after I have closed all opened sftp connection(sftp = self.client.open_sftp() -> sftp.close()). How could I still receive the socket exception error even when there is no opened sftp connection. Could this error between FastAPI and paramiko? Any one got the same problem before?
```
File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
return self.receive_nowait()
File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
raise WouldBlock
anyio.WouldBlock
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 43, in call_next
message = await recv_stream.receive()
File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
raise EndOfStream
anyio.EndOfStream
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
result = await app(self.scope, self.receive, self.send)
File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
return await self.app(scope, receive, send)
File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
await super().__call__(scope, receive, send)
File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
await self.middleware_stack(scope, receive, send)
File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
raise exc
File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
await self.app(scope, receive, _send)
File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 68, in __call__
response = await self.dispatch_func(request, call_next)
File "/api/middleware.py", line 53, in dispatch
raise e
File "/api/middleware.py", line 27, in dispatch
response = await call_next(request)
File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 47, in call_next
raise RuntimeError("No response returned.")
RuntimeError: No response returned.
```

**Comment by jun66j5** [comment]
Have you checked https://stackoverflow.com/questions/71222144/runtimeerror-no-response-returned-in-fastapi-when-refresh-request ?

I suggest to ask on stackoverflow and/or fastapi and/or starlette community. I don't think that is a paramiko issue.

**Comment by Stella-Sirius** [comment]
Thanks @jun66j5 , the issue has been solved and can be closed, but the problem is not FASTAPI or starlette relevant.

The thing is the sftp connection has been closed, but we actually need to close SSHClient as well.

so after `client =  paramiko.SSHClient().connect()`

we need to call `client.close() `to close them all properly.

But thank you for your help!
