### ISSUE TITLE
curve25519-sha256@libssh.org leads to "Signature verification (ssh-rsa) failed" SSHException using paramiko sftp via duplicity

### ISSUE THREAD

**Issue by AInteriorB** [paramiko/paramiko#2102]
Hey @bitprophet @alex, hey all 👋 

we observe a strange behaviour of our duplicity backups using paramiko when enabling curve25519-sha256 for sftp access on remote servers. The initial handshake seems to be always ok:

```
ssh: starting thread (client mode): 0x95ba9fa0
ssh: Local version/idstring: SSH-2.0-paramiko_2.10.4
ssh: Remote version/idstring: SSH-2.0-mod_sftp
ssh: Connected (version 2.0, client mod_sftp)
ssh: === Key exchange possibilities ===
ssh: kex algos: curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp521, ecdh-sha2-nistp384, ecdh-sha2-nistp256, diffie-hellman-group18-sha512, diffie-hellman-group16-sha512, ...
ssh: server key: rsa-sha2-512, rsa-sha2-256, ssh-rsa, ssh-dss
ssh: client encrypt: aes256-ctr, aes192-ctr, aes128-ctr
ssh: server encrypt: aes256-ctr, aes192-ctr, aes128-ctr
ssh: client mac: hmac-sha2-256, hmac-sha2-512
ssh: server mac: hmac-sha2-256, hmac-sha2-512
ssh: client compress: none
ssh: server compress: none
ssh: client lang: <none>
ssh: server lang: <none>
ssh: kex follows: False
ssh: === Key exchange agreements ===
ssh: Kex: curve25519-sha256@libssh.org
ssh: HostKey: ssh-rsa
ssh: Cipher: aes128-ctr
ssh: MAC: hmac-sha2-256
ssh: Compression: none
ssh: === End of kex handshake ===
ssh: kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
ssh: Switch to new keys ...
ssh: Got EXT_INFO: {'server-sig-algs': b'ssh-ed25519,rsa-sha2-256,rsa-sha2-512,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss'}
ssh: Trying discovered key b'***' in /root/.ssh/id_rsa
ssh: userauth is OK
ssh: Finalizing pubkey algorithm for key of type 'ssh-rsa'
ssh: Our pubkey algorithm list: ['rsa-sha2-512', 'rsa-sha2-256']
ssh: Server-side algorithm list: ['ssh-ed25519', 'rsa-sha2-256', 'rsa-sha2-512', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521', 'ssh-rsa', 'ssh-dss']
ssh: Agreed upon 'rsa-sha2-512' pubkey algorithm
ssh: userauth is OK
```

But while transferring several files, paramiko randomly throws a SSHExcetion: Signature verification (ssh-rsa) failed on **rekeying**:
```
ssh: [chan 0] open(b'/file/to/duplicity-inc.***.vol2.difftar.gpg', 'wb') -> 231254225445463453423
ssh: Rekeying (hit 32701 packets, 536885232 bytes sent)
ssh: === Key exchange possibilities ===
ssh: kex algos: curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp521, ecdh-sha2-nistp384, ecdh-sha2-nistp256, diffie-hellman-group18-sha512, diffie-hellman-group16-sha512, ...
ssh: server key: rsa-sha2-512, rsa-sha2-256, ssh-rsa, ssh-dss
ssh: client encrypt: aes256-ctr, aes192-ctr, aes128-ctr
ssh: server encrypt: aes256-ctr, aes192-ctr, aes128-ctr
ssh: client mac: hmac-sha2-256, hmac-sha2-512
ssh: server mac: hmac-sha2-256, hmac-sha2-512
ssh: client compress: none
ssh: server compress: none
ssh: client lang: <none>
ssh: server lang: <none>
ssh: kex follows: False
ssh: === Key exchange agreements ===
ssh: Kex: curve25519-sha256@libssh.org
ssh: HostKey: ssh-rsa
ssh: Cipher: aes128-ctr
ssh: MAC: hmac-sha2-256
ssh: Compression: none
ssh: === End of kex handshake ===
ssh: Exception (client): Signature verification (ssh-rsa) failed.
ssh: Traceback (most recent call last):
ssh:   File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2137, in run
ssh:     self.kex_engine.parse_next(ptype, m)
ssh:   File "/usr/lib/python3/dist-packages/paramiko/kex_curve25519.py", line 64, in parse_next
ssh:     return self._parse_kexecdh_reply(m)
ssh:   File "/usr/lib/python3/dist-packages/paramiko/kex_curve25519.py", line 130, in _parse_kexecdh_reply
ssh:     self.transport._verify_key(peer_host_key_bytes, sig)
ssh:   File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1949, in _verify_key
ssh:     raise SSHException(
ssh: paramiko.ssh_exception.SSHException: Signature verification (ssh-rsa) failed.
ssh:
ssh: Dropping user packet because connection is dead.
ssh: [chan 0] close(30663561636662646164383862353261)
```

Tested with paramiko **v2.10.4** and **v.2.7.2**.

Current workaround is to disable curve25519-sha256 and  curve25519-sha256@libssh.org either on remote or local side to fall back to another kex algo.

Does anybody observe a similar issue or have information how to fix it?

**Comment by jun66j5** [comment]
Are you using [ProFTPD](https://github.com/proftpd/proftpd) with mod_sftp? What version?

```
ssh: Remote version/idstring: SSH-2.0-mod_sftp
```

I think the mod_sftp of ProFTPD should send version string.

**Comment by AInteriorB** [comment]
I don't know the exact software running on the remote endpoint (have no full access/insights) but I guess it is a simple debian sshd sftp subsystem.

**Comment by jun66j5** [comment]
Thanks for the feedback. I guess the sftp server is one of 1.3.7a through 1.3.7d. I try to reproduce it.

* https://packages.debian.org/search?keywords=proftpd-mod-crypto&exact=1
* https://packages.ubuntu.com/search?keywords=proftpd-mod-crypto&exact=1

**Comment by AInteriorB** [comment]
> Thanks for the feedback. I guess the sftp server is one of 1.3.7a through 1.3.7d. I try to reproduce it.
Yes, that makes sens, @jun66j5 . Thanks for your effort and good luck!

**Comment by jun66j5** [comment]
The issue is reproduced with ProFTPd 1.3.7a (debian 11), however unable to reproduce with OpenSSH 8.2p1.

Workaround is to disable pipelining feature, but it makes pretty slow.

```python
import random
import sys
import time
import paramiko

paramiko.util.log_to_file('/dev/stderr')
#paramiko.Packetizer.REKEY_PACKETS = pow(2, 22)
#paramiko.Packetizer.REKEY_BYTES = pow(2, 22)
#paramiko.Packetizer.REKEY_PACKETS_OVERFLOW_MAX = pow(2, 22)
#paramiko.Packetizer.REKEY_BYTES_OVERFLOW_MAX = pow(2, 22)

def write_file(out):
    randbytes = random.Random().randbytes
    chunk_size = 32 * 1024
    out.set_pipelined(True)  # To comment out this line, the issue goes away
    ts = time.time()
    written = 0
    while 1:
        chunk = randbytes(chunk_size)
        out.write(chunk)
        out.flush()
        written += chunk_size
        sys.stderr.write('%d bytes written (%.2f MB/s)\r' %
                         (written,
                          written / (1024 * 1024) / (time.time() - ts)))

def main(host, port, user, password):
    cli = paramiko.SSHClient()
    cli.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    with cli:
        cli.connect(host, int(port), user, password,
                    look_for_keys=False, allow_agent=True,
                    disabled_algorithms={'keys': ('rsa-sha2-512', 'rsa-sha2-256'),
                                         'pubkeys': ('rsa-sha2-512', 'rsa-sha2-256')})
        with cli.open_sftp() as sftp:
            with sftp.open('/dev/null', 'wb') as out:
                write_file(out)

if __name__ == '__main__':
    main(*sys.argv[1:])
```

**Comment by AInteriorB** [comment]
Any news on this?

**Comment by bskinn** [comment]
Flagging for attention in the key/auth overhaul of #387 in case the problem is on the auth side.

@jun66j5 Does your diagnosis here suggest a solution?

**Comment by jun66j5** [comment]
Currently, no solution.

I think rekey logic in paramiko and/or ProFTPD have something wrong while transfer of sftp with pipelining feature.
