### ISSUE TITLE
_check_banner timeout for subsequent lines

### ISSUE THREAD

**Issue by matt-leolabs** [paramiko/paramiko#2105]
Hello,

I am doing ssh over ssm, and while I can set the banner_timeout for the first line, the subsequent lines still fail unless I increase the timeout there. The error I get below has been discussed many times, but I am able to fix it only if I overwrite the timeout in the `else` clause of the `_check_banner` method here: https://github.com/paramiko/paramiko/blob/main/paramiko/transport.py#L2269

Why doesn't the else clause also respect the banner timeout?

```Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 2139, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/packet.py", line 577, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 2144, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 2139, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/packet.py", line 367, in readline
    buf += self._read_timeout(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/packet.py", line 577, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/fab", line 10, in <module>
    sys.exit(program.run())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/invoke/program.py", line 363, in run
    self.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/invoke/program.py", line 532, in execute
    executor.execute(*self.tasks)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/invoke/tasks.py", line 128, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/matt/work/leo-radar/deploy/fabfile.py", line 158, in test
    ctx.run('printenv | grep HOSTNAME')
  File "<decorator-gen-3>", line 2, in run
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fabric/connection.py", line 29, in opens
    self.open()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fabric/connection.py", line 615, in open
    self.client.connect(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 587, in start_client
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 1966, in run
    self._check_banner()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paramiko/transport.py", line 2144, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner```

**Comment by ronkorving** [comment]
I've also gotten sporadic `"Error reading SSH protocol banner"` errors, and this line from transport.py doesn't expose any details: `"Error reading SSH protocol banner" + str(e)`. I suspect it's a timeout, but it's not always easy to get your hands on stack traces after the fact. For one, if the error was more specific, that would be helpful. But perhaps the unconfigurable "2 seconds for subsequent lines" is a bit too extreme?

**Comment by perrinjerome** [comment]
Relevant code is 

https://github.com/paramiko/paramiko/blob/b77ef44a049c3b99e770a360e7b1312ca6940ce4/paramiko/transport.py#L2265-L2268

instead of using `banner_timeout` to wait for the first line and then using a timeout of 2 for subsequent lines, I believe it would be more natural if the timeout was "global" for all the reads from `_check_banner`. It is also incorrect that if we set a `banner_timeout` of 10 seconds and the first line takes 9 seconds to read, a second line 1 second, a third line 1 second and a forth line 1 second, etc, we would exceeds the timeout of 10 seconds without raising a timeout error. In practice it's probably not a problem, but as a user I expect banner timeout to be the maximum time spent to wait for reading the banner.

**Comment by bskinn** [comment]
On re-reading this, I'm going to re-categorize as a feature request around the banner timeout handling.

**Comment by Rakesh-Dakshinamoorthy** [comment]
@bskinn Could you please look into this as priority. If this gets resolve it would be really helpful.

**Comment by rambangaru** [comment]
Happening to me as well. end up handling by monkey patch transport class. it makes life easy if it is configurable.

**Comment by kjoyce77** [comment]
OK, yep...  me too.
