### ISSUE TITLE
Missing KEX algorithms

### ISSUE THREAD

**Issue by NicoPy** [paramiko/paramiko#2116]
Hi,

I try to connect to a Paramiko SSH server from a ssh client. 
For the SSH server, I use the [server demo code](https://github.com/paramiko/paramiko/blob/main/demos/demo_server.py).
For the ssh client, I use a OpenSSH client.

The Paramiko server outputs this log :
```
DEB [20220921-15:15:18.603] thr=1   paramiko.transport: starting thread (server mode): 0x93ef6170
DEB [20220921-15:15:18.603] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.11.0
DEB [20220921-15:15:18.603] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-OpenSSH_8.5
INF [20220921-15:15:18.604] thr=1   paramiko.transport: Connected (version 2.0, client OpenSSH_8.5)
DEB [20220921-15:15:18.606] thr=1   paramiko.transport: === Key exchange possibilities ===
DEB [20220921-15:15:18.606] thr=1   paramiko.transport: kex algos: curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group-exchange-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group14-sha256, ext-info-c
DEB [20220921-15:15:18.606] thr=1   paramiko.transport: server key: ssh-ed25519-cert-v01@openssh.com, ecdsa-sha2-nistp256-cert-v01@openssh.com, ecdsa-sha2-nistp384-cert-v01@openssh.com, ecdsa-sha2-nistp521-cert-v01@openssh.com, sk-ssh-ed25519-cert-v01@openssh.com, sk-ecdsa-sha2-nistp256-cert-v01@openssh.com, rsa-sha2-512-cert-v01@openssh.com, rsa-sha2-256-cert-v01@openssh.com, ssh-rsa-cert-v01@openssh.com, ssh-ed25519, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, sk-ssh-ed25519@openssh.com, sk-ecdsa-sha2-nistp256@openssh.com, rsa-sha2-512, rsa-sha2-256, ssh-rsa
DEB [20220921-15:15:18.607] thr=1   paramiko.transport: client encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com
DEB [20220921-15:15:18.607] thr=1   paramiko.transport: server encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com
DEB [20220921-15:15:18.607] thr=1   paramiko.transport: client mac: umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1
DEB [20220921-15:15:18.607] thr=1   paramiko.transport: server mac: umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1
DEB [20220921-15:15:18.607] thr=1   paramiko.transport: client compress: none, zlib@openssh.com, zlib
DEB [20220921-15:15:18.607] thr=1   paramiko.transport: server compress: none, zlib@openssh.com, zlib
DEB [20220921-15:15:18.607] thr=1   paramiko.transport: client lang: <none>
DEB [20220921-15:15:18.607] thr=1   paramiko.transport: server lang: <none>
DEB [20220921-15:15:18.607] thr=1   paramiko.transport: kex follows: False
DEB [20220921-15:15:18.607] thr=1   paramiko.transport: === Key exchange agreements ===
DEB [20220921-15:15:18.607] thr=1   paramiko.transport: Kex: curve25519-sha256@libssh.org
ERR [20220921-15:15:18.607] thr=1   paramiko.transport: Exception (server): Incompatible ssh peer (no acceptable host key)
ERR [20220921-15:15:18.608] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20220921-15:15:18.608] thr=1   paramiko.transport:   File "C:\Python310\lib\site-packages\paramiko\transport.py", line 2138, in run
ERR [20220921-15:15:18.608] thr=1   paramiko.transport:     self._handler_table[ptype](self, m)
ERR [20220921-15:15:18.608] thr=1   paramiko.transport:   File "C:\Python310\lib\site-packages\paramiko\transport.py", line 2258, in _negotiate_keys
ERR [20220921-15:15:18.608] thr=1   paramiko.transport:     self._parse_kex_init(m)
ERR [20220921-15:15:18.609] thr=1   paramiko.transport:   File "C:\Python310\lib\site-packages\paramiko\transport.py", line 2474, in _parse_kex_init
ERR [20220921-15:15:18.609] thr=1   paramiko.transport:     raise IncompatiblePeer(
ERR [20220921-15:15:18.609] thr=1   paramiko.transport: paramiko.ssh_exception.IncompatiblePeer: Incompatible ssh peer (no acceptable host key)
```

The ssh client outputs this :
```
# ssh -vvv -p 2200  nico@192.168.2.79                             
OpenSSH_8.5p1, OpenSSL 1.1.1o  3 May 2022
debug2: resolve_canonicalize: hostname 192.168.2.79 is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug3: ssh_connect_direct: entering
debug1: Connecting to 192.168.2.79 [192.168.2.79] port 2200.
debug3: set_sock_tos: set socket 3 IP_TOS 0x48
debug1: Connection established.
debug1: identity file /root/.ssh/id_rsa type -1
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa_sk type -1
debug1: identity file /root/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: identity file /root/.ssh/id_ed25519_sk type -1
debug1: identity file /root/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /root/.ssh/id_xmss type -1
debug1: identity file /root/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.5
debug1: Remote protocol version 2.0, remote software version paramiko_2.11.0
debug1: compat_banner: no match: paramiko_2.11.0
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 192.168.2.79:2200 as 'nico'
debug3: put_host_port: [192.168.2.79]:2200
debug1: load_hostkeys: fopen /root/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug3: order_hostkeyalgs: no algorithms matched; accept original
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: 
debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
debug2: MACs stoc: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: (no match)
Unable to negotiate with 192.168.2.79 port 2200: no matching host key type found. Their offer: 

```

One can see that the Paramiko and the ssh client  KEX algorithms lists do not overlap. This makes the connection impossible.
Is there a way to add a sha KEX algorithm to the Paramiko server ?

**Comment by jun66j5** [comment]
Weird. The demo_server.py advertises `rsa-sha2-512,rsa-sha2-256,ssh-rsa` for host key.

I guess that is caused by your installation. Please describe installed libraries in your environment.

<details>
<summary>ssh -vv -p 2200 ...</summary>

```
$ ssh -vv -p 2200 192.168.11.122
OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022
debug1: Reading configuration data /home/jun66j5/.ssh/config
debug1: /home/jun66j5/.ssh/config line 24: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolve_canonicalize: hostname 192.168.11.122 is address
debug1: Connecting to 192.168.11.122 [192.168.11.122] port 2200.
debug1: Connection established.
debug1: identity file /home/jun66j5/.ssh/id_rsa type 0
debug1: identity file /home/jun66j5/.ssh/id_rsa-cert type -1
debug1: identity file /home/jun66j5/.ssh/id_ecdsa type -1
debug1: identity file /home/jun66j5/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/jun66j5/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/jun66j5/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/jun66j5/.ssh/id_ed25519 type -1
debug1: identity file /home/jun66j5/.ssh/id_ed25519-cert type -1
debug1: identity file /home/jun66j5/.ssh/id_ed25519_sk type -1
debug1: identity file /home/jun66j5/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/jun66j5/.ssh/id_xmss type -1
debug1: identity file /home/jun66j5/.ssh/id_xmss-cert type -1
debug1: identity file /home/jun66j5/.ssh/id_dsa type 1
debug1: identity file /home/jun66j5/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
debug1: Remote protocol version 2.0, remote software version paramiko_2.11.0
debug1: compat_banner: no match: paramiko_2.11.0
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 192.168.11.122:2200 as 'jun66j5'
debug1: load_hostkeys: fopen /home/jun66j5/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: zlib@openssh.com,zlib,none
debug2: compression stoc: zlib@openssh.com,zlib,none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
debug2: MACs stoc: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-rsa SHA256:OhNL391d/beeFnxxg18AwWVYTAHww+D4djEE7Co0Yng
debug1: load_hostkeys: fopen /home/jun66j5/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: checking without port identifier
debug1: load_hostkeys: fopen /home/jun66j5/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: hostkeys_find_by_key_hostfile: hostkeys file /home/jun66j5/.ssh/known_hosts2 does not exist
debug1: hostkeys_find_by_key_hostfile: hostkeys file /etc/ssh/ssh_known_hosts does not exist
debug1: hostkeys_find_by_key_hostfile: hostkeys file /etc/ssh/ssh_known_hosts2 does not exist
The authenticity of host '[192.168.11.122]:2200 ([192.168.11.122]:2200)' can't be established.
```
</details>

**Comment by NicoPy** [comment]
On the server side, Paramiko runs on a Windows-10 (x64) box on a freshly installed Python 3.10 (x64).
On the client side, this is OpenSSH running on a closed source OS (QNX). I can change the configuration but not recompile OpenSSH. 
What should I look for on the server and client side ?

**Comment by jun66j5** [comment]
I just try it with fresh venv using Python 3.10 on Windows 10, but no issue on my environment.

```
C> C:\usr\tmp\paramiko\Scripts\python.exe --version
Python 3.10.4

C> C:\usr\tmp\paramiko\Scripts\python.exe -m pip list
Package      Version Editable project location
------------ ------- -------------------------
bcrypt       4.0.0
cffi         1.15.1
cryptography 38.0.1
paramiko     2.11.0  c:\usr\src\paramiko.git
pip          22.0.4
pycparser    2.21
PyNaCl       1.5.0
setuptools   58.1.0
six          1.16.0

C> C:\Windows\system32\OpenSSH\ssh.exe -vv -p 2200 127.0.0.1
...
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
...
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
...
```

**Comment by NicoPy** [comment]
Trying to connect on the same machine, like the example you provided :
```
C:\Users\Nicolas>ssh.exe -vv -p 2200 127.0.0.1
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug2: resolve_canonicalize: hostname 127.0.0.1 is address
debug2: ssh_connect_direct
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 2200.
debug1: Connection established.
debug1: identity file C:\\Users\\Nicolas/.ssh/id_rsa type -1
debug1: identity file C:\\Users\\Nicolas/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\Nicolas/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\Nicolas/.ssh/id_dsa-cert type -1
debug1: identity file C:\\Users\\Nicolas/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\Nicolas/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\Nicolas/.ssh/id_ed25519 type -1
debug1: identity file C:\\Users\\Nicolas/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\Nicolas/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\Nicolas/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
debug1: Remote protocol version 2.0, remote software version paramiko_2.11.0
debug1: no match: paramiko_2.11.0
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 127.0.0.1:2200 as 'nicolas'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms:
debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
debug2: MACs stoc: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: (no match)
Unable to negotiate with 127.0.0.1 port 2200: no matching host key type found. Their offer:

```

**Comment by jun66j5** [comment]
Did you modify demo_server.py? Did you removed `t.add_server_key(host_key)` line in the file?

I'm using demo_server.py in 2.11.0 which is replacing  `DoGSSAPIKeyExchange = ...` line with `False` (GSS-API module is not installed).

```
C> git status -b
HEAD detached at 2.11.0
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   demos/demo_server.py

no changes added to commit (use "git add" and/or "git commit -a")

C> git diff
diff --git a/demos/demo_server.py b/demos/demo_server.py
index 6cb2dc51..a6c351d9 100644
--- a/demos/demo_server.py
+++ b/demos/demo_server.py
@@ -113,7 +113,7 @@ class Server(paramiko.ServerInterface):
         return True


-DoGSSAPIKeyExchange = True
+DoGSSAPIKeyExchange = False

 # now connect
 try:
```

**Comment by jun66j5** [comment]
I suggest closing this issue because of no feedback.

**Comment by NicoPy** [comment]
Sorry for the lack of feedback. I have not forgotten this issue. I have a higher priority task running.

**Comment by NicoPy** [comment]
> Did you modify demo_server.py? Did you removed t.add_server_key(host_key) line in the file?

Yes, I commented `t.add_server_key(host_key)` out.

I also modified `DoGSSAPIKeyExchange` to False and tried again. Same error message.

**Comment by jun66j5** [comment]
> Yes, I commented `t.add_server_key(host_key)` out.

That is root cause of the issue. SSH server must have 1 server key at least.

**Comment by NicoPy** [comment]
OK. So I re-activated the serveur key (user_rsa.key) and the error message is gone.
Thanks for your support.
