### ISSUE TITLE
'paramiko.ssh_exception.SSHException: No existing session' since 2.7.0 

### ISSUE THREAD

**Issue by dylanbob** [paramiko/paramiko#2123]
Hi, and thank you for developing open source software.

I am using paramiko through ansible with netconf. Following a platform upgrade, some code stopped working.

Digging a bit, I noticed the problems only occur when using paramiko>=2.7.0 (I tested on 2.7.0, 2.8.1 and 2.11.0). I do NOT face any problem using 2.6.0.

My testing code:
``` python3
#! /usr/bin/env python
# -*- coding: utf-8 -*-

import paramiko

hostname="xxxxx"
port=22 # CLI port

ssh_user="xxxxx"
password="xxxxx"

def _ssh_run_remote_command(cmd):
    ssh_client = paramiko.SSHClient()
    ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh_client.connect(hostname=hostname,
                        username=ssh_user,
                        password=password)
    stdin, stdout, stderr = ssh_client.exec_command(cmd)

    out = stdout.read().decode().strip()
    error = stderr.read().decode().strip()
    print(out)
    if error:
        raise Exception('There was an error pulling the runtime: {}'.format(error))
    ssh_client.close()

    return out 

_ssh_run_remote_command("show version")
```

Logs running 2.6.0 (good!):
```
Mon Oct  3 18:57:05.106 CEST
Cisco IOS XR Software, Version 7.4.2
Copyright (c) 2013-2022 by Cisco Systems, Inc.

Build Information:
 Built By     : ingunawa
 Built On     : Wed Feb 16 03:23:21 PST 2022
 Built Host   : iox-ucs-067
 Workspace    : /auto/srcarchive15/prod/7.4.2/ncs5500/ws
 Version      : 7.4.2
 Location     : /opt/cisco/XR/packages/
 Label        : 7.4.2

cisco NCS-5500 () processor
System uptime is 1 week 8 hours 19 minutes
```

Logs running 2.7.0:
```
Traceback (most recent call last):
  File "test-paramiko.py", line 29, in <module>
    _ssh_run_remote_command("show version")
  File "test-paramiko.py", line 15, in _ssh_run_remote_command
    ssh_client.connect(hostname=hostname,
  File "/home/sysadmin/.pyenv/versions/paramiko/lib/python3.8/site-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/home/sysadmin/.pyenv/versions/paramiko/lib/python3.8/site-packages/paramiko/client.py", line 766, in _auth
    raise saved_exception
  File "/home/sysadmin/.pyenv/versions/paramiko/lib/python3.8/site-packages/paramiko/client.py", line 753, in _auth
    self._transport.auth_password(username, password)
  File "/home/sysadmin/.pyenv/versions/paramiko/lib/python3.8/site-packages/paramiko/transport.py", line 1553, in auth_password
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
```

My setup:
Testing is a pyenv virtualenv on a custom Debian 10 with python 3.8.13, using either pip packages like in my environment:
```
bcrypt==3.2.0
cffi==1.13.2
cryptography==2.8
pycparser==2.19
PyNaCl==1.5.0
six==1.12.0
```
or using pip's choices when installing paramiko 2.6.0 or 2.7.0:
```
bcrypt==4.0.0
cffi==1.15.1
cryptography==38.0.1
paramiko==2.7.0
pycparser==2.21
PyNaCl==1.5.0
six==1.16.0
```
yields exactly the same results.

Any help or instructions to dig deeper would be greatly appreciated!
Regards

**Comment by dylanbob** [comment]
FYI I get exactly the same result usinge a code example closer to the demo given in the repo :

``` python3
#! /usr/bin/env python
# -*- coding: utf-8 -*-

import paramiko

hostname = "xxxxxxxx"
port = 22

ssh_user = "xxxxxxxx"
password = "xxxxxxxx"

my_command = "show version"

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(hostname=hostname,
                username=ssh_user,
                password=password,
                port=port)
stdin, stdout, stderr = client.exec_command(my_command)
for line in stdout:
    print('... ' + line.strip('\n'))
client.close()
```

**Comment by jun66j5** [comment]
At least, it is unable to reproduce it with OpenSSH 8.2p1 ssh server. I think ssh server implementation in Cisco has something wrong or different with OpenSSH.

Could you please post paramiko.log after the following line is added?

```diff
+paramiko.util.log_to_file('paramiko.log')
 client = paramiko.SSHClient()
```

See also: https://www.paramiko.org/faq.html#paramiko-doesn-t-work-with-my-cisco-windows-or-other-non-unix-system

**Comment by dylanbob** [comment]
paramiko.log for 2.6.0 (good):
```
DEB [20221004-11:00:56.330] thr=1   paramiko.transport: starting thread (client mode): 0x70b34e80
DEB [20221004-11:00:56.332] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.6.0
DEB [20221004-11:00:56.698] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-Cisco-2.0
INF [20221004-11:00:56.698] thr=1   paramiko.transport: Connected (version 2.0, client Cisco-2.0)
DEB [20221004-11:00:56.701] thr=1   paramiko.transport: kex algos:['ecdh-sha2-nistp521', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp256', 'diffie-hellman-group14-sha1'] server key:['ssh-dss', 'rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] server mac:['hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEB [20221004-11:00:56.701] thr=1   paramiko.transport: Kex agreed: ecdh-sha2-nistp256
DEB [20221004-11:00:56.702] thr=1   paramiko.transport: HostKey agreed: ssh-rsa
DEB [20221004-11:00:56.702] thr=1   paramiko.transport: Cipher agreed: aes128-ctr
DEB [20221004-11:00:56.702] thr=1   paramiko.transport: MAC agreed: hmac-sha2-256
DEB [20221004-11:00:56.702] thr=1   paramiko.transport: Compression agreed: none
DEB [20221004-11:00:56.923] thr=1   paramiko.transport: kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEB [20221004-11:00:56.925] thr=1   paramiko.transport: Switch to new keys ...
DEB [20221004-11:00:56.926] thr=2   paramiko.transport: Adding ssh-rsa host key for xxxxxxx: b'yyyyyyy'
DEB [20221004-11:00:56.930] thr=1   paramiko.transport: userauth is OK
INF [20221004-11:00:57.103] thr=1   paramiko.transport: Authentication (password) successful!
DEB [20221004-11:00:57.104] thr=2   paramiko.transport: [chan 0] Max packet in: 32768 bytes
DEB [20221004-11:00:57.106] thr=1   paramiko.transport: [chan 0] Max packet out: 32768 bytes
DEB [20221004-11:00:57.107] thr=1   paramiko.transport: Secsh channel 0 opened.
DEB [20221004-11:00:57.115] thr=1   paramiko.transport: [chan 0] Sesch channel 0 request ok
DEB [20221004-11:00:57.510] thr=1   paramiko.transport: [chan 0] EOF received (0)
DEB [20221004-11:00:57.511] thr=1   paramiko.transport: EOF in transport thread
DEB [20221004-11:00:57.520] thr=2   paramiko.transport: [chan 0] EOF sent (0)
DEB [20221004-11:00:57.520] thr=2   paramiko.transport: Dropping user packet because connection is dead.
```
with added censorship.

paramiko.log for 2.7.0 (bad):
```
DEB [20221004-10:54:01.763] thr=1   paramiko.transport: starting thread (client mode): 0x91d05340
DEB [20221004-10:54:01.764] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.7.0
DEB [20221004-10:54:01.956] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-Cisco-2.0
INF [20221004-10:54:01.956] thr=1   paramiko.transport: Connected (version 2.0, client Cisco-2.0)
DEB [20221004-10:54:01.959] thr=1   paramiko.transport: kex algos:['ecdh-sha2-nistp521', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp256', 'diffie-hellman-group14-sha1'] server key:['ssh-dss', 'rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] server mac:['hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEB [20221004-10:54:01.959] thr=1   paramiko.transport: Kex agreed: ecdh-sha2-nistp256
DEB [20221004-10:54:01.959] thr=1   paramiko.transport: HostKey agreed: ssh-rsa
DEB [20221004-10:54:01.960] thr=1   paramiko.transport: Cipher agreed: aes128-ctr
DEB [20221004-10:54:01.960] thr=1   paramiko.transport: MAC agreed: hmac-sha2-256
DEB [20221004-10:54:01.960] thr=1   paramiko.transport: Compression agreed: none
DEB [20221004-10:54:02.178] thr=1   paramiko.transport: kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEB [20221004-10:54:02.179] thr=1   paramiko.transport: Switch to new keys ...
DEB [20221004-10:54:02.180] thr=2   paramiko.transport: Adding ssh-rsa host key for xxxxxx: b'xxxxxx'
DEB [20221004-10:54:02.184] thr=2   paramiko.transport: Trying discovered key b'yyyyyy' in /home/sysadmin/.ssh/id_rsa
DEB [20221004-10:54:02.187] thr=1   paramiko.transport: userauth is OK
DEB [20221004-10:54:02.222] thr=1   paramiko.transport: EOF in transport thread
```
with added censorship.

I noticed these was a tentative to use a id_rsa in ~/.ssh. So I added the `look_for_keys=False` option to 2.7.0 (better!):
```
...
...
... Tue Oct  4 11:04:15.256 CEST
... Cisco IOS XR Software, Version 7.4.2
... Copyright (c) 2013-2022 by Cisco Systems, Inc.
...
... Build Information:
...  Built By     : ingunawa
...  Built On     : Wed Feb 16 03:23:21 PST 2022
...  Built Host   : iox-ucs-067
...  Workspace    : /auto/srcarchive15/prod/7.4.2/ncs5500/ws
...  Version      : 7.4.2
...  Location     : /opt/cisco/XR/packages/
...  Label        : 7.4.2
...
... cisco NCS-5500 () processor
... System uptime is 1 week 1 day 26 minutes
...
Exception ignored in: <function BufferedFile.__del__ at 0x7f7753bd4a60>
Traceback (most recent call last):
  File "/home/sysadmin/.pyenv/versions/paramiko/lib/python3.8/site-packages/paramiko/file.py", line 66, in __del__
  File "/home/sysadmin/.pyenv/versions/paramiko/lib/python3.8/site-packages/paramiko/channel.py", line 1392, in close
  File "/home/sysadmin/.pyenv/versions/paramiko/lib/python3.8/site-packages/paramiko/channel.py", line 991, in shutdown_write
  File "/home/sysadmin/.pyenv/versions/paramiko/lib/python3.8/site-packages/paramiko/channel.py", line 963, in shutdown
  File "/home/sysadmin/.pyenv/versions/paramiko/lib/python3.8/site-packages/paramiko/channel.py", line 1248, in _send_eof
  File "/home/sysadmin/.pyenv/versions/paramiko/lib/python3.8/site-packages/paramiko/channel.py", line 1212, in _log
  File "/home/sysadmin/.pyenv/versions/3.8.13/lib/python3.8/logging/__init__.py", line 1512, in log
  File "/home/sysadmin/.pyenv/versions/3.8.13/lib/python3.8/logging/__init__.py", line 1589, in _log
  File "/home/sysadmin/.pyenv/versions/3.8.13/lib/python3.8/logging/__init__.py", line 1598, in handle
  File "/home/sysadmin/.pyenv/versions/3.8.13/lib/python3.8/logging/__init__.py", line 811, in filter
  File "/home/sysadmin/.pyenv/versions/paramiko/lib/python3.8/site-packages/paramiko/util.py", line 266, in filter
TypeError: 'NoneType' object is not callable
```
NB: 2.8.1 and 2.11.0 yields similar outputs.
associated 2.7.0 paramiko.log:
```
DEB [20221004-11:04:14.351] thr=1   paramiko.transport: starting thread (client mode): 0x525f3340
DEB [20221004-11:04:14.352] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.7.0
DEB [20221004-11:04:14.544] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-Cisco-2.0
INF [20221004-11:04:14.544] thr=1   paramiko.transport: Connected (version 2.0, client Cisco-2.0)
DEB [20221004-11:04:14.547] thr=1   paramiko.transport: kex algos:['ecdh-sha2-nistp521', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp256', 'diffie-hellman-group14-sha1'] server key:['ssh-dss', 'rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] server mac:['hmac-sha2-512', 'hmac-sha2-256', 'hmac-sha1'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEB [20221004-11:04:14.547] thr=1   paramiko.transport: Kex agreed: ecdh-sha2-nistp256
DEB [20221004-11:04:14.547] thr=1   paramiko.transport: HostKey agreed: ssh-rsa
DEB [20221004-11:04:14.548] thr=1   paramiko.transport: Cipher agreed: aes128-ctr
DEB [20221004-11:04:14.548] thr=1   paramiko.transport: MAC agreed: hmac-sha2-256
DEB [20221004-11:04:14.548] thr=1   paramiko.transport: Compression agreed: none
DEB [20221004-11:04:14.765] thr=1   paramiko.transport: kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEB [20221004-11:04:14.766] thr=1   paramiko.transport: Switch to new keys ...
DEB [20221004-11:04:14.768] thr=2   paramiko.transport: Adding ssh-rsa host key for xxxxx: b'yyyyy'
DEB [20221004-11:04:14.771] thr=1   paramiko.transport: userauth is OK
INF [20221004-11:04:14.945] thr=1   paramiko.transport: Authentication (password) successful!
DEB [20221004-11:04:14.946] thr=2   paramiko.transport: [chan 0] Max packet in: 32768 bytes
DEB [20221004-11:04:14.948] thr=1   paramiko.transport: [chan 0] Max packet out: 32768 bytes
DEB [20221004-11:04:14.949] thr=1   paramiko.transport: Secsh channel 0 opened.
DEB [20221004-11:04:14.958] thr=1   paramiko.transport: [chan 0] Sesch channel 0 request ok
DEB [20221004-11:04:15.332] thr=1   paramiko.transport: [chan 0] EOF received (0)
DEB [20221004-11:04:15.333] thr=1   paramiko.transport: EOF in transport thread
```

Using the [associated option](https://docs.ansible.com/ansible/latest/collections/ansible/netcommon/netconf_connection.html#parameter-look_for_keys) in my ansible.cfg solved the problem there as well.

So it seems that the Cisco ssh server implementation closes the channel when the first authentication try with the id_rsa (used for other purposes in our case) fails. I will report that to their support.

Thank you for your logging instruction, and I hope this will help others as well.
