### ISSUE TITLE
TCP forwarding request denied 

### ISSUE THREAD

**Issue by 1337kingOf** [paramiko/paramiko#2133]
What the piece of sheet i tried every port and its keep saying TCP forwarding request denied
(venv) andreupupkin@Andreus-MacBook-Pro tcpClient % python rforward.py 192.168.1.242 -p 8081 -r 127.0.0.1:3000 --user=1 --password
Enter SSH password: 
Connecting to ssh host 192.168.1.242:22 ...
/Users/andreupupkin/PycharmProjects/tcpClient/venv/lib/python3.10/site-packages/paramiko/client.py:837: UserWarning: Unknown ssh-rsa host key for 192.168.1.242: b'60733844cb5186657fdedaa22b5a57d5'
  warnings.warn(
Now forwarding remote port 8081 to 127.0.0.1:3000 ...
Traceback (most recent call last):
  File "/Users/andreupupkin/PycharmProjects/tcpClient/rforward.py", line 230, in <module>
    main()
  File "/Users/andreupupkin/PycharmProjects/tcpClient/rforward.py", line 221, in main
    reverse_forward_tunnel(
  File "/Users/andreupupkin/PycharmProjects/tcpClient/rforward.py", line 75, in reverse_forward_tunnel
    transport.request_port_forward("", server_port)
  File "/Users/andreupupkin/PycharmProjects/tcpClient/venv/lib/python3.10/site-packages/paramiko/transport.py", line 1104, in request_port_forward
    raise SSHException("TCP forwarding request denied")
paramiko.ssh_exception.SSHException: TCP forwarding request denied

**Comment by jun66j5** [comment]
That is not a paramiko issue.

Your remote server rejects tcpip-forward request. Check log file and configuration file of your remote server.

**Comment by 1337kingOf** [comment]
import os
import paramiko
import socket
import sys
import threading

CWD = os.path.dirname(os.path.realpath(__file__))
HOSTKEY = paramiko.RSAKey(filename=os.path.join(CWD, 'test_rsa.key'))



class Server(paramiko.ServerInterface):
    def __init__(self):
        self.event = threading.Event()

    def check_channel_request(self, kind, chanid):
        if kind == 'session':
            return paramiko.OPEN_SUCCEEDED
        return paramiko.OPEN_FAILED_ADMINISTRATIVELY_PROHIBITED

    def check_auth_password(self, username, password):
        if (username == 'tim') and (password == '1'):
            return paramiko.AUTH_SUCCESSFUL


if __name__ == '__main__':
    server = '192.168.1.56'
    ssh_port = 22
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.bind((server, ssh_port))
        sock.listen(100)
        print('[+] Listening for connection ...')
        client, addr = sock.accept()
    except Exception as e:
        print('[-] Listen failed: ' + str(e))
        sys.exit(1)
    else:
        print(f'[+] Got a connection! from {addr}')

    bhSession = paramiko.Transport(client)
    bhSession.add_server_key(HOSTKEY)
    server = Server()
    bhSession.start_server(server=server)

    chan = bhSession.accept(20)
    if chan is None:
        print('*** No channel.')
        sys.exit(1)

    print('[+] Authenticated!')
    print(chan.recv(1024).decode())
    chan.send('Welcome to bh_ssh')
    try:
        while True:
            command = input("Enter command: ")
            if command != 'exit':
                chan.send(command)
                r = chan.recv(8192)
                print(r.decode())
            else:
                chan.send('exit')
                print('exiting')
                bhSession.close()
                break
    except KeyboardInterrupt:
        bhSession.close()
 
its my server, i think there problem with my pc, i have tried do it on 3 different pc

> That is not a paramiko issue.
> 
> Your remote server rejects tcpip-forward request. Check log file and configuration file of your remote server.

**Comment by jun66j5** [comment]
Have you checked log and configuration on the `192.168.1.56` server?

If unable to check/find the cause, provide debug log of paramiko when reqesting port forward, using `paramiko.util.log_to_file()`.

**Comment by 1337kingOf** [comment]
> Have you checked log and configuration on the `192.168.1.56` server?
> 
> If unable to check/find the cause, provide debug log of paramiko when reqesting port forward, using `paramiko.util.log_to_file()`.

How can i check it, do u have guide?

**Comment by jun66j5** [comment]
> How can i check it, do u have guide?

That is dependent on your ssh server and its version. What are you using the server and its version?

Anyway, please provide debug log of paramiko and the details (about server, paramiko version, etc.) if you want support.

**Comment by jun66j5** [comment]
p.s. I recommend using code block for script, log text, .... See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code.

**Comment by 1337kingOf** [comment]
`import os
import paramiko
import socket
import sys
import threading

CWD = os.path.dirname(os.path.realpath(__file__))
HOSTKEY = paramiko.RSAKey(filename=os.path.join(CWD, 'test_rsa.key'))



class Server(paramiko.ServerInterface):
    def __init__(self):
        self.event = threading.Event()

    def check_channel_request(self, kind, chanid):
        if kind == 'session':
            return paramiko.OPEN_SUCCEEDED
        return paramiko.OPEN_FAILED_ADMINISTRATIVELY_PROHIBITED

    def check_auth_password(self, username, password):
        if (username == '1') and (password == '2'):
            return paramiko.AUTH_SUCCESSFUL


if __name__ == '__main__':
    server = '192.168.1.56'
    ssh_port = 22
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.bind((server, ssh_port))
        sock.listen(100)
        print('[+] Listening for connection ...')
        client, addr = sock.accept()
    except Exception as e:
        print('[-] Listen failed: ' + str(e))
        sys.exit(1)
    else:
        print(f'[+] Got a connection! from {addr}')

    bhSession = paramiko.Transport(client)
    bhSession.add_server_key(HOSTKEY)
    server = Server()
    bhSession.start_server(server=server)

    chan = bhSession.accept(20)
    if chan is None:
        print('*** No channel.')
        sys.exit(1)

    print('[+] Authenticated!')
    print(chan.recv(1024).decode())
    chan.send('Welcome to bh_ssh')
    try:
        while True:
            command = input("Enter command: ")
            if command != 'exit':
                chan.send(command)
                r = chan.recv(8192)
                print(r.decode())
            else:
                chan.send('exit')
                print('exiting')
                bhSession.close()
                break
    except KeyboardInterrupt:
        bhSession.close()
`
its my ssh server 

> p.s. I recommend using code block for script, log text, .... See [Quoting code](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by 1337kingOf** [comment]
Where can i get this log?

**Comment by jun66j5** [comment]
You must provide the details which you've tried.

Add `paramiko.util.log_to_file('/tmp/paramiko.log')` after `import paramiko` line in your script.

**Comment by 1337kingOf** [comment]
[rforward.log](https://github.com/paramiko/paramiko/files/9895646/rforward.log)
[ssh_server.log](https://github.com/paramiko/paramiko/files/9895647/ssh_server.log)

**Comment by jun66j5** [comment]
The remote server is paramiko 2.11.0, logged in rforward.log.

```
DEB [20221030-12:55:09.438] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.11.0
DEB [20221030-12:55:09.438] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-paramiko_2.11.0
```

The reason of tcpip-forward request denied is lack of [ServerInterface.check_port_forward_request](https://docs.paramiko.org/en/stable/api/server.html#paramiko.server.ServerInterface.check_port_forward_request) implementation in your ssh server. I recommend you read [Server implementation](https://docs.paramiko.org/en/stable/api/server.html) page carefully if you want to make ssh server with paramiko.

**Comment by 1337kingOf** [comment]
> 

plz can u tell me, what i have to do , i want to fix this problem

**Comment by jun66j5** [comment]
I found the same question for `check_port_forward_request` in #561, but not answered yet.

**Comment by 1337kingOf** [comment]
> #561
is there problem with my os,or python version?

**Comment by jun66j5** [comment]
> is there problem with my os,or python version?

I've commented that the reason of tcpip-forward request denied is lack of check_port_forward_request implementation in your server. Have you read comments?

The check_port_forward_request and cancel_port_forward_request methods should be implemented to serve remote port forward with paramiko.

Also, I recommend using openssh as a client rather than paramiko, when implementing ssh server.

#### check_port_forward_request

1. Create a socket, bind with `address` and `port` parameters, and listen.
2. Accept new connection from the listened socket.
3. Retrieve new channel using `open_forwarded_tcpip_channel`.
4. Read data from the accepted connection and write the data to the channel until the connection is closed.
5. Read data from the channel and write the data to the accepted connection until the channel is closed.

#### cancel_port_forward_request

1. Close the socket which is created in `check_port_forward_request`.

**Comment by 1337kingOf** [comment]
> > is there problem with my os,or python version?
> 
> I've commented that the reason of tcpip-forward request denied is lack of check_port_forward_request implementation in your server. Have you read comments?
> 
> The check_port_forward_request and cancel_port_forward_request methods should be implemented to serve remote port forward with paramiko.
> 
> Also, I recommend using openssh as a client rather than paramiko, when implementing ssh server.
> 
> #### check_port_forward_request
> 1. Create a socket, bind with `address` and `port` parameters, and listen.
> 2. Accept new connection from the listened socket.
> 3. Retrieve new channel using `open_forwarded_tcpip_channel`.
> 4. Read data from the accepted connection and write the data to the channel until the connection is closed.
> 5. Read data from the channel and write the data to the accepted connection until the channel is closed.
> 
> #### cancel_port_forward_request
> 1. Close the socket which is created in `check_port_forward_request`.

have u given me advice to write this methods myself?

**Comment by jun66j5** [comment]
> have u given me advice to write this methods myself?

Yes, of course. Only you can implement what you want for yourself.
