### ISSUE TITLE
Hangs indefinitely when calling `SSHClient`'s `connect()`

### ISSUE THREAD

**Issue by shreyamalviya** [paramiko/paramiko#2147]
When running the following, it hangs indefinitely. I have to send it a keyboard interrupt to get it to stop.
```python
import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.WarningPolicy())
ssh.connect("10.2.2.11", username=username, password=password, timeout=15)
```

The output of this:
```
/home/shreya_malviya/.local/lib/python3.7/site-packages/paramiko/client.py:854: UserWarning: Unknown ssh-ed25519 host key for 10.2.2.11: b'redacted'
  key.get_name(), hostname, hexlify(key.get_fingerprint())
^CTraceback (most recent call last):
  File "x.py", line 11, in <module>
    ssh.connect("10.2.2.11", username=username, password=password, timeout=15)
  File "/home/shreya_malviya/.local/lib/python3.7/site-packages/paramiko/client.py", line 461, in connect
    passphrase,
  File "/home/shreya_malviya/.local/lib/python3.7/site-packages/paramiko/client.py", line 708, in _auth
    self._agent = Agent()
  File "/home/shreya_malviya/.local/lib/python3.7/site-packages/paramiko/agent.py", line 393, in __init__
    self._connect(conn)
  File "/home/shreya_malviya/.local/lib/python3.7/site-packages/paramiko/agent.py", line 77, in _connect
    ptype, result = self._send_message(cSSH2_AGENTC_REQUEST_IDENTITIES)
  File "/home/shreya_malviya/.local/lib/python3.7/site-packages/paramiko/agent.py", line 96, in _send_message
    msg = Message(self._read_all(struct.unpack(">I", data)[0]))
  File "/home/shreya_malviya/.local/lib/python3.7/site-packages/paramiko/agent.py", line 104, in _read_all
    extra = self._conn.recv(wanted - len(result))
KeyboardInterrupt
```

Python 3.7
Paramiko 2.10.3

**Comment by jun66j5** [comment]
In this case, paramiko is waiting for response from your ssh agent. If you don't want to use the ssh agent, pass `allow_agent=False` to disable it.


```diff
-ssh.connect("10.2.2.11", username=username, password=password, timeout=15)
+ssh.connect("10.2.2.11", username=username, password=password, timeout=15, allow_agent=False)
```

**Comment by shreyamalviya** [comment]
Thanks!

**Comment by shreyamalviya** [comment]
Update for anyone interested: I was running into this issue on Ubuntu with ssh-agent not running. I noticed that `ssh-add -l` was giving me "error fetching identities: invalid format". Starting the agent, killing the process, and then running `ssh-add -l` gave me "Error connecting to agent: Connection refused", after which the paramiko script worked.

```bash
shreya_malviya@island-linux-250:~$ # ssh-agent is not running at this point
shreya_malviya@island-linux-250:~$ ssh-add -l
error fetching identities: invalid format
shreya_malviya@island-linux-250:~$ eval `ssh-agent`
Agent pid 2549
shreya_malviya@island-linux-250:~$ ssh-add -l
The agent has no identities.
shreya_malviya@island-linux-250:~$ kill -9 2549
shreya_malviya@island-linux-250:~$ ssh-add -l
Error connecting to agent: Connection refused
```

**Comment by bskinn** [comment]
@shreyamalviya, if your problem is resolved, please go ahead and close the issue...thanks!
