### ISSUE TITLE
Race condition while garbage collection results in ignored exception

### ISSUE THREAD

**Issue by lokesh2019** [paramiko/paramiko#2153]
When an ssh command fails on server end, the connection is closed and the stdin, stdout, stderr file descriptors are garbage collected. Due to some race condition, I get the stack trace below once for every ~10 runs of same command in a loop.
```
Exception ignored in: <function BufferedFile.__del__ at 0x7f7e9c621990>
Traceback (most recent call last):
  File "/opt/nfast/python3/lib/python3.10/site-packages/paramiko/file.py", line 66, in __del__
    self.close()
  File "/opt/nfast/python3/lib/python3.10/site-packages/paramiko/file.py", line 84, in close
    self.flush()
  File "/opt/nfast/python3/lib/python3.10/site-packages/paramiko/file.py", line 92, in flush
    self._write_all(self._wbuffer.getvalue())
ValueError: I/O operation on closed file.
```

Originally observed on Paramiko version 2.7.1, but the same code exists on version 2.12.0 and `main` branch.
Fix is to add a `if not self._wbuffer.closed` before this line: https://github.com/paramiko/paramiko/blob/main/paramiko/file.py#L92
Also not sure what this line achieves but it is harmless: https://github.com/paramiko/paramiko/blob/main/paramiko/file.py#L93

While I was investigating the issue, I noticed another potential improvement to the two `_write()` methods here to avoid potential race conditions: https://github.com/paramiko/paramiko/blob/main/paramiko/channel.py#L1363 and at line 1378.
Something like this would prevent similar race conditions between clean up of Channel and ChannelFile objects:
```
    def _write(self, data):
        self.channel.lock.acquire()
        try:
            if not self.channel.active or self.channel.closed:
                return
            self.channel.sendall(data)
            return len(data)
        finally:
            self.channel.lock.release()
```
Comments welcome on suggested fixes. If not, I'll raise a PR with suggested changes next week.

**Comment by bitprophet** [comment]
Thanks for this! Quick comments:

- race conditions at cleanup time are a really long-lived class of issue in this repo; there are very likely to be existing PRs or tickets about one or both of these problem spots. Can you (or @bskinn?) please search around a bit first to make sure a new PR isn't duplicative?
- similarly, one reason this issue type _is_ long lived is because a lot of folks keep submitting fixes that have their own bugs - ie they fix the identified symptom/usecase but just kick the can around to another usecase instead. This has made me pretty allergic to "simple" "fixes" in most of the threading lock stuff :(
  - one method to help overcome this allergy: brainstorm some tests proving the bugs exist (which fail w/o the fix in place, eg by artificially inducing the race condition, and then of course pass with the fix in place - basic "I wrote a test with the fix already committed, and the test passed! yay!" won't cut it :D)
  -  this still counts as a useful task you could tackle even if other PRs exist for these same lines of code - those PRs probably don't have any tests, as most lack them 😭
