### ISSUE TITLE
The 3.0.0 version of paramiko.transport will immediately create a session

### ISSUE THREAD

**Issue by wnark** [paramiko/paramiko#2190]
version:3.0.0
![image](https://user-images.githubusercontent.com/24355466/220870470-baf11cfb-316b-4af0-929b-0b5688b2fa6a.png)

For paramiko version 3.0.0, a session will be created immediately when using paramiko.transport, instead of creating a connection when using the connect method as mentioned in the description.
![image](https://user-images.githubusercontent.com/24355466/220871156-ea795d86-4db4-4cc5-9aba-74fb4830a158.png)

**Comment by bskinn** [comment]
@wnark -- can you copy that REPL session into a fenced code block as another comment in this issue, for easier reference? It's hard & inconvenient to read out of that screenshot.

To confirm: this misbehavior is new in 3.0? 2.x worked as expected?

**Comment by wnark** [comment]
@bskinn
Sorry, I haven't used the 2.x version so far。
The code prompt is as follows：
```
class Transport(
    sock: _SocketLike,
    default_window_size: int = ...,
    default_max_packet_size: int = ...,
    gss_kex: bool = ...,
    gss_deleg_creds: bool = ...,
    disabled_algorithms: dict[str, Iterable[str]] | None = ...,
    server_sig_algs: bool = ...
)
Create a new SSH session over an existing socket, or socket-like object. This only creates the .Transport object; it doesn't begin the SSH session yet. Use connect or start_client to begin a client session, or start_server to begin a server session.

If the object is not actually a socket, it must have the following methods:

send(bytes): Writes from 1 to len(bytes) bytes, and returns an int representing the number of bytes written. Returns 0 or raises EOFError if the stream has been closed.
recv(int): Reads from 1 to int bytes and returns them as a string. Returns 0 or raises EOFError if the stream has been closed.
close(): Closes the socket.
settimeout(n): Sets a (float) timeout on I/O operations.
For ease of use, you may also pass in an address (as a tuple) or a host string as the sock argument. (A host string is a hostname with an
optional port (separated by ":") which will be converted into a tuple of (hostname, port).) A socket will be connected to this address and used for communication. Exceptions from the socket call may be thrown in this case.

:param socket sock:
    a socket or socket-like object to create the session over.
:param int default_window_size:
    sets the default window size on the transport. (defaults to 2097152)
:param int default_max_packet_size:
    sets the default max packet size on the transport. (defaults to 32768)
:param bool gss_kex:
    Whether to enable GSSAPI key exchange when GSSAPI is in play.
    Default: False.
:param bool gss_deleg_creds:
    Whether to enable GSSAPI credential delegation when GSSAPI is in
    play. Default: True.
:param dict disabled_algorithms:
    If given, must be a dictionary mapping algorithm type to an iterable of algorithm identifiers, which will be disabled for the lifetime of the transport.

    Keys should match the last word in the class' builtin algorithm tuple attributes, such as "ciphers" to disable names within _preferred_ciphers; or "kex" to disable something defined inside _preferred_kex. Values should exactly match members of the matching attribute.

    For example, if you need to disable diffie-hellman-group16-sha512 key exchange (perhaps because your code talks to a server which implements it differently from Paramiko), specify disabled_algorithms={"kex": ["diffie-hellman-group16-sha512"]}.
:param bool server_sig_algs:
    Whether to send an extra message to compatible clients, in server mode, with a list of supported pubkey algorithms. Default: True.
```

**Comment by wnark** [comment]
The error code is as follows:
```
>>> import paramiko
>>> trans=paramiko.Transport("1.0.0.1",22)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/reboot_check_dropped/venv/lib/python3.11/site-packages/paramiko/transport.py", line 444, in __init__
    raise SSHException(
paramiko.ssh_exception.SSHException: Unable to connect to 1.0.0.1: [Errno 110] Connection timed out
>>> 
```

**Comment by bskinn** [comment]
Is the `22` in your code snippet meant to tell the `Transport` that it should use port 22?

If so, I don't think that's correct usage. For that, I think you need to either pass the single string `"1.0.0.1:22"`, or pass an explicit tuple:

```
trans = paramiko.Transport(("1.0.0.1", 22))
```

Note the doubled parentheses.

The way you've written it, I'm pretty sure that second argument of `22` is actually being interpreted as the `default_window_size` argument, if I read the docstring right...and that may be what's triggering the `Transport` to create the session?

**Comment by wnark** [comment]
@bskinn 
You're right. I'm not using it correctly.
But when I use a tuple or string pass, it still tries to connect at the first initialization.
```
>>> import paramiko
>>> trans=paramiko.Transport(("1.0.0.1",22))                         
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/reboot_check_dropped/venv/lib/python3.11/site-packages/paramiko/transport.py", line 444, in __init__
    raise SSHException(
paramiko.ssh_exception.SSHException: Unable to connect to 1.0.0.1: [Errno 110] Connection timed out
>>> 
>>> trans=paramiko.Transport("1.0.0.1:22")                     
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/reboot_check_dropped/venv/lib/python3.11/site-packages/paramiko/transport.py", line 444, in __init__
    raise SSHException(
paramiko.ssh_exception.SSHException: Unable to connect to 1.0.0.1: [Errno 110] Connection timed out
>>> 
```

**Comment by bskinn** [comment]
> But when I use a tuple or string pass, it still tries to connect at the first initialization.

Indeed, that definitely doesn't look right -- flagging for attention.

**Comment by bskinn** [comment]
Do you have the ability to test if it still happens on `<3.0`, @wnark? It would be helpful to know if this is a 3.0 regression, or something carried over from 2.x.

**Comment by wnark** [comment]
@bskinn 
Hello, when I use version 2.12.0, there is still this situation:
```
(venv) C:\Users\ZETTAKIT\Downloads\1>pip list
Package      Version
------------ -------
bcrypt       4.0.1
cffi         1.15.1
cryptography 39.0.1
paramiko     2.12.0
pip          23.0
pycparser    2.21
PyNaCl       1.5.0
setuptools   65.5.0
six          1.16.0
wheel        0.38.4

[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) C:\Users\ZETTAKIT\Downloads\1>trans = paramiko.Transport(("1.0.0.1", 22))
'trans' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

(venv) C:\Users\ZETTAKIT\Downloads\1>python
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> trans = paramiko.Transport(("1.0.0.1", 22))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'paramiko' is not defined
>>> import paramiko
>>> trans = paramiko.Transport(("1.0.0.1", 22))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ZETTAKIT\Downloads\1\venv\lib\site-packages\paramiko\transport.py", line 441, in __init__
    raise SSHException(
paramiko.ssh_exception.SSHException: Unable to connect to 1.0.0.1: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
>>> trans=paramiko.Transport("1.0.0.1:22")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ZETTAKIT\Downloads\1\venv\lib\site-packages\paramiko\transport.py", line 441, in __init__
    raise SSHException(
paramiko.ssh_exception.SSHException: Unable to connect to 1.0.0.1: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
>>>
```

![image](https://user-images.githubusercontent.com/24355466/222307964-5650bd7e-98d5-414b-99f5-f25fd717352d.png)

**Comment by bskinn** [comment]
Very helpful to know, thank you for testing, @wnark!

**Comment by jun66j5** [comment]
I don't think that's a paramiko issue. It is working properly.

Make sure you can connect to the server using curl or ssh in your environment, before suspecting paramiko.

The curl and ssh raise the same error as well.

Why are you connecting to 1.0.0.1:22? (1.0.0.1 is Cloudflare DNS). Is the connection destination correct?

```
C> curl -v telnet://1.0.0.1:22/
*   Trying 1.0.0.1:22...
* connect to 1.0.0.1 port 22 failed: Timed out
* Failed to connect to 1.0.0.1 port 22 after 21076 ms: Timed out
* Closing connection 0
curl: (28) Failed to connect to 1.0.0.1 port 22 after 21076 ms: Timed out
```

```
C> ssh -vvv -p 22 1.0.0.1
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug3: Failed to open file:C:/Users/<username>/.ssh/config error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolve_canonicalize: hostname 1.0.0.1 is address
debug2: ssh_connect_direct
debug1: Connecting to 1.0.0.1 [1.0.0.1] port 22.
debug3: finish_connect - ERROR: async io completed with error: 10060, io:0000014239142290
debug1: connect to address 1.0.0.1 port 22: Connection timed out
ssh: connect to host 1.0.0.1 port 22: Connection timed out
```

```
C> paramiko\Scripts\python -m pip list
Package      Version
------------ -------
bcrypt       4.0.1
cffi         1.15.1
cryptography 39.0.1
paramiko     3.0.0
pip          23.0.1
pycparser    2.21
PyNaCl       1.5.0
setuptools   57.4.0

C> paramiko\Scripts\python -c "import paramiko; paramiko.Transport('1.0.0.1:22')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\usr\tmp\paramiko\lib\site-packages\paramiko\transport.py", line 444, in __init__
    raise SSHException(
paramiko.ssh_exception.SSHException: Unable to connect to 1.0.0.1: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

**Comment by bskinn** [comment]
@jun66j5 The problem isn't the failure to connect.

It's the creation of the session and attempt to connect prior to `trans.connect()` (or similar) being called.

**Comment by bskinn** [comment]
The docs indicate that initializing `Transport` should not create the session.

**Comment by jun66j5** [comment]
> It's the creation of the session and attempt to connect prior to `trans.connect()` (or similar) being called.

The `Transport` constructor requires `socket` instance or server address (a string or a pair of address and port). When server address is passed, it connects to the server (using socket.connect). The "session" is an ssh's session (aka channel), it just connects but doesn't create a session.

**Comment by wnark** [comment]
> > It's the creation of the session and attempt to connect prior to `trans.connect()` (or similar) being called.
> 
> The `Transport` constructor requires `socket` instance or server address (a string or a pair of address and port). When server address is passed, it connects to the server (using socket.connect). The "session" is an ssh's session, it just connects but doesn't create a session. It is need to invoke `Trasnport.start_client` to start an ssh's session.

You are right, I tried again, when the port is open, is the normal configuration, in this step may be similar to try to check whether the tcp port is open? Instead of using the ssh protocol to connect/check.
It's only later when using connect that you try to connect by ssh.
Thank you for your reply
```
[root@f3 reboot_check_dropped]# source /root/reboot_check_dropped/venv/bin/activate
(venv) [root@f3 reboot_check_dropped]# python
Python 3.11.2 (main, Feb 13 2023, 16:01:03) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> trans = paramiko.Transport(("1.0.0.0",443))            
>>> 
```

**Comment by bitprophet** [comment]
Thanks everyone for troubleshooting this! 🙌🏻
