### ISSUE TITLE
OSError when stablishing SSH connection

### ISSUE THREAD

**Issue by ebersaj** [paramiko/paramiko#2210]
Hi!

I'm running a Python script inside an Azure Automation account that's supposed to send some data through an SFTP connection using the `paramiko` package.

The script runs just fine when executing in my computer. But when executing in the cloud environment, I get the following error when trying to stablish an SSH connection using the `ssh.connect()` function call.

```
Traceback (most recent call last):
  File "C:\Temp\vjtgkdb0.eh1\xxxxxxx", line 587, in <module>
    generate_files()
  File "C:\Temp\xxxxx", line 50, in generate_files
    ssh.connect(hostname=ftp_host, port=ftp_port, username=ftp_user, password=ftp_pwd)
  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\paramiko\client.py", line 459, in connect
    self._auth(
  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\paramiko\client.py", line 717, in _auth
    self._agent = Agent()
  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\paramiko\agent.py", line 403, in __init__
    conn = get_agent_connection()
  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\paramiko\agent.py", line 230, in get_agent_connection
    elif win_openssh.can_talk_to_agent():
  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\paramiko\win_openssh.py", line 32, in can_talk_to_agent
    return any(name == n.lower() for n in os.listdir(dir_)
OSError: [WinError 1] Incorrect function: '\\\\.\\pipe\\'
```

This is the code I'm using to stablish the connection.

```
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(hostname=ftp_host, port=ftp_port, username=ftp_user, password=ftp_pwd)
```

Does anyone have any idea on how I can solve it?

Thanks in advance

**Comment by jun66j5** [comment]
I'm unsure why the error is raised, but as a workaround try passing `allow_agent=False` to `SSHClient.connect()`.

**Comment by ebersaj** [comment]
It worked. Thanks a lot!
