### ISSUE TITLE
Permission denied error when trying to connect 

### ISSUE THREAD

**Issue by SclerA-prog** [paramiko/paramiko#2212]
I have implemented a reverse ssh tunnel successfully using get_transport method from remote machine to local machine. But when I try to connect to the tunnel from a local machine. It is giving me a permission denied error. But when I try to connect manually, there are no issues. So it has something to do with the paramiko.

**Comment by jun66j5** [comment]
I suspect that is due to your script. Please share the script and the raised errors.

**Comment by SclerA-prog** [comment]
ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

        # Connect to the remote host using SSH
        #

        
        while True:
            ssh.connect('host address', username='user', password='password')

        # Set up a reverse SSH tunnel from the remote host to the local host
        # ssh.exec_command(f'ssh -R {remote_port}:localhost:{local_port} {server} -f')

            reverse_tunnel = ssh.get_transport().request_port_forward('', 1300, handle_forwarded_port)
            if(ssh.get_transport().is_active()):
                print("connected")
            else:
                print("not connected")
            try:
                # Send a keepalive message to the remote hocst
                ssh.exec_command('echo "keepalive"')
            except:
                # If an exception occurs, close the SSH connection and exit the loop
                ssh.close()
                break
            time.sleep(1)

**Comment by jun66j5** [comment]
You said "It is giving me a permission denied error". Please describe the detail of the error and where the error is raised from, post log message of the error.

It seems that `request_port_forward` is invoked twice and the 2nd invoke failed.
```
$ /dev/shm/paramiko-venv/bin/python /dev/shm/issue2212.py
connected
Traceback (most recent call last):
  File "/dev/shm/issue2212.py", line 17, in <module>
    reverse_tunnel = ssh.get_transport().request_port_forward('', 1300)
  File "/home/jun66j5/src/paramiko/paramiko/transport.py", line 1104, in request_port_forward
    raise SSHException("TCP forwarding request denied")
paramiko.ssh_exception.SSHException: TCP forwarding request denied
```

If you want to do remote port forwarding, demos/rforward.py should be more useful than writing your own.

**Comment by SclerA-prog** [comment]
Yeah this also happend. But then I was able to create tunnel successfully. But after creating the tunnel. When I try to connect to the remote machine by local machine, it is showing permission denied error

**Comment by jun66j5** [comment]
Your script is wrong. Instead, try demos/rforward.py.
