### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by rustyscottweber** [paramiko/paramiko#2232]
I get the following exception spammed to the console while attempting to connect to an ssh server which has just started on a machine which has just rebooted.

```
Exception (client): Error reading SSH protocol banner[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2270, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/lib/python3/dist-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/usr/lib/python3/dist-packages/paramiko/packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2093, in run
    self._check_banner()
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2274, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
Exception (client): Error reading SSH protocol banner[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2270, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/lib/python3/dist-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/usr/lib/python3/dist-packages/paramiko/packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer
```

This sometimes continues for 20+ minutes until 1 of 3 things happen.
1. I get lucky and things start working on their own.
2. I break into the program to debug it and the pause in the program allows some timeouts to expire which causes the next time a transport thread to be spawned to succeed.
3. I kill the program.

I'm not sure what the best policy is to fix this.

**Comment by jstnfst** [comment]
So paramiko is spamming your logs with errors? Just ignore them! 
```python
### NOTE: here's the workaround
import os
# anything that running this program prints to stderr should be
# redirected to /dev/null
os.dup2(os.open(os.devnull, os.O_WRONLY), 2)
```
Just add this code because paramiko runs on a different thread and you can't prevent it from printing those errors to stderr.

**Comment by bskinn** [comment]
Closing this issue for now. @rustyscottweber, if you still require assistance, please reopen and comment with any updates.
