### ISSUE TITLE
paramiko.ssh_exception.SSHException: Invalid key

### ISSUE THREAD

**Issue by cmason3** [paramiko/paramiko#2253]
Running Paramiko 3.2.0 under Python 3.9.13 and I am struggling to authenticate to a Cisco device using a password protected OpenSSH based RSA 2048 key. I was trying to get Ansible working using the `net_put` module, but it was failing with `No existing session` error, so I went back to basics and tried with the following simple Python script:

```
import paramiko

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('<IP>', username='ansible', passphrase='<KEY_PASSWORD>', key_filename="/home/ansible/.ssh/ansible/ansible_rsa2048", allow_agent=False, look_for_keys=False, timeout=10)
```

This results in the following (some lines excluded for brevity):

```
DEBUG:paramiko.transport:starting thread (client mode): 0xf4ce47f0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_3.2.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-1.25
INFO:paramiko.transport:Connected (version 2.0, client Cisco-1.25)
DEBUG:paramiko.transport:Trying discovered key b'45c7f2561309bbe78927141a6c4864e9' in /home/ansible/.ssh/ansible/ansible_rsa2048
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) failed.
DEBUG:paramiko.transport:Trying discovered key b'08278851e5fccacd788300e519db8760' in /home/ansible/.ssh/ansible/ansible_rsa2048
INFO:paramiko.transport:Disconnect (code 2): Protocol error: expected packet type 50, got 5
Traceback (most recent call last):
  File "/home/ansible/itpc/./x.py", line 12, in <module>
    client.connect('<IP>', username='ansible', passphrase='<KEY_PASSWORD>', key_filename="/home/ansible/.ssh/ansible/ansible_rsa2048", allow_agent=False, look_for_keys=False, timeout=10)
  File "/home/ansible/itpc/python/lib64/python3.9/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/ansible/itpc/python/lib64/python3.9/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/ansible/itpc/python/lib64/python3.9/site-packages/paramiko/client.py", line 730, in _auth
    key = self._key_from_filepath(
  File "/home/ansible/itpc/python/lib64/python3.9/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/ansible/itpc/python/lib64/python3.9/site-packages/paramiko/pkey.py", line 421, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/ansible/itpc/python/lib64/python3.9/site-packages/paramiko/ed25519key.py", line 65, in __init__
    signing_key = self._parse_signing_key_data(data, password)
  File "/home/ansible/itpc/python/lib64/python3.9/site-packages/paramiko/ed25519key.py", line 114, in _parse_signing_key_data
    raise SSHException("Invalid key")
paramiko.ssh_exception.SSHException: Invalid key
```

I don't understand why it is discovering two different keys in my keyfile - it was created with `ssh-keygen -b 2048 -t rsa`. I know the key is good as it works perfectly fine if I use OpenSSH:

```
$ ssh -i /home/ansible/.ssh/ansible/ansible_rsa2048 ansible@<IP>
Enter passphrase for key '/home/ansible/.ssh/ansible/ansible_rsa2048':

<IP>#
```

If I drop Paramiko down to 2.8.1 then it works perfectly fine (it also fixes my `net_put` Ansible issue) - I have tested numerous releases and it seems that it has been broken from 2.9.0 onwards

```
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.8.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-1.25
INFO:paramiko.transport:Connected (version 2.0, client Cisco-1.25)
DEBUG:paramiko.transport:Trying discovered key b'45c7f2561309bbe78927141a6c4864e9' in /home/ansible/.ssh/ansible/ansible_rsa2048
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) successful!
```

**Comment by cmason3** [comment]
Looks to be linked to #2143 - although the workaround isn't going to work with Ansible as I don't believe I can disable SSH algorithms from within an Ansible playbook?

**Comment by jun66j5** [comment]
It seems to be the same as #2012. Try to disable [use_rsa_sha2_algorithms](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/paramiko_ssh_connection.html#parameter-use_rsa_sha2_algorithms) option in ansible configuration.

**Comment by bskinn** [comment]
Another option to consider is the **experimental** new features described in the [3.2.0 paramiko CHANGELOG] (including the new `OpenSSHAuthStrategy` implementation in [Fabric 3.1.0]).

I'm not deeply familiar with what the current features enable, so I can't say for sure whether they address this use case, but I'm pretty sure they're at least in the ballpark. We would greatly appreciate any investigation you might be able to do and report back here.

[3.2.0 paramiko changelog]: https://www.paramiko.org/changelog.html#3.2.0
[fabric 3.1.0]: https://www.paramiko.org/changelog.html#3.2.0

**Comment by cmason3** [comment]
Thanks for the pointers, but I am slightly confused - I have checked the device in question and it supports `rsa-sha2-512` and `rsa-sha2-256` as publickey algorithms?

```
cisco(config)#ip ssh server algorithm publickey ?
  ecdsa-sha2-nistp256         ECDSA_SHA2_NISTP256 Publickey based authentication
  ecdsa-sha2-nistp384         ECDSA_SHA2_NISTP384 Publickey based authentication
  ecdsa-sha2-nistp521         ECDSA_SHA2_NISTP521 Publickey based authentication
  rsa-sha2-256                RSA-SHA2-256 Publickey based authentication
  rsa-sha2-512                RSA-SHA2-512 Publickey based authentication
  ssh-ed25519                 ED25519 Publickey based authentication
  ssh-rsa                     RSA-SHA1 Publickey based authentication
  x509v3-ecdsa-sha2-nistp256  ECDSA_SHA2_NISTP256 Certificate based authentication
  x509v3-ecdsa-sha2-nistp384  ECDSA_SHA2_NISTP384 Certificate based authentication
  x509v3-ecdsa-sha2-nistp521  ECDSA_SHA2_NISTP521 Certificate based authentication
  x509v3-ssh-rsa              RSA-SHA1 Certificate based authentication
```

I have disabled `ssh-rsa` on the device and made sure that `rsa-sha2-512` and `rsa-sha2-256` are enabled, but I am still failing to connect using Paramiko 3.2.0?

OpenSSH keys by default are rsa-sha2-512 and I haven't changed it. However, from looking at the below debug Paramiko is declaring my key of type `ssh-rsa`?

```
DEBUG:paramiko.transport:Trying discovered key b'45c7f2561309bbe78927141a6c4864e9' in /home/ansible/.ssh/ansible/ansible_rsa2048
DEBUG:paramiko.transport:userauth is OK
DEBUG:paramiko.transport:Finalizing pubkey algorithm for key of type 'ssh-rsa'
DEBUG:paramiko.transport:Our pubkey algorithm list: ['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa']
DEBUG:paramiko.transport:Server did not send a server-sig-algs list; defaulting to our first preferred algo ('rsa-sha2-512')
```

**Comment by bskinn** [comment]
If I read this right, the problems here are entirely on the Cisco side...have you found the workaround you need to make paramiko serve your needs?

**Comment by cmason3** [comment]
I took the easy way out for the time being and disabled rsa_sha2 using `use_rsa_sha2_algorithms = False`.

**Comment by bskinn** [comment]
&lt;nod&gt; -- at that point, the currently-experimental features in 3.2 will be the paradigm to investigate migrating to. 

If your needs are met for now, please close the ticket... thanks!
