### ISSUE TITLE
[BUG] - close client and reconnect fails with ConnectionResetError

### ISSUE THREAD

**Issue by avatarofhope2** [paramiko/paramiko#2289]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SSH

### What version(s) of paramiko are you using?

3.2

### What version(s) of Python are you using?

3.9.6

### What operating system and version are you using?

CentOS Linux release 7.2.1511 (Core)

### If you're connecting as a client, which SSH server are you connecting to?

Cisco NCS-5500

### Expected/desired behavior

If I close a connection, and re-open it, I expect that it will reconnect and work the same as the first time it connected.

### Actual behavior

Unless I wait for about 30 seconds, the reconnect fails.

### How to reproduce

I am seeing a similar issue with the following code:

```python
import time

import paramiko

hostname = 'test-host'
command = 'show version/r/n'.encode('utf-8')

for i in range(1, 3):
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(hostname, **{
        'look_for_keys': False,
        'timeout': 15,
        'port': 22,
        'username': 'test_user',
        'password': 'test_password',
    })

    channel = client.invoke_shell()
    channel.send(command)
    time.sleep(4)
    channel.close()
    client.close()
```

When I run this with paramiko logger basicConfig set, I get:
```
2023-08-24 19:34:49,825 [19186] [Thread-3] [paramiko.transport] transport:1893 (ERROR) Exception (client): Error reading SSH protocol banner[Errno 104] Connection reset by peer
2023-08-24 19:34:49,826 [19186] [Thread-3] [paramiko.transport] transport:1891 (ERROR) Traceback (most recent call last):
2023-08-24 19:34:49,826 [19186] [Thread-3] [paramiko.transport] transport:1891 (ERROR)   File "/home/my_user/py_env/lib/python3.9/site-packages/paramiko/transport.py", line 2292, in _check_banner
2023-08-24 19:34:49,826 [19186] [Thread-3] [paramiko.transport] transport:1891 (ERROR)     buf = self.packetizer.readline(timeout)
2023-08-24 19:34:49,826 [19186] [Thread-3] [paramiko.transport] transport:1891 (ERROR)   File "/home/my_user/py_env/lib/python3.9/site-packages/paramiko/packet.py", line 374, in readline
2023-08-24 19:34:49,826 [19186] [Thread-3] [paramiko.transport] transport:1891 (ERROR)     buf += self._read_timeout(timeout)
2023-08-24 19:34:49,826 [19186] [Thread-3] [paramiko.transport] transport:1891 (ERROR)   File "/home/my_user/py_env/lib/python3.9/site-packages/paramiko/packet.py", line 601, in _read_timeout
2023-08-24 19:34:49,826 [19186] [Thread-3] [paramiko.transport] transport:1891 (ERROR)     x = self.__socket.recv(128)
2023-08-24 19:34:49,826 [19186] [Thread-3] [paramiko.transport] transport:1891 (ERROR) ConnectionResetError: [Errno 104] Connection reset by peer
```

### Anything else?

I would love a way to ensure that state is fully cleared out when everything is closed. If I put a sleep(30) in there, it seems to work again, but I can't wait that long after every close call, and this behavior is very confusing.

Reproduction of the error may be dependent on the specific device I am connecting to, which is a Cisco NCS-5500, but I am stuck until I can ensure this works. I've tried manually closing the socket, channel, transport, client, and setting their references to None, but it doesn't seem to work. I'm wondering if the issue is that I need to wait for the transport thread to end, but I would think it smart enough to start brand new instance of a socket.

**Comment by avatarofhope2** [comment]
I had been troubleshooting the issue for about a day before submitting the bug, but I've reproduced the issue via CLI, so this is most definitely not a Paramiko bug! Sorry for the false positive, but maybe this will help someone else in the future.

```
(py_env) [user@server dir]$ ssh test_user@test-host
Password:

***********************************
* banner text     *
***********************************

RP/0/RP0/CPU0:test-host#exit
Connection to test-host closed.
(py_env) [user@server dir]$ ssh test_user@test-host
ssh_exchange_identification: read: Connection reset by peer
(py_env) [user@server dir]$ 
```

I'm still waiting on more information, but I think there may be a setting that rate limits new connections on the ssh server.

**Comment by jun66j5** [comment]
That is not a paramiko issue. The error means that _the server disconnected the connection_.

Try to check [ssh server logging](https://www.cisco.com/c/en/us/td/docs/iosxr/ncs5500/security/b-system-security-cr-ncs5500/secure-shell-commands.html#wp1109878216) on the CISCO device and configure [ssh server rate-limit](https://www.cisco.com/c/en/us/td/docs/iosxr/ncs5500/security/b-system-security-cr-ncs5500/secure-shell-commands.html#wp1990448414).
