### ISSUE TITLE
[SUPPORT] - <Login on device PSS failed>

### ISSUE THREAD

**Issue by devilution1979** [paramiko/paramiko#2305]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

Keys/auth

### What version(s) of paramiko are you using?

2.7.0

### What version(s) of Python are you using?

3.10.7

### What operating system and version are you using?

Windows 11

### If you're connecting as a client, which SSH server are you connecting to?

open SSH

### If you're using paramiko as part of another tool, which tool/version?

nokia-1830pss-ssh

### What are you trying to do with paramiko?

I'm having issues to figure out how to login on device where I need to run some periodically commands:

I was trying to use pss1830ssh driver but unsuccessfully, well let me explain the regular loging from cli:

FIRST:
$ ssh cli@10.10.68.12

SECOND:
Username: panda

THIRD:
Password: *****

FOURTH:
Do you acknowledge? (Y/N)?Y

PSS16II-ADC1# show version

my codes:
from pss1830ssh.pss1830cli import PSS1830Cli

cli = PSS1830Cli('10.10.68.12', 22, 'panda', 'panda')
cli.open()
result = cli.execute('show version')
for data in result:
print(data)
cli.close()

This is the OUTPUT ERROR:
C:\Users\anggo\OneDrive\Documents\Tutorial Python\Netmiko1>sshPSS16.py
Traceback (most recent call last):
File "C:\Users\anggo\OneDrive\Documents\Tutorial Python\Netmiko1\sshPSS16.py", line 4, in
cli.open()
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\pss1830ssh\pss1830cli.py", line 30, in open
super(PSS1830Cli, self).open()
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\pss1830ssh\pss1830.py", line 47, in open
self.client.connect(self.host, self.port, self.username, self.password)
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\client.py", line 435, in connect
self._auth(
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\client.py", line 764, in _auth
raise saved_exception
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\client.py", line 751, in _auth
self._transport.auth_password(username, password)
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\transport.py", line 1509, in auth_password
return self.auth_handler.wait_for_response(my_event)
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\auth_handler.py", line 250, in wait_for_response
raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

before I faced some error relates to blowfish:
CryptographyDeprecationWarning: Blowfish has been deprecated
"class": algorithms.Blowfish,

and it clear after Remove blowfish from transport ciphers #2039.

already installed:
nokia1830pss 1.0.3
paramiko 2.7.0
netmiko 4.1.2

### How are you trying to do it, and what's happening instead?

This is the OUTPUT ERROR:
C:\Users\anggo\OneDrive\Documents\Tutorial Python\Netmiko1>sshPSS16.py
Traceback (most recent call last):
File "C:\Users\anggo\OneDrive\Documents\Tutorial Python\Netmiko1\sshPSS16.py", line 4, in
cli.open()
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\pss1830ssh\pss1830cli.py", line 30, in open
super(PSS1830Cli, self).open()
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\pss1830ssh\pss1830.py", line 47, in open
self.client.connect(self.host, self.port, self.username, self.password)
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\client.py", line 435, in connect
self._auth(
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\client.py", line 764, in _auth
raise saved_exception
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\client.py", line 751, in _auth
self._transport.auth_password(username, password)
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\transport.py", line 1509, in auth_password
return self.auth_handler.wait_for_response(my_event)
File "C:\Users\anggo\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\auth_handler.py", line 250, in wait_for_response
raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

**Comment by bskinn** [comment]
@devilution1979 Please reformat your inputs and outputs using triple-backtick code fences (` ``` {content} ``` `) -- without fixed-width formatting it's very hard to read. Thanks!

**Comment by jun66j5** [comment]
I guess that authentication failure is caused by your wrong username/password (because `AuthenticationException` is raised from `Transport.auth_password`). Check paramiko's log using `paramiko.util.log_to_file('/tmp/paramiko.log')`.

**Comment by devilution1979** [comment]
> @devilution1979 Please reformat your inputs and outputs using triple-backtick code fences (`` ``` {content} ``` ``) -- without fixed-width formatting it's very hard to read. Thanks!

ok thanks a lot,, I will try it
