### ISSUE TITLE
[SUPPORT] - <UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 167-168: invalid continuation byte>

### ISSUE THREAD

**Issue by imPage** [paramiko/paramiko#2321]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SFTP

### What version(s) of paramiko are you using?

3.3.1

### What version(s) of Python are you using?

 3.7.1 

### What operating system and version are you using?

Linux centos7 3.10.0-1160.99.1.el7.x86_64 

### What are you trying to do with paramiko?

Retrieve files from a remote SFTP server.

### How are you trying to do it, and what's happening instead?

`
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(host, int(port), uname, pwd)
sftp_cli = ssh.open_sftp()
files = sftp_cli.listdir(wdir)
`

_**Traceback (most recent call last):
  File "sftp_proxy_timing.py", line 294, in <module>
    files = sftp_cli.listdir(wdir)
  File "/usr/local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 218, in listdir
    return [f.filename for f in self.listdir_attr(path)]
  File "/usr/local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 255, in listdir_attr
    longname = msg.get_text()
  File "/usr/local/lib/python3.7/site-packages/paramiko/message.py", line 184, in get_text
    return u(self.get_string())
  File "/usr/local/lib/python3.7/site-packages/paramiko/util.py", line 333, in u
    return s.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 167-168: invalid continuation byte**_

**Comment by bskinn** [comment]
Hi, @imPage, thanks for the report.

If you would, please reformat your code and output/tracebacks using [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks), and lay out your code with one line of code per one line of display in your issue text.

Without that formatting it's very hard to read. Thanks!

**Comment by imPage** [comment]
> Hi, @imPage, thanks for the report.
> 
> If you would, please reformat your code and output/tracebacks using [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks), and lay out your code with one line of code per one line of display in your issue text.
> 
> Without that formatting it's very hard to read. Thanks!


 I'm very sorry, I have reformatted my code as follows:
```
ssh = paramiko.SSHClient() 
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy()) 
ssh.connect(host, int(port), uname, pwd) 
sftp_cli = ssh.open_sftp()
files = sftp_cli.listdir(wdir)
```
Traceback:
```
Traceback (most recent call last):
File "sftp_proxy_timing.py", line 294, in
files = sftp_cli.listdir(wdir)
File "/usr/local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 218, in listdir
return [f.filename for f in self.listdir_attr(path)]
File "/usr/local/lib/python3.7/site-packages/paramiko/sftp_client.py", line 255, in listdir_attr
longname = msg.get_text()
File "/usr/local/lib/python3.7/site-packages/paramiko/message.py", line 184, in get_text
return u(self.get_string())
File "/usr/local/lib/python3.7/site-packages/paramiko/util.py", line 333, in u
return s.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 167-168: invalid continuation byte
```
Looking forward to your reply, thank you very much.

**Comment by imPage** [comment]
After my continuous attempts, I found that when a file with this name exists on the SFTP server, such as : **_D1 XXXX (XXX) - XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX. docx_**, the error mentioned above will be triggered.

`D1-XXXX（XXX）-XXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXX-XXX.docx`
