### ISSUE TITLE
[SUPPORT] - `channel.get_pty` causes channel to close.

### ISSUE THREAD

**Issue by GamePlayer-8** [paramiko/paramiko#2329]
### Are you using paramiko as a client or server?

Server

### What feature(s) aren't working right?

SSH

### What version(s) of paramiko are you using?

3.3.1

### What version(s) of Python are you using?

3.11.5

### What operating system and version are you using?

Artix Linux Rolling

### If you're connecting as a client, which SSH server are you connecting to?

-

### What are you trying to do with paramiko?

I'm trying to run a basic SSH Server using `paramiko`.

### How are you trying to do it, and what's happening instead?

I'm doing the `channel.get_pty` part like so:
```python
with t.accept(20) as channel:
    channel.get_pty(term='vt100')
    channel.invoke_shell()
```
Full script available [here](https://gist.github.com/GamePlayer-8/2eff0e41b78c8e149baaecfdeb5cfa85).

<hr/>

Although it's crashing with:
```python
Exception in thread Thread-1 (run_server):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gameplayer/workspace/payload/app/parassh.py", line 95, in run_server
    listener()
  File "/home/gameplayer/workspace/payload/app/parassh.py", line 87, in listener
    channel.get_pty(term='vt100')
  File "/usr/lib/python3.11/site-packages/paramiko/channel.py", line 70, in _check
    return func(self, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paramiko/channel.py", line 201, in get_pty
    self._wait_for_event()
  File "/usr/lib/python3.11/site-packages/paramiko/channel.py", line 1224, in _wait_for_event
    raise e
paramiko.ssh_exception.SSHException: Channel closed.
```
Formatted log:
```python
2023-11-14 17:28:39,648 - root - INFO - Socket (re)activated.
2023-11-14 17:28:41,812 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.5)
2023-11-14 17:28:41,837 - paramiko.transport - INFO - Auth rejected (none).
2023-11-14 17:28:41,848 - paramiko.transport - INFO - Auth granted (publickey).
2023-11-14 17:28:41,851 - root - ERROR - Channel closed.
2023-11-14 17:28:41,851 - root - INFO - Socket (re)activated.
```

**Comment by jun66j5** [comment]
Your script is wrong. `Channel.get_pty` and `Channel.invoke_shell` are used to send the request from the client to the server (after invoking `start_client`). The `pty` request from server to client is ignored. Your script is in server mode.

See https://datatracker.ietf.org/doc/html/rfc4254#section-6.2

**Comment by GamePlayer-8** [comment]
I see. How should I accomplish the goal of getting shell like `/bin/sh` running on the server side and be interactable by the client?
