### ISSUE TITLE
[BUG] - SSHException: No authentication methods available after successful authentication (Tailscale)

### ISSUE THREAD

**Issue by selevit** [paramiko/paramiko#2370]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SSH, Keys/auth

### What version(s) of paramiko are you using?

3.4.0

### What version(s) of Python are you using?

3.10.12

### What operating system and version are you using?

Ubuntu 22.04

### If you're connecting as a client, which SSH server are you connecting to?

OpenSSH, via Tailscale SSH

### Expected/desired behavior

When connecting to a server using [Tailscale SSH](https://tailscale.com/tailscale-ssh) it must authenticate successfully even if there are no ssh keys are in the `~/.ssh/` directory.

### Actual behavior

It firstly authenticates well via Tailscale (due to DEBUG logs) and then raises `paramiko.ssh_exception.SSHException: No authentication methods available`.

Logs:

```
DEBUG:paramiko.transport:starting thread (client mode): 0xba4bf730
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_3.4.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Tailscale
INFO:paramiko.transport:Connected (version 2.0, client Tailscale)
DEBUG:paramiko.transport:=== Key exchange possibilities ===
DEBUG:paramiko.transport:kex algos: curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group14-sha256, diffie-hellman-group14-sha1
DEBUG:paramiko.transport:server key: rsa-sha2-256, rsa-sha2-512, ssh-rsa, ecdsa-sha2-nistp256, ssh-ed25519
DEBUG:paramiko.transport:client encrypt: aes128-gcm@openssh.com, aes256-gcm@openssh.com, chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr
DEBUG:paramiko.transport:server encrypt: aes128-gcm@openssh.com, aes256-gcm@openssh.com, chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr
DEBUG:paramiko.transport:client mac: hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1, hmac-sha1-96
DEBUG:paramiko.transport:server mac: hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1, hmac-sha1-96
DEBUG:paramiko.transport:client compress: none
DEBUG:paramiko.transport:server compress: none
DEBUG:paramiko.transport:client lang: <none>
DEBUG:paramiko.transport:server lang: <none>
DEBUG:paramiko.transport:kex follows: False
DEBUG:paramiko.transport:=== Key exchange agreements ===
DEBUG:paramiko.transport:Kex: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey: ssh-ed25519
DEBUG:paramiko.transport:Cipher: aes128-ctr
DEBUG:paramiko.transport:MAC: hmac-sha2-256
DEBUG:paramiko.transport:Compression: none
DEBUG:paramiko.transport:=== End of kex handshake ===
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Got EXT_INFO: {'server-sig-algs': b'ssh-ed25519,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-256,rsa-sha2-512,ssh-rsa,ssh-dss'}
DEBUG:paramiko.transport:Adding ssh-ed25519 host key for <censored>: b'3ecfd30634ebb36208b1420ed711a105'
Traceback (most recent call last):
  File "/home/selevit/projects/sparkland/scripts/paramiko_test.py", line 9, in <module>
    ssh.connect('<censored>', username='ubuntu')
  File "/home/selevit/.local/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/home/selevit/.local/lib/python3.10/site-packages/paramiko/client.py", line 819, in _auth
    raise SSHException("No authentication methods available")
paramiko.ssh_exception.SSHException: No authentication methods available
```

### How to reproduce

1. Ensure that you don't have any private and public keys in `~/.ssh/`.
1. Ensure that you have a Tailscale SSH connection with a server, and normal (openssh) client can connect well by a hostname.
1. Then run this script, and you will be able to see the same log as above.

```python
#!/usr/bin/env python3
import paramiko
import logging

logging.basicConfig(level=logging.DEBUG)

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('hostname', username='user')

stdin, stdout, stderr = ssh.exec_command('uname')
stdin.close()
output = stdout.read().decode('utf-8')
print(output)

ssh.close()
```

**Comment by jun66j5** [comment]
I guess that is caused by the paramiko client is not sending the `none` method for authentication by default.

You could use `auth_strategy` parameter to send the `none` method like this.

```python
import paramiko
import paramiko.auth_strategy

class AuthStrategy(paramiko.auth_strategy.AuthStrategy):

    def __init__(self, ssh_config, username):
        super().__init__(ssh_config)
        self.username = username

    def get_sources(self):
        yield paramiko.auth_strategy.NoneAuth(self.username)

hostname = 'hostname'
username = 'user'

ssh_config = paramiko.SSHConfig()
auth_strategy = AuthStrategy(ssh_config, username)
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(hostname, auth_strategy=auth_strategy)
```

Also, please ask clients which supported by tailscale on tailscale support.

**Comment by selevit** [comment]
> You could use auth_strategy parameter to send the none method like this.

Thanks a lot for the example! I already mitigated this in a little different way: by passing a dummy key into `connect_kwargs={"pkey": paramiko.ecdsakey.ECDSAKey.generate()}`.

> I guess that is caused by the paramiko client is not sending the none method for authentication by default.

That's why I created this bug, as it doesn't sound as an expected default behavior.
