### ISSUE TITLE
Accept Path objects for remote file name in sftp.put

### ISSUE THREAD

**Issue by ESPR3SS0** [paramiko/paramiko#2401]
### Is this feature for paramiko acting as a client or a server?

Both

### What functionality does this feature request relate to?

SFTP

### Desired behavior

Given a Path object for the remote file, ```sftp.put()``` fails:
```python
local = Path("/some/path")
remote = Path("remote.txt")
sftp.put(file, remote)
```
Raises:
```bash
TypeError: Expected unicode or bytes, got <class 'pathlib.PosixPath'> 
```
While the workaround is simple:
```python
local = Path("/some/path")
file = Path("remote.txt")
sftp.put(local, str(file))
```

But it would feel more _intuitive_ is both the local on the remote could be Path objects.

Pathlib has been widely adopted in the python ecosystem so integrating this would make the experience of a new comer who's use to this kind of behavior with Path objects all the better (I'm one of these new comers :) ).

I'm assuming such an addition would not be too difficult and I'd be more than happy to add this myself !

**Comment by jun66j5** [comment]
Duplicate: #1853 #1255 #1252

**Comment by jun66j5** [comment]
Also, `pathlib.Path` for local and `pathlib.PurePosixPath` for remote should be used. Otherwise, it will be broken on Windows.

```pycon
>>> import os, pathlib
>>> os.name
'nt'
>>>
>>> str(pathlib.Path('/path/to/remote-file'))
'\\path\\to\\remote-file'
>>> str(pathlib.PosixPath('/path/to/remote-file'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\usr\apps\python312\Lib\pathlib.py", line 1422, in __new__
    raise NotImplementedError(
NotImplementedError: cannot instantiate 'PosixPath' on your system
>>> str(pathlib.PurePosixPath('/path/to/remote-file'))
'/path/to/remote-file'
```
