### ISSUE TITLE
[BUG] - Paramiko doesnt work with OpenSSH 7.8

### ISSUE THREAD

**Issue by tobyX** [paramiko/paramiko#2404]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SSH, Keys/auth

### What version(s) of paramiko are you using?

3.4.0

### What version(s) of Python are you using?

3.11.7

### What operating system and version are you using?

Ubuntu 22.04.4 LTS (Jammy Jellyfish)

### If you're connecting as a client, which SSH server are you connecting to?

SSH-2.0-OpenSSH_7.8

### Expected/desired behavior

Can call connect and can establish an connection.

### Actual behavior

Paramiko throws an exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/usr/local/lib/python3.11/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.11/site-packages/paramiko/client.py", line 805, in _auth
    self._transport.auth_password(username, password)
  File "/usr/local/lib/python3.11/site-packages/paramiko/transport.py", line 1603, in auth_password
    return self.auth_handler.wait_for_response(my_event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paramiko/auth_handler.py", line 248, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed: transport shut down or saw EOF
```

### How to reproduce

Connect to a OpenSSH server 7.8:
```
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(hostname="<YOURHOST>", username="<YOURUSER>", password="<YOURPASSWORD>")
```

### Anything else?

In Paramiko 3.2 this specific host worked fine, when we upgraded to Paramiko 3.4 it always failed with the exception above.
We pinned it down to the bugfix for "Address [CVE 2023-48795](https://terrapin-attack.com/) (aka the “Terrapin Attack”".
I've interpret the Changelog as strict_kex should not be used when a server less than OpenSSH 9.6 is detected. My server identifies correctly but the fix is used nonetheless:

```
DEBUG:paramiko.transport:starting thread (client mode): 0x5f481bd0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_3.4.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.8
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.8)
DEBUG:paramiko.transport:=== Key exchange possibilities ===
DEBUG:paramiko.transport:kex algos: curve25519-sha256, curve25519-sha256@libssh.org, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, kex-strict-s-v00@openssh.com
DEBUG:paramiko.transport:server key: rsa-sha2-512, rsa-sha2-256, ssh-rsa
DEBUG:paramiko.transport:client encrypt: aes128-gcm@openssh.com, aes192-ctr, aes256-ctr, aes256-gcm@openssh.com, chacha20-poly1305@openssh.com
DEBUG:paramiko.transport:server encrypt: aes128-gcm@openssh.com, aes192-ctr, aes256-ctr, aes256-gcm@openssh.com, chacha20-poly1305@openssh.com
DEBUG:paramiko.transport:client mac: hmac-sha2-256, hmac-sha2-256-etm@openssh.com, hmac-sha2-512, hmac-sha2-512-etm@openssh.com, umac-128-etm@openssh.com, umac-128@openssh.com, umac-64@openssh.com, umac-64-etm@openssh.com
DEBUG:paramiko.transport:server mac: hmac-sha2-256, hmac-sha2-256-etm@openssh.com, hmac-sha2-512, hmac-sha2-512-etm@openssh.com, umac-128-etm@openssh.com, umac-128@openssh.com, umac-64@openssh.com, umac-64-etm@openssh.com
DEBUG:paramiko.transport:client compress: none, zlib@openssh.com
DEBUG:paramiko.transport:server compress: none, zlib@openssh.com
DEBUG:paramiko.transport:client lang: <none>
DEBUG:paramiko.transport:server lang: <none>
DEBUG:paramiko.transport:kex follows: False
DEBUG:paramiko.transport:=== Key exchange agreements ===
DEBUG:paramiko.transport:Strict kex mode: True
DEBUG:paramiko.transport:Kex: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey: ssh-rsa
DEBUG:paramiko.transport:Cipher: aes192-ctr
DEBUG:paramiko.transport:MAC: hmac-sha2-256
DEBUG:paramiko.transport:Compression: none
DEBUG:paramiko.transport:=== End of kex handshake ===
DEBUG:paramiko.transport:Resetting outbound seqno after NEWKEYS due to strict mode
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Resetting inbound seqno after NEWKEYS due to strict mode
DEBUG:paramiko.transport:EOF in transport thread
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/usr/local/lib/python3.11/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.11/site-packages/paramiko/client.py", line 805, in _auth
    self._transport.auth_password(username, password)
  File "/usr/local/lib/python3.11/site-packages/paramiko/transport.py", line 1603, in auth_password
    return self.auth_handler.wait_for_response(my_event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paramiko/auth_handler.py", line 248, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed: transport shut down or saw EOF
```

When I set strict_kex to False it works as expected:

```
class MyTrans(Transport):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, strikt_kex=False, **kwargs)

ssh.connect(hostname="<YOURHOST>", username="<YOURUSER>", password="<YOURPASSWORD>", transport_factory=MyTrans)
```

```
DEBUG:paramiko.transport:starting thread (client mode): 0x5f462650
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_3.4.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.8
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.8)
DEBUG:paramiko.transport:=== Key exchange possibilities ===
DEBUG:paramiko.transport:kex algos: curve25519-sha256, curve25519-sha256@libssh.org, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, kex-strict-s-v00@openssh.com
DEBUG:paramiko.transport:server key: rsa-sha2-512, rsa-sha2-256, ssh-rsa
DEBUG:paramiko.transport:client encrypt: aes128-gcm@openssh.com, aes192-ctr, aes256-ctr, aes256-gcm@openssh.com, chacha20-poly1305@openssh.com
DEBUG:paramiko.transport:server encrypt: aes128-gcm@openssh.com, aes192-ctr, aes256-ctr, aes256-gcm@openssh.com, chacha20-poly1305@openssh.com
DEBUG:paramiko.transport:client mac: hmac-sha2-256, hmac-sha2-256-etm@openssh.com, hmac-sha2-512, hmac-sha2-512-etm@openssh.com, umac-128-etm@openssh.com, umac-128@openssh.com, umac-64@openssh.com, umac-64-etm@openssh.com
DEBUG:paramiko.transport:server mac: hmac-sha2-256, hmac-sha2-256-etm@openssh.com, hmac-sha2-512, hmac-sha2-512-etm@openssh.com, umac-128-etm@openssh.com, umac-128@openssh.com, umac-64@openssh.com, umac-64-etm@openssh.com
DEBUG:paramiko.transport:client compress: none, zlib@openssh.com
DEBUG:paramiko.transport:server compress: none, zlib@openssh.com
DEBUG:paramiko.transport:client lang: <none>
DEBUG:paramiko.transport:server lang: <none>
DEBUG:paramiko.transport:kex follows: False
DEBUG:paramiko.transport:=== Key exchange agreements ===
DEBUG:paramiko.transport:Strict kex mode: False
DEBUG:paramiko.transport:Kex: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey: ssh-rsa
DEBUG:paramiko.transport:Cipher: aes192-ctr
DEBUG:paramiko.transport:MAC: hmac-sha2-256
DEBUG:paramiko.transport:Compression: none
DEBUG:paramiko.transport:=== End of kex handshake ===
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Auth banner: b'<Some Legal stuff>'
INFO:paramiko.transport:Authentication (password) successful!
>>> DEBUG:paramiko.transport:Received global request "hostkeys-00@openssh.com"
DEBUG:paramiko.transport:Rejecting "hostkeys-00@openssh.com" global request from server.
```

Disclaimer: This is not a regular host but some kind of appliance. Thus we cant upgrade OpenSSH until the supplier does upgrade it.

I only report this as the Changelog reads as if this is not the intended behaviour and Paramiko should disable strict_kex when detecting OpenSSH less than 9.6

**Comment by tobyX** [comment]
We also see in the logs of the appliance following message:
`ssh_dispatch_run_fatal: Connection from X.X.X.X port 35894: message authentication code incorrect [preauth]`

**Comment by bskinn** [comment]
@tobyX Can you check this with paramiko v3.5? It adds some new gcm ciphers that might or might not resolve the problem. See #2444 and links therein.
