### ISSUE TITLE
[BUG] - <paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.0.89.23>

### ISSUE THREAD

**Issue by seraphzl** [paramiko/paramiko#2427]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SSH

### What version(s) of paramiko are you using?

3.0.0

### What version(s) of Python are you using?

3.10.3

### What operating system and version are you using?

ubuntu

### If you're connecting as a client, which SSH server are you connecting to?

local server 10.0.89.23

### If you're using paramiko as part of another tool, which tool/version?

dask 2024.7.1, distributed 2024.7.1

### Expected/desired behavior

paramiko connect to port 2233 on server

### Actual behavior

Exception in thread Thread-4 (async_ssh):
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/distributed/deploy/old_ssh.py", line 48, in async_ssh
    ssh.connect(
  File "/root/miniconda3/lib/python3.10/site-packages/paramiko/client.py", line 380, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.0.89.23

### Anything else?

ssh port on server is 2233
how to set the ssh port in paramiko?

**Comment by seraphzl** [comment]
solved.

**Comment by viki435** [comment]
> solved.

What's the solution?
