### ISSUE TITLE
No way to catch exception when reboot via ssh

### ISSUE THREAD

**Issue by pulina** [paramiko/paramiko#244]
I am connecting via previous created tunel(Channel) to remote host and when i reboot remote

```
 exec_command('sync && reboot& && exit ')
```

SocketServer raise Exception  - Broken pipe

I can't catch it because is not in my application, only in SocketServer. There is no way to push command and close socket or hendle exception. 

Full trace:

``` traceback
Exception happened during processing of request from ('127.0.0.1', 48467)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "./virtualenv/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 139, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib64/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

Code:

``` python

        try:
            #Create shhClient object from factory class
            tun = Paramiko()
            tun.connect(tun_ip, 2222, 'root', timeout=1, look_for_keys=True,      key_filename=settings.SSH_KEYFILE)
            ssh_transport = tun.get_transport()
            chan = ssh_transport.open_channel('direct-tcpip', (remote_ip, 22), (tun_ip,port))
            ssh = Paramiko()
            key_file = open('key','r')
            key = paramiko.RSAKey.from_private_key(key_file,password='some pass')
            #Useles hostname and host port because we use socket    
            ssh.connect('',0,None,sock=chan, timeout=1, look_for_keys=True, pkey=key)
            def handler(signum, frame):    
                # this not working               
                ssh.close()
                tun.close()
                return HttpResponse("ok")
            signal.signal(signal.SIGALRM, handler)       
            signal.alarm(5)                              
            ssh.exec_command('sync && reboot & && exit')
            signal.alarm(0)  
        except Exception as e:
            print e
            pass
        finally:
            ssh.close()
            tun.close()
            return HttpResponse("ok")


```

**Comment by ljluestc** [comment]
```

import paramiko
import signal
from django.http import HttpResponse

def handle_alarm(signum, frame):
    raise TimeoutError("Execution timed out")

try:
    # Set up signal handler for timeout
    signal.signal(signal.SIGALRM, handle_alarm)
    
    # Create SSH client object for tunneling
    tun = paramiko.SSHClient()
    tun.connect(tun_ip, 2222, 'root', timeout=1, look_for_keys=True, key_filename=settings.SSH_KEYFILE)
    ssh_transport = tun.get_transport()
    chan = ssh_transport.open_channel('direct-tcpip', (remote_ip, 22), (tun_ip, port))
    
    # Create SSH client object for executing commands
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    key = paramiko.RSAKey.from_private_key_file('key', password='some pass')
    ssh.connect('', 0, None, sock=chan, timeout=1, look_for_keys=True, pkey=key)

    # Execute the command (sync, reboot, and exit)
    signal.alarm(5)  # Set a timeout for the command execution
    stdin, stdout, stderr = ssh.exec_command('sync && reboot && exit')
    for line in stdout:
        print(line.strip())
    signal.alarm(0)  # Cancel the timeout

except paramiko.SSHException as e:
    print("SSH error:", e)
except TimeoutError:
    print("Command execution timed out")
except Exception as e:
    print("An error occurred:", e)

finally:
    try:
        ssh.close()
        tun.close()
    except NameError:
        pass  # If SSH or tunnel objects were not created, skip closing them
    
    return HttpResponse("ok")
```
