### ISSUE TITLE
Connect timeout without effect on windows

### ISSUE THREAD

**Issue by smurn** [paramiko/paramiko#279]
Giving the timeout option to `SSHClient.connect` seems not to have any effect on Windows.

I think paramiko is expecting errno.EINTR (code 4) but Windows, as usual, does things differently from everyone else and produces code 10060.

Tested on Windows 7.

```
  File "C:\Python27\lib\site-packages\paramiko\client.py", line 301, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "C:\Python27\lib\site-packages\paramiko\util.py", line 278, in retry_on_signal
    return function()
  File "C:\Python27\lib\site-packages\paramiko\client.py", line 301, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat
```

Sorry about the german error message, let me try to translate:
"A connection attempt has failed since the other side did not react in a certain time span, or the created connection was faulty since the connected host did not react."

**Comment by gregasmaximus** [comment]
Hard to believe that this is unfixed over 3 years later, but I get similar result. With either defaults timeouts (None, according to docs) or timeout, auth_timeout and banner_timeout set to 6000, I get the following message:

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by jun66j5** [comment]
This issue occurs on all platforms, when the timeout parameter is shorter than time to wait SYN+ACK packet from remote host after sending SYN packet by kernel tcp stack.

Also, `TimeoutError` is introduced in Python 3.3. The `TimeoutError` instead of `socket.error` is raised on Python 3.3+ in the issue.

#### Python 3 on Linux

```pycon
>>> import paramiko, sys
>>> sys.version
'3.9.13 (main, May 23 2022, 22:01:06) \n[GCC 9.4.0]'
>>> client = paramiko.SSHClient()
>>> client.connect('192.0.2.1', timeout=3600)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "paramiko/client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "paramiko/util.py", line 279, in retry_on_signal
    return function()
  File "paramiko/client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
TimeoutError: [Errno 110] Connection timed out
>>> import inspect
>>> inspect.getclasstree([TimeoutError])
[(<class 'OSError'>, (<class 'Exception'>,)), [(<class 'TimeoutError'>, (<class 'OSError'>,))]]
```

#### Python 2.7 on Linux

```pycon
>>> import paramiko, sys
>>> sys.version
'2.7.18 (default, Mar  8 2021, 13:02:45) \n[GCC 9.3.0]'
>>> client = paramiko.SSHClient()
>>> client.connect('192.0.2.1', timeout=3600)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "paramiko/client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "paramiko/util.py", line 279, in retry_on_signal
    return function()
  File "paramiko/client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 110] Connection timed out
>>> import inspect
>>> inspect.getclasstree([socket.error])
[(<type 'exceptions.IOError'>, (<type 'exceptions.EnvironmentError'>,)), [(<class 'socket.error'>, (<type 'exceptions.IOError'>,))]]
```
