### ISSUE TITLE
unit test fails with python 2.7.6 on openSUSE 13.1

### ISSUE THREAD

**Issue by rjschwei** [paramiko/paramiko#317]
With version 1.13 the unit tests fail with python 2.7.6

[   29s] ERROR: test_K_utf8 (tests.test_sftp.SFTPTest)
[   29s] ----------------------------------------------------------------------
[   29s] Traceback (most recent call last):
[   29s]   File "/home/abuild/rpmbuild/BUILD/paramiko-1.13.0/tests/test_sftp.py", line 158, in tearDown
[   29s]     sftp.rmdir(FOLDER)
[   29s]   File "/home/abuild/rpmbuild/BUILD/paramiko-1.13.0/paramiko/sftp_client.py", line 306, in rmdir
[   29s]     self._request(CMD_RMDIR, path)
[   29s]   File "/home/abuild/rpmbuild/BUILD/paramiko-1.13.0/paramiko/sftp_client.py", line 647, in _request
[   29s]     return self._read_response(num)
[   29s]   File "/home/abuild/rpmbuild/BUILD/paramiko-1.13.0/paramiko/sftp_client.py", line 694, in _read_response
[   29s]     self._convert_status(msg)
[   29s]   File "/home/abuild/rpmbuild/BUILD/paramiko-1.13.0/paramiko/sftp_client.py", line 724, in _convert_status
[   29s]     raise IOError(text)
[   29s] IOError: Failure
[   29s] 
[   29s] ======================================================================
[   29s] ERROR: test_L_utf8_chdir (tests.test_sftp.SFTPTest)
[   29s] ----------------------------------------------------------------------
[   29s] Traceback (most recent call last):
[   29s]   File "/home/abuild/rpmbuild/BUILD/paramiko-1.13.0/tests/test_sftp.py", line 631, in test_L_utf8_chdir
[   29s]     sftp.mkdir(FOLDER + '/' + unicode_folder)
[   29s]   File "/home/abuild/rpmbuild/BUILD/paramiko-1.13.0/paramiko/sftp_client.py", line 296, in mkdir
[   29s]     self._request(CMD_MKDIR, path, attr)
[   29s]   File "/home/abuild/rpmbuild/BUILD/paramiko-1.13.0/paramiko/sftp_client.py", line 647, in _request
[   29s]     return self._read_response(num)
[   29s]   File "/home/abuild/rpmbuild/BUILD/paramiko-1.13.0/paramiko/sftp_client.py", line 694, in _read_response
[   29s]     self._convert_status(msg)
[   29s]   File "/home/abuild/rpmbuild/BUILD/paramiko-1.13.0/paramiko/sftp_client.py", line 724, in _convert_status
[   29s]     raise IOError(text)
[   29s] IOError: Failure
[   29s] 
[   29s] ======================================================================
[   29s] FAIL: test_K_utf8 (tests.test_sftp.SFTPTest)
[   29s] ----------------------------------------------------------------------
[   29s] Traceback (most recent call last):
[   29s]   File "/home/abuild/rpmbuild/BUILD/paramiko-1.13.0/tests/test_sftp.py", line 627, in test_K_utf8
[   29s]     self.fail('exception ' + str(e))
[   29s] AssertionError: exception Failure
[   29s] 
[   29s] ======================================================================
[   29s] FAIL: test_O_getcwd (tests.test_sftp.SFTPTest)
[   29s] ----------------------------------------------------------------------
[   29s] Traceback (most recent call last):
[   29s]   File "/home/abuild/rpmbuild/BUILD/paramiko-1.13.0/tests/test_sftp.py", line 686, in test_O_getcwd
[   29s]     self.assertEqual(None, sftp.getcwd())
[   29s] AssertionError: None != u'/'
[   29s] 
[   29s] ----------------------------------------------------------------------

**Comment by comay** [comment]
I still see this with Paramiko 1.15.2 under Python 2.7.9 - one note is the two errors (test_K_utf8 and test_L_utf8_chdir) seem to be associated with the following exceptions:

DEB [20150414-22:40:59.031] thr=3   paramiko.transport.sftp: [chan 2] rename('/temp-testing000/something', '/temp-testing000/\xc3\xbcnic\xc3\xb8de')
DEB [20150414-22:40:59.035] thr=83  paramiko.transport.sftp: [chan 2] Request: rename
DEB [20150414-22:40:59.035] thr=83  paramiko.transport.sftp: [chan 2] Exception in server processing: 'ascii' codec can't encode character u'\xfc' in position 79: ordinal not in range(128)

DEB [20150414-22:40:59.050] thr=3   paramiko.transport.sftp: [chan 2] mkdir('/temp-testing001/\xc3\xbcnic\xc3\xb8de', 511)
DEB [20150414-22:40:59.053] thr=83  paramiko.transport.sftp: [chan 2] Request: mkdir
DEB [20150414-22:40:59.053] thr=83  paramiko.transport.sftp: [chan 2] Exception in server processing: 'ascii' codec can't encode character u'\xfc' in position 79: ordinal not in range(128)
