### ISSUE TITLE
open_session() raises EOFError instead of SSHException [paramiko 1.14.1]

### ISSUE THREAD

**Issue by mrysbekov** [paramiko/paramiko#385]
I'm trying to figure out how to handle networking problems on different stages of SSH session establishment. Something seems to be wrong with the way **open_session()** reacts to loss of connectivity with SSH server. Here's my code:

``` python
# coding: utf-8

import paramiko, time, socket

ssh_target_ip = 'X.X.X.X'
ssh_target_port = 22
ssh_username = 'user'
ssh_password = 'password'

ssh_socket = socket.socket()
ssh_socket.connect((ssh_target_ip, ssh_target_port))
ssh_transport = paramiko.transport.Transport(ssh_socket)
ssh_transport.start_client()
ssh_transport.auth_password(ssh_username, ssh_password)

print('Change the route now...')
time.sleep(10)

try:
    ssh_session_channel = ssh_transport.open_session()
except paramiko.ssh_exception.SSHException:
    print('ERROR')
    exit(1)

print('OK')
```

When execution is paused at **time.sleep(10)** I simulate a networking problem by changing the route to X.X.X.X on my router, effectively making X.X.X.X unreachable. The docs state that **open_session()** raises **SSHException** when the request is rejected or the session ends prematurely, so I expect to catch it. Instead, in about a minute of waiting I get this:

> Traceback (most recent call last):
>   File "D:\dev\test\ssh_issue.py", line 20, in <module>
>     ssh_session_channel = ssh_transport.open_session()
>   File "C:\Python27\lib\site-packages\paramiko\transport.py", line 542, in open_
> session
>     return self.open_channel('session')
>   File "C:\Python27\lib\site-packages\paramiko\transport.py", line 639, in open_
> channel
>     raise e
> EOFError

If I don't change the route to X.X.X.X **open_session()** returns and excecution proceeds to **print('OK')**.

**Comment by Rahul14singh** [comment]
were you able to figure this out ? I am also getting the same error. 

This is my log file for paramiko 

DEB [20170603-18:40:31.080] thr=1   paramiko.transport: starting thread (client mode): 0x538fd30
DEB [20170603-18:40:31.080] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.1.2
DEB [20170603-18:40:31.393] thr=1   paramiko.transport: Banner: Security Violation<br> Please logout and log back in<br>
ERR [20170603-18:40:31.393] thr=1   paramiko.transport: Exception: Error reading SSH protocol banner
ERR [20170603-18:40:31.393] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20170603-18:40:31.393] thr=1   paramiko.transport:   File "C:\Users\RakeshS\AppData\Local\Programs\Python\Python35-32\lib\site-packages\paramiko\transport.py", line 1893, in _check_banner
ERR [20170603-18:40:31.393] thr=1   paramiko.transport:     buf = self.packetizer.readline(timeout)
ERR [20170603-18:40:31.393] thr=1   paramiko.transport:   File "C:\Users\RakeshS\AppData\Local\Programs\Python\Python35-32\lib\site-packages\paramiko\packet.py", line 331, in readline
ERR [20170603-18:40:31.393] thr=1   paramiko.transport:     buf += self._read_timeout(timeout)
ERR [20170603-18:40:31.408] thr=1   paramiko.transport:   File "C:\Users\RakeshS\AppData\Local\Programs\Python\Python35-32\lib\site-packages\paramiko\packet.py", line 487, in _read_timeout
ERR [20170603-18:40:31.408] thr=1   paramiko.transport:     raise EOFError()
ERR [20170603-18:40:31.408] thr=1   paramiko.transport: EOFError
ERR [20170603-18:40:31.408] thr=1   paramiko.transport: 
ERR [20170603-18:40:31.408] thr=1   paramiko.transport: During handling of the above exception, another exception occurred:
ERR [20170603-18:40:31.408] thr=1   paramiko.transport: 
ERR [20170603-18:40:31.408] thr=1   paramiko.transport: Traceback (most recent call last):
ERR [20170603-18:40:31.408] thr=1   paramiko.transport:   File "C:\Users\RakeshS\AppData\Local\Programs\Python\Python35-32\lib\site-packages\paramiko\transport.py", line 1749, in run
ERR [20170603-18:40:31.408] thr=1   paramiko.transport:     self._check_banner()
ERR [20170603-18:40:31.408] thr=1   paramiko.transport:   File "C:\Users\RakeshS\AppData\Local\Programs\Python\Python35-32\lib\site-packages\paramiko\transport.py", line 1897, in _check_banner
ERR [20170603-18:40:31.408] thr=1   paramiko.transport:     raise SSHException('Error reading SSH protocol banner' + str(e))
ERR [20170603-18:40:31.408] thr=1   paramiko.transport: paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERR [20170603-18:40:31.408] thr=1   paramiko.transport:

**Comment by matjohn2** [comment]
Another "me too!" I'm using paramiko to check on a CTF style challenge where devices will regularly go away as a result of commands / reboots etc, seeing this a lot.

**Comment by srish** [comment]
Same! I am using paramiko (`timeout  = 10`) to watch Gerrit's stream event patchset-created. For the most part the bot which relies on paramiko executes well, but once in a few days, I run into this error:  

```
2018-09-07 22:17:20,474 DEBUG    EOF in transport thread
2018-09-07 22:17:25,482 DEBUG    ('Error occured while watching event: %s', AttributeError("'NoneType' object has no attribute 'open_session'",))
```

**Comment by saifhhasan** [comment]
I get similar error with latest version of paramiko-2.4.1

```
Traceback (most recent call last):
  File "/data/users/has/fbsource/fbcode/buck-out/dev/gen/openr/facebook/py/openr/emulation/emulator#link-tree/paramiko/transport.py", line 2044, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/data/users/has/fbsource/fbcode/buck-out/dev/gen/openr/facebook/py/openr/emulation/emulator#link-tree/paramiko/packet.py", line 353, in readline
    buf += self._read_timeout(timeout)
  File "/data/users/has/fbsource/fbcode/buck-out/dev/gen/openr/facebook/py/openr/emulation/emulator#link-tree/paramiko/packet.py", line 542, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/users/has/fbsource/fbcode/buck-out/dev/gen/openr/facebook/py/openr/emulation/emulator#link-tree/openr/common/tasks/tasks.py", line 354, in tasklet
    result = task(ctx, task_id, c, *args, **kwargs)
  File "/data/users/has/fbsource/fbcode/buck-out/dev/gen/openr/facebook/py/openr/emulation/emulator#link-tree/emulation/cli/containers.py", line 169, in task_create_node_rootfs
    c.run('umount -l {rootfs} || true'.format(rootfs=data.rootfs))
  File "<decorator-gen-8>", line 2, in run
  File "/data/users/has/fbsource/fbcode/buck-out/dev/gen/openr/facebook/py/openr/emulation/emulator#link-tree/fabric/connection.py", line 29, in opens
    self.open()
  File "/data/users/has/fbsource/fbcode/buck-out/dev/gen/openr/facebook/py/openr/emulation/emulator#link-tree/fabric/connection.py", line 501, in open
    self.client.connect(**kwargs)
  File "/data/users/has/fbsource/fbcode/buck-out/dev/gen/openr/facebook/py/openr/emulation/emulator#link-tree/paramiko/client.py", line 392, in connect
    t.start_client(timeout=timeout)
  File "/data/users/has/fbsource/fbcode/buck-out/dev/gen/openr/facebook/py/openr/emulation/emulator#link-tree/paramiko/transport.py", line 545, in start_client
    raise e
  File "/data/users/has/fbsource/fbcode/buck-out/dev/gen/openr/facebook/py/openr/emulation/emulator#link-tree/paramiko/transport.py", line 1893, in run
    self._check_banner()
  File "/data/users/has/fbsource/fbcode/buck-out/dev/gen/openr/facebook/py/openr/emulation/emulator#link-tree/paramiko/transport.py", line 2049, in _check_banner
    'Error reading SSH protocol banner' + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

**Comment by Kani999** [comment]
Also running into the same issue.

```
Local version/idstring: SSH-2.0-paramiko_2.7.2
Exception: Error reading SSH protocol banner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/opt/nautobot/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

I'm using optional arguments as follow `{'conn_timeout': 3000, 'auth_timeout': 3000, 'banner_timeout': 3000, 'session_timeout': 3000}` but with no luck.
