### ISSUE TITLE
Native async support (asyncio/greenlets/just-use-threads/???)

### ISSUE THREAD

**Issue by bitprophet** [paramiko/paramiko#389]
Paramiko has always used regular threads and as far as I'm aware has never been set up to support eventlet/gevent/greenlets in general.

I'm also not 100% sure what it would take to make that work since my personal experience there is lacking. It might only require a few tweaks or it might require serious work in a lot of places.

There are a few 'bug' tickets about this that I've closed: #337, #173.

**Comment by nchammas** [comment]
FWIW, there is already a project out there called [parallel-ssh](https://github.com/pkittenis/parallel-ssh) that claims to use Paramiko with gevent successfully. Perhaps their use case is limited enough that they haven't run into any issues yet.

**Comment by nchammas** [comment]
Oh, and to make another connection, there is an (abandoned) [PR here to support asynchronous SSH connections](https://github.com/paramiko/paramiko/pull/68) by using Python's builtin asyncore library. 

asyncore was replaced by [asyncio](https://docs.python.org/3/library/asyncio.html) in 3.4 (which has a Python 2.6/2.7 backport called [trollius](https://pypi.python.org/pypi/trollius)).

If the main purpose of this issue is to track progress towards asynchronous SSH support, shouldn't we rename the issue accordingly and consider asyncio support as another option that could replace having to support gevent (or similar libraries)?

**Comment by bitprophet** [comment]
asyncio is the same as 'tulip' right? (EDIT: yup, it is) - yes, I had my eye on that since last PyCon and it feels like the best place to start for this kind of topic.

I've got "look at a better way to do parallelism" on my plate for Fabric 2 (which used `multiprocessing` + Paramiko, for various reasons), as well as "push Fabric-y things back down into Paramiko where they make sense", so we'll see what happens there.

**Comment by nchammas** [comment]
Sounds good to me. Yes, asyncio seems to be the way of the future.

As an example of prior art in this space, you may want to take a look at the [asyncssh](https://github.com/ronf/asyncssh) project, which implements SSH using asyncio.

**Comment by ytrezq** [comment]
:+1:

**Comment by sivabudh** [comment]
+1

**Comment by giampaolo** [comment]
asyncio at this point is Python 3.X only as Trollius (the port of asyncio to python 2.7) is no longer being maintained. Tornado, gevent and Twisted would represent viable options as they work on both 2.X and 3.X. My personal preference would be Tornado, as it's self contained and well documented.

**Comment by Fizzadar** [comment]
I am using Paramiko + gevent without (many) issues for my [pyinfra](https://github.com/Fizzadar/pyinfra) project. Everything works as expected in Python 2 (with Paramiko < 2 & 2) - however in Python 3 the process hangs indefinitely (both Paramiko's) at:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/nick/.venvs/pyinfra3/lib/python3.5/site-packages/paramiko/transport.py", line 79, in _join_lingering_threads
    thr.stop_thread()
  File "/Users/nick/.venvs/pyinfra3/lib/python3.5/site-packages/paramiko/transport.py", line 1536, in stop_thread
    self.join(10)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 1058, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/Users/nick/Dropbox/Oxygem/Webroot/pyinfra/src/pyinfra/__main__.py", line 85, in _signal_handler
    sys.exit(0)
SystemExit: 0
```

Weirdly - this has only just started happening. I have previously been able to run deploys using Python 3 without issue.

**Comment by YevIgn** [comment]
Also, I recently used paramiko 2.0.2 (through plumbum's PramikoMachine) successfully with the eventlet 0.19 under Python 3.5.2. Everything (uploading/downloading files, long-running commands, etc.) worked flawlessly.

**Comment by johnarnold** [comment]
Is anybody working on this?

**Comment by johnarnold** [comment]
@bitprophet I had similar thoughts.  I just completed some code using asyncio event loop + ThreadPoolExecutor to get thread-level parallelism with paramiko (netmiko), but I think it's going to suck performance-wise when communicating on more than a few dozen (?hundred?) devices.   Process parallelism has its own headaches, and either way we're still blocking on I/O within threads.

I'd like to see paramiko fix the blocking-on-io thing with async/await methods to optimize single-thread performance, and let the users sort out thread-vs-process for their intended app.  I can probably contribute to that, but I would like to first hear thoughts on how to proceed -- my bias is to implement new async classes/methods for Python3 and python2.7 can stay the way it is.  Thoughts?

**Comment by bitprophet** [comment]
If there's no useful 2.7 analogue (my Python ~3.3 era memory is of the 'tulip' backport library, but no idea if that maps to the newer 3.4/3.5 constructs) then yea, "extra goodness if you're on 3.5+" sounds reasonable, as long as the code is organized cleanly. Thanks!

**Comment by Fizzadar** [comment]
Just to note on performance - [pyinfra](https://github.com/Fizzadar/pyinfra) is using paramiko + gevent (working perfectly) and I've found that this scales amazingly well across hundreds of hosts (limiting the gevent pool to ~75-100 gives the best performance, above that things slow down), especially when compared to threaded solutions like Ansible. There's a chart of results [here](https://github.com/Fizzadar/pyinfra-performance/blob/develop/chart.png).

**Comment by vincenthcui** [comment]
In our project, we use paramiko within celery to check ssh port available, and use gevent as celery concurrent engine.Bug every time I try to connect ssh server by `client.connect`, gevent raise timeout exception.

I have try connect ssh server inner gevent Timeout context, but nothing changed.

timeout context example:
```
    with gevent.Timeout(5):
        client.connect(ip, port, user, passwd, timeout=timeout, look_for_keys=False)
        stdin, stdout, stderr = client.exec_command(command)
```

timeout exception traceback:
```
Traceback (most recent call last):
  File "/data/backend/tasks/tools.py", line 300, in inner
    last_success = func(*args, **kwargs)
  File "/data/backend/tasks/tools.py", line 330, in inner
    return func(task, last_success, *args, **kwargs)
  File "/data/backend/tasks/qcloudresource/cvm/__init__.py", line 336, in check_port_status
    ssh.test_connection(ip, ssh_port, user, password, command=command)
  File "/data/backend/tools/ssh.py", line 34, in test_connection
    client.connect(ip, port, user, passwd, timeout=timeout, look_for_keys=False)
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 343, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python2.7/site-packages/paramiko/util.py", line 280, in retry_on_signal
    return function()
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 343, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python2.7/site-packages/gevent/_socket2.py", line 236, in connect
    self._wait(self._write_event)
  File "/usr/local/lib/python2.7/site-packages/gevent/_socket2.py", line 182, in _wait
    self.hub.wait(watcher)
  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 651, in wait
    result = waiter.get()
  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 898, in get
    return self.hub.switch()
  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
timeout: timed out
```

**Comment by graingert** [comment]
this might be worth revisiting now that Python 2 support may be dropped soon. Also I'd like to see a sansio interface like h2/h11

**Comment by inlann** [comment]
Is there any updates?
