### ISSUE TITLE
Weird error with older device

### ISSUE THREAD

**Issue by markomo** [paramiko/paramiko#456]
Error:

```
Traceback (most recent call last):
  File "exscript test.py", line 17, in <module>
    conn.login(account)
  File "C:\Python27\lib\site-packages\exscript-development-py2.7.egg\Exscript\protocols\Protocol.py", line 594, in login

    self.authenticate(account, flush = False)
  File "C:\Python27\lib\site-packages\exscript-development-py2.7.egg\Exscript\protocols\Protocol.py", line 617, in authe
nticate
    self.protocol_authenticate(account)
  File "C:\Python27\lib\site-packages\exscript-development-py2.7.egg\Exscript\protocols\Protocol.py", line 643, in proto
col_authenticate
    self._protocol_authenticate(user, password)
  File "C:\Python27\lib\site-packages\exscript-development-py2.7.egg\Exscript\protocols\SSH2.py", line 267, in _protocol
_authenticate
    self._paramiko_shell()
  File "C:\Python27\lib\site-packages\exscript-development-py2.7.egg\Exscript\protocols\SSH2.py", line 256, in _paramiko
_shell
    raise LoginFailure('Failed to open shell: ' + str(e))
Exscript.protocols.Exception.LoginFailure: Failed to open shell: Channel closed.
```

Code: 

```
from Exscript.util.interact import read_login
from Exscript.protocols import SSH2
import time
import re

account = read_login()
host = raw_input("Please type the hostname: ")

commandfile = open('commands.txt')
p = re.compile(ur'(.+?)\n')
active = commandfile.read()
commands = re.findall(p, active)
commandfile.close()

conn = SSH2()
conn.connect(str(host))
conn.login(account)

for cmd in commands:
    print "current command: ",cmd
    conn.execute(str(cmd))
    print "Response was:", conn.response
    time.sleep(1)



conn.send('exit\r')
conn.close()
```

It works fine with other hosts, and the host I am trying it against works with putty when forced to SSH v1 and v2

How can I troubleshoot this? I recreated the error in a program only using paramiko

Error:

```
Traceback (most recent call last):
  File "ssh.py", line 24, in <module>
    stdin, stdout, stderr = ssh.exec_command(cmd)
  File "build\bdist.win32\egg\paramiko\client.py", line 345, in exec_command
  File "build\bdist.win32\egg\paramiko\channel.py", line 60, in _check
  File "build\bdist.win32\egg\paramiko\channel.py", line 229, in exec_command
  File "build\bdist.win32\egg\paramiko\channel.py", line 1086, in _wait_for_event
paramiko.ssh_exception.SSHException: Channel closed.
```

Code:

```
import paramiko
import getpass
import time
import re

user = raw_input("Please type the username: ")
password = getpass.getpass("Please type the password: ")
host = raw_input("Please type the hostname: ")

commandfile = open('commands.txt')
p = re.compile(ur'(.+?)\n')
active = commandfile.read()
commands = re.findall(p, active)
commandfile.close()

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(host, username=user, password=password)

leangh = len(commands)
print commands
for i, cmd in enumerate(commands):
    print "current command ",i+1," of ",leangh,": ",cmd
    stdin, stdout, stderr = ssh.exec_command(cmd)
    print "Response was:", stdout.readlines()
    time.sleep(1)
```

**Comment by teadur** [comment]
same problem as issue #96
