### ISSUE TITLE
paramiko.ssh_exception.SSHException: SSH session not active

### ISSUE THREAD

**Issue by gauravvjn** [paramiko/paramiko#464]
I'm trying to SFTP into remote machine using this piece of code

``` python
import paramiko

import logging
logging.basicConfig()

host = 'ftp.xyz.com'
username = 'myusername'
password = 'mypassword'

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
try:
    ssh.connect(host, username=username, password=password)
except paramiko.SSHException:
    print "Connection Error"
sftp = ssh.open_sftp()
print sftp.listdir()
ssh.close()
```

but I'm getting this error

```
ERROR:paramiko.transport:Exception: Incompatible ssh server (no acceptable compression) [] [] ('none',)
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/home/eric/Desktop/env/local/lib/python2.7/site-packages/paramiko/transport.py", line 1614, in run
ERROR:paramiko.transport:    self._handler_table[ptype](self, m)
ERROR:paramiko.transport:  File "/home/eric/Desktop/env/local/lib/python2.7/site-packages/paramiko/transport.py", line 1694, in _negotiate_keys
ERROR:paramiko.transport:    self._parse_kex_init(m)
ERROR:paramiko.transport:  File "/home/eric/Desktop/env/local/lib/python2.7/site-packages/paramiko/transport.py", line 1858, in _parse_kex_init
ERROR:paramiko.transport:    raise SSHException('Incompatible ssh server (no acceptable compression) %r %r %r' % (agreed_local_compression, agreed_remote_compression, self._preferred_compression))
ERROR:paramiko.transport:SSHException: Incompatible ssh server (no acceptable compression) [] [] ('none',)
ERROR:paramiko.transport:
Connection Error
Traceback (most recent call last):
  File "sftp_test.py", line 17, in <module>
    sftp = ssh.open_sftp()
  File "/home/eric/Desktop/env/local/lib/python2.7/site-packages/paramiko/client.py", line 379, in open_sftp
    return self._transport.open_sftp_client()
  File "/home/eric/Desktop/env/local/lib/python2.7/site-packages/paramiko/transport.py", line 811, in open_sftp_client
    return SFTPClient.from_transport(self)
  File "/home/eric/Desktop/env/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 128, in from_transport
    max_packet_size=max_packet_size)
  File "/home/eric/Desktop/env/local/lib/python2.7/site-packages/paramiko/transport.py", line 615, in open_session
    max_packet_size=max_packet_size)
  File "/home/eric/Desktop/env/local/lib/python2.7/site-packages/paramiko/transport.py", line 696, in open_channel
    raise SSHException('SSH session not active')
paramiko.ssh_exception.SSHException: SSH session not active
```

pip freeze>

``````
ecdsa==0.11
paramiko==1.15.2
pycrypto==2.6.1```

PS: I'm able to SFTP using terminal.
``````

**Comment by rsimchuk** [comment]
@safiyat 
```
SSHException: Unable to open channel.
```
Received.
