### ISSUE TITLE
Broken pipe when ProxyCommand is used

### ISSUE THREAD

**Issue by pedromagnus** [paramiko/paramiko#495]
Hi there. Apparently last version (1.15.2) has a change that raises a `ProxyCommandFailure` (Broken pipe) when tunneling a deploy process using Fabric 1.10.1.

**Comment by bitprophet** [comment]
I don't see other reports of this elsewhere, can you provide a detailed reproduction case?

ProxyCommand got a lot of love in 1.15.2 (see http://www.paramiko.org/changelog.html) so it doesn't surprise me that some other use cases may have inadvertently suffered. Thanks for the report!

**Comment by pedromagnus** [comment]
Hi there!
As I don't know the level of detail I am authorized to give because of the nature of the project, I edited the traceback replacing some important URLs or data with `<stuff like this>`. As those replacements aren't important on the (crossing fingers here) resolution of the error, I think no harm could be done to anyone.
Here is the traceback: https://gist.github.com/pedromagnus/2f9017ebf706619a4142
Again: this happens just in 1.15.2, in 1.15.1 works fine.
Thanks in advance!

**Comment by bitprophet** [comment]
Thanks, great to know it specifically broke in 1.15.2, that should help narrow it down. And that traceback should be fine. Assigning to release milestone.

**Comment by Strekerud** [comment]
Hello! We seem to be having the same issue with our project. Great to know it's beeing looked at!

**Comment by bitprophet** [comment]
(Months later...) I can't reproduce this on my end :(

Using a checkout of the 1.15.2 tag, setting `env.use_ssh_config = True` in my fabfile, having `~/.ssh/config` set to use a (known to be working in regular ssh use) gateway for a test target host, and confirming that the ProxyCommand is in fact running while the session is active.

All that is hunky dory and doing both basic things like `whoami` and longer things like `cat <huge log file>` fail to reproduce the traceback provided.

if @pedromagnus or @Strekerud can provide more deets about the circumstances of the error (e.g.: is it only happening, say, 5 minutes into a nontrivial deploy process, or right away? Does it happen for all tasks or just a specific task? If you trim down your deploy task to something very small, does the problem still occur? Etc etc.) maybe something will pop up.

I reviewed the diff of 1.15.1-1.15.2 and there's a few tweaks that *might* contribute to this kind of error but nothing that seems specifically suspicious :(

**Comment by Strekerud** [comment]
Hi,

@bitprophet, thanks for looking into it.

Tried installing 1.16.0 today and tried to deploy, but still found myself having to revert back to 1.15.1, which still works fine.

Traceback gist: https://gist.github.com/Strekerud/c314d1b76188f5b1f769

It seems like the error happens quite early on in the deployment.

**Comment by ddimensia** [comment]
I get the same behavior as @Strekerud, 1.15.1 works as expected.

**Comment by kaaveland** [comment]
Don't know if this is helpful, but I just introduced a change in our deploy script today that made this error surface. I'll try to describe the change I made (I unfortunately cannot make this code public) in case it is helpful.

We're using fabric/paramiko to deploy (And I'm starting to believe that the problem is caused in the fabric layer) through a "management host" that has network access to our hosts. So we're dependent on ProxyCommand to actually reach the servers that run our apps.

This has been working fine until today. What I did today was to introduce a change that would mutate temporarily change fabrics hosts-list; simplified it looks something like this:
```python
def upload(app):
    with api.settings(hosts=[app.hosts[0]]):
        api.local('rsync ...')
    with api.settings(hosts=[app.hosts[1]):
        # downloads app from app.hosts[0] -- this works fine
```
This runs inside a block that sets hosts like this:
```python
with api.settings(hosts=app.hosts):
    upload(app)
    api.execute(restart)
```
The upload-function will work just fine, but the restart step will fail consistently with ProxyCommandFailure. I'm thinking (without knowing the fabric code very well) that fabric invalidates the connection when `hosts` changes, but forgets to invalidate the running ProxyCommand. 

Either way, I can successfully work around this issue by deleting the relevant connections from `fabric.state.connections` between the upload and restart step. My best guess is that the other people who posted here use fabric as well, so maybe this should be registered as a fabric issue?

**Comment by bitprophet** [comment]
@kaaveland It's certainly plausible that the issue is in fabric's hosts handling, I'd have to look. IIRC the gateway/proxy settings are kept on the Paramiko client object so it *shouldn't* be a problem, but I could be wrong or there could be a wrinkle I'm not recalling. Thanks a lot for the info.

**Comment by kaaveland** [comment]
I can't reproduce it using fabrics gateway-setting, so I think it's also plausible that there's a problem with ProxyCommand (maybe a premature `.close()` in some edge-case)?

**Comment by notpeter** [comment]
I ran into a similar issue using fabric that resulted in the same traceback:
````
paramiko.ssh_exception.ProxyCommandFailure: ('ssh -p XXXX bastion.domain.tld nc host.domain.tld 22 2>/dev/null', 'Broken pipe')
````

Which I was able to solved by adding `env.gateway = 'bastion.domain.tld:XXXX' to my fabfile.  Previously I had just relied on `env.use_ssh_config = True` to get me to the correct host.

My issue had a different cause (user initiated ctrl-c being delivered to `nc` running on the bastion instead of to the process running on the private host) but I figured I'd mention it here in case maybe other people's might be solved with the same workaround.

**Comment by int32bit** [comment]
I ran into a similar issue but not using  fabric, is there an alternative solution?

**Comment by bitprophet** [comment]
@int32bit doesn't look like anyone's actually nailed down quite what the problem is yet, Fabric or no Fabric. If you can share details about your setup (versions of paramiko, python, OS etc; traceback; your code; etc etc) that might help - thanks!

**Comment by steven-sortable** [comment]
I think there's a race condition [in `Transport.run`](https://github.com/paramiko/paramiko/blob/5915e9c991cdf5cacdaa1542c9330b2ca9b11208/paramiko/transport.py#L1708-L1710) which is relevant to this issue.

Suppose the target host is not accepting connections (say, because it's rebooting after a deploy), the proxy command will be unable to connect to it and its process will exit.  If it exits before the call to `self.packetizer.write_all`, then that function will try to write to a pipe with no process on the other side, so it will fail with `Broken pipe`, throwing a `ProxyCommandFailure`.  But if the proxy command process exits after the call to `write_all`, then it will be `_check_banner` that fails, throwing `SSHException` with message `"Error reading SSH protocol banner"`.

(How to confirm this race:  (1) Insert `time.sleep(5)` before the call to `write_all` and see that it's all `ProxyCommandFailure`.  (2) Move the call to `_check_banner` to before the call to `write_all` and see that it's all `SSHException`.)

In the context of fabric, this race causes intermittent deployment failures during reboots because fabric [will retry on `"Error reading SSH protocol banner"`](https://github.com/fabric/fabric/blob/ce18b67efe5985cdb0887c9edc55b03fc25fea6e/fabric/network.py#L501-L508) but not on a `ProxyCommandFailure`.

I'm not sure what is best to do about this if it's true.  Moving the call to `_check_banner` to before the call to `write_all` would make this code will reliably throw `SSHException` when the target host is down (and then fabric would retry as desired), but it would mean that paramiko waits for the server's version before sending its own, and I don't know the consequences of that.

**Comment by twirrim** [comment]
Ran in to this myself.

To connect to our servers I have to go via bastion boxes.  I've told fabric to use my ssh config.  I initiated a reboot of the remote host, and while it did successfully trigger off a reboot, the command eventually failed (still experimenting to see if that's because it isn't waiting long enough. Certainly plausible, given it's a physical host being rebooted, rather than a virtual machine)
Once that reboot failed, I've been unable to re-establish a connection.

`>>> run("uname -r")
....
    raise ProxyCommandFailure(' '.join(self.cmd), e.strerror)
paramiko.ssh_exception.ProxyCommandFailure: ('ssh -q -W target.server:22 bastion.server.address', 'Broken pipe')`

Not sure if there is a way to force fabric/paramiko to invalidate the session and re-establish.  Changing the host string to another location, and then back again, doesn't seem to achieve that.

**Comment by TomCos** [comment]
Can confirm this is still an issue in Paramiko 2.4.1.

IOError is being generated at self.process.stdin.write(content) in the send function

**Comment by TomCos** [comment]
I was able to replicate the broken pipe issue and I think I might have an answer for this thread.  Any time I was receiving broken pipe, if I did the ssh -v manually outside of paramiko, the real error would show.  For example I had some key exchange issues.  In paramiko, it shows up as broken pipe.  I suggest any proxycommand you're trying, do it by hand, it might show your actual issue.

**Comment by JaldhiPandya** [comment]
Facing the same issue with paramiko-2.7
Any help is appreciated.

**Comment by ViCrack** [comment]
> 

Facing the same issue with fabric Paramiko-2.9.2

```
Traceback (most recent call last):
  File "c:\app\python38-32\lib\site-packages\fabric\network.py", line 485, in connect
    client.connect(**kwargs)
  File "c:\app\python38-32\lib\site-packages\paramiko\client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "c:\app\python38-32\lib\site-packages\paramiko\transport.py", line 698, in start_client
    raise e
  File "c:\app\python38-32\lib\site-packages\paramiko\transport.py", line 2093, in run
    self._check_banner()
  File "c:\app\python38-32\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "c:\app\python38-32\lib\site-packages\paramiko\packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "c:\app\python38-32\lib\site-packages\paramiko\packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
  File "c:\app\python38-32\lib\site-packages\paramiko\proxy.py", line 119, in recv
    raise ProxyCommandFailure(" ".join(self.cmd), e.strerror)
paramiko.ssh_exception.ProxyCommandFailure: ProxyCommand("ssh.exe -q -x -N -W xxx.xxx.0.xxx:22 xxx.xxx.0.70") returne
d nonzero exit status
```

**Comment by gilad9366** [comment]
Having the same issue with version Paramiko 2.7.2.
It's flaky but reproduces most of the time.
Happens when I use EC2 Instance Connect, not sure if it's relevant.
Code:
```
c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect(hostname=ip, username="ubuntu", sock=proxy_cmd, key_filename=private_key_path)
```
Error:
```
ProxyCommand("ssh ubuntu@x.x.x.x -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W y.y.y.y:22 -o IdentitiesOnly=yes -i path/to/key") returned nonzero exit status: Broken pipe
```

**Comment by AlexPetul** [comment]
The same issue here, paramiko==2.8.1

`{"msg": "Failed to open session: ProxyCommand(\"ssh -I ~/keys/somekey -W 192.168.1.6:22 -q pradmin@jumphost\") returned nonzero exit status: Broken pipe", "_ansible_no_log": false}`
