### ISSUE TITLE
_winapi.py: NameError: global name 'descriptor' is not defined

### ISSUE THREAD

**Issue by fredricj** [paramiko/paramiko#497]
Traceback (most recent call last):
  File "C:\Program Files\MySQL\MySQL Workbench 6.2 CE\sshtunnel.py", line 265, in _connect_ssh
    look_for_keys=has_key, allow_agent=has_key)
  File "C:\Program Files\MySQL\MySQL Workbench 6.2 CE/python/site-packages\paramiko\client.py", line 366, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "C:\Program Files\MySQL\MySQL Workbench 6.2 CE/python/site-packages\paramiko\client.py", line 515, in _auth
    self._agent = Agent()
  File "C:\Program Files\MySQL\MySQL Workbench 6.2 CE/python/site-packages\paramiko\agent.py", line 343, in __init__
    self._connect(conn)
  File "C:\Program Files\MySQL\MySQL Workbench 6.2 CE/python/site-packages\paramiko\agent.py", line 66, in _connect
    ptype, result = self._send_message(cSSH2_AGENTC_REQUEST_IDENTITIES)
  File "C:\Program Files\MySQL\MySQL Workbench 6.2 CE/python/site-packages\paramiko\agent.py", line 83, in _send_message
    self._conn.send(struct.pack('>I', len(msg)) + msg)
  File "C:\Program Files\MySQL\MySQL Workbench 6.2 CE/python/site-packages\paramiko\win_pageant.py", line 123, in send
    self._response = _query_pageant(data)
  File "C:\Program Files\MySQL\MySQL Workbench 6.2 CE/python/site-packages\paramiko\win_pageant.py", line 89, in _query_pageant
    _winapi.get_security_attributes_for_user(),
  File "C:\Program Files\MySQL\MySQL Workbench 6.2 CE/python/site-packages\paramiko\_winapi.py", line 273, in get_security_attributes_for_user
    SA.descriptor = SD
  File "C:\Program Files\MySQL\MySQL Workbench 6.2 CE/python/site-packages\paramiko\_winapi.py", line 222, in descriptor
    self._descriptor = descriptor
NameError: global name 'descriptor' is not defined

**Comment by lndbrg** [comment]
Being tracked with patch in #488.
