### ISSUE TITLE
Unexpected SSHException: Error reading SSH protocol banner(10038, 'An operation was attempted on something that is not a socket)

### ISSUE THREAD

**Issue by toniatop** [paramiko/paramiko#512]
I am trying to set up a ssh connection through paramiko, using a proxy. 

Considering the following code:

    import paramiko
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    sock = paramiko.ProxyCommand('ssh user@proxy_host nc host 22')
    ssh.connect(host, username='my_username',sock=sock) 
    stdin,stdout,stderr = ssh.exec_command("ls .") 
    ssh.close()
Under cygwin it works just fine. 
On the same machine, under Windows 8.1 it gives:

    No handlers could be found for logger "paramiko.transport"
    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "C:\Users\user\Anaconda\lib\threading.py", line 810, in __bootstrap_inner
        self.run()
      File "build\bdist.win-amd64\egg\paramiko\transport.py", line 1673, in run
        self.sock.close()
      File "build\bdist.win-amd64\egg\paramiko\proxy.py", line 110, in close
        os.kill(self.process.pid, signal.SIGTERM)
    WindowsError: [Error 5] Access is denied
    
    Traceback (most recent call last):
      File ".\test_python_ssh.py", line 14, in <module>
        ssh.connect(host, username='my_username',sock=sock) 
      File "build\bdist.win-amd64\egg\paramiko\client.py", line 324, in connect
      File "build\bdist.win-amd64\egg\paramiko\transport.py", line 406, in start_client
    paramiko.ssh_exception.SSHException: Error reading SSH protocol banner(10038, 'An operation was attempted on something t
    hat is not a socket')

Any ideas how to solve the situation?

**Comment by jrvilda** [comment]
I have a similar problem.

Environment:
```
>ver
Microsoft Windows [Versión 6.1.7601]
>python
ActivePython 2.6.7.20 (ActiveState Software Inc.) based on
Python 2.6.7 (r267:88850, Jun 27 2011, 13:56:33) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print paramiko.__version__
1.15.2
```

Execution failed :

```
>>> import paramiko
>>> ssh = paramiko.SSHClient()
>>> ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> sock = paramiko.ProxyCommand('connect.exe -4 -S proxy:1080 %h %p')
>>> ssh.connect('host', username='user',sock=sock)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python26\lib\threading.py", line 534, in __bootstrap_inner
    self.run()
  File "C:\Python26\lib\site-packages\paramiko\transport.py", line 1661, in run
    self.packetizer.close()
  File "C:\Python26\lib\site-packages\paramiko\packet.py", line 153, in close
    self.__socket.close()
  File "C:\Python26\lib\site-packages\paramiko\proxy.py", line 110, in close
    os.kill(self.process.pid, signal.SIGTERM)
AttributeError: 'module' object has no attribute 'kill'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python26\lib\site-packages\paramiko\client.py", line 265, in connect
    t.start_client()
  File "C:\Python26\lib\site-packages\paramiko\transport.py", line 406, in start_client
    raise e
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner(10038, 'Se intent\xf3 realizar una operaci\xf3n en un elemento que no es un socket')

>>> stdin,stdout,stderr = ssh.exec_command("ls .")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python26\lib\site-packages\paramiko\client.py", line 341, in exec_command
    chan = self._transport.open_session()
  File "C:\Python26\lib\site-packages\paramiko\transport.py", line 615, in open_session
    max_packet_size=max_packet_size)
  File "C:\Python26\lib\site-packages\paramiko\transport.py", line 696, in open_channel
    raise SSHException('SSH session not active')
paramiko.ssh_exception.SSHException: SSH session not active
>>> ssh.close()
>>>
```

With openssh for windows and changing ssh_config file, OK
```
>more ssh_config
Host *
ProxyCommand connect.exe -4 -d -S proxy:1080 %h %p
>ssh user@host
```
I offer to help in any way possible.

**Comment by Lauregos** [comment]
I have the same issue as well, and some more information which might be useful. 

Debugging the application, I found the error to be triggered by the `select()` call in `recv()` in `proxy.py`:
`
r, w, x = select(
    [self.process.stdout], [], [], select_timeout)
`

[Apparently](https://docs.python.org/2/library/socket.html), select doesn't work on file objects (like stdout) on Windows. Instead another method to read from the process opened by the ProxyCommand would have to be implemented.

**Comment by JulianEberius** [comment]
I've encountered this Windows issue as well. I fixed in my fork by simply using a blocking read() call on Windows, instead of the select-then-read. This is actually the implementation as it was before 2014: 

https://github.com/paramiko/paramiko/commit/58489c893e3f62947ee8235c2a07fc5465949aeb#diff-da0434ac18262900f26e452884887940

My simple fix is 

https://github.com/JulianEberius/paramiko/commit/bb1f795db46891961b6a816df3c59e132de7f211

While this is fine for my use case, I'm not sure if this is good enough for a PR. Is there anything I can do to improve on this?

**Comment by ploxiln** [comment]
I'd go ahead and open a pull request with that. It's simple, and it definitely improves the case for windows, while not hurting it for anything else.

**Comment by feland207** [comment]
> I've encountered this Windows issue as well. I fixed in my fork by simply using a blocking read() call on Windows, instead of the select-then-read. This is actually the implementation as it was before 2014:
> 
> [58489c8#diff-da0434ac18262900f26e452884887940](https://github.com/paramiko/paramiko/commit/58489c893e3f62947ee8235c2a07fc5465949aeb#diff-da0434ac18262900f26e452884887940)
> 
> My simple fix is
> 
> [JulianEberius@bb1f795](https://github.com/JulianEberius/paramiko/commit/bb1f795db46891961b6a816df3c59e132de7f211)
> 
> While this is fine for my use case, I'm not sure if this is good enough for a PR. Is there anything I can do to improve on this?

Hi @JulianEberius , I'm having the same issue under windows as you described and would like to try your workaround. Should I just modify the lines on paramiko/proxy.py to what you wrote? 

Does this mean replace on proxy.py from lines 17 to 89? As a reference this is my proxy.py: 
[proxy.zip](https://github.com/paramiko/paramiko/files/3827400/proxy.zip)

Thanks for taking the time to reply this. 

Regards,

**Comment by lfourquaux** [comment]
This happens e.g. when using ProxyCommand with Xpra (client) on Windows.

**Comment by geblanco** [comment]
Working in Linux here, happens the same.

**Comment by p-sherratt** [comment]
Same here - fix from @JulianEberius works for me too.. any chance in opening a pull request to get this merged in next release?

**Comment by leicaoatcanoo** [comment]
> I've encountered this Windows issue as well. I fixed in my fork by simply using a blocking read() call on Windows, instead of the select-then-read. This is actually the implementation as it was before 2014:
> 
> [58489c8#diff-da0434ac18262900f26e452884887940](https://github.com/paramiko/paramiko/commit/58489c893e3f62947ee8235c2a07fc5465949aeb#diff-da0434ac18262900f26e452884887940)
> 
> My simple fix is
> 
> [JulianEberius@bb1f795](https://github.com/JulianEberius/paramiko/commit/bb1f795db46891961b6a816df3c59e132de7f211)
> 
> While this is fine for my use case, I'm not sure if this is good enough for a PR. Is there anything I can do to improve on this?

Works like a charm! Thank you so much.

**Comment by jun66j5** [comment]
I posted pull request #2130 (timeout works in the changes). We could use `WaitForSingleObject()` for stdout of `ProxyCommand` instead of `select()` on Windows.
