### ISSUE TITLE
NameError: global name 'descriptor' is not defined

### ISSUE THREAD

**Issue by setevoy2** [paramiko/paramiko#538]
Paramiko 1.16.0 - under Windows 8 faced with issue, described here:
https://github.com/paramiko/paramiko/issues/461

>>> ssh.connect('54.***.***.110', key_filename='D:\Keys\MyOWN\setevoy_priv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\paramiko\client.py", line 366, in connect
  File "build\bdist.win32\egg\paramiko\client.py", line 515, in _auth
  File "build\bdist.win32\egg\paramiko\agent.py", line 343, in __init__
  File "build\bdist.win32\egg\paramiko\agent.py", line 66, in _connect
  File "build\bdist.win32\egg\paramiko\agent.py", line 83, in _send_message
  File "build\bdist.win32\egg\paramiko\win_pageant.py", line 123, in send
  File "build\bdist.win32\egg\paramiko\win_pageant.py", line 89, in _query_pageant
  File "build\bdist.win32\egg\paramiko\_winapi.py", line 273, in get_security_attributes_for_user
  File "build\bdist.win32\egg\paramiko\_winapi.py", line 223, in descriptor
NameError: global name 'descriptor' is not defined

**Comment by setevoy2** [comment]
Fixed locally with:

    @descriptor.setter
    def descriptor(self, value):
        self._descriptor = value
        self.lpSecurityDescriptor = ctypes.addressof(value)

**Comment by bitprophet** [comment]
Same as #488, no?
