### ISSUE TITLE
Possible Multi-threading problem?

### ISSUE THREAD

**Issue by urban-1** [paramiko/paramiko#567]
Hi all,

Does anyone know if paramiko connections can be used in threads? I found [this](https://answers.launchpad.net/ubuntu/+source/paramiko/+question/146803) saying that ```connect``` function is not thread-safe... but is old.

I have threads disappearing (stop logging at least). My main thread is hanging. This tends to happen after the following exception:

```
31-07-2015 20:41:48 26100 ERROR       transport.py: Exception: Incompatible version (1.5 instead of 2.0)
31-07-2015 20:41:48 26100 ERROR       transport.py: Traceback (most recent call last):
31-07-2015 20:41:48 26100 ERROR       transport.py:   File "/usr/lib/pymodules/python2.6/paramiko/transport.py", line 1516, in run
31-07-2015 20:41:48 26100 ERROR       transport.py:     self._check_banner()
31-07-2015 20:41:48 26100 ERROR       transport.py:   File "/usr/lib/pymodules/python2.6/paramiko/transport.py", line 1654, in _check_banner
31-07-2015 20:41:48 26100 ERROR       transport.py:     raise SSHException('Incompatible version (%s instead of 2.0)' % (version,))
31-07-2015 20:41:48 26100 ERROR       transport.py: SSHException: Incompatible version (1.5 instead of 2.0)
```

My problem might be totally unrelated with paramiko but I thought I should ask... feel free to close this if it is irrelevant.

Thanks in advance,

Andreas 

on:
Python 2.6.6 (r266:84292, Dec 26 2010, 22:31:48)
[GCC 4.4.5] on linux2
debian 6

**Comment by urban-1** [comment]
AaaHmmm ignore and close this!

Explanation:

Seemed like ```connect``` was causing the problem. However, paramiko is wrapped into ```device``` class here which tries to disconnect from the device "properly" issuing a series of commands (exit, Ctrl-Z, logout, etc). This generates messages that were not needed when running unittest suite... Therefore it was wrapped in this awesome (but very stupid in this case - disabling logging) decorator:

```
def nologging(func):
    """
    Decorator that disables logging
    """
    @wraps(func)
    def inner(*args, **kwargs):
        previousloglevel = lg.getLogger().getEffectiveLevel()
        lg.getLogger().setLevel(lg.ERROR+10)
        try:
            return func(*args, **kwargs)
        finally:
            lg.getLogger().setLevel(previousloglevel)
    return inner
``` 

I know... I shouldn't be coding at this time on a Friday... Apologies again.

Andreas
