### ISSUE TITLE
public-key auth works in shell, not working in paramiko for some hosts

### ISSUE THREAD

**Issue by l4cr0ss** [paramiko/paramiko#574]
System info:
> -\> uname -a
&nbsp;&nbsp;&nbsp;&nbsp;Linux ... 3.14.37-ti-r57 #1 SMP PREEMPT Fri Apr 3 20:41:12 UTC 2015 armv7l GNU/Linux
-\> python3 -V
&nbsp;&nbsp;&nbsp;&nbsp;Python 3.4.2

Installed paramiko:
> -\> sudo pip3 install paramiko
-\> python3 -c "import paramiko; print(paramiko.\_\_version\_\_)"
&nbsp;&nbsp;&nbsp;&nbsp;1.15.2
-\> python -c "import paramiko; print(paramiko.\_\_version\_\_)"
&nbsp;&nbsp;&nbsp;&nbsp;1.16.0

Simple connection code:
> #!/usr/bin/python3 /* also tested with #!/usr/bin/python */
> import paramiko
> import sys
>
> paramiko.util.log_to_file('ssh.log')
> client = paramiko.SSHClient()
> client.load_system_host_keys()
> client.connect(sys.argv[1])
> stdin, stdout, stderr = client.exec_command('ls -l')

Bash connects to both machines:
>-\> ssh `hostname`

Paramiko connects to this machine:
>Linux ... 2.6.18-308.el5 #1 SMP Fri Jan 27 17:17:51 EST 2012 x86_64 x86_64 x86_64 GNU/Linux
>python3: not present
>python: 2.4.3
OpenSSH_4.3p2, OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

Paramiko doesn't connect to this machine:
>Linux ... 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux
python3: 3.2.3
python: 2.7.3
OpenSSH_6.0p1 Debian-4+deb7u2, OpenSSL 1.0.1e 11 Feb 2013

Paramiko runtime exception:
> -\> ./example.py 10.11.6.87
> Traceback (most recent call last):
>   &nbsp;&nbsp;File "./example.py", line 8, in <module>
>   &nbsp;&nbsp;&nbsp;&nbsp;client.connect(sys.argv[1])
>   &nbsp;&nbsp;File "/usr/local/lib/python3.4/dist-packages/paramiko/client.py", line 288, in connect
>   &nbsp;&nbsp;&nbsp;&nbsp;server_key)
>   &nbsp;&nbsp;File "/usr/local/lib/python3.4/dist-packages/paramiko/client.py", line 570, in missing_host_key
>   &nbsp;&nbsp;&nbsp;&nbsp;raise SSHException('Server %r not found in known_hosts' % hostname)
> paramiko.ssh_exception.SSHException: Server '10.11.6.87' not found in known_hosts

Paramiko log output:
>DEB [20150814-10:27:54.648] thr=1   paramiko.transport: starting thread (client mode): 0xb660bf30
>INF [20150814-10:27:54.709] thr=1   paramiko.transport: Connected (version 2.0, client OpenSSH_6.0p1)
>DEB [20150814-10:27:54.715] thr=1   paramiko.transport: kex algos:['ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'arcfour256', 'arcfour128', 'aes128-cbc', '3des-cbc', 'blowfish-cbc', 'cast128-cbc', 'aes192-cbc', 'aes256-cbc', 'arcfour', 'rijndael-cbc@lysator.liu.se'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'arcfour256', 'arcfour128', 'aes128-cbc', '3des-cbc', 'blowfish-cbc', 'cast128-cbc', 'aes192-cbc', 'aes256-cbc', 'arcfour', 'rijndael-cbc@lysator.liu.se'] client mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-sha2-256', 'hmac-sha2-256-96', 'hmac-sha2-512', 'hmac-sha2-512-96', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] server mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-sha2-256', 'hmac-sha2-256-96', 'hmac-sha2-512', 'hmac-sha2-512-96', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
>DEB [20150814-10:27:54.717] thr=1   paramiko.transport: Ciphers agreed: local=aes128-ctr, remote=aes128-ctr
>DEB [20150814-10:27:54.718] thr=1   paramiko.transport: using kex diffie-hellman-group14-sha1; server key type ssh-rsa; cipher: local aes128-ctr, remote aes128-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
>DEB [20150814-10:27:55.807] thr=1   paramiko.transport: Switch to new keys ...
>DEB [20150814-10:27:55.952] thr=2   paramiko.transport: Rejecting ssh-rsa host key for 10.11.6.87: b'bd2e0d95e8f2040850813db5beca9d08'
>DEB [20150814-10:27:56.028] thr=1   paramiko.transport: EOF in transport thread

Formatted the 3rd line a little bit:
>"kex algos": [
    "ecdh-sha2-nistp256",
    "ecdh-sha2-nistp384",
    "ecdh-sha2-nistp521",
    "diffie-hellman-group-exchange-sha256",
    "diffie-hellman-group-exchange-sha1",
    "diffie-hellman-group14-sha1",
    "diffie-hellman-group1-sha1"
  ],
  "server key": [
    "ssh-rsa",
    "ssh-dss",
    "ecdsa-sha2-nistp256"
  ],
  "client encrypt": [
    "aes128-ctr",
    "aes192-ctr",
    "aes256-ctr",
    "arcfour256",
    "arcour128",
    "aes128-cbc",
    "3des-cbc",
    "blowfish-cbc",
    "cast128-cbc",
    "aes192-cbc",
    "aes256-cbc",
    "arcfour",
   "rijndael-cbc@lysator.liu.se"
  ],
  "server encrypt": [
    "aes128-ctr",
    "aes192-ctr",
    "aes256-ctr",
    "arcfour256",
    "arcfour128",
    "aes128-cbc",
    "3des-cbc",
    "blowfish-cbc",
    "cast128-cbc",
    "aes192-cbc",
    "aes256-cbc",
    "arcfour",
    "rijndael-cbc@lysator.liu.se"
  ],
  "client mac": [
    "hmac-md5",
    "hmac-sha1",
    "umac-64@openssh.com",
    "hmac-sha2-256",
    "hmac-sha2-256-96",
    "hmac-sha2-512",
    "hmac-sha2-512-96",
    "hmac-ripemd160",
    "hmac-ripemd160@openssh.com",
    "hmac-sha1-96",
    "hmac-md5-96"
  ],
  "server mac": [
    "hmac-md5",
    "hmac-sha1",
    "umac-64@openssh.com",
    "hmac-sha2-256",
    "hmac-sha2-256-96",
    "hmac-sha2-512",
    "hmac-sha2-512-96",
    "hmac-ripemd160",
    "hmac-ripemd160@openssh.com",
    "hmac-sha1-96",
    "hmac-md5-96"
  ],
  "client compress": [
    "none",
    "zlib@openssh.com"
  ],
  "server compress": [
    "none",
    "zlib@openssh.com"
  ]

**Comment by l4cr0ss** [comment]
This is starting to look like an ECDSA <-> RSA key problem. Closing the issue until I can get more information.

**Comment by l4cr0ss** [comment]
This seems very much related to #387 and #435. I see that there are several commits supposedly addressing this problem but those two issues remain open. Is it safe to say this is an ongoing issue? Is there anyone working on it at the moment? I do not mind taking at a stab at it, if it's an open problem.

**Comment by mbr** [comment]
I'm willing to help out (I did submit a PR in #473), but I would like some official OK first =).

**Comment by bitprophet** [comment]
@l4cr0ss Ongoing, they're near the top of the list for the next release. It's all a thorny and related set of functionality so I'm hoping to rearchitect or at least rework it so things are clearer and easier to debug. Open to suggestions but I probably won't be able to merge any PRs unless they're pretty all-encompassing & well tested =/ (I.e. - most folks are only trying to solve one slice of this problem at a time)

**Comment by bitprophet** [comment]
(Re: timing, I'm planning to dig into it early next month if not sooner.)

**Comment by asajjans** [comment]
Hi All,
I'm seeing the below error when only ECDSA key is enabled on server side

DEBUG:paramiko.transport:starting thread (client mode): 0xea6c1748
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_6.6.1_hpn13v11)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group-exchange-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'curve25519-sha256@libssh.org'] server key:['ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['aes256-ctr', 'aes192-ctr', 'aes128-ctr', 'aes256-cbc', 'aes192-cbc', 'aes128-cbc', '3des-cbc', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['aes256-ctr', 'aes192-ctr', 'aes128-ctr', 'aes256-cbc', 'aes192-cbc', 'aes128-cbc', '3des-cbc', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-sha1-etm@openssh.com', 'hmac-sha1-96-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', ''] server mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-sha1-etm@openssh.com', 'hmac-sha1-96-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', ''] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Ciphers agreed: local=aes128-ctr, remote=aes128-ctr
DEBUG:paramiko.transport:using kex diffie-hellman-group14-sha1; server key type ssh-rsa; cipher: local aes128-ctr, remote aes128-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
DEBUG:paramiko.transport:EOF in transport thread
Traceback (most recent call last):
  File "./b.py", line 21, in <module>
    conn=ssh.connect(hostname='sti39-vsim-ucs505m.ctl.gdl.englab.netapp.com',port=22, username='admin',password='netapp1!')
  File "/usr/software/lib/python3.4/site-packages/paramiko-1.15.2-py3.4.egg/paramiko/client.py", line 265, in connect
  File "/usr/software/lib/python3.4/site-packages/paramiko-1.15.2-py3.4.egg/paramiko/transport.py", line 406, in start_client
  File "/usr/software/lib/python3.4/site-packages/paramiko-1.15.2-py3.4.egg/paramiko/transport.py", line 1592, in run
  File "/usr/software/lib/python3.4/site-packages/paramiko-1.15.2-py3.4.egg/paramiko/packet.py", line 341, in read_message
  File "/usr/software/lib/python3.4/site-packages/paramiko-1.15.2-py3.4.egg/paramiko/packet.py", line 206, in read_all
EOFError

It is trying to authenticate using 'ssh-rsa' and failing because that is not enabled on the server. But i think, if authentication using 'ssh-rsa' fails it should have tried with ECDSA key right?

Please help me if i'm missing anything and also help me how can force paramiko to use only ECDSA

Thanks and Regards,
Amresh
