### ISSUE TITLE
SSHException: Incompatible ssh peer (no acceptable kex algorithm) on specific service configutation

### ISSUE THREAD

**Issue by samuelsh** [paramiko/paramiko#600]
Hello,

I've got an issue that could be reproduction of #356. 
But there may be some other use case, related to specific sshd configuration on my server.

paramiko - 1.15.3
python - 2.6.6

2015-10-20 16:56:57,940;ERROR - Exception: Incompatible ssh peer (no acceptable kex algorithm)
2015-10-20 16:56:57,941;ERROR - Traceback (most recent call last):
2015-10-20 16:56:57,941;ERROR -   File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 1630, in run
2015-10-20 16:56:57,941;ERROR -     self._handler_table[ptype](self, m)
2015-10-20 16:56:57,941;ERROR -   File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 1711, in _negotiate_keys
2015-10-20 16:56:57,941;ERROR -     self._parse_kex_init(m)
2015-10-20 16:56:57,941;ERROR -   File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 1826, in _parse_kex_init
2015-10-20 16:56:57,941;ERROR -     raise SSHException('Incompatible ssh peer (no acceptable kex algorithm)')
2015-10-20 16:56:57,941;ERROR - SSHException: Incompatible ssh peer (no acceptable kex algorithm)
2015-10-20 16:56:57,941;ERROR -
2015-10-20 16:56:57,942;ERROR - Incompatible ssh peer (no acceptable kex algorithm)
Traceback (most recent call last):
  File "./set_ssh.py", line 65, in set_key_policy
    ssh.connect(host, username=username, password=password, port=port, timeout=30)
  File "/usr/lib/python2.6/site-packages/paramiko/client.py", line 265, in connect
    t.start_client()
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 408, in start_client
    raise e
SSHException: Incompatible ssh peer (no acceptable kex algorithm)

Server sshd_config:

# fixsshd: KexAlgorithms set to "diffie-hellman-group-exchange-sha256"
KexAlgorithms diffie-hellman-group-exchange-sha256
# fixsshd: Ciphers set to "aes256-cbc,aes256-ctr,aes128-cbc,aes128-ctr,aes192-cbc,aes192-ctr,3des-cbc"
Ciphers aes256-cbc,aes256-ctr,aes128-cbc,aes128-ctr,aes192-cbc,aes192-ctr,3des-cbc
# fixsshd: MACs set to "hmac-sha2-256,hmac-sha2-512"
MACs hmac-sha2-256,hmac-sha2-512

There's solution on stackoverflow that allowed the workaround http://stackoverflow.com/a/32691055/524743:
MACs hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,hmac-sha1

Thanks

**Comment by bitprophet** [comment]
It probably is the lack of SHA256 support as noted, but let's just leave this open & linked, and please follow #356 to retry your specific setup once that's merged (soon...finally). thanks!
