### ISSUE TITLE
Transport is close after forking

### ISSUE THREAD

**Issue by vsjha18** [paramiko/paramiko#620]
We have built a large scale for connecting to routers and switches. It is powered by paramiko and we extensively use "invoke_shell" to create channels and handle interactions. 

But when we make connection in the current process and use multiprocessing library to fork and use the handle in the child process, we get this error.

Success for unrequested channel! [??]
Traceback (most recent call last):
  File "unicon/demos/repro.py", line 19, in <module>
    stdin, stdout, stderr = client.exec_command("ifconfig")
  File "/Users/vivejha/Projects/cisco/lib/python3.4/site-packages/paramiko/client.py", line 401, in exec_command
    chan = self._transport.open_session(timeout=timeout)
  File "/Users/vivejha/Projects/cisco/lib/python3.4/site-packages/paramiko/transport.py", line 702, in open_session
    timeout=timeout)
  File "/Users/vivejha/Projects/cisco/lib/python3.4/site-packages/paramiko/transport.py", line 823, in open_channel
    raise e
paramiko.ssh_exception.SSHException: Unable to open channel.

This is not desirable, we cannot afford to see "transport" being closed in the child process. We can handle all the race conditions using some kind of process locks but we need the handles to at least work in the child process.

If you are suggesting to reconnect in the child process, then this will not be a good option because our connections takes time because we perform a lot for hardware checks during the connection procedure. We would still prefer to connect once and use the handles in the child process or main process.

Can you help us or suggest some workaround to solve this problem.

Regards
Vivek Jha

**Comment by mmohdnowfal** [comment]
We are also facing a similar issue, while using connection handles in child process, is there a fix for this. Also what is transport.Transport.atfork ? We thought we can control this problem using that, but it doesn't look like it is called anywhere in paramiko framework.

**Comment by vsjha18** [comment]
@bitprophet Is there any way we can workaround this.

**Comment by davescriptingspot** [comment]
@vsjha18 have you tried modifying  
stdin, stdout, stderr = handle.exec_command("ifconfig")

to 

stdin, stdout, stderr = handle.send("ifconfig\n")

?
