### ISSUE TITLE
ctypes.ArgumentError trying to connect to agent

### ISSUE THREAD

**Issue by thorstenkampe** [paramiko/paramiko#627]
I get the following exception (see below) from `agent.Agent()` under Python 3.5 64-bit when PuTTY Agent is running. The error does not occur under Python 3.4 64-bit or when PuTTY Agent is not running:
```
Traceback (most recent call last):
  File "F:\Documents\dev\python\script\resources\examples\ssh.py", line 57, in <module>
    agent_connection = paramiko.agent.Agent()
  File "F:\PortableApps\Python3x\lib\site-packages\paramiko\agent.py", line 363, in __init__
    self._connect(conn)
  File "F:\PortableApps\Python3x\lib\site-packages\paramiko\agent.py", line 66, in _connect
    ptype, result = self._send_message(cSSH2_AGENTC_REQUEST_IDENTITIES)
  File "F:\PortableApps\Python3x\lib\site-packages\paramiko\agent.py", line 83, in _send_message
    self._conn.send(struct.pack('>I', len(msg)) + msg)
  File "F:\PortableApps\Python3x\lib\site-packages\paramiko\win_pageant.py", line 123, in send
    self._response = _query_pageant(data)
  File "F:\PortableApps\Python3x\lib\site-packages\paramiko\win_pageant.py", line 89, in _query_pageant
    _winapi.get_security_attributes_for_user(),
  File "F:\PortableApps\Python3x\lib\site-packages\paramiko\_winapi.py", line 364, in get_security_attributes_for_user
    user.SID, 0)
ctypes.ArgumentError: argument 2: <class 'OverflowError'>: int too long to convert
```

**Comment by bitprophet** [comment]
This sounds a lot like #353, which Paramiko version are you on? If not on a release dated after that ticket was closed, please try upgrading to see if that fixes for you. Thanks!

**Comment by thorstenkampe** [comment]
Sorry for the late response. I downloaded the latest `paramiko-master.zip` updated my site-package installation from there. The files are from January, 19th, The issue still persists.

Please reopen the issue!

**Comment by miso-belica** [comment]
@bitprophet I have the same problem (using Fabric) on Win10. I am using `paramiko==1.16.0` and python `Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32` and get the error below:

```
  File "c:\applications\py35\lib\site-packages\fabric\main.py", line 749, in main
    *args, **kwargs
  File "c:\applications\py35\lib\site-packages\fabric\tasks.py", line 425, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "c:\applications\py35\lib\site-packages\fabric\tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "C:\Users\m\Work\roih\fabfile.py", line 140, in test
    execute(test_on_host, branch)
  File "c:\applications\py35\lib\site-packages\fabric\tasks.py", line 385, in execute
    multiprocessing
  File "c:\applications\py35\lib\site-packages\fabric\tasks.py", line 275, in _execute
    return task.run(*args, **kwargs)
  File "c:\applications\py35\lib\site-packages\fabric\tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "C:\Users\m\Work\roih\fabfile.py", line 147, in test_on_host
    func(config["server"]["cmd_status"], pty=False)
  File "c:\applications\py35\lib\site-packages\fabric\network.py", line 654, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "c:\applications\py35\lib\site-packages\fabric\operations.py", line 1121, in sudo
    stderr=stderr, timeout=timeout, shell_escape=shell_escape,
  File "c:\applications\py35\lib\site-packages\fabric\operations.py", line 929, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "c:\applications\py35\lib\site-packages\fabric\state.py", line 397, in default_channel
    chan = _open_session()
  File "c:\applications\py35\lib\site-packages\fabric\state.py", line 389, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "c:\applications\py35\lib\site-packages\fabric\network.py", line 156, in __getitem__
    self.connect(key)
  File "c:\applications\py35\lib\site-packages\fabric\network.py", line 148, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "c:\applications\py35\lib\site-packages\fabric\network.py", line 449, in connect
    sock=sock
  File "c:\applications\py35\lib\site-packages\paramiko\client.py", line 367, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "c:\applications\py35\lib\site-packages\paramiko\client.py", line 517, in _auth
    self._agent = Agent()
  File "c:\applications\py35\lib\site-packages\paramiko\agent.py", line 363, in __init__
    self._connect(conn)
  File "c:\applications\py35\lib\site-packages\paramiko\agent.py", line 66, in _connect
    ptype, result = self._send_message(cSSH2_AGENTC_REQUEST_IDENTITIES)
  File "c:\applications\py35\lib\site-packages\paramiko\agent.py", line 83, in _send_message
    self._conn.send(struct.pack('>I', len(msg)) + msg)
  File "c:\applications\py35\lib\site-packages\paramiko\win_pageant.py", line 123, in send
    self._response = _query_pageant(data)
  File "c:\applications\py35\lib\site-packages\paramiko\win_pageant.py", line 89, in _query_pageant
    _winapi.get_security_attributes_for_user(),
  File "c:\applications\py35\lib\site-packages\paramiko\_winapi.py", line 364, in get_security_attributes_for_user
    user.SID, 0)
ctypes.ArgumentError: argument 2: <class 'OverflowError'>: int too long to convert
```

**Comment by bitprophet** [comment]
Note: this particular instance of the exception is probably the same as the one in #758 - linking.
