### ISSUE TITLE
ValueError trying to connect to agent

### ISSUE THREAD

**Issue by thorstenkampe** [paramiko/paramiko#628]
I get the following exception (see below) from agent.Agent() under Python 2.7.10 32-bit when PuTTY Agent is running. The error does not occur when PuTTY Agent is not running:
```
Traceback (most recent call last):
  File "ssh.py", line 57, in <module>
    agent_connection = paramiko.agent.Agent()
  File "F:\PortableApps\Python2x\lib\site-packages\paramiko\agent.py", line 363, in __init__
    self._connect(conn)
  File "F:\PortableApps\Python2x\lib\site-packages\paramiko\agent.py", line 66, in _connect
    ptype, result = self._send_message(cSSH2_AGENTC_REQUEST_IDENTITIES)
  File "F:\PortableApps\Python2x\lib\site-packages\paramiko\agent.py", line 83, in _send_message
    self._conn.send(struct.pack('>I', len(msg)) + msg)
  File "F:\PortableApps\Python2x\lib\site-packages\paramiko\win_pageant.py", line 123, in send
    self._response = _query_pageant(data)
  File "F:\PortableApps\Python2x\lib\site-packages\paramiko\win_pageant.py", line 92, in _query_pageant
    pymap.write(msg)
  File "F:\PortableApps\Python2x\lib\site-packages\paramiko\_winapi.py", line 162, in write
    ctypes.windll.kernel32.RtlMoveMemory(dest, msg, length)
ValueError: Procedure probably called with too many arguments (4 bytes in excess)
```

**Comment by rbeagrie** [comment]
I'm getting the same exception. Python 2.7.10 64 bit, paramiko 1.16.0, Windows 10 64 bit.

I fixed it for now by downgrading to paramiko 1.15.0

**Comment by hobbsd** [comment]
This might be the same as #613, although it seemed that the problem was only related to 32-bit Python.

**Comment by bitprophet** [comment]
What @hobbsd said, this sounds a lot like #613 and may otherwise be fixed by the patch addressing that. Will be cutting 1.16.1 pretty soon with that fix in it. Please follow #613 / #619 and reopen this if the release doesn't fix it for you, @thorstenkampe - thanks!
