### ISSUE TITLE
Error using pageant with a 4096-bit key

### ISSUE THREAD

**Issue by maludwig** [paramiko/paramiko#654]
I'm using pageant with a 4096-bit key and I can't get paramiko to work on Windows with MySQL Workbench and Pageant. Originally, I suspected Workbench itself, so I installed the latest paramiko with pip, and tried things directly. But even using it from the command line, it broke, giving this traceback:

    Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import paramiko
    >>> ssh = paramiko.SSHClient()
    >>> ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    >>> ssh.connect('some.host.com', username='mitchell')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python27\lib\site-packages\paramiko\client.py", line 367, in connect
        look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
      File "C:\Python27\lib\site-packages\paramiko\client.py", line 517, in _auth
        self._agent = Agent()
      File "C:\Python27\lib\site-packages\paramiko\agent.py", line 363, in __init__
        self._connect(conn)
      File "C:\Python27\lib\site-packages\paramiko\agent.py", line 66, in _connect
        ptype, result = self._send_message(cSSH2_AGENTC_REQUEST_IDENTITIES)
      File "C:\Python27\lib\site-packages\paramiko\agent.py", line 83, in _send_message
        self._conn.send(struct.pack('>I', len(msg)) + msg)
      File "C:\Python27\lib\site-packages\paramiko\win_pageant.py", line 123, in send
        self._response = _query_pageant(data)
      File "C:\Python27\lib\site-packages\paramiko\win_pageant.py", line 92, in _query_pageant
        pymap.write(msg)
      File "C:\Python27\lib\site-packages\paramiko\_winapi.py", line 163, in write
        ctypes.windll.kernel32.RtlMoveMemory(dest, msg, length)
    ValueError: Procedure probably called with too many arguments (4 bytes in excess)

**Comment by bitprophet** [comment]
This is #613 / #619, will be out in next bugfix, thanks!
