### ISSUE TITLE
paramiko not working when build with nuitka

### ISSUE THREAD

**Issue by thehung12a3** [paramiko/paramiko#660]
File: main.py

import paramiko
import logging

logging.basicConfig(level=logging.DEBUG)

conversation = paramiko.SSHClient()
ssh_policy = paramiko.AutoAddPolicy()
conversation.set_missing_host_key_policy(ssh_policy)
try:
    conversation.connect("187.115.122.201",
                         port=22,
                         username="admin",
                         password="admin", timeout=5, banner_timeout=7)

except Exception as e:
    print e

+When build with nuitka and run main.exe then output:
Traceback (most recent call last):
  File "E:\data_sourcecode\tools\main.py", line 13, in <module>
    password=str("admin"),  look_for_keys=False,timeout=int(5), banner_timeout=int(7))
  File "E:\data_sourcecode\tools\paramiko\client.py", line 367, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "E:\data_sourcecode\tools\paramiko\client.py", line 571, in _auth
    self._transport.auth_password(username, password)
  File "E:\data_sourcecode\tools\paramiko\transport.py", line 1257, in auth_password
    self.auth_handler.auth_password(username, password, my_event)
  File "E:\data_sourcecode\tools\paramiko\auth_handler.py", line 107, in auth_password
    self._request_auth()
  File "E:\data_sourcecode\tools\paramiko\auth_handler.py", line 158, in _request_auth
    self.transport._send_message(m)
  File "E:\data_sourcecode\tools\paramiko\transport.py", line 1565, in _send_message
    self.packetizer.send_message(data)
  File "E:\data_sourcecode\tools\paramiko\packet.py", line 355, in send_message
    out = self.__block_engine_out.encrypt(packet)
  File "C:\python-32bit\python-2.7.10\lib\site-packages\Crypto\Cipher\blockalgo.py", line 244, in encrypt
    return self._cipher.encrypt(plaintext)
TypeError: argument must be string or read-only buffer, not tuple

Error:argument must be string or read-only buffer, not tuple
-----------------------------------------------------------------------------------------------------------------
But run python main.py the output:

DEBUG:paramiko.transport:MAC agreed: hmac-md5
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in 
function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 187.115.122.201: 
487f27f44b70ee213d2de8a1e18a818f
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Auth banner: 
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:EOF in transport thread

Output:
successful

**Comment by thehung12a3** [comment]
When will you finish it? I hope that it will coming soon.
Thanks

**Comment by rombr** [comment]
Hello, I have the same problem.
