### ISSUE TITLE
[Errno 3] No such process with ProxyCommand on cygwin

### ISSUE THREAD

**Issue by nilsga** [paramiko/paramiko#684]
Using paramiko through fabric with native `~/.ssh/config` and ProxyCommand on cygwin. The script is successfully executed, but always yields the below error on exit:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/paramiko-1.16.0-py2.7.egg/paramiko/transport.py", line 1673, in run
    self.sock.close()
  File "/usr/lib/python2.7/site-packages/paramiko-1.16.0-py2.7.egg/paramiko/proxy.py", line 110, in close
    os.kill(self.process.pid, signal.SIGTERM)
OSError: [Errno 3] No such process

Disconnecting from svvpdatainn01... Traceback (most recent call last):
  File "/usr/bin/fab", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/fabric/main.py", line 760, in main
    disconnect_all()
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 668, in disconnect_all
    connections[key].close()
  File "/usr/lib/python2.7/site-packages/paramiko-1.16.0-py2.7.egg/paramiko/client.py", line 374, in close
  File "/usr/lib/python2.7/site-packages/paramiko-1.16.0-py2.7.egg/paramiko/transport.py", line 561, in close
  File "/usr/lib/python2.7/site-packages/paramiko-1.16.0-py2.7.egg/paramiko/proxy.py", line 110, in close
OSError: [Errno 3] No such process
```

The ProxyCommand is 

`ProxyCommand ssh -q user@jumphost nc %h %p`

**Comment by gtalton** [comment]
Nils-Helge,

I think I ran into this problem a few weeks ago and fixed it with a change in Cygwin /etc/profile to remove the export of the SHELL variable export there.

Check this Cygwin thread and then try it .. I found it fixed my problem.

[Cygwin Support Msg00349](https://www.cygwin.com/ml/cygwin/2012-02/msg00349.html)

Regards,

Gerald

**Comment by nilsga** [comment]
Thanks for the input! However, the proposed solution doesn't seem to work for me.

**Comment by avoidik** [comment]
I know it's a little bit old post, but PR for this was proposed recently
#962
