### ISSUE TITLE
SshClient.connect() - not failing over IPv6 to IPv4 when IPv6 address is unreachable.

### ISSUE THREAD

**Issue by gwtp** [paramiko/paramiko#686]
Example Scenario:

- Hostname has both IPv4 and IPv6 address. 
- IPv6 address is unreachable, 
- IPv4 address is reachable. 
- When specifying hostname as IPv4 address, the connection is successful. 

Paramiko is not failing over to IPv4 any thoughts here? 

Here is the exception raised:

>>> client.connect(hostname=hostname, username=username, password=password, allow_agent=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 292, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python2.7/dist-packages/paramiko/util.py", line 270, in retry_on_signal
    return function()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 292, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 110] Connection timed out

**Comment by bitprophet** [comment]
This may be a bug in the connection code, which is *supposed* to try all possible versions of the requested address in order, optionally with an explicit timeout (which you can pass to `.connect()`). See https://github.com/paramiko/paramiko/blob/0ae019c8259924438f4247784d56beda639b1e11/paramiko/client.py#L296-L316 which is the relevant code snippet.

Going by the Python stdlib docs for `getaddrinfo`, IPv4 probably pops up before IPv6 most of the time, which would be why it's tried first and is then gumming up the works.

At a glance, I'm thinking that this code was never actually tried in the "IPv4 times out, instead of being outright unreachable/unroutable" scenario, since the exception handling only skips unreachable/unconnectable errors - not timeouts. The fix may thus be as simple as updating that `except` line.

So either @gwtp needs to be comfortable testing a PR, or I (or another contributor) need to find/create a reproducible network case triggering this.

Of note: another user (`weylin` on Freenode) has encountered a similar or identical issue, which they phrased initially as wanting to force IPv4-only support. Something to consider as an alternative solution here, though I suspect "make sure timeout-failover actually works, make sure users know they can supply the timeout explicitly" is the better one.

**Comment by Poply** [comment]
Had this same issue when using paramiko 2.4. I could `.connect()` fine when the host resolved to a single IPv4 address, but if it also had an IPv6 address associated I got a timeout error.

Had to use `socket.gethostbyname(myhostname)` as a workaround when connecting.

**Comment by wsw70** [comment]
The problem is still present in 3.4.0. @Poply workaround to use `hostname=socket.gethostbyname(myhostname)` works.
