### ISSUE TITLE
SSHException: Invalid packet blocking

### ISSUE THREAD

**Issue by frmdstryr** [paramiko/paramiko#704]
I'm using a twisted ssh server and connecting to it using paramiko.  If I try to send a lot of data I get this error message:
```python
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "C:\Python27\lib\site-packages\paramiko\transport.py", line 1608, in run
ERROR:paramiko.transport:    ptype, m = self.packetizer.read_message()
ERROR:paramiko.transport:  File "C:\Python27\lib\site-packages\paramiko\packet.py", line 396, in read_message
ERROR:paramiko.transport:    raise SSHException('Invalid packet blocking')
ERROR:paramiko.transport:SSHException: Invalid packet blocking
```

Can someone please explain what may be causing this?  Is this an issue with Twisted?

Edit: If it helps, the error is coming from a direct-tcp forwarded channel.

**Comment by frmdstryr** [comment]
I implemented the client in twisted and get a similar error. Seems like a server issue, not paramiko. Closing.
