### ISSUE TITLE
Potential to hang during authentication?

### ISSUE THREAD

**Issue by sanseihappa** [paramiko/paramiko#719]
Not sure if this is related to other open issues I see regarding hangs, but I am seeing an apparent hang client side when connecting to a server that sometimes behaves badly.

Basically, the server is potentially hard-resetting on its own due to a HW-based watchdog timer.

I happened to catch this traceback:

```
^CERROR: KEYBOARDINTERRUPT

ABORTED: By user.
   
^CERROR: keyboardinterrupt
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/anon/Work/proj/test/.tox/behave/lib/python2.7/site-packages/behave/__main__.py", line 162, in <module>
    sys.exit(main())
  File "/Users/anon/Work/proj/test/.tox/behave/lib/python2.7/site-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/Users/anon/Work/proj/test/.tox/behave/lib/python2.7/site-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/Users/anon/Work/proj/test/.tox/behave/lib/python2.7/site-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/Users/anon/Work/proj/test/.tox/behave/lib/python2.7/site-packages/behave/runner.py", line 504, in run_model
    self.run_hook('after_all', self.context)
  File "/Users/anon/Work/proj/test/.tox/behave/lib/python2.7/site-packages/behave/runner.py", line 405, in run_hook
    self.hooks[name](context, *args)
  File "features/environment.py", line 154, in after_all
    try_get_data_dump(context.hostname, context.username, context.password, context.client
  File "/Users/anon/Work/proj/test/utils.py", line 615, in try_get_data_dump
    f.write(get_dmesg_output(hostname, username, password))
  File "/Users/anon/Work/proj/test/utils.py", line 1340, in get_dmesg_output
    client.connect(hostname, user, password)
  File "/Users/anon/Work/proj/test/.tox/behave/lib/python2.7/site-packages/myclient/Client.py", line 147, in connect
    allow_agent=False, look_for_keys=False)
  File "/Users/anon/Work/proj/test/.tox/behave/lib/python2.7/site-packages/paramiko/client.py", line 367, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/Users/anon/Work/proj/test/.tox/behave/lib/python2.7/site-packages/paramiko/client.py", line 571, in _auth
    self._transport.auth_password(username, password)
  File "/Users/anon/Work/proj/test/.tox/behave/lib/python2.7/site-packages/paramiko/transport.py", line 1262, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "/Users/anon/Work/proj/test/.tox/behave/lib/python2.7/site-packages/paramiko/auth_handler.py", line 192, in wait_for_response
    event.wait(0.1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 621, in wait
    self.__cond.wait(timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt
```

It seems that this portion of the code may be prone to endlessly hanging in such a scenario:

```
    def wait_for_response(self, event):
        while True:
            event.wait(0.1)
            if not self.transport.is_active():
                e = self.transport.get_exception()
                if (e is None) or issubclass(e.__class__, EOFError):
                    e = AuthenticationException('Authentication failed.')
                raise e
            if event.is_set():
                break
```

https://github.com/paramiko/paramiko/blob/master/paramiko/auth_handler.py#L190

**Comment by lneuhaus** [comment]
I second this bug report. Strangely, this problem occurs for me only when I load paramiko in the ipython console and connect automatically, i.e. by doing something like
from mycode import MyClass
m=MyClass()
and the __init__ of MyClass tries to establish a connection with paramiko. 

If I manually type:
from mycode import MyClass
#wait for it to finish
#typing...
m=MyClass()

it works correctly and does not get hung up. It seems to me that some thread of paramiko is started when the module is loaded, and this thread apparently waits for the ipython console to be ready to be ready itself. So some kind of deadlock. Unfortunately I have no idea where to start here.

**Comment by sanseihappa** [comment]
I'm closing this and referring to #520, which I've discovered is what I'm actually hitting.
@lneuhaus I suggest using `faulthandler` to see if your issue is the same as #520.
