### ISSUE TITLE
Intermittent SFTP test failure on Travis

### ISSUE THREAD

**Issue by bitprophet** [paramiko/paramiko#730]
Got the below tonight in the 1.17 line, but after merging a lot of stuff (including what I can only assume is the trigger, #578). Seeing that it was *only* affecting Python 3.5, I figured it would be another race condition related, intermittent bug like #612. And **sure enough** mashing the 're-test' button on Travis made it green :(

I haven't attempted to reproduce locally yet but will soon.

```
test_9_big_file_big_buffer (tests.test_sftp_big.BigSFTPTest) ... ERROR
ERROR
Exception ignored in: <bound method SFTPFile.__del__ of <paramiko.sftp_file.SFTPFile object at 0x7f2f551cda20>>
Traceback (most recent call last):
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_file.py", line 66, in __del__
    self._close(async=True)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_file.py", line 87, in _close
    BufferedFile.close(self)
  File "/home/travis/build/paramiko/paramiko/paramiko/file.py", line 79, in close
    self.flush()
  File "/home/travis/build/paramiko/paramiko/paramiko/file.py", line 87, in flush
    self._write_all(self._wbuffer.getvalue())
  File "/home/travis/build/paramiko/paramiko/paramiko/file.py", line 498, in _write_all
    count = self._write(data)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_file.py", line 176, in _write
    self._reqs.append(self.sftp._async_request(type(None), CMD_WRITE, self.handle, long(self._realpos), data[:chunk]))
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 754, in _async_request
    self._send_packet(t, msg)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 170, in _send_packet
    self._write_all(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 133, in _write_all
    n = self.sock.send(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 715, in send
    return self._send(s, m)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 1075, in _send
    raise socket.error('Socket is closed')
OSError: Socket is closed
test_A_big_file_renegotiate (tests.test_sftp_big.BigSFTPTest) ... ERROR
ERROR
======================================================================
ERROR: test_9_big_file_big_buffer (tests.test_sftp_big.BigSFTPTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 760, in _read_response
    t, data = self._read_packet()
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 173, in _read_packet
    x = self._read_all(4)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 159, in _read_all
    raise EOFError()
EOFError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/paramiko/paramiko/tests/test_sftp_big.py", line 337, in test_9_big_file_big_buffer
    f.write(mblob)
  File "/home/travis/build/paramiko/paramiko/paramiko/file.py", line 397, in write
    self.flush()
  File "/home/travis/build/paramiko/paramiko/paramiko/file.py", line 87, in flush
    self._write_all(self._wbuffer.getvalue())
  File "/home/travis/build/paramiko/paramiko/paramiko/file.py", line 498, in _write_all
    count = self._write(data)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_file.py", line 180, in _write
    t, msg = self.sftp._read_response(req)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 762, in _read_response
    raise SSHException('Server connection dropped: %s' % str(e))
paramiko.ssh_exception.SSHException: Server connection dropped: 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/paramiko/paramiko/tests/test_sftp_big.py", line 337, in test_9_big_file_big_buffer
    f.write(mblob)
  File "/home/travis/build/paramiko/paramiko/paramiko/util.py", line 322, in __exit__
    self.close()
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_file.py", line 72, in close
    self._close(async=False)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_file.py", line 87, in _close
    BufferedFile.close(self)
  File "/home/travis/build/paramiko/paramiko/paramiko/file.py", line 79, in close
    self.flush()
  File "/home/travis/build/paramiko/paramiko/paramiko/file.py", line 87, in flush
    self._write_all(self._wbuffer.getvalue())
  File "/home/travis/build/paramiko/paramiko/paramiko/file.py", line 498, in _write_all
    count = self._write(data)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_file.py", line 176, in _write
    self._reqs.append(self.sftp._async_request(type(None), CMD_WRITE, self.handle, long(self._realpos), data[:chunk]))
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 754, in _async_request
    self._send_packet(t, msg)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 170, in _send_packet
    self._write_all(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 133, in _write_all
    n = self.sock.send(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 715, in send
    return self._send(s, m)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 1075, in _send
    raise socket.error('Socket is closed')
OSError: Socket is closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/paramiko/paramiko/tests/test_sftp_big.py", line 341, in test_9_big_file_big_buffer
    sftp.remove('%s/hongry.txt' % FOLDER)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 348, in remove
    self._request(CMD_REMOVE, path)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 729, in _request
    num = self._async_request(type(None), t, *arg)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 754, in _async_request
    self._send_packet(t, msg)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 170, in _send_packet
    self._write_all(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 133, in _write_all
    n = self.sock.send(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 715, in send
    return self._send(s, m)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 1075, in _send
    raise socket.error('Socket is closed')
OSError: Socket is closed
======================================================================
ERROR: test_9_big_file_big_buffer (tests.test_sftp_big.BigSFTPTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/paramiko/paramiko/tests/test_sftp_big.py", line 54, in tearDown
    sftp.rmdir(FOLDER)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 390, in rmdir
    self._request(CMD_RMDIR, path)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 729, in _request
    num = self._async_request(type(None), t, *arg)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 754, in _async_request
    self._send_packet(t, msg)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 170, in _send_packet
    self._write_all(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 133, in _write_all
    n = self.sock.send(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 715, in send
    return self._send(s, m)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 1075, in _send
    raise socket.error('Socket is closed')
OSError: Socket is closed
======================================================================
ERROR: test_A_big_file_renegotiate (tests.test_sftp_big.BigSFTPTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/paramiko/paramiko/tests/test_sftp_big.py", line 352, in test_A_big_file_renegotiate
    with sftp.open('%s/hongry.txt' % FOLDER, 'w', 128 * 1024) as f:
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 327, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 729, in _request
    num = self._async_request(type(None), t, *arg)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 754, in _async_request
    self._send_packet(t, msg)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 170, in _send_packet
    self._write_all(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 133, in _write_all
    n = self.sock.send(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 715, in send
    return self._send(s, m)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 1075, in _send
    raise socket.error('Socket is closed')
OSError: Socket is closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/paramiko/paramiko/tests/test_sftp_big.py", line 367, in test_A_big_file_renegotiate
    sftp.remove('%s/hongry.txt' % FOLDER)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 348, in remove
    self._request(CMD_REMOVE, path)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 729, in _request
    num = self._async_request(type(None), t, *arg)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 754, in _async_request
    self._send_packet(t, msg)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 170, in _send_packet
    self._write_all(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 133, in _write_all
    n = self.sock.send(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 715, in send
    return self._send(s, m)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 1075, in _send
    raise socket.error('Socket is closed')
OSError: Socket is closed
======================================================================
ERROR: test_A_big_file_renegotiate (tests.test_sftp_big.BigSFTPTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/paramiko/paramiko/tests/test_sftp_big.py", line 54, in tearDown
    sftp.rmdir(FOLDER)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 390, in rmdir
    self._request(CMD_RMDIR, path)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 729, in _request
    num = self._async_request(type(None), t, *arg)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp_client.py", line 754, in _async_request
    self._send_packet(t, msg)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 170, in _send_packet
    self._write_all(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/sftp.py", line 133, in _write_all
    n = self.sock.send(out)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 715, in send
    return self._send(s, m)
  File "/home/travis/build/paramiko/paramiko/paramiko/channel.py", line 1075, in _send
    raise socket.error('Socket is closed')
OSError: Socket is closed
----------------------------------------------------------------------
Ran 161 tests in 26.974s
FAILED (errors=4)
```

**Comment by bitprophet** [comment]
I suppose it's also remotely possible this was a one-time wacky hijinx problem on travis' end, i.e. the socket was legitimately, actually closed from outside our process. But if that was a thing that could happen on travis I'd expect to have seen it before, and I don't think I have.

**Comment by bitprophet** [comment]
Attempting to repro this now...

* `while` loop running `inv test -f "--no-transport --no-pkey"` on my localhost under Python 3.5.0 (against master)...
    * Note: the errors are in the big-file suite which has implicit dependencies on the regular sftp suite, despite them being separate arguments to `test.py`. really need to replace all this with something modern...
    * Got up to 180 iterations before deciding it's probably best to test 1.17 anyways (quite possible if it's a timing related issue, the backend switch will impact it)
    * Ran same against 1.17; hours later, 591 iterations, zero errors. So not reproducible on my localhost.
* Same, against deadsnakes' Python 3.5.1 on an Ubuntu 14.04 cloud instance (my poor MBA can only run so much at once; also, isolation++): 161 iterations so far, no errors. Going to let it keep running while I do other things for a while.

**Comment by bitprophet** [comment]
488 iterations on the Ubuntu box, still no errors. Crossing my fingers and hoping this was indeed a fluke.
