### ISSUE TITLE
Error while using agent=True

### ISSUE THREAD

**Issue by fakuivan** [paramiko/paramiko#747]
Traceback:

```
Traceback (most recent call last):
  File "C:\really cool path\Network Administration Tool\ssh_api\connection.py", line 18, in <module>
    ssh.connect(hostname, port = port, username = username, allow_agent = True) #you have to add the key to pageant
  File "C:\Python 3.5\lib\site-packages\paramiko\client.py", line 380, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "C:\Python 3.5\lib\site-packages\paramiko\client.py", line 530, in _auth
    self._agent = Agent()
  File "C:\Python 3.5\lib\site-packages\paramiko\agent.py", line 363, in __init__
    self._connect(conn)
  File "C:\Python 3.5\lib\site-packages\paramiko\agent.py", line 66, in _connect
    ptype, result = self._send_message(cSSH2_AGENTC_REQUEST_IDENTITIES)
  File "C:\Python 3.5\lib\site-packages\paramiko\agent.py", line 83, in _send_message
    self._conn.send(struct.pack('>I', len(msg)) + msg)
  File "C:\Python 3.5\lib\site-packages\paramiko\win_pageant.py", line 123, in send
    self._response = _query_pageant(data)
  File "C:\Python 3.5\lib\site-packages\paramiko\win_pageant.py", line 89, in _query_pageant
    _winapi.get_security_attributes_for_user(),
  File "C:\Python 3.5\lib\site-packages\paramiko\_winapi.py", line 364, in get_security_attributes_for_user
    user.SID, 0)
ctypes.ArgumentError: argument 2: <class 'OverflowError'>: int too long to convert
```

I ran into this issue while trying to intergrate Pageant into my ssh scripts. I've seen some solutions pointing to the get_int() method but that had nothing to do with it (since I have the lastest version of the paramiko api), I "fixed" this issue by changing the second argument to ctypes.c_int(user.SID), but that just created a lot more exeptions because the user.SID int is lager than 2^32 and it had to truncate it.

This is the script

```
import paramiko
from nvram_entities import forward

hostname = "router.local"
port = 22
username = "supersecretuser"

def parse_entries(nvram_stdout):
    forward_spec_sep = " "
    return list(map(forward, nvram_stdout.split(forward_spec_sep)))

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

ssh.connect(hostname, port = port, username = username, allow_agent = True)

stdin, stdout, stderr = ssh.exec_command("nvram get forward_spec")

print(parse_entries(stdout.read().decode("utf-8")))
```

Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32
Lastest paramiko version, downloaded from [this](https://github.com/paramiko/paramiko) repository

**Comment by miso-belica** [comment]
I reported the same problem here https://github.com/paramiko/paramiko/issues/627#issuecomment-201836614 but it desn't seem someone is watching the issue. Is there any chance to fix this, please? Can I help with this somehow?

**Comment by fakuivan** [comment]
I ran into this while doing a quick script, I am not that experienced in python (nor c++ on windows). I guess I just run the script on linux :u.

**Comment by bk8190** [comment]
I'm having the same error - unable to use Paramiko on Windows 10

**Comment by bitprophet** [comment]
This is #758 I think - let's roll into that.
