### ISSUE TITLE
Unable to Connect after upgrading EL Captain

### ISSUE THREAD

**Issue by Kirannk007** [paramiko/paramiko#749]
I upgraded my workstation to EL Caption and now unable to connect to remote machine using paramiko.

Below is more on the code part.

import paramiko
keyfile = '/Users/user_name/.ssh/user-internal-04-22'
host = 'xxxx'
un_con = paramiko.SSHClient()
un_con.set_missing_host_key_policy(paramiko.AutoAddPolicy())
un_con.connect(host, username=local_user, key_filename=keyfile)

blr-mppet:integrate_fil user$ which openssl
/usr/local/bin/openssl

Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> 

I don't see any issue importing the module, but the connection fails.
When manually tried connecting to server it's in without any issues.

Error :
_

> ERROR:paramiko.transport:Unknown exception: dynamic module does not define init function (init_constant_time)
> ERROR:paramiko.transport:Traceback (most recent call last):
> ERROR:paramiko.transport:  File "build/bdist.macosx-10.11-intel/egg/paramiko/transport.py", line 1757, in run
> ERROR:paramiko.transport:    self.kex_engine.parse_next(ptype, m)
> ERROR:paramiko.transport:  File "build/bdist.macosx-10.11-intel/egg/paramiko/kex_group1.py", line 75, in parse_next
> ERROR:paramiko.transport:    return self._parse_kexdh_reply(m)
> ERROR:paramiko.transport:  File "build/bdist.macosx-10.11-intel/egg/paramiko/kex_group1.py", line 111, in _parse_kexdh_reply
> ERROR:paramiko.transport:    self.transport._verify_key(host_key, sig)
> ERROR:paramiko.transport:  File "build/bdist.macosx-10.11-intel/egg/paramiko/transport.py", line 1602, in _verify_key
> ERROR:paramiko.transport:    key = self._key_info[self.host_key_type](Message(host_key))
> ERROR:paramiko.transport:  File "build/bdist.macosx-10.11-intel/egg/paramiko/rsakey.py", line 58, in __init__
> ERROR:paramiko.transport:    ).public_key(default_backend())
> ERROR:paramiko.transport:  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
> ERROR:paramiko.transport:    _default_backend = MultiBackend(_available_backends())
> ERROR:paramiko.transport:  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
> ERROR:paramiko.transport:    "cryptography.backends"
> ERROR:paramiko.transport:  File "build/bdist.macosx-10.11-intel/egg/pkg_resources/__init__.py", line 2235, in resolve
> ERROR:paramiko.transport:    module = __import__(self.module_name, fromlist=['__name__'], level=0)
> ERROR:paramiko.transport:  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
> ERROR:paramiko.transport:    from cryptography.hazmat.backends.openssl.backend import backend
> ERROR:paramiko.transport:  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 14, in <module>
> ERROR:paramiko.transport:    from cryptography import utils, x509
> ERROR:paramiko.transport:  File "/Library/Python/2.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
> ERROR:paramiko.transport:    from cryptography.x509.base import (
> ERROR:paramiko.transport:  File "/Library/Python/2.7/site-packages/cryptography/x509/base.py", line 15, in <module>
> ERROR:paramiko.transport:    from cryptography.x509.extensions import Extension, ExtensionType
> ERROR:paramiko.transport:  File "/Library/Python/2.7/site-packages/cryptography/x509/extensions.py", line 19, in <module>
> ERROR:paramiko.transport:    from cryptography.hazmat.primitives import constant_time, serialization
> ERROR:paramiko.transport:  File "/Library/Python/2.7/site-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
> ERROR:paramiko.transport:    from cryptography.hazmat.bindings._constant_time import lib
> ERROR:paramiko.transport:ImportError: dynamic module does not define init function (init_constant_time)
> ERROR:paramiko.transport:
> Unix connection error :: dynamic module does not define init function (init_constant_time)

_

**Comment by Kirannk007** [comment]
Things work fine when downgraded to 1.17.0 the issue is only with the recent version of paramiko
