### ISSUE TITLE
paramiko (called through fabric lib) with gateway set fails with EOFERROR when using gevent 

### ISSUE THREAD

**Issue by hokadiri** [paramiko/paramiko#764]
I'm using gevent and fabric to execute some tasks asynchronously. Being that I want to hit servers behind a firewall, I use a proxy host (gateway) to connect to the end servers

Sample version of my script.
To run please replace: \<host1\>, \<cmd1\>, \<host2\>,\<cmd2\>, \<username\>, \<password\>, \<gateway\> with some valid items

I used:
\<cmd1\> = 'whoami'
\<cmd2\> = 'ls'
```
import gevent
import gevent.monkey;
gevent.monkey.patch_all()
from fabric.api import run, sudo
from fabric.tasks import execute
from fabric.context_managers import quiet, settings
from fabric.state import env
from gevent.queue import Queue, Empty

tasks = Queue()
to_do = [{'host': '<host1>', 'task': '<cmd1>'}, {'host': '<host2>', 'task': '<cmd2>'}]
username = '<username>'
password = '<password>'
gateway = '<gateway>'
def do_work(cmd_str=None, use_sudo=False):
    with settings(quiet(), warn_only=True):
        if use_sudo:
            return sudo(cmd_str)
        else:
            return run(cmd_str)


def run_command(cmd_str, hosts, **kwargs):
    # import pdb;pdb.set_trace()
    try:
        env.pool_size = kwargs['pool_size']
    except KeyError:
        pass

    try:
        env.parallel = kwargs['parallel']
    except KeyError:
        pass

    try:
        env.no_agent = not kwargs['allow_agent']
    except KeyError:
        pass

    try:
        env.user = kwargs['username']
    except KeyError:
        pass

    try:
        env.password = kwargs['password']
    except KeyError:
        pass

    try:
        env.gateway = kwargs['gateway']
    except KeyError:
        pass

    try:
        use_sudo = kwargs['use_sudo']
    except KeyError:
        use_sudo = False

    output = execute(do_work, cmd_str=cmd_str, hosts=hosts, use_sudo=use_sudo)

    for host in hosts:
        print output[host].failed
        print output[host].return_code
        print output[host].succeeded
        ss = output[host]
        print ss
        print ss.split()
    # '''
    return output


def do_g_work(worker):
    use_sudo = True
    try:
        while not tasks.empty():
            task = tasks.get(timeout=1)
            print task, worker
            host = task['host']
            cmd_str = task['cmd']
            run_command(cmd_str, [host], gateway=gateway, allow_agent=False, username=username,
                        password=password, parallel=False, use_sudo=use_sudo)
            gevent.sleep(0)
    except Empty:
        print('Quitting time!')


def producer_function(iterable_item):
    for item in iterable_item:
        tasks.put(item)


if __name__ == "__main__":
    use_sudo = True
    gevent.spawn(producer_function, to_do).join()

    workers = [
        gevent.spawn(do_g_work, 'worker0'),
        gevent.spawn(do_g_work, 'worker1')
    ]

    gevent.joinall(workers)
```

Get EOFError
```
File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/fabric/network.py", line 481, in connect
    client.connect(**kwargs)
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/client.py", line 341, in connect
    t.start_client()
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/transport.py", line 503, in start_client
    raise e

Traceback (most recent call last):
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/transport.py", line 1866, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/packet.py", line 327, in readline
    buf += self._read_timeout(timeout)
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/packet.py", line 483, in _read_timeout
    raise EOFError()
EOFError
No handlers could be found for logger "paramiko.transport"
ACTIVE:False
EXECPTION

Aborting.
```

EOFError is happening because socket is closed error is raised [in this line](https://github.com/paramiko/paramiko/blob/master/paramiko/channel.py#L1075)
Placing `_send` function here for reference.
```
    def _send(self, s, m):
        size = len(s)
        self.lock.acquire()
        try:
            if self.closed:
                # this doesn't seem useful, but it is the documented behavior of Socket
                raise socket.error('Socket is closed')
            size = self._wait_for_send_window(size)
            if size == 0:
                # eof or similar
                return 0
            m.add_string(s[:size])
        finally:
            self.lock.release()
        # Note: We release self.lock before calling _send_user_message.
        # Otherwise, we can deadlock during re-keying.
        self.transport._send_user_message(m)
        return size
```

Placed a debugger just before the socket error inside the greenlet thread and here is the traceback
```
> /home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/channel.py(1077)_send()
-> raise socket.error('Socket is closed')
(Pdb) where
  /home/hkadiri/pssh_0_9/lib/python2.7/site-packages/gevent/greenlet.py(534)run()
-> result = self._run(*self.args, **self.kwargs)
  /usr/local/lib/python2.7/threading.py(783)__bootstrap()
-> self.__bootstrap_inner()
  /usr/local/lib/python2.7/threading.py(810)__bootstrap_inner()
-> self.run()
  /home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/transport.py(1724)run()
-> self.packetizer.write_all(b(self.local_version + '\r\n'))
  /home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/packet.py(285)write_all()
-> n = self.__socket.send(out)
  /home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/channel.py(715)send()
-> return self._send(s, m)
> /home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/channel.py(1077)_send()
-> raise socket.error('Socket is closed')
```

Now, If I don't monkey patch the socket module
```
gevent.monkey.patch_socket()
```
It works but its serial

If I don't use a gateway, it works but I need to use a gateway.

Could there be an issue with monkey-patching socket + using a gateway in paramiko?

I posted on the gevent repo but was adviced to check here. See my post [here ](https://github.com/gevent/gevent/issues/816) 

The issue I have here is similar to #633. The main difference is using a gateway (proxy) to connect to the end server

**Comment by bitprophet** [comment]
At the moment we don't support using gevent - it has unknown repercussions when mixed into all of the threading, etc Paramiko does. Sorry! "Just rub gevent on it" sadly doesn't work everywhere :(
