### ISSUE TITLE
Having issues with paramiko for session that need to be open for long time. 

### ISSUE THREAD

**Issue by arshdeeptinna** [paramiko/paramiko#797]
So I have a script where I need to connect to a few nodes sequentially to run a bunch commands that can take a few hours to complete. For each node I do something like following

```
for node in nodes:
    tunnel = spur.SshShell(hostname=node, username='xyz')
    with tunnel:
        for cmd in cmds:
            result = tunnel.run(cmd)
           do_something()
```
I run the above script in a screen session. The issue I am seeing is that all commands are run succesfully for first node but after that following exception is raised

```
Original error: No authentication methods available
Traceback (most recent call last):
  File "xyz.py", line 219, in <module>
    main()
  File "xyz.py", line 55, in __init__
    self.nodes = self.get_nodes_info()
  File xyz, line 63, in get_nodes_info
    tunnel = ssh_tunnel(str(self.seed_ip))
  File "xyy", line 29, in ssh_tunnel
    tunnel.run(["uptime"])
  File "/usr/local/lib/python2.7/dist-packages/spur/ssh.py", line 162, in run
    return self.spawn(*args, **kwargs).wait_for_result()
  File "/usr/local/lib/python2.7/dist-packages/spur/ssh.py", line 173, in spawn
    channel = self._get_ssh_transport().open_session()
  File "/usr/local/lib/python2.7/dist-packages/spur/ssh.py", line 251, in _get_ssh_transport
    raise self._connection_error(error)
spur.ssh.ConnectionError: Error creating SSH connection
Original error: No authentication methods available
```

I also noticed that in this same screen session I can not use spur at all. Even in python interpreter keep on hitting the same error. However I can connect to the same node in a different screen session. It seems like  the fact that commands take a long time to complete and thus need to keep session active for a long time messes up spur or paramiko.

Another scenario that I tried was to open a different screen session and replaced the commands that I need to run with simpler bash commands. In this case the commands were executed on all nodes without any issues.

**Comment by arshdeeptinna** [comment]
This is the output when I try to use paramiko in the same screen session again.
```
paramiko.transport: DEBUG    starting thread (client mode): 0xa339f590L
paramiko.transport: INFO     Connected (version 2.0, client OpenSSH_6.6.1p1)
paramiko.transport: DEBUG    kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: DEBUG    Ciphers agreed: local=aes128-ctr, remote=aes128-ctr
paramiko.transport: DEBUG    using kex diffie-hellman-group14-sha1; server key type ssh-rsa; cipher: local aes128-ctr, remote aes128-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
paramiko.transport: DEBUG    Switch to new keys ...
paramiko.transport: DEBUG    EOF in transport thread
root        : ERROR    Error creating SSH connection
Original error: No authentication methods available
```

However I have no issues in a different session

```
paramiko.transport: DEBUG    starting thread (client mode): 0x9303c550L
paramiko.transport: INFO     Connected (version 2.0, client OpenSSH_6.6.1p1)
paramiko.transport: DEBUG    kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: DEBUG    Ciphers agreed: local=aes128-ctr, remote=aes128-ctr
paramiko.transport: DEBUG    using kex diffie-hellman-group14-sha1; server key type ssh-rsa; cipher: local aes128-ctr, remote aes128-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
paramiko.transport: DEBUG    Switch to new keys ...
paramiko.transport: DEBUG    Trying SSH agent key b195f2b6f49212ae70cc400ba0e1e404
paramiko.transport: DEBUG    userauth is OK
paramiko.transport: INFO     Authentication (publickey) failed.
paramiko.transport: DEBUG    Trying SSH agent key 2b131c42b5127ffdddaf22df847d3a3f
paramiko.transport: DEBUG    userauth is OK
paramiko.transport: INFO     Authentication (publickey) successful!
paramiko.transport: DEBUG    [chan 0] Max packet in: 32768 bytes
paramiko.transport: DEBUG    [chan 0] Max packet out: 32768 bytes
paramiko.transport: DEBUG    Secsh channel 0 opened.
paramiko.transport: DEBUG    [chan 0] Sesch channel 0 request ok
paramiko.transport: DEBUG    [chan 0] EOF received (0)
paramiko.transport: DEBUG    [chan 1] Max packet in: 32768 bytes
paramiko.transport: DEBUG    [chan 0] EOF sent (0)
paramiko.transport: DEBUG    [chan 1] Max packet out: 32768 bytes
paramiko.transport: DEBUG    Secsh channel 1 opened.
paramiko.transport: DEBUG    [chan 1] Sesch channel 1 request ok
paramiko.transport: DEBUG    [chan 2] Max packet in: 32768 bytes
paramiko.transport: DEBUG    [chan 1] EOF received (1)
paramiko.transport: DEBUG    [chan 1] EOF sent (1)
paramiko.transport: DEBUG    [chan 2] Max packet out: 32768 bytes
paramiko.transport: DEBUG    Secsh channel 2 opened.
paramiko.transport: DEBUG    [chan 2] Sesch channel 2 request ok
root        : INFO     All nodes healthy. Proceeding with repairs...
paramiko.transport: DEBUG    [chan 2] EOF received (2)
paramiko.transport: DEBUG    starting thread (client mode): 0x9303c2d0L
paramiko.transport: INFO     Connected (version 2.0, client OpenSSH_6.6.1p1)
```

**Comment by bitprophet** [comment]
Thanks for the report! Need some clarification:

- What Paramiko version is this on?
- How long is "a long time to complete"? (FWIW, people have definitely used Paramiko to host commands/sessions that live for many minutes and perhaps hours.)
- Can you reproduce the issue with regular `ssh`? It's possible this is a networking issue, e.g. intermediate network devices timing out old connections.

**Comment by arshdeeptinna** [comment]
- I saw the issue originally on 1.15.2 and then upgraded paramiko to latest version. Still seeing the same error. 
- I believe it takes more than a couple of hours for the commands to run.
- I can try reproducing the issue with ssh.However I tried using paramiko in the python interpreter in the same screen session after the script exited. It failed to create a tunnel with same error.

**Comment by bitprophet** [comment]
Oh, I see what you mean now. That's really interesting, I don't think I've seen that sort of thing before.

Not familiar with `spur` but I can't see offhand why Paramiko would have a problem there unless the long-lived screen session itself is generating environmental limitations, e.g. running afoul of ulimits or something like that. Certainly anything that causes errors which *span* multiple Python interpreter sessions seems like it'd have to be environmental in origin if it's not 100% so.

If you post the raw-Paramiko-no-Spur code snippet that might also give us a clue. If it's tunnel related, and something in your screen/shell is e.g. preventing properly spawning or piping to `ProxyCommand` related subprocesses, that can cause all kinds of strange behaviors at the "inner connection" level (i.e. the connection trying to use the tunnel socket).

**Comment by arshdeeptinna** [comment]
```
def ssh_tunnel(ip):
    tunnel = paramiko.SSHClient()
    tunnel.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    tunnel.connect(ip, username="ubuntu",timeout=20)
    return tunnel
```

```
def run_cmd(tunnel,cmd):

    stdin, stdout, stderr = tunnel.exec_command(cmd)
    stdout_chunks = []
    stdout_chunks.append(stdout.channel.recv(len(stdout.channel.in_buffer)))
    channel = stdout.channel
    stdin.close()
    channel.shutdown_write()
    while  not channel.exit_status_ready() or channel.recv_ready() or channel.recv_stderr_ready():
        #got_chunk = False
        #readq, _, _ = select.select([channel], [], [])
        if channel.recv_ready():
                stdout_chunks.append(channel.recv(1024))
                got_chunk = True
        if channel.recv_stderr_ready(): 
                stderr.channel.recv_stderr(1024)
                got_chunk = True 
        if channel.closed:
            print("here")
            break
    
    while channel.recv_ready():
        stdout_chunks.append(channel.recv(1024))        
    while channel.recv_stderr_ready():
        stdout_chunks.append(channel.recv_stderr(1024))

    if channel.exit_status_ready() \
    and not channel.recv_stderr_ready()  \
    and not channel.recv_ready():
        channel.shutdown_read() 
        channel.close()
    
    stdout.close()
    stderr.close()
    return channel.recv_exit_status() == 0, ''.join(stdout_chunks)
```

For each node I spawn a thread and then use the above two functions to create a tunnel and then run commands respectively.

**Comment by arshdeeptinna** [comment]
This is not a paramiko issue!!

**Comment by bitprophet** [comment]
Glad you got some resolution - thanks for the update!
