### ISSUE TITLE
hang after transferring several files

### ISSUE THREAD

**Issue by dellelce** [paramiko/paramiko#814]
Hello,

After transferring several files using paramiko(2.0.2)/sftp I see the connection simply hangs with both parties (paramiko/python) and sftp-server hanging, these is what I have:

## client side (python logs)

```
2016-09-08 12:34:53,938:[chan 0] stat(b'/ftp/wuftpd/log/xferlog-20151110.gz')
2016-09-08 12:34:53,939:[chan 0] open(b'/ftp/wuftpd/log/xferlog-20151110.gz', 'rb')
2016-09-08 12:34:53,940:[chan 0] open(b'/ftp/wuftpd/log/xferlog-20151110.gz', 'rb') -> b'00000001'
2016-09-08 12:34:53,978:[chan 0] close(b'00000001')
```

the close line is the last line after which the hang happens.

## client (python): strace

```
(default) app@server:/u01/app/ftpdashboard/background/py/tests> strace -fp 2059
Process 2059 attached with 2 threads - interrupt to quit
[pid  2060] --- SIGTSTP (Stopped) @ 0 (0) ---
[pid  2060] clock_gettime(CLOCK_MONOTONIC, {21165770, 992682563}) = 0
[pid  2060] clock_gettime(CLOCK_MONOTONIC, {21165770, 992804563}) = 0
[pid  2060] poll([{fd=5, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid  2060] clock_gettime(CLOCK_MONOTONIC, {21165771, 93872563}) = 0
[pid  2060] poll([{fd=5, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid  2060] clock_gettime(CLOCK_MONOTONIC, {21165771, 194814563}) = 0
[pid  2060] poll([{fd=5, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid  2060] clock_gettime(CLOCK_MONOTONIC, {21165771, 295771563}) = 0
[pid  2060] poll([{fd=5, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid  2060] clock_gettime(CLOCK_MONOTONIC, {21165771, 396766563}) = 0
[pid  2060] poll([{fd=5, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid  2060] clock_gettime(CLOCK_MONOTONIC, {21165771, 497727563}) = 0
[pid  2060] poll([{fd=5, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid  2060] clock_gettime(CLOCK_MONOTONIC, {21165771, 598603563}) = 0
[pid  2060] poll([{fd=5, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid  2060] clock_gettime(CLOCK_MONOTONIC, {21165771, 699664563}) = 0
[pid  2060] poll([{fd=5, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid  2060] clock_gettime(CLOCK_MONOTONIC, {21165771, 800579563}) = 0
[pid  2060] poll([{fd=5, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid  2060] clock_gettime(CLOCK_MONOTONIC, {21165771, 900491563}) = 0
[pid  2060] poll([{fd=5, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid  2060] clock_gettime(CLOCK_MONOTONIC, {21165772, 474563}) = 0
[pid  2060] poll([{fd=5, events=POLLIN}], 1, 100 <unfinished ...>
Process 2059 detached
Process 2060 detached
```

## sftp-server side: lsof (final lines)

```
sftp-serv 15213 oracle    0r  FIFO    0,8      0t0 117487002 pipe
sftp-serv 15213 oracle    1w  FIFO    0,8      0t0 117487003 pipe
sftp-serv 15213 oracle    2w  FIFO    0,8      0t0 117487004 pipe
sftp-serv 15213 oracle    3r  FIFO    0,8      0t0 117487002 pipe
sftp-serv 15213 oracle    4w  FIFO    0,8      0t0 117487003 pipe
sftp-serv 15213 oracle    5r   DIR  253,2   126976   6029707 /ftp/wuftpd/log
```

## sftp-server side: strace

```
-bash-4.1$ strace -fp 15213
Process 15213 attached - interrupt to quit
select(5, [3], [], NULL, NULL^C <unfinished ...>
Process 15213 detached
-bash-4.1$ 
```

## comments

I am unable to change sftp-server configuration (no root access) and enable logging there for more detailed analysis there, but I believe it is a client side issue as that specific server is used a lot for file-transfers and it would be noticed if sshd/sftp-server side had any issue like that..

Probably just closing the connection after each file could be used as a workaround?

**Comment by bitprophet** [comment]
Possibly related to #515 or #462, haven't verified yet. Thanks for the report!

**Comment by dellelce** [comment]
I believe the issue is in ```listdir_iter```, as this control-c trace tells:

```
Traceback (most recent call last):
  File "./testsftp.py", line 110, in <module>
    main(sys.argv)
  File "./testsftp.py", line 74, in main
    for i in sftp.listdir_iter(dirName,  read_aheads=500):
  File "/u01/app/django/envs/default/lib/python3.5/site-packages/paramiko/sftp_client.py", line 258, in listdir_iter
    t, pkt_data = self._read_packet()
  File "/u01/app/django/envs/default/lib/python3.5/site-packages/paramiko/sftp.py", line 173, in _read_packet
    x = self._read_all(4)
  File "/u01/app/django/envs/default/lib/python3.5/site-packages/paramiko/sftp.py", line 156, in _read_all
    x = self.sock.recv(n)
  File "/u01/app/django/envs/default/lib/python3.5/site-packages/paramiko/channel.py", line 613, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/u01/app/django/envs/default/lib/python3.5/site-packages/paramiko/buffered_pipe.py", line 156, in read
    self._cv.wait(timeout)
  File "/u01/app/apache/default/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
```

I replaced it with a ```listdir_attr``` call and a list and the issue has gone.

**Comment by naoko** [comment]
I'm having similar if not the same...
I have a program that `ls` directory of remote server and if file exists then download.
After running a few to several hours, it goes to the state of deadlock.

strace
```
[pid 29681] futex(0x7ff34383b6a0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1498156886, tv_nsec=274999000}, 0xffffffff <unfinished ...>
[pid  1488] <... poll resumed> )        = 0 (Timeout)
[pid  1488] poll([{fd=7, events=POLLIN}], 1, 100 <unfinished ...>
[pid 29681] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 29681] futex(0x7ff34383b6a0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1498156886, tv_nsec=375448000}, 0xffffffff^Cstrace: Process 29681 detached
```

```
(gdb) py-list
 292                if timeout is None:
 293                    waiter.acquire()
 294                    gotit = True
 295                else:
 296                    if timeout > 0:
>297                        gotit = waiter.acquire(True, timeout)
 298                    else:
 299                        gotit = waiter.acquire(False)
 300                return gotit
 301            finally:
 302                self._acquire_restore(saved_state)
(gdb) py-bt
Traceback (most recent call first):
  <built-in method acquire of _thread.lock object at remote 0x7ff3307e1a80>
  File "/usr/lib/python3.5/threading.py", line 297, in wait
    gotit = waiter.acquire(True, timeout)
  File "/usr/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/srv/transporter/venv/lib/python3.5/site-packages/paramiko/transport.py", line 821, in open_channel
    event.wait(0.1)
  File "/srv/transporter/venv/lib/python3.5/site-packages/paramiko/transport.py", line 705, in open_session
    timeout=timeout)
  File "/srv/transporter/venv/lib/python3.5/site-packages/paramiko/client.py", line 420, in exec_command
    chan = self._transport.open_session(timeout=timeout)
  File "/srv/transporter/venv/lib/python3.5/site-packages/nextdata/transporter/client.py", line 61, in _run
    stdin, stdout, stderr = client.exec_command(command)
```
The command above is `ls` remote directory.

lsof only diff with state where no-deadlock
```
naoko.t 29681 root    7u  IPv4 151203236      0t0       TCP mach-learn-dev01-s01:43992->123.22.333.104.bc.googleusercontent.com:ssh (ESTABLISHED)
```

**Comment by alkuzad** [comment]
Same, small recursive function does not work with `listdir_iter`

**Comment by faydogan** [comment]
Hi folks,

We use vast amount of threads to connect more than 10,000 equipment and I guess our problem related with this subject.

After an hour of our script execution we are getting lots of threads like '<paramiko.Transport at 0x16e38f50 (cipher aes128-ctr, 128 bits) (active; 0 open channel(s))>' this. Threads hangs on waiting. 

We have adjusted our code with:
- Well used try/catch blocks (to cover every type of error/warning,
- We are sure that we have kill/close statement for our SSH connections,

but still getting a lot of hanged threads.

I think the main problem in here, Paramiko is not killing connection when it gets an error/warning or the socket it used stays open after an error occured.

**Comment by ploxiln** [comment]
I think this particular issue is originally about `SFTPClient.list_iter()` - looking at this function, it looks like it has always been a bit flawed, because it assumes you do nothing with that ssh channel in the middle of the generator, like opening and reading some of the files you are iterating over. This change might help, or it might not be sufficient:

```diff
--- a/paramiko/sftp_client.py
+++ b/paramiko/sftp_client.py
@@ -300,12 +300,9 @@ class SFTPClient(BaseSFTP, ClosingContextManager):
                 # Exit the loop when we've reached the end of the directory
                 # handle
                 for num in nums:
-                    t, pkt_data = self._read_packet()
+                    t, pkt_data = self._read_response(num)
                     msg = Message(pkt_data)
                     new_num = msg.get_int()
-                    if num == new_num:
-                        if t == CMD_STATUS:
-                            self._convert_status(msg)
                     count = msg.get_int()
                     for i in range(count):
                         filename = msg.get_text()
```

`_read_response()` does `_read_packet()`, and the `CMD_STATUS` check, and it also checks if the next packet received is actually for an open SFTPFile and handles it appropriately, until it gets the appropriate command response packet.

Another idea is that the `read_aheads` argument may be too big, you could try overriding the default 50 with something like 2.
