### ISSUE TITLE
Attempting to open a file against Windows Server 2012 R2

### ISSUE THREAD

**Issue by espguitarist33** [paramiko/paramiko#843]
We have been using the same put command to place files on our server for years now and it has been working across all of the platforms in use.

I'm having this problem in this Windows Server 2012 R2 environment that the put throws:
  File "C:\DeploymentUnit\Python27\lib\site-packages\paramiko\sftp_client.py", line 565, in put
    fr = self.file(remotepath, 'wb')
  File "C:\DeploymentUnit\Python27\lib\site-packages\paramiko\sftp_client.py", line 247, in open
    raise SFTPError('Expected handle')
paramiko.SFTPError: Expected handle

I'm noticing that t is actually 101 instead of 102. if I change my target IP to another operating system the code works successfully.  I can't find any documentation for Expected Handle error and don't know enough about the internal workings to speculate further.

Thanks!

**Comment by derks** [comment]
I am having similar issues against Windows Server 2012 R2, though wrapped with Fabric's `put` operations.  System info:

Python: `2.7.11`
Paramiko: `2.0.2` 
Fabric: `1.12.0`
OSX: `10.12.1`
Windows Powershell Server (SSH): `6.0.6100`

On the client side, the destination path looks correct (`C:\\path\\to\\my\\destination`), but on the Windows server side the path looks like it's being converted to a unix type path (`/C:/path/to/my/destination`) which fails.

To tract this down, I added a print statement at the very last point in `paramiko/sftp_client.py`:

```
$ diff -Naur ~/.env/proctor-scenarios-py2/lib/python2.7/site-packages/paramiko/sftp_client.py.orig ~/.env/proctor-scenarios-py2/lib/python2.7/site-packages/paramiko/sftp_client.py
--- /Users/derks/.env/proctor-scenarios-py2/lib/python2.7/site-packages/paramiko/sftp_client.py.orig    2016-11-08 16:54:58.000000000 -0600
+++ /Users/derks/.env/proctor-scenarios-py2/lib/python2.7/site-packages/paramiko/sftp_client.py 2016-11-08 16:54:38.000000000 -0600
@@ -311,6 +311,7 @@
         :raises IOError: if the file could not be opened.
         """
         filename = self._adjust_cwd(filename)
+        print('open(%r, %r)' % (filename, mode))
         self._log(DEBUG, 'open(%r, %r)' % (filename, mode))
         imode = 0
         if ('r' in mode) or ('+' in mode):
```

Which prints:

```
open('C:\\path\\to\\my\\destination', 'wb')
```


Nothing has changed on the Windows side... so having a really hard time understanding where the breakage is.

**Comment by derks** [comment]
Simplified, and reduced down to a working/reproducable Paramiko SFTPClient example (without Fabric in the middle).

**Vagrantfile**

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "trueability/windows-server-2012-r2"
  config.vm.communicator = "winrm"
  config.rdp.username = 'Administrator'
  config.winrm.username = 'Administrator'
  config.winrm.password = 'vagrant'
  config.ssh.username = 'Administrator'
  config.vm.network :forwarded_port,
    guest: 3389,
    host: 3389,
    auto_correct:true
  config.vm.network :forwarded_port,
    guest: 5985,
    host: 5985,
    id: "winrm",
    auto_correct:true
end
```

**test.file**

```
Arbitrary test file
```

**sftp_example.py**

```python
import socket
from paramiko import SFTPClient, SSHConfig, Transport

source = 'test.file'
hostname = '127.0.0.1'
hostkey = '/Users/derks/.vagrant.d/insecure_private_key'
username = 'Administrator'
password = 'vagrant'

t = Transport((hostname, 2200))
t.connect(username=username, password=password)
sftp = SFTPClient.from_transport(t)

### relative upload (wherever sftp server upload path is)
print('RELATIVE UPLOAD PATH')
sftp.put(source, 'test.file')

### absolute path
print('ABSOLUTE UPLOAD PATH')
sftp.put(source, 'C:\\test.file')

sftp.close()
```

**Steps to Reproduce**

```
$ vagrant up

$ python sftp_example.py
RELATIVE UPLOAD PATH
ABSOLUTE UPLOAD PATH
Traceback (most recent call last):
  File "sftp_example.py", line 19, in <module>
    sftp.put(source, 'C:\\test.file')
  File "/usr/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 669, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
  File "/usr/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 621, in putfo
    with self.file(remotepath, 'wb') as fr:
  File "/usr/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 327, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 729, in _request
    return self._read_response(num)
  File "/usr/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 776, in _read_response
    self._convert_status(msg)
  File "/usr/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 806, in _convert_status
    raise IOError(text)
IOError: Server error.
```

**SFTP Server Log**
```
### relative upload path - success
[11/14/2016 13:57:31] [1132] [7] [66540731] Connection received from: 10.0.2.2:58025
[11/14/2016 13:57:32] [1132] [5] [66540731] AcceptClient 10.0.2.2 .
[11/14/2016 13:57:32] [1132] [5] Client accepted from 58025 with username WINDOWS-SERVER-\Administrator
[11/14/2016 13:57:32] [1132] [541] [66540731] Client 10.0.2.2 disconnected.

### absolute upload path - fail
[11/14/2016 13:59:10] [1132] [7] [48360500] Connection received from: 10.0.2.2:59616
[11/14/2016 13:59:10] [1132] [4] [48360500] AcceptClient 10.0.2.2 .
[11/14/2016 13:59:10] [1132] [4] Client accepted from 59616 with username WINDOWS-SERVER-\Administrator
[11/14/2016 13:59:10] [1132] [202] SFTP error: 2001 Specified path is invalid ("/C:/test.file")
[11/14/2016 13:59:10] [1132] [202] [48360500] Client 10.0.2.2 disconnected.
```

**Comment by derks** [comment]
Well... I just did this same test with an alternate Windows SSH Server (Bitvise) and it went through without issues.... now I have no clue as I don't see any reason why a Powershell/SSH/SFTP server on Windows would be trying to convert `C:\\path\\to\\some\\file` to `/C:/path/to/some/file`.  Make no sense... but I'll continue foward with their support on it also.

Any pointers, or anyone having similar issue would be great appreciated.

**Comment by derks** [comment]
Please disregard all of my noise... the issue ended up being a permission issue on the server side and had nothing to do with Paramiko.  In my tests, I was attempting to upload to `C:\myfile` directly, which was failing (I think because of permissions or maybe restrictions in the SFTP server I was using).  By changing the path to `C:\sftp\myfile` it was fine.

At this point, it's likely that my issue is unrelated to the OP... but worth keeping here just in case.
