### ISSUE TITLE
Call to missing_host_key missing the 'key' positional argument

### ISSUE THREAD

**Issue by pmariani** [paramiko/paramiko#850]
On https://github.com/paramiko/paramiko/blob/master/paramiko/client.py#L360 , that call should provide a 3rd positional argument.

**Comment by bitprophet** [comment]
Thanks for the report! Can you provide specific details re: how this is surfacing in your environment? Stack trace, unexpected behavior, etc. (Assuming you're getting an arity/type/etc error...)

If I'm reading this right, it's _probably_ only affecting a specific policy class, if it was affecting all of them I'd expect this to have come up much more often. But, that's why I'm asking for details :) (Plus they're just useful for folks searching for the error themselves, etc.)

**Comment by pmariani** [comment]
Hi,

Here is a painfully detailed but hopefully complete repro transcript.

```shell
vagrant@dev:~$ ls -al ~/.ssh
total 20
drwx------ 2 vagrant vagrant 4096 Nov 29 23:11 .
drwxr-xr-x 7 vagrant vagrant 4096 Nov 29 19:01 ..
-rw------- 1 vagrant vagrant 1167 Nov 29 18:50 authorized_keys
-rw------- 1 vagrant vagrant 1679 Nov 29 23:11 id_rsa
-rw-r--r-- 1 vagrant vagrant  393 Nov 29 23:11 id_rsa.pub
vagrant@dev:~$
vagrant@dev:~$ lxc list
+------+---------+-------------------+-----------------------------------------------+------------+-----------+
| NAME |  STATE  |       IPV4        |                     IPV6                      |    TYPE    | SNAPSHOTS |
+------+---------+-------------------+-----------------------------------------------+------------+-----------+
| c1   | RUNNING | 10.0.3.205 (eth0) | fd7e:d2c7:515e:e67a:216:3eff:fef4:4fc3 (eth0) | PERSISTENT | 0         |
+------+---------+-------------------+-----------------------------------------------+------------+-----------+
vagrant@dev:~$
vagrant@dev:~$ lxc exec c1 bash
root@c1:~# id ubuntu
uid=1000(ubuntu) gid=1000(ubuntu) groups=4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),102(netdev),1000(ubuntu)
root@c1:~# exit
vagrant@dev:~$ lxc file push ~/.ssh/id_rsa.pub c1/home/ubuntu/.ssh/authorized_keys --uid=1000 --gid=1000 
vagrant@dev:~$
vagrant@dev:~$ virtualenv --python python3 venv
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/vagrant/venv/bin/python3
Also creating executable in /home/vagrant/venv/bin/python
Installing setuptools, pip, wheel...done.
vagrant@dev:~$ . venv/bin/activate
(venv) vagrant@dev:~$
(venv) vagrant@dev:~$ pip install paramiko
Collecting paramiko
  Downloading https://packages.<redacted>.org/root/pypi/+f/730/907c61546286d/paramiko-2.0.2-py2.py3-none-any.whl (171kB)
    100% |████████████████████████████████| 174kB 4.6MB/s 
Collecting cryptography>=1.1 (from paramiko)
  Using cached https://packages.<redacted>.org/root/pypi/+f/33e/d393be75f04cd/cryptography-1.6.tar.gz
Collecting pyasn1>=0.1.7 (from paramiko)
  Using cached https://packages.<redacted>.org/root/pypi/+f/012/2c4548f64510b/pyasn1-0.1.9-py2.py3-none-any.whl
Collecting idna>=2.0 (from cryptography>=1.1->paramiko)
  Using cached https://packages.<redacted>.org/root/pypi/+f/350/4ea3c28f95c5c/idna-2.1-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography>=1.1->paramiko)
  Using cached https://packages.<redacted>.org/build/external/+f/0ff/78c403d9bccf5/six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=11.3 in ./venv/lib/python3.4/site-packages (from cryptography>=1.1->paramiko)
Collecting cffi>=1.4.1 (from cryptography>=1.1->paramiko)
  Downloading https://packages.<redacted> .org/root/pypi/+f/b8e/356442d98843b/cffi-1.9.1-cp34-cp34m-manylinux1_x86_64.whl (398kB)
    100% |████████████████████████████████| 399kB 3.5MB/s 
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.1->paramiko)
Building wheels for collected packages: cryptography
  Running setup.py bdist_wheel for cryptography ... done
  Stored in directory: /home/vagrant/.cache/pip/wheels/89/5c/a0/bc5e27d130550979617c157a37e1e4e61770766f9f5a42493e
Successfully built cryptography
Installing collected packages: idna, pyasn1, six, pycparser, cffi, cryptography, paramiko
Successfully installed cffi-1.9.1 cryptography-1.6 idna-2.1 paramiko-2.0.2 pyasn1-0.1.9 pycparser-2.17 six-1.10.0
(venv) vagrant@dev:~$ python /vagrant/paramiko-repro.py 
Traceback (most recent call last):
  File "/vagrant/paramiko-repro.py", line 32, in <module>
    try_connecting_with_policy(policy)
  File "/vagrant/paramiko-repro.py", line 25, in try_connecting_with_policy
    client.connect(IP, username='ubuntu')
  File "/home/vagrant/venv/lib/python3.4/site-packages/paramiko/client.py", line 361, in connect
    server_key)
TypeError: missing_host_key() missing 1 required positional argument: 'key'

Traceback (most recent call last):
  File "/vagrant/paramiko-repro.py", line 32, in <module>
    try_connecting_with_policy(policy)
  File "/vagrant/paramiko-repro.py", line 25, in try_connecting_with_policy
    client.connect(IP, username='ubuntu')
  File "/home/vagrant/venv/lib/python3.4/site-packages/paramiko/client.py", line 361, in connect
    server_key)
TypeError: missing_host_key() missing 1 required positional argument: 'key'

Traceback (most recent call last):
  File "/vagrant/paramiko-repro.py", line 32, in <module>
    try_connecting_with_policy(policy)
  File "/vagrant/paramiko-repro.py", line 25, in try_connecting_with_policy
    client.connect(IP, username='ubuntu')
  File "/home/vagrant/venv/lib/python3.4/site-packages/paramiko/client.py", line 361, in connect
    server_key)
TypeError: missing_host_key() missing 1 required positional argument: 'key'

Traceback (most recent call last):
  File "/vagrant/paramiko-repro.py", line 32, in <module>
    try_connecting_with_policy(policy)
  File "/vagrant/paramiko-repro.py", line 25, in try_connecting_with_policy
    client.connect(IP, username='ubuntu')
  File "/home/vagrant/venv/lib/python3.4/site-packages/paramiko/client.py", line 361, in connect
    server_key)
TypeError: missing_host_key() missing 1 required positional argument: 'key'

(venv) vagrant@dev:~$ 

```

The content of /vagrant/paramiko-repro.py is:
```python
import traceback

import paramiko
import paramiko.client

IP = '10.0.3.205'


class MyDoNothingPolicy():
    def missing_host_key(self, *args):
        pass

POLICIES_AND_EXPECTING_ERROR = (
    (paramiko.client.MissingHostKeyPolicy, True),
    (paramiko.client.AutoAddPolicy, True),
    (paramiko.client.RejectPolicy, True),
    (paramiko.client.WarningPolicy, True),
    (MyDoNothingPolicy, False),
)


def try_connecting_with_policy(policy):
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(policy)
    client.connect(IP, username='ubuntu')


if __name__ == '__main__':
    for policy, expecting_error in POLICIES_AND_EXPECTING_ERROR:
        if expecting_error:
            try:
                try_connecting_with_policy(policy)
                assert False, 'should get error when expecting one'
            except TypeError as e:
                assert str(e) == "missing_host_key() missing 1 required positional argument: 'key'"
                print(traceback.format_exc())
        else:
            try_connecting_with_policy(policy)


```

**Comment by bitprophet** [comment]
Fun, thanks! Which policy were you using in your real world code, if I may ask?

**Comment by pmariani** [comment]
In my case I wanted to use the WarningPolicy.

**Comment by radssh** [comment]
``client.set_missing_host_key_policy()`` is somewhat of an oddball at a glance. The docs do state that it takes as a parameter the policy object, not class. The ``self`` passed into it is not the typical python object self-reference of the policy, but the **client** instance. Try invoking ``client.set_missing_host_key_policy(policy())`` instead, it looks like that should fix your errors.

Paramiko probably ought to raise an exception (plain TypeError?) within ``client.set_missing_host_key_policy()`` is the parameter is not an instance of ``MissingHostKeyPolicy``.

**Comment by pmariani** [comment]
Ah, yes, that makes sense. The self argument that is actually the client confused me. Thanks!

**Comment by bitprophet** [comment]
Totally missed that earlier...yup, it's an oldie and a goodie. I continue to not understand why it was written that way, feels like a classic example of "Java in Python".

Think we could probably update `set_missing_host_key_policy` to auto-instantiate if given a class, and I actually bet $1 there's already a moldy old PR somewhere in here that does that...if there isn't TBH we should reopen this and make it track that idea.

**Comment by bitprophet** [comment]
See #857
