### ISSUE TITLE
login to a server with an empty password and no keys

### ISSUE THREAD

**Issue by mzakharocsc** [paramiko/paramiko#890]
Hi,
I am trying to login to SSH server that has no password set. aka: no password, and no key file. It works through command line 'ssh', but not through paramiko.  Is this type of authentication supported?

**Comment by bitprophet** [comment]
I've never tried this; my guess is that it "should" be supported, but I'd bet dollars to donuts that the current auth module would break when you try (it's scheduled for a rework as it's old and crusty, e.g. we only fixed two-factor auth a year or two ago).

A quick browse of the code implies that there is support for an auth type of `none`, e.g. if one calls `Transport.auth_none(username)` (provided one has set up the transport correctly otherwise; see e.g. where `client.py` calls things like `self.transport.auth_publickey`, which is the area you'd want to mimic/branch off.)

Again, I'd bet that particular code path is not frequently tested, but it might be worth a shot :) good luck and do report back if you try! Closing for now as unactionable but comments welcome and can always reopen if you find legit bugs we can fix.

**Comment by jkilpatr** [comment]
It in fact does not work, here's a stack trace for future adventurers 

INFO:root:ssh root@192.168.1.1:22
DEBUG:paramiko.transport:starting thread (client mode): 0xe5359e80
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-dropbear
INFO:paramiko.transport:Connected (version 2.0, client dropbear)
DEBUG:paramiko.transport:kex algos:['curve25519-sha256@libssh.org', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1', 'kexguess2@matt.ucc.asn.au'] server key:['ssh-rsa'] client encrypt:['aes128-ctr', 'aes256-ctr'] server encrypt:['aes128-ctr', 'aes256-ctr'] client mac:['hmac-sha1', 'hmac-sha2-256'] server mac:['hmac-sha1', 'hmac-sha2-256'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group14-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup14 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
/home/justin/.local/lib/python3.6/site-packages/paramiko/client.py:779: UserWarning: Unknown ssh-rsa host key for [192.168.1.1]:22: b'3958d0180f721bd78965fc86e7ceacbc'
  key.get_name(), hostname, hexlify(key.get_fingerprint()),
DEBUG:paramiko.transport:Trying SSH agent key b'4ce300485736ef8269b27d8f0ce2dec8'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) failed.
DEBUG:paramiko.transport:Trying SSH agent key b'ed92dc5bd7b84366b2d0c86d3fc21ba5'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) failed.
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) failed.
Traceback (most recent call last):
  File "flash-althea.py", line 240, in <module>
    main()
  File "flash-althea.py", line 237, in main
    flash_device(device, opts)
  File "flash-althea.py", line 191, in flash_device
    flash_sysupgrade(device)
  File "flash-althea.py", line 118, in flash_sysupgrade
    client, scp = ssh_setup(device)
  File "flash-althea.py", line 90, in ssh_setup
    password=device['sshPassword'])
  File "/home/justin/.local/lib/python3.6/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/justin/.local/lib/python3.6/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
  File "/home/justin/.local/lib/python3.6/site-packages/paramiko/client.py", line 701, in _auth
    self._transport.auth_password(username, password)
  File "/home/justin/.local/lib/python3.6/site-packages/paramiko/transport.py", line 1381, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "/home/justin/.local/lib/python3.6/site-packages/paramiko/auth_handler.py", line 226, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

**Comment by basic-settings** [comment]
Facing the same issue in our R&D, as our devices come off prod line without a password and no keyfile.

**Comment by pavelrad** [comment]
Doesn't work in `paramiko==2.4.2`. From the fork above it looks to be a simple fix: https://github.com/mzakharo/paramiko/commit/6e979ea686975579a204472a1414c8d76c11d6eb. Could it be added here?

**Comment by thaurelia** [comment]
For situations where maintaining own fork is not feasible or impossible (think Pythonista iOS app etc.) the following ad-hoc fix can be applied

```
from contextlib import suppress
with suppress(paramiko.ssh_exception.AuthenticationException):
    client.connect(host, username=username, password='')
client.get_transport().auth_none(username)
```

**Comment by hughesxu** [comment]
I am also facing the same issue. 
I add the fix mzakharo@6e979ea in my script code.

`self.transport = paramiko.Transport((self.host, self.port))`
`self.transport.auth_none(username=self.username)`
`self.transport.connect(username=self.username, password=None)`
`self.client = paramiko.SSHClient() `
`self.client._transport = self.transport `

But it shows: No existing session.
How can I solve this problem?

**Comment by thaurelia** [comment]
@hughesxu 
When you call `auth_none` on the second line, `self.transport.active` is `False` – you just initialised it and haven't done anything yet. Because of the default values set in `Transport.__init__`, [this check](https://github.com/paramiko/paramiko/blob/cf7d49d66f3b1fbc8b0853518a54050182b3b5eb/paramiko/transport.py#L1368) in `auth_none` fails.

I suggest you use the high-level `paramiko.SSHClient` that will set all the flags and after that, just replace the auth method in transport, like I did in my example.

If you insist on constructing everything from lower-level pieces, make sure to shuffle the manual method calls in the correct order so that `Transport.active` and `Transport.initial_kex_done` are both `True` before calling `Transport.auth_none`

**Comment by hughesxu** [comment]
> @hughesxu
> When you call `auth_none` on the second line, `self.transport.active` is `False` – you just initialised it and haven't done anything yet. Because of the default values set in `Transport.__init__`, [this check](https://github.com/paramiko/paramiko/blob/cf7d49d66f3b1fbc8b0853518a54050182b3b5eb/paramiko/transport.py#L1368) in `auth_none` fails.
> 
> I suggest you use the high-level `paramiko.SSHClient` that will set all the flags and after that, just replace the auth method in transport, like I did in my example.
> 
> If you insist on constructing everything from lower-level pieces, make sure to shuffle the manual method calls in the correct order so that `Transport.active` and `Transport.initial_kex_done` are both `True` before calling `Transport.auth_none`

Thanks.
I tried with high-level paramiko.SSHClient, and succeed!

> self.client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>                 self.client.connect(hostname=self.host, username=self.username, port=self.port, password=None, timeout=self.timeout, allow_agent=False, look_for_keys=False)
>

**Comment by sachinteotia30** [comment]
@hughesxu 

I am also facing the auth issue when I am tring to connect without password.  Following is the way I am trying to conect to my_hostname without password.
===============================================
import paramiko
port=22
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(hostname=my_hostname, username=my_username, port=port, password=None, timeout=10, allow_agent=False, look_for_keys=False)
===============================================

I am geting the below Exception-
>>> client.connect(hostname=hostname, username=username, port=port, password=None, timeout=10, allow_agent=False, look_for_keys=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 307, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 520, in _auth
    raise SSHException('No authentication methods available')
paramiko.ssh_exception.SSHException: No authentication methods available
======================================================

Am I doing something wrong?

Regards,
Sachin

**Comment by ploxiln** [comment]
paramiko currently cannot login without any password or key ... but try https://github.com/paramiko/paramiko/pull/1106 (also incorporated in recent releases of my fork https://github.com/ploxiln/paramiko-ng/)

**Comment by AlbertEmil** [comment]
@ploxiln

Just to clarify: Is this behavior (unable to login without password) still a problem and just related to pull request #1106 which is over three years old?

I just tried to use paramiko (in conjunction with fabric) against an DropBear SSH server instance on OpenWRT which do not have any passwords set on initial login. Logging in and setting a password solved the problem, but this seems to be rather tedious in and production environment with multiple deployments/devices.

**Comment by basic-settings** [comment]
"Logging in and setting a password solved the problem" is not always a solution, especially in end-of-line testing.

We can produce and test more than 1000 devices a day, this would be more than tedious (time/money loss). Currently the fork seems to do it fine, it would be great if it's part of the main repo for easier testing environment maintenance.

**Comment by poleguy** [comment]
Unfortunately I can't find a way to work around this issue in fabric as get_transport doesn't seem to be exposed.

**Comment by poleguy** [comment]
Actually I got fabric to work with no password by modifying these lines... 
site-packages/fabric/connection.py

```
        # Actually connect!
        try:
            self.client.connect(**kwargs)
        except SSHException as e:
            self.client.get_transport().auth_none('root')
        
        self.transport = self.client.get_transport()
```
It seems paramiko should try auth_none by default because that's what normal ssh does. PR anyone?

I decided not to use fabric, in favor of just raw paramiko, as it was a better fit for my use case: interactive control, like in this question:
https://stackoverflow.com/questions/61290921/how-to-control-an-interactive-ssh-session-with-pythons-subprocess

**Comment by bskinn** [comment]
Reopening for re-consideration.

**Comment by TimonLukas** [comment]
I just encountered this issue, it would be great to see a fix implemented. I used [@thaurelia's suggestion](https://github.com/paramiko/paramiko/issues/890#issuecomment-423198893) and created a small factory:

```python
def create_ssh_client(ip: str, username: str, password: str = None, port: int = 22, auto_add_unknown_hosts: bool = True):
    client = paramiko.SSHClient()

    if auto_add_unknown_hosts:
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy)

    if password is None:
        with suppress(paramiko.ssh_exception.AuthenticationException):
            client.connect(ip, port, username=username)
        client.get_transport().auth_none(username)
        return client

    client.connect(ip, port, username=username, password=password)
    return client
```

But it would be nice not to have to do so - especially since this keeps me from using Fabric.

**Comment by Nagidal** [comment]
> @hughesxu When you call `auth_none` on the second line, `self.transport.active` is `False` – you just initialised it and haven't done anything yet. Because of the default values set in `Transport.__init__`, [this check](https://github.com/paramiko/paramiko/blob/cf7d49d66f3b1fbc8b0853518a54050182b3b5eb/paramiko/transport.py#L1368) in `auth_none` fails.
> ...
> If you insist on constructing everything from lower-level pieces, make sure to shuffle the manual method calls in the correct order so that `Transport.active` and `Transport.initial_kex_done` are both `True` before calling `Transport.auth_none`

I tried to compose the client from the low-level commands. This is what works for my no-auth machine:

```python
from paramiko import AutoAddPolicy, SSHClient
from paramiko.transport import Transport

sock = ("192.168.1.123", 22) # address and port
username = "root"

client = SSHClient()
client.set_missing_host_key_policy(AutoAddPolicy())

transport = Transport(sock)
transport.start_client()
transport.auth_none(username)
client._transport = transport
```

the log is such:
```
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_3.0.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-dropbear_2017.75
INFO:paramiko.transport:Connected (version 2.0, client dropbear_2017.75)
DEBUG:paramiko.transport:=== Key exchange possibilities ===
DEBUG:paramiko.transport:kex algos: curve25519-sha256@libssh.org, ecdh-sha2-nistp521, ecdh-sha2-nistp384, ecdh-sha2-nistp256, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1, kexguess2@matt.ucc.asn.au
DEBUG:paramiko.transport:server key: ssh-rsa
DEBUG:paramiko.transport:client encrypt: aes128-ctr, aes256-ctr, aes128-cbc, aes256-cbc, twofish256-cbc, twofish-cbc, twofish128-cbc, 3des-ctr, 3des-cbc
DEBUG:paramiko.transport:server encrypt: aes128-ctr, aes256-ctr, aes128-cbc, aes256-cbc, twofish256-cbc, twofish-cbc, twofish128-cbc, 3des-ctr, 3des-cbc
DEBUG:paramiko.transport:client mac: hmac-sha1-96, hmac-sha1, hmac-sha2-256, hmac-sha2-512, hmac-md5
DEBUG:paramiko.transport:server mac: hmac-sha1-96, hmac-sha1, hmac-sha2-256, hmac-sha2-512, hmac-md5
DEBUG:paramiko.transport:client compress: zlib@openssh.com, none
DEBUG:paramiko.transport:server compress: zlib@openssh.com, none
DEBUG:paramiko.transport:client lang: <none>
DEBUG:paramiko.transport:server lang: <none>
DEBUG:paramiko.transport:kex follows: False
DEBUG:paramiko.transport:=== Key exchange agreements ===
DEBUG:paramiko.transport:Kex: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey: ssh-rsa
DEBUG:paramiko.transport:Cipher: aes128-ctr
DEBUG:paramiko.transport:MAC: hmac-sha2-256
DEBUG:paramiko.transport:Compression: none
DEBUG:paramiko.transport:=== End of kex handshake ===
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (none) successful!
```

**Comment by eeintech** [comment]
After pulling my hair for an hour, I found this issue and I am _really_ surprised the no password case is not handled properly 😨 It sound like a no brainer...

**Comment by bskinn** [comment]
bitprophet has been working on improving the flexibility of the key/auth tooling lately, per #387 and #23. It would be great if someone with an interest in this could check out the **experimental** new features described in the [3.2.0 paramiko CHANGELOG] (including the new `OpenSSHAuthStrategy` implementation in [Fabric 3.1.0]) -- it's possible that they may enable this sort of auth on the user side, and not require augmentation of `paramiko` itself.

If nothing else, that would provide a clean recipe for folks to use, not requiring hotfixing or use of a side branch. It may also provide a template for a possible paramiko or Fabric implementation.

[3.2.0 paramiko changelog]: https://www.paramiko.org/changelog.html#3.2.0
[fabric 3.1.0]: https://www.fabfile.org/changelog.html#3.1.0
