### ISSUE TITLE
Connection fails with AES-CTR: CTR mode needs counter parameter, not IV

### ISSUE THREAD

**Issue by apapsch** [paramiko/paramiko#901]
When Paramiko uses AES-CTR mode, connection fails:

```
Unknown exception: CTR mode needs counter parameter, not IV
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/paramiko/transport.py", line 1744, in run
    self.kex_engine.parse_next(ptype, m)
  File "/usr/lib64/python3.4/site-packages/paramiko/kex_group1.py", line 75, in parse_next
    return self._parse_kexdh_reply(m)
  File "/usr/lib64/python3.4/site-packages/paramiko/kex_group1.py", line 112, in _parse_kexdh_reply
    self.transport._activate_outbound()
  File "/usr/lib64/python3.4/site-packages/paramiko/transport.py", line 2074, in _activate_outbound
    engine = self._get_cipher(self.local_cipher, key_out, IV_out)
  File "/usr/lib64/python3.4/site-packages/paramiko/transport.py", line 1649, in _get_cipher
    return self._cipher_info[name]['class'].new(key, self._cipher_info[name]['mode'], iv, counter)
  File "/usr/lib64/python3.4/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: CTR mode needs counter parameter, not IV
```

The issue has been reported to pycrypto:
https://github.com/dlitz/pycrypto/issues/149

However, they insist that the behaviour of pycrypto has changed and that clients need to adapt. In this case, paramiko should not assume IV will be ignored in AES-CTR mode. Instead it should not pass an IV.

This has also been discussed for Debians duplicity package. They have come to the same conclusion as the pycrypto authors, i.e. that clients of pycrypto need to fix it.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851551

**Comment by mattgodbolt** [comment]
Just hit this on a production site too; applying the workaround at http://uucode.com/blog/2015/02/20/workaround-for-ctr-mode-needs-counter-parameter-not-iv/

**Comment by ploxiln** [comment]
fixed in #889

**Comment by apapsch** [comment]
Thanks! Mental note for me: Also search the pull requests :-)

**Comment by bitprophet** [comment]
And #889 was literally pushed to PyPI a few hours before you posted this :D

**Comment by chandrapola** [comment]
Seeing this again in 2021 . 

Working in on Ubuntu 14.04 -- 

uname -a
Linux cp736799atmclient 4.4.0-148-generic #174~14.04.1-Ubuntu SMP Thu May 9 08:17:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Failing on Ubuntu 

Linux robotscasnode 4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
