### ISSUE TITLE
Mismatched MAC after running for a very long time

### ISSUE THREAD

**Issue by Hoegje** [paramiko/paramiko#941]
I have a number of python processes, that has a shared managed object which does regular updates through the SSH paramiko library. This runs very smooth for a long time, but after a while (24 hours is my best guess at the moment) it throws the following exception

Exception: Mismatched MAC
Traceback (most recent call last):
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/transport.py", line 1765, in run
    ptype, m = self.packetizer.read_message()
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/packet.py", line 416, in read_message
    raise SSHException('Mismatched MAC')
paramiko.ssh_exception.SSHException: Mismatched MAC

Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/transport.py", line 1893, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/packet.py", line 331, in readline
    buf += self._read_timeout(timeout)
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/packet.py", line 501, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/transport.py", line 1749, in run
    self._check_banner()
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/transport.py", line 1897, in _check_banner
    raise SSHException('Error reading SSH protocol banner' + str(e))
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

I looked around a bit and found this similar issue, but the linked #ssh#41 issue is no longer there.
[https://github.com/fabric/fabric/issues/500](https://github.com/fabric/fabric/issues/500)

Does anybody have an idea why this may be occuring after running for a long time? I locally added more output to the 'Mismatched MAC' string, to see what is changed after the long running period.

Thx.

**Comment by Hoegje** [comment]
Some more info maybe. It seems to occur very infrequently, and in different parts of the packet.py code, so it seems. The last dump I got was this. Do you want me to add more debug to my running version, just tell me what you would like to see and I'll try to add it.

Exception: Invalid packet blocking
Traceback (most recent call last):
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/transport.py", line 1765, in run
    ptype, m = self.packetizer.read_message()
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/packet.py", line 401, in read_message
    raise SSHException('Invalid packet blocking')
paramiko.ssh_exception.SSHException: Invalid packet blocking

Exception: Error reading SSH protocol banner  None 2
Traceback (most recent call last):
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/transport.py", line 1895, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/packet.py", line 331, in readline
    buf += self._read_timeout(timeout)
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/packet.py", line 502, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/transport.py", line 1749, in run
    self._check_banner()
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/transport.py", line 1905, in _check_banner
    raise SSHException('Error reading SSH protocol banner {0} {1} {2}'.format(e,buf,timeout))
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner  None 2

**Comment by Hoegje** [comment]
Maybe not 100% related, but why is there a mix between linefeed_byte and cr_byte**_value** in the readline method of Packetizer

    def readline(self, timeout):
        """
        Read a line from the socket.  We assume no data is pending after the
        line, so it's okay to attempt large reads.
        """
        buf = self.__remainder
        while not _linefeed_byte_ in buf:
            buf += self._read_timeout(timeout)
        n = buf.index(_linefeed_byte_)
        self.__remainder = buf[n + 1:]
        buf = buf[:n]
        if (len(buf) > 0) and (buf[-1] == _cr_byte_**value**_):
            buf = buf[:-1]
        return u(buf)

**Comment by Hoegje** [comment]
And once more. Also added more debug output to the py3compat.u method now.

Exception: Invalid packet blocking
Exception: Error reading SSH protocol banner 'utf-8' codec can't decode byte 0x92 in position 3: invalid start byte None 2
Traceback (most recent call last):
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/transport.py", line 1765, in run
    ptype, m = self.packetizer.read_message()
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/packet.py", line 401, in read_message
    raise SSHException('Invalid packet blocking')
paramiko.ssh_exception.SSHException: Invalid packet blocking

Traceback (most recent call last):
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/transport.py", line 1895, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/packet.py", line 337, in readline
    return u(buf)
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/py3compat.py", line 148, in u
    return s.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 3: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/transport.py", line 1749, in run
    self._check_banner()
  File "/opt/python-3/lib/python3.5/site-packages/paramiko/transport.py", line 1905, in _check_banner
    raise SSHException('Error reading SSH protocol banner {0} {1} {2}'.format(e,buf,timeout))
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner 'utf-8' codec can't decode byte 0x92 in position 3: invalid start byte None 2

**Comment by routetehpacketz** [comment]
This thread is a little old, but I'm getting "invalid packet blocking" with paramiko 2.4.1

I'm using paramiko to run commands on Cisco switches and started getting this exception when adding several close() commands throughout my script. They're placed so that they won't interfere with the script's ability to complete. I get the output I'm expecting, but it's littered with these "raise SSHException('Invalid packet blocking')" messages.

**Comment by ioveme110220** [comment]
chan = ssh.invoke_shell(height=8000,width=400)
调整ssh.invoke_shell的高

**Comment by bert107** [comment]
Dear all

I am having the same issue on my new desktop computer (Windows 10) which became very annoying. I am using Visual Studio Code and psycopg2 to connect to my cloud based database via SSH. Especially for longer queries (like >1 min) this "Mismatched MAC" error occurs very often which forces me to rerun my code many times before it goes through. It also occurs if the connection is (re-)established frequently (e.g. when running several small modules on an automized schedule where each are connecting individually).

On my older notebook (windows 10 as well) I do not have this problem at all, when running the exactly same files. Therefore, I would exclude a problem on my cloudserver.


_**
> 2022-05-19 10:28:27,181| ERROR   | Exception (client): Mismatched MAC
> 2022-05-19 10:28:27,193| ERROR   | Traceback (most recent call last):
> 2022-05-19 10:28:27,194| ERROR   |   File "C:\...\Python\Python37\lib\site-packages\paramiko\transport.py", line 2117, in run
> 2022-05-19 10:28:27,194| ERROR   |     ptype, m = self.packetizer.read_message()
> 2022-05-19 10:28:27,194| ERROR   |   File "C:\...\Python\Python37\lib\site-packages\paramiko\packet.py", line 528, in read_message
> 2022-05-19 10:28:27,194| ERROR   |     raise SSHException("Mismatched MAC")

> **the following lines appear when my code is interrupted, probably not related to the error above.**
> Backend TkAgg is interactive backend. Turning interactive mode on.
> 84.45s - Error when getting str with custom provider: <pydevd_plugins.extensions.types.pydevd_plugin_pandas_types.PandasDataFrameTypeResolveProvider object at 0x000001BA1171F6D8>.
> Traceback (most recent call last):
>   File "c:\...\.vscode\extensions\ms-python.python-2022.6.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_xml.py", line 216, in str_from_providers
>     return provider.get_str(o)
>   File "c:\...\.vscode\extensions\ms-python.python-2022.6.2\pythonfiles\lib\python\debugpy\_vendored\pydevd\pydevd_plugins\extensions\types\pydevd_plugin_pandas_types.py", line 75, in get_str     
>     show_dimensions=True,
> TypeError: to_string() got an unexpected keyword argument 'max_colwidth'

**_

I checked inside the packet.py where the exception is raised and could see that this error occurs in the compute_hmac function. I found one proposed solution online to adjust the keepalive parameters, which in my case did not solve the problem.

It is a very odd error, occurring only on my desktop but not on my notebook even though all else is the same. I deinstalled my psycopg2 and paramiko packages to match the version with my notebook but also this did not solve the problem.

Hopefully you can tell me what I can do to get this error fixed. Having this arbitrary behaviour is very frustrating since it does not allow me using automated updates since it kicks out regularly and unpredictably.

Best wishes
Bertan

**Comment by 0x7162** [comment]
@bert107 
your link is not working..
( https://fixexception.com/paramiko/mismatched-mac/ )

My current findings are it could be in ssl malfunction at all.
i.e. openssl lib issues,
and "Mismatched MAC" is just a sign of it.

I would share such info for the gilty setups:
```
import ssl
print(ssl.OPENSSL_VERSION_INFO)
```

**Comment by 0x7162** [comment]
@Hoegje @bitprophet 
any ideas on the issue?

I used different versions of paramiko (including the latest)
and the problem improves but not solves if I install openssl111 on top of 102

it's a sequence of errors like
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2055, in run
    ptype, m = self.packetizer.read_message()
    File "/usr/local/lib/python3.8/site-packages/paramiko/packet.py", line 517, in read_message
    raise SSHException("Mismatched MAC")
    Mismatched MAC
```

```
Exception: Invalid packet blocking
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2055, in run
    ptype, m = self.packetizer.read_message()
    File "/usr/local/lib/python3.8/site-packages/paramiko/packet.py", line 493, in read_message
    raise SSHException("Invalid packet blocking")
paramiko.ssh_exception.SSHException: Invalid packet blocking
We were not able to execute the command because of an error: Invalid packet blocking
```

and finally getting EOF:

```
  File "/usr/local/lib/python3.8/site-packages/paramiko/client.py", line 514, in exec_command
    chan.exec_command(command)
  File "/usr/local/lib/python3.8/site-packages/paramiko/channel.py", line 72, in _check
    return func(self, *args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/paramiko/channel.py", line 257, in exec_command
    self._wait_for_event()
  File "/usr/local/lib/python3.8/site-packages/paramiko/channel.py", line 1226, in _wait_for_event
    raise e
  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 2055, in run
    ptype, m = self.packetizer.read_message()
  File "/usr/local/lib/python3.8/site-packages/paramiko/packet.py", line 459, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/usr/local/lib/python3.8/site-packages/paramiko/packet.py", line 303, in read_all
    raise EOFError()
EOFError
```

**Comment by jun66j5** [comment]
@0x7162 It seems to be caused by network connectivity on your environment. Also, check paramiko logs using `paramiko.util.log_to_file()` and logs in remote server also.

```
    raise SSHException("Mismatched MAC")
    raise SSHException("Invalid packet blocking")
    raise EOFError()
```
