### ISSUE TITLE
invoke_shell() on Juniper NetScreen 50 raises SSHException ("Channel closed")

### ISSUE THREAD

**Issue by andyka** [paramiko/paramiko#96]
When connecting to NetScreen 50 I always get SSHException. Connecting to other devices in the same fashion works. Also, command-line ssh works with the same credentials.
Note: I have edited the outputs below manually to hide the IP, username and password. Other than that they are copy/pasted.

```
Python 2.6.6 (r266:84292, Dec 26 2010, 22:31:48) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> paramiko.__version__
'1.8.0'
>>> h = paramiko.SSHClient()
>>> h.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> h.connect('192.168.1.1', username='username', password='password', key_filename=None)
>>> chan = h.invoke_shell(term='vt100')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.6/dist-packages/paramiko/client.py", line 389, in invoke_shell
    chan.get_pty(term, width, height)
  File "/usr/local/lib/python2.6/dist-packages/paramiko/channel.py", line 158, in get_pty
    self._wait_for_event()
  File "/usr/local/lib/python2.6/dist-packages/paramiko/channel.py", line 1114, in _wait_for_event
    raise e
paramiko.SSHException: Channel closed.
>>> 
```

SSH works:

```
$ ssh -v username@192.168.1.1
OpenSSH_5.5p1 Debian-6+squeeze2, OpenSSL 0.9.8o 01 Jun 2010
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Applying options for *
debug1: Connecting to 192.168.1.1 [192.168.1.1] port 22.
debug1: Connection established.
debug1: identity file /home/testssh/.ssh/id_rsa type -1
debug1: identity file /home/testssh/.ssh/id_rsa-cert type -1
debug1: identity file /home/testssh/.ssh/id_dsa type -1
debug1: identity file /home/testssh/.ssh/id_dsa-cert type -1
debug1: Remote protocol version 2.0, remote software version NetScreen
debug1: no match: NetScreen
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_5.5p1 Debian-6+squeeze2
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client 3des-cbc hmac-sha1 none
debug1: kex: client->server 3des-cbc hmac-sha1 none
debug1: sending SSH2_MSG_KEXDH_INIT
debug1: expecting SSH2_MSG_KEXDH_REPLY
debug1: Host '192.168.1.1' is known and matches the DSA host key.
debug1: Found key in /home/testssh/.ssh/known_hosts:1
debug1: ssh_dss_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: password
debug1: Next authentication method: password
username@192.168.1.1's password:
debug1: Authentication succeeded (password).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: Sending environment.
debug1: Sending env LANG = C
Remote Management Console
ns50-> 
```

And this is the output of Paramiko when debugging is on:

```
Python 2.6.6 (r266:84292, Dec 26 2010, 22:31:48) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
>>> h = paramiko.SSHClient()
>>> h.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> h.connect('192.168.1.1', username='username', password='password', key_filename=None)
DEBUG:paramiko.transport:starting thread (client mode): 0x1198650L
INFO:paramiko.transport:Connected (version 2.0, client NetScreen)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group1-sha1'] server key:['ssh-dss'] client encrypt:['3des-cbc'] server encrypt:['3des-cbc'] client mac:['hmac-sha1'] server mac:['hmac-sha1'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Ciphers agreed: local=3des-cbc, remote=3des-cbc
DEBUG:paramiko.transport:using kex diffie-hellman-group1-sha1; server key type ssh-dss; cipher: local 3des-cbc, remote 3des-cbc; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-dss host key for 192.168.1.1: *****
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
>>> chan = h.invoke_shell(term='vt100')
DEBUG:paramiko.transport:[chan 1] Max packet in: 34816 bytes
DEBUG:paramiko.transport:[chan 1] Max packet out: 1024 bytes
INFO:paramiko.transport:Secsh channel 1 opened.
DEBUG:paramiko.transport:[chan 1] EOF sent (1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.6/dist-packages/paramiko/client.py", line 389, in invoke_shell
    chan.get_pty(term, width, height)
  File "/usr/local/lib/python2.6/dist-packages/paramiko/channel.py", line 158, in get_pty
    self._wait_for_event()
  File "/usr/local/lib/python2.6/dist-packages/paramiko/channel.py", line 1114, in _wait_for_event
    raise e
paramiko.SSHException: Channel closed.
>>> DEBUG:paramiko.transport:EOF in transport thread
```

I have debugged a bit and found that we are sending EOF because at some point `Channel._request_failed` is called...  But from then on I have no idea how to debug further. If someone is willing to guide me I would be more than happy to help fix this issue.

**Comment by teadur** [comment]
the above mentioned fix doesnot seem to fix the issue for me either, anyone has any new ideas ?

**Comment by teadur** [comment]
The above mentioned fix doesnot seem to resolve the sitsuation indeed.

python test.py 
DEBUG:paramiko.transport:starting thread (client mode): 0x19dd2d0L
INFO:paramiko.transport:Connected (version 2.0, client NetScreen)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group1-sha1'] server key:['ssh-dss'] client encrypt:['3des-cbc'] server encrypt:['3des-cbc'] client mac:['hmac-sha1'] server mac:['hmac-sha1'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Ciphers agreed: local=3des-cbc, remote=3des-cbc
DEBUG:paramiko.transport:using kex diffie-hellman-group1-sha1; server key type ssh-dss; cipher: local 3des-cbc, remote 3des-cbc; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Trying key keyid from path to key
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 34816 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 1024 bytes
INFO:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    stdin, stdout, stderr = ssh.exec_command('get clock')
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 364, in exec_command
    chan.exec_command(command)
  File "/usr/lib/python2.7/dist-packages/paramiko/channel.py", line 213, in exec_command
    self._wait_for_event()
  File "/usr/lib/python2.7/dist-packages/paramiko/channel.py", line 1084, in _wait_for_event
    raise e
paramiko.SSHException: Channel closed.
