### ISSUE TITLE
Paramiko Error reading SSH protocol banner : SSH to a Cisco IOS Device

### ISSUE THREAD

**Issue by toghraee** [paramiko/paramiko#965]
Hello

I'm trying to use ansible to run a very basic script which is to SSH to a switch and run a show version.
I'm using the standard ios_command module which is from ansible.

by default it uses Paramiko as ssh agent and I'm getting the following Error : 

 paramiko.transport starting thread (client mode): 0x78c7f250L
 paramiko.transport Local version/idstring: SSH-2.0-paramiko_2.1.2
 paramiko.transport Banner: C6509#SSH-2.0-paramiko_2.1.2
 paramiko.transport Banner: Translating "SSH-2.0-paramiko_2.1.2"
 paramiko.transport Banner: % Unknown command or computer name, or unable to find computer address
 paramiko.transport Banner: C6509#
 paramiko.transport Exception: Error reading SSH protocol banner
 paramiko.transport Traceback (most recent call last):
 paramiko.transport   File "/usr/local/lib/python2.7/site-packages/paramiko/transport.py", line 1749, in run
 paramiko.transport     self._check_banner()
 paramiko.transport   File "/usr/local/lib/python2.7/site-packages/paramiko/transport.py", line 1897, in _check_banner
 paramiko.transport     raise SSHException('Error reading SSH protocol banner' + str(e))
 paramiko.transport SSHException: Error reading SSH protocol banner

I have tried to do some chnages and troubleshooting on paramiko packet.py and transport.py   but couldnt get that working.

can anyone help me what is this  SSH protocol banner checking is  and how to solve this?

Thanks
Reza Toghraee

**Comment by bitprophet** [comment]
I know I've seen this before but cannot find the ticket offhand ; you may want to try searching the other tickets. That said, this (targeting non POSIX ssh servers) is a common issue that we don't have a lot of resources for fixing unfortunately. Leaving open for now but may close as dupe later.

**Comment by radssh** [comment]
Don't have time to test this out right now, but it looks like the TCP connection remote side is just a plain telnet connection, not consistent with the opening protocol exchange for an ssh transport, where both client and server expect to send/receive a plaintext SSH version exchange (see [RFC4253](https://tools.ietf.org/html/rfc4253#section-4.2)).

It looks like the remote side is issuing an input prompt ("C6509#") and taking the text sent by the client as a command to invoke, sending an error message and reprompting ("C6509#") that the paramiko client side can't find anything looking like a SSH version string, and aborting the connection.

Can you double check that you can successfully use a standard ssh client to connect to the hostname (and port) that you are using under Ansible? Does the Ansible ios_command module have support for telnet connections, in addition to ssh connections?

**Comment by toghraee** [comment]
What I found today was that I have the same issue and same debug log as sent by Kaag on my Cisco Catalyst 6500 , running IOS s72033-advipservicesk9-mz.151-2.SY10

However, today I tried to connect a Cisco 3850 running cat3k_caa-universalk9.16.03.02.SPA
interestingly it worked on Cisco 3850. 

I captured both paramiko logs on 6500 and 3850 to compare :  

============6500============
paramiko.transport: Connected (version 2.0, client Cisco-1.25)
paramiko.transport: kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] client mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: Kex agreed: diffie-hellman-group1-sha1
paramiko.transport: Cipher agreed: aes128-cbc
paramiko.transport: MAC agreed: hmac-md5
paramiko.transport: Compression agreed: none
paramiko.transport: kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
paramiko.transport: Switch to new keys ...
paramiko.transport: Trying key 542f7f11dcaafae42ec947dbf96bac97 from /root/.ssh/id_rsa
paramiko.transport: userauth is OK
paramiko.transport: Exception: Illegal info request from server
paramiko.transport: Traceback (most recent call last):
paramiko.transport:   File "/usr/local/lib/python2.7/site-packages/paramiko/transport.py", line 1800, in run
paramiko.transport:     self.auth_handler._handler_table[ptype](self.auth_handler, m)
paramiko.transport:   File "/usr/local/lib/python2.7/site-packages/paramiko/auth_handler.py", line 575, in _parse_userauth_info_request
paramiko.transport:     raise SSHException('Illegal info request from server')
paramiko.transport: SSHException: Illegal info request from server
paramiko.transport:
paramiko.transport: Trying SSH agent key 542f7f11dcaafae42ec947dbf96bac97
paramiko.transport: Trying discovered key 542f7f11dcaafae42ec947dbf96bac97 in /root/.ssh/id_rsa


============3850============
paramiko.transport: starting thread (client mode): 0xdeb37810L
paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.1.2
paramiko.transport: Remote version/idstring: SSH-2.0-Cisco-1.25
paramiko.transport: Connected (version 2.0, client Cisco-1.25)
paramiko.transport: kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] client mac:[u'hmac-sha1', u'hmac-sha1-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: Kex agreed: diffie-hellman-group14-sha1
paramiko.transport: Cipher agreed: aes128-ctr
paramiko.transport: MAC agreed: hmac-sha1-96
paramiko.transport: Compression agreed: none
paramiko.transport: kex engine KexGroup14 specified hash_algo <built-in function openssl_sha1>
paramiko.transport: Switch to new keys ...
paramiko.transport: Trying key 542f7f11dcaafae42ec947dbf96bac97 from /root/.ssh/id_rsa
paramiko.transport: userauth is OK
paramiko.transport: Authentication (publickey) successful!
paramiko.transport: EOF in transport thread



===============================

The difference between the 2 is   :   

3850 : Kex agreed: diffie-hellman-group14-sha1
6500:  Kex agreed: diffie-hellman-group1-sha1

3850: Cipher agreed: aes128-ctr
6500: Cipher agreed: aes128-cbc

3550: MAC agreed: hmac-sha1-96
6500: MAC agreed: hmac-md5


===========================

This seems to be related to Cisco IOS implementation of SSH on 6500 or 3560

6509#sh ip ssh
SSH Enabled - version 2.0
Authentication timeout: 120 secs; Authentication retries: 3
Minimum expected Diffie Hellman key size : 1024 bits


3850#sh ip ssh
SSH Enabled - version 2.0
Authentication methods:publickey,keyboard-interactive,password
Authentication Publickey Algorithms:x509v3-ssh-rsa,ssh-rsa
Hostkey Algorithms:x509v3-ssh-rsa,ssh-rsa
Encryption Algorithms:aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
MAC Algorithms:hmac-sha1,hmac-sha1-96
KEX Algorithms:diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1
Authentication timeout: 120 secs; Authentication retries: 3
Minimum expected Diffie Hellman key size : 2048 bits


===My Python File ====

root@HOST~ cat test_paramiko_cisco.py
import logging
import paramiko

logging.getLogger("paramiko").setLevel(logging.DEBUG)
ssh = paramiko.SSHClient()
ssh.load_system_host_keys('/root/.ssh/known_hosts')
ssh.set_missing_host_key_policy(paramiko.WarningPolicy())
paramiko.util.log_to_file("/root/paramiko.log")
ssh.connect('SWITCH_IP', username='USERNAME',password='KEY_PASS_PHRASE', key_filename='/root/.ssh/id_rsa', allow_agent='False')
remote_conn=ssh.invoke_shell()
remote_conn.send("show run\n")
output=remote_conn.recv(5000)
print output



I'm still looking forward to see how to fix the issue with IOS / 6500 .

Regards
Reza Toghraee

**Comment by ktbyers** [comment]
The general fix for the "SSH protocol banner" on network devices including Cisco IOS devices is to increase the banner_timeout.

Here is the fix for this in Netmiko which is using Paramiko under-the-hood.

I think we should close this issue as I don't think there are additional actions to take here.

**Comment by amitsova** [comment]
Hi,

Can somebody please help?

I can't manage with this:

"Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner"

Here's my code:

#! /usr/bin/env python3

from netmiko import ConnectHandler

for i in range(1, 3):
    ip_add = "10.1.0." + str(i)
    devices = {
        'device_type': 'cisco_ios',
        'ip': ip_add,
        'username': 'addie',
        'password': 'admin',
    }
    try:
        devices['device_type'] = 'cisco_ios_ssh'
        net_connect = ConnectHandler(**devices)
        hostname = net_connect.send_command("show run | i hostname")
        print("Connecting to " + hostname.split()[1] + ", ip: " + ip_add)
    except:
        try:
            devices['device_type'] = 'cisco_ios_telnet'
            net_connect = ConnectHandler(**devices)
            hostname = net_connect.send_command("show run | i hostname")
            print("Connecting to " + hostname.split()[1] + ", ip: " + ip_add)
            show_ver = net_connect.send_command("show ver | i IOS")
            print(show_ver)
        except:
            print("Neither SSH nor telnet is working!")

That's the output:

Connecting to R1, ip: 10.1.0.1
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "C:\Users\addie\PycharmProjects\ProjectThree\venv\lib\site-packages\paramiko\transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "C:\Users\addie\PycharmProjects\ProjectThree\venv\lib\site-packages\paramiko\packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "C:\Users\addie\PycharmProjects\ProjectThree\venv\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\addie\PycharmProjects\ProjectThree\venv\lib\site-packages\paramiko\transport.py", line 2039, in run
    self._check_banner()
  File "C:\Users\addie\PycharmProjects\ProjectThree\venv\lib\site-packages\paramiko\transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Connecting to R2, ip: 10.1.0.2
Cisco IOS Software, IOSv Software (VIOS-ADVENTERPRISEK9-M), Version 15.6(2)T, RELEASE SOFTWARE (fc2)
ROM: Bootstrap program is IOSv
Cisco IOSv (revision 1.0) with  with 460017K/62464K bytes of memory.

Where should I increase this banner_timeout? Please help!

Thanks in advance!

**Comment by amitsova** [comment]
Hi all,

Can somebody please help?

I keep seeing the below error, even though the "show" command is run successfully:

 Connecting to R1, ip: 10.1.0.1 

Cisco IOS Software, IOSv Software (VIOS-ADVENTERPRISEK9-M), Version 15.6(2)T, RELEASE SOFTWARE (fc2)
ROM: Bootstrap program is IOSv
Cisco IOSv (revision 1.0) with  with 460017K/62464K bytes of memory.
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "C:\Users\addie\PycharmProjects\ProjectThree\venv\lib\site-packages\paramiko\transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "C:\Users\addie\PycharmProjects\ProjectThree\venv\lib\site-packages\paramiko\packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "C:\Users\addie\PycharmProjects\ProjectThree\venv\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\addie\PycharmProjects\ProjectThree\venv\lib\site-packages\paramiko\transport.py", line 2039, in run
    self._check_banner()
  File "C:\Users\addie\PycharmProjects\ProjectThree\venv\lib\site-packages\paramiko\transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner


 Connecting to R2, ip: 10.1.0.2 

Cisco IOS Software, IOSv Software (VIOS-ADVENTERPRISEK9-M), Version 15.6(2)T, RELEASE SOFTWARE (fc2)
ROM: Bootstrap program is IOSv
Cisco IOSv (revision 1.0) with  with 460017K/62464K bytes of memory.

 Connecting to R3, ip: 10.1.0.3 

Cisco IOS Software, IOSv Software (VIOS-ADVENTERPRISEK9-M), Version 15.6(2)T, RELEASE SOFTWARE (fc2)
ROM: Bootstrap program is IOSv
Cisco IOSv (revision 1.0) with  with 460017K/62464K bytes of memory.

Process finished with exit code 0

Here's my code:

#! /usr/bin/env python3

from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException
from netmiko.ssh_exception import NetMikoAuthenticationException
from paramiko.ssh_exception import SSHException

for i in range(1, 4):
    ip_add = "10.1.0." + str(i)
    devices = {
        'device_type': 'cisco_ios',
        'ip': ip_add,
        'username': 'addie',
        'password': 'admin',
    }
    try:
        devices['device_type'] = 'cisco_ios_ssh'
        net_connect = ConnectHandler(**devices)
        hostname = net_connect.send_command("show run | i hostname")
        print('\n', "Connecting to " + hostname.split()[1] + ", ip: " + ip_add, '\n')
        show_ver = net_connect.send_command("show ver | i IOS")
        print(show_ver)
    except(NetMikoTimeoutException, SSHException, NetMikoAuthenticationException, EOFError):
        try:
            devices['device_type'] = 'cisco_ios_telnet'
            net_connect = ConnectHandler(**devices)
            hostname = net_connect.send_command("show run | i hostname")
            print('\n', "Connecting to " + hostname.split()[1] + ", ip: " + ip_add, '\n')
            show_ver = net_connect.send_command("show ver | i IOS")
            print(show_ver)
        except:
            print("Neither SSH nor telnet is working!")

I did increase the banner_timeout:

    def _check_banner(self):
        # this is slow, but we only have to do it once
        for i in range(100):
            # give them 15 seconds for the first line, then just 2 seconds
            # each additional line.  (some sites have very high latency.)
            if i == 0:
                timeout = self.banner_timeout
            else:
                timeout = 9800
            try:
                buf = self.packetizer.readline(timeout)

Note: R1 and R3 are enabled with SSH, R2 is enabled with telnet.


Any help will be much appreciated.

Thanks in advance!
